import { CookiePreferencesButton } from '@/components/marketing/CookiePreferencesButton'
import { LegalPage, type LegalSection } from '@/components/marketing/LegalPage'
import { generateMetadata, pageMetadata } from '@/lib/metadata'

export const metadata = generateMetadata(pageMetadata.privacy)

const sections: LegalSection[] = [
  { id: 'commitment', title: 'Our commitment to privacy', content: <><p>At CPAAutomation, we understand that your documents contain sensitive financial and legal information. We are committed to protecting your privacy and maintaining the highest standards of data security.</p><p>This privacy policy explains how we collect, use, and protect your information when you use our document extraction services.</p></> },
  { id: 'information', title: 'Information we collect', content: <><h3>Document data</h3><ul><li>Files you upload for processing (opt-out option provided)</li><li>Extracted data and results from your documents</li><li>Custom extraction rules and templates</li><li>Processing metadata</li></ul><h3>Account information</h3><ul><li>Name, email, and company information</li><li>Subscription plan and billing information</li><li>Usage statistics and feature preferences</li><li>Support communication and feedback</li></ul><h3>Technical data</h3><ul><li>IP address and browser information</li><li>Device type and operating system</li><li>API usage logs and error reports</li><li>Performance and analytics data</li></ul></> },
  { id: 'protection', title: 'How we protect your data', content: <ul><li><strong>Immediate file deletion</strong> — If you choose not to keep your files stored for later use, they are permanently deleted from our servers immediately after processing is complete.</li><li><strong>US-only hosting</strong> — All our servers are located exclusively in the United States, ensuring your data remains within US jurisdiction and subject to US privacy laws.</li><li><strong>AES-256 encryption</strong> — All data is encrypted using industry-standard AES-256 encryption both in transit and at rest, providing military-grade security for your documents.</li><li><strong>Access controls</strong> — Strict access controls limit data access to authorized personnel only, with comprehensive audit logs of all system access and activities.</li></ul> },
  { id: 'use', title: 'How we use your information', content: <><h3>Service provision</h3><p>We use your data solely to provide document extraction services, including processing your files, delivering results, and maintaining your account.</p><h3>Service improvement</h3><p>Anonymous, aggregated usage data helps us improve our AI models and service quality. No personally identifiable information is used for this purpose.</p><h3>Customer support</h3><p>We may access your account information to provide technical support, resolve issues, and respond to your inquiries.</p><h3>Legal compliance</h3><p>We may process data as required by law, regulation, or legal process, but will notify you when legally permitted to do so.</p></> },
  { id: 'sharing', title: 'Data sharing & third parties', content: <><h3>We do not sell your data</h3><p>CPAAutomation does not sell, rent, or trade your personal information or document data to third parties for marketing or any other commercial purposes.</p><h3>Limited third-party services</h3><p>We may use trusted third-party services for specific functions such as payment processing, email delivery, and hosting infrastructure. These providers are contractually bound to protect your data.</p><h3>Business transfers</h3><p>In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of the business transaction, subject to the same privacy protections.</p></> },
  { id: 'rights', title: 'Your rights and choices', content: <ul><li><strong>Access and portability</strong> — You have the right to access your account data and export your extraction templates and results in a portable format at any time.</li><li><strong>Correction and updates</strong> — You can update your account information, preferences, and settings through your dashboard or by contacting our support team.</li><li><strong>Account deletion</strong> — You may delete your account at any time. Upon deletion, all your data will be permanently removed from our systems within 30 days.</li></ul> },
  { id: 'questions', title: 'Questions about your privacy?', content: <><p>If you have questions about this privacy policy or how we handle your data, please contact us:</p><ul><li>Email: <a className="ps-link" href="mailto:privacy@CPAAutomation.ai">privacy@CPAAutomation.ai</a></li><li>Address: United States (US-based support team)</li></ul></> },
  { id: 'updates', title: 'Policy updates', content: <p>We may update this privacy policy from time to time. We will notify you of any material changes by email and by posting the updated policy on our website. Your continued use of CPAAutomation after such changes constitutes acceptance of the updated policy.</p> },
]

export default function PrivacyPage() { return <LegalPage title="Privacy policy" description="How we protect and handle your data at CPAAutomation." lastUpdated="August 2025" sections={sections} action={<CookiePreferencesButton />} /> }
