"""Canonical Prepared by Client request-list templates.

The library is intentionally data-only so the same definitions can be used by
the application bootstrap path and the production seeding command.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class PbcTemplateDefinition:
    name: str
    description: str
    engagement_type: str
    items: tuple[dict[str, Any], ...]


def item(
    category: str,
    title: str,
    *formats: str,
    priority: str = "normal",
    description: str | None = None,
    sensitive: bool = False,
    requires_redaction: bool = False,
) -> dict[str, Any]:
    value: dict[str, Any] = {
        "category": category,
        "title": title,
        "priority": priority,
        "expected_formats": list(formats),
    }
    if description:
        value["description"] = description
    if sensitive:
        value["sensitive"] = True
    if requires_redaction:
        value["requires_redaction"] = True
    return value


PBC_TEMPLATE_LIBRARY: tuple[PbcTemplateDefinition, ...] = (
    PbcTemplateDefinition(
        "Annual financial statement audit",
        "Comprehensive year-end financial statement audit request list. Tailor for the entity and assessed risks before publishing.",
        "audit",
        (
            item("Planning and general", "Final adjusted trial balance and chart of accounts", "xlsx", "csv", priority="high"),
            item("Planning and general", "Current-year general ledger detail", "xlsx", "csv", priority="high"),
            item("Planning and general", "Prior-year audited financial statements and management letter", "pdf"),
            item("Planning and general", "Organization chart and list of key personnel", "pdf", "xlsx"),
            item("Planning and general", "Board and committee minutes for the year and through report date", "pdf", priority="high"),
            item("Planning and general", "Summary of significant transactions, accounting changes, and estimates", "docx", "pdf"),
            item("Cash", "Bank account listing with authorized signers", "xlsx"),
            item("Cash", "Year-end bank statements and reconciliations for all accounts", "pdf", "xlsx", priority="high"),
            item("Cash", "Outstanding check and deposit-in-transit support", "xlsx", "pdf"),
            item("Accounts receivable", "Accounts receivable aging as of year end", "xlsx", priority="high"),
            item("Accounts receivable", "Subsequent cash receipts detail", "xlsx", "pdf"),
            item("Accounts receivable", "Allowance for credit losses analysis", "xlsx", "docx"),
            item("Revenue", "Revenue detail by customer, product, or service", "xlsx", priority="high"),
            item("Revenue", "Significant customer contracts and amendments", "pdf", priority="high"),
            item("Revenue", "Deferred revenue and contract asset rollforward", "xlsx"),
            item("Inventory", "Year-end inventory listing and reconciliation to the general ledger", "xlsx"),
            item("Inventory", "Physical inventory count instructions and final count sheets", "pdf", "xlsx"),
            item("Inventory", "Inventory reserve and obsolescence analysis", "xlsx"),
            item("Prepaids and other assets", "Prepaid expense and other asset schedules", "xlsx"),
            item("Fixed assets", "Property and equipment rollforward with additions and disposals", "xlsx", priority="high"),
            item("Fixed assets", "Invoices and approvals for significant capital additions", "pdf"),
            item("Leases", "Lease population, agreements, and ASC 842 rollforward", "xlsx", "pdf"),
            item("Accounts payable", "Accounts payable aging as of year end", "xlsx", priority="high"),
            item("Accounts payable", "Subsequent disbursements listing and unrecorded liability search support", "xlsx", "pdf"),
            item("Payroll", "Year-end payroll registers and Forms W-2/W-3", "xlsx", "pdf", sensitive=True),
            item("Payroll", "Employee census and accrued compensation schedule", "xlsx", sensitive=True),
            item("Debt", "Debt agreements, amendments, and lender statements", "pdf", priority="high"),
            item("Debt", "Debt and interest rollforward with covenant calculations", "xlsx"),
            item("Equity", "Equity rollforward and supporting agreements", "xlsx", "pdf"),
            item("Income taxes", "Current and deferred income tax provision", "xlsx", "pdf", sensitive=True),
            item("Legal and contingencies", "Attorney listing, litigation summary, and legal representation contacts", "xlsx", "docx", sensitive=True),
            item("Related parties", "Related-party listing, balances, and transactions", "xlsx", "docx", sensitive=True),
            item("Completion", "Proposed financial statements with footnotes", "docx", "xlsx", priority="high"),
            item("Completion", "Going-concern assessment and cash-flow forecast", "xlsx", "docx"),
            item("Completion", "Subsequent-events summary through the report date", "docx", "pdf", priority="high"),
            item("Completion", "Signed management representation letter", "pdf", priority="high"),
        ),
    ),
    PbcTemplateDefinition(
        "Employee benefit plan audit",
        "ERISA employee benefit plan audit request list covering plan governance, census data, investments, contributions, distributions, and Form 5500.",
        "audit",
        (
            item("Plan documents", "Executed plan document and all amendments", "pdf", priority="high"),
            item("Plan documents", "Current summary plan description", "pdf"),
            item("Plan documents", "IRS determination or opinion letter", "pdf"),
            item("Governance", "Plan committee minutes and fiduciary acknowledgments", "pdf"),
            item("Governance", "Service-provider agreements and fee disclosures", "pdf"),
            item("Financial", "Year-end trial balance and general ledger", "xlsx", "csv", priority="high"),
            item("Financial", "Prior-year audited financial statements and management letter", "pdf"),
            item("Financial", "Trust statements and certified investment information", "pdf", "xlsx", priority="high"),
            item("Financial", "Investment rollforward and realized/unrealized gain detail", "xlsx"),
            item("Participant data", "Complete employee census with eligibility and compensation fields", "xlsx", priority="high", sensitive=True),
            item("Participant data", "Participant account balance detail at beginning and end of year", "xlsx", sensitive=True),
            item("Contributions", "Employee and employer contribution detail by pay period", "xlsx", sensitive=True),
            item("Contributions", "Payroll registers and remittance dates for contribution testing", "xlsx", "pdf", priority="high", sensitive=True),
            item("Contributions", "Employer match or profit-sharing calculation", "xlsx"),
            item("Distributions", "Distribution and rollover population with supporting approvals", "xlsx", "pdf", sensitive=True),
            item("Loans", "Participant loan population and deemed-distribution report", "xlsx", sensitive=True),
            item("Loans", "Sample loan agreements and repayment histories", "pdf", "xlsx", sensitive=True),
            item("Compliance", "Nondiscrimination and compliance testing results", "pdf", "xlsx"),
            item("Compliance", "Late contributions, prohibited transactions, and correction documentation", "xlsx", "pdf", priority="high"),
            item("Compliance", "SOC 1 reports and user-control consideration responses", "pdf"),
            item("Form 5500", "Draft Form 5500 and all schedules", "pdf", priority="high"),
            item("Form 5500", "Reconciliation of Form 5500 to trust and financial statements", "xlsx"),
            item("Completion", "ERISA fidelity bond and fiduciary insurance policies", "pdf"),
            item("Completion", "Related-party and party-in-interest transaction representation", "docx", "pdf"),
            item("Completion", "Subsequent-events and plan-changes summary", "docx", "pdf"),
        ),
    ),
    PbcTemplateDefinition(
        "Nonprofit financial statement audit",
        "Year-end nonprofit audit request list with contributions, grants, restrictions, functional expenses, governance, and compliance coverage.",
        "audit",
        (
            item("General", "Final trial balance, chart of accounts, and general ledger", "xlsx", "csv", priority="high"),
            item("General", "Prior-year audited financial statements, Form 990, and management letter", "pdf"),
            item("Governance", "Board and committee minutes", "pdf", priority="high"),
            item("Governance", "Articles, bylaws, conflict-of-interest policy, and annual disclosures", "pdf"),
            item("Cash and investments", "Bank and investment statements with year-end reconciliations", "pdf", "xlsx", priority="high"),
            item("Contributions", "Contribution and pledge detail by donor", "xlsx", priority="high", sensitive=True),
            item("Contributions", "Pledge receivable aging and collectability analysis", "xlsx"),
            item("Contributions", "Donor restriction documentation for significant gifts", "pdf", sensitive=True),
            item("Grants", "Grant schedule with revenue, receivables, and deferred amounts", "xlsx", priority="high"),
            item("Grants", "Significant grant agreements and compliance reports", "pdf"),
            item("Programs", "Program service revenue detail and significant contracts", "xlsx", "pdf"),
            item("Expenses", "Functional expense allocation methodology and calculation", "xlsx", "docx", priority="high"),
            item("Expenses", "Accounts payable aging and subsequent disbursements", "xlsx"),
            item("Payroll", "Payroll registers, employee census, and compensation by function", "xlsx", sensitive=True),
            item("Fixed assets", "Fixed asset rollforward and significant addition invoices", "xlsx", "pdf"),
            item("Leases", "Lease agreements and ASC 842 schedule", "pdf", "xlsx"),
            item("Debt", "Debt agreements, lender statements, and covenant calculations", "pdf", "xlsx"),
            item("Net assets", "Net asset rollforward by donor restriction", "xlsx", priority="high"),
            item("Endowments", "Endowment rollforward, spending calculation, and underwater-fund analysis", "xlsx"),
            item("Compliance", "Federal and state awards schedule and grant expenditures", "xlsx"),
            item("Compliance", "Regulatory correspondence and questioned-cost summaries", "pdf", sensitive=True),
            item("Related parties", "Related-party and board-member transaction listing", "xlsx", "docx", sensitive=True),
            item("Completion", "Draft financial statements and footnotes", "docx", "xlsx", priority="high"),
            item("Completion", "Budget-to-actual results and going-concern assessment", "xlsx", "docx"),
            item("Completion", "Subsequent-events summary", "docx", "pdf", priority="high"),
        ),
    ),
    PbcTemplateDefinition(
        "Financial statement review",
        "SSARS financial statement review request list focused on analytical procedures, inquiries, account support, and disclosures.",
        "other",
        (
            item("General", "Adjusted trial balance, chart of accounts, and general ledger", "xlsx", "csv", priority="high"),
            item("General", "Prior-year financial statements and accountant communications", "pdf"),
            item("General", "Current-year budget and monthly financial statements", "xlsx", "pdf"),
            item("Cash", "Year-end bank reconciliations and statements", "xlsx", "pdf", priority="high"),
            item("Receivables", "Accounts receivable aging and allowance analysis", "xlsx"),
            item("Inventory", "Inventory summary and valuation methodology", "xlsx", "docx"),
            item("Fixed assets", "Fixed asset rollforward", "xlsx"),
            item("Payables", "Accounts payable aging and accrued liabilities schedule", "xlsx"),
            item("Debt", "Debt agreements, balances, and covenant calculations", "pdf", "xlsx"),
            item("Equity", "Equity rollforward and owner transaction detail", "xlsx", sensitive=True),
            item("Revenue", "Monthly revenue detail and significant contract changes", "xlsx", "pdf"),
            item("Payroll", "Annual payroll summary and officer compensation", "xlsx", sensitive=True),
            item("Taxes", "Income tax provision or tax-return reconciliation", "xlsx", "pdf", sensitive=True),
            item("Analytics", "Explanations for significant current-year and prior-year variances", "xlsx", "docx"),
            item("Commitments", "Lease, legal, guarantee, and other commitment summary", "docx", "pdf", sensitive=True),
            item("Related parties", "Related-party balances and transactions", "xlsx", "docx", sensitive=True),
            item("Completion", "Draft financial statements and footnotes", "docx", "xlsx", priority="high"),
            item("Completion", "Going-concern and liquidity assessment", "xlsx", "docx"),
            item("Completion", "Subsequent-events summary", "docx", "pdf", priority="high"),
            item("Completion", "Signed management representation letter", "pdf", priority="high"),
        ),
    ),
    PbcTemplateDefinition(
        "Financial statement compilation",
        "SSARS compilation request list for assembling complete, properly classified financial statements and disclosures.",
        "other",
        (
            item("General", "Final trial balance and chart of accounts", "xlsx", "csv", priority="high"),
            item("General", "Prior-year financial statements", "pdf"),
            item("Cash", "Year-end bank reconciliations", "xlsx", "pdf"),
            item("Working capital", "Accounts receivable and accounts payable aging reports", "xlsx"),
            item("Inventory", "Year-end inventory summary", "xlsx"),
            item("Fixed assets", "Fixed asset and depreciation schedule", "xlsx"),
            item("Liabilities", "Accrued liabilities and deferred revenue schedules", "xlsx"),
            item("Debt", "Debt balances and current loan statements", "xlsx", "pdf"),
            item("Equity", "Owner contributions, distributions, and equity changes", "xlsx", sensitive=True),
            item("Revenue", "Annual revenue summary by major category", "xlsx"),
            item("Payroll", "Annual payroll and officer compensation summary", "xlsx", sensitive=True),
            item("Taxes", "Most recently filed income tax return", "pdf", sensitive=True),
            item("Disclosures", "Related parties, commitments, contingencies, and subsequent events questionnaire", "docx", "pdf", sensitive=True),
            item("Disclosures", "Significant accounting policies and changes", "docx", "pdf"),
            item("Completion", "Management-approved adjusting entries", "xlsx", "pdf", priority="high"),
            item("Completion", "Draft financial statements and requested disclosures", "docx", "xlsx", priority="high"),
        ),
    ),
    PbcTemplateDefinition(
        "Individual income tax return",
        "Federal and state individual income tax organizer covering common Form 1040 income, deduction, credit, and reporting items.",
        "tax",
        (
            item("Organizer", "Completed tax organizer and prior-year federal and state returns", "pdf", priority="high", sensitive=True),
            item("Personal information", "Changes in address, dependents, marital status, residency, or bank information", "docx", "pdf", sensitive=True),
            item("Income", "Forms W-2 and W-2G", "pdf", priority="high", sensitive=True),
            item("Income", "Forms 1099-INT, 1099-DIV, and consolidated brokerage statements", "pdf", sensitive=True),
            item("Income", "Forms 1099-NEC, 1099-MISC, and self-employment income records", "pdf", "xlsx", sensitive=True),
            item("Income", "Schedule K-1 forms and state K-1 equivalents", "pdf", priority="high", sensitive=True),
            item("Income", "Rental property income and expense detail", "xlsx", "pdf", sensitive=True),
            item("Income", "Forms 1099-R, SSA-1099, and pension statements", "pdf", sensitive=True),
            item("Investments", "Digital asset transaction report", "xlsx", "csv", sensitive=True),
            item("Investments", "Private investment purchases, sales, and basis support", "xlsx", "pdf", sensitive=True),
            item("Business", "Business income, expenses, mileage, and home-office detail", "xlsx", "csv", sensitive=True),
            item("Adjustments", "HSA, IRA, SEP, SIMPLE, and self-employed retirement contribution forms", "pdf", sensitive=True),
            item("Deductions", "Mortgage interest and real estate tax statements", "pdf", sensitive=True),
            item("Deductions", "Charitable contribution receipts and noncash donation support", "pdf", "xlsx", sensitive=True),
            item("Deductions", "Medical expense summary when potentially deductible", "xlsx", sensitive=True),
            item("Credits", "Dependent care expenses and provider tax information", "xlsx", "pdf", sensitive=True),
            item("Credits", "Education Forms 1098-T, loan interest, and qualified expense detail", "pdf", "xlsx", sensitive=True),
            item("Property", "Real estate purchase, sale, refinance, and improvement documents", "pdf", "xlsx", sensitive=True),
            item("Estimated taxes", "Federal and state estimated tax payments and extension payments", "pdf", "xlsx", priority="high", sensitive=True),
            item("Foreign reporting", "Foreign accounts, assets, trusts, and income detail", "xlsx", "pdf", priority="high", sensitive=True),
            item("Other", "Health insurance marketplace Form 1095-A", "pdf", sensitive=True),
            item("Other", "Identity protection PINs and tax authority correspondence", "pdf", priority="high", sensitive=True),
            item("Other", "Gift, inheritance, casualty, legal settlement, or other unusual transaction documents", "pdf", "docx", sensitive=True),
        ),
    ),
    PbcTemplateDefinition(
        "Partnership and S corporation tax return",
        "Federal and state pass-through entity income tax request list for Forms 1065 and 1120-S.",
        "tax",
        (
            item("General", "Prior-year federal, state, and local income tax returns", "pdf", priority="high", sensitive=True),
            item("General", "Final trial balance, chart of accounts, and general ledger", "xlsx", "csv", priority="high"),
            item("General", "Book-to-tax adjusting entries and financial statements", "xlsx", "pdf"),
            item("Ownership", "Current ownership schedule and changes during the year", "xlsx", "pdf", priority="high", sensitive=True),
            item("Ownership", "Partner or shareholder legal names, addresses, tax IDs, and entity types", "xlsx", sensitive=True),
            item("Capital", "Tax-basis capital or stock basis rollforward", "xlsx", priority="high", sensitive=True),
            item("Capital", "Contributions, distributions, redemptions, and transfers", "xlsx", "pdf", sensitive=True),
            item("Income", "Revenue detail and Forms 1099 received", "xlsx", "pdf"),
            item("Income", "Schedule K-1 forms received from other entities", "pdf", sensitive=True),
            item("Fixed assets", "Fixed asset additions, disposals, and depreciation records", "xlsx", "pdf"),
            item("Payroll", "Quarterly payroll returns, annual W-2/W-3, and officer compensation", "pdf", "xlsx", sensitive=True),
            item("Contractors", "Forms 1099 filed and contractor payment detail", "pdf", "xlsx", sensitive=True),
            item("Debt", "Debt schedule and new or modified loan agreements", "xlsx", "pdf"),
            item("Deductions", "Meals, travel, auto, gifts, dues, penalties, and charitable contribution detail", "xlsx"),
            item("Benefits", "Owner health insurance and retirement plan contribution detail", "xlsx", "pdf", sensitive=True),
            item("State and local", "State apportionment data by jurisdiction", "xlsx", priority="high"),
            item("State and local", "State tax notices, estimates, extensions, and payments", "pdf", "xlsx", sensitive=True),
            item("International", "Foreign operations, owners, accounts, transactions, and taxes", "xlsx", "pdf", priority="high", sensitive=True),
            item("Credits", "Research, energy, payroll, and other tax credit support", "xlsx", "pdf"),
            item("Elections", "Tax elections, method changes, and transaction documents", "pdf", sensitive=True),
            item("Other", "Related-party transaction and loan detail", "xlsx", "pdf", sensitive=True),
            item("Other", "Tax authority correspondence and audit notices", "pdf", priority="high", sensitive=True),
            item("Other", "PPP, debt forgiveness, grants, or other nonrecurring transaction support", "pdf", "xlsx"),
        ),
    ),
    PbcTemplateDefinition(
        "C corporation income tax return",
        "Federal and state C corporation income tax request list for Form 1120 filers, including provision and international considerations.",
        "tax",
        (
            item("General", "Prior-year federal, state, and local income tax returns", "pdf", priority="high", sensitive=True),
            item("General", "Final trial balance, chart of accounts, and general ledger", "xlsx", "csv", priority="high"),
            item("General", "Audited or management financial statements", "pdf", "xlsx"),
            item("Provision", "Current-year income tax provision and deferred tax rollforward", "xlsx", priority="high", sensitive=True),
            item("Provision", "Uncertain tax position and valuation allowance analysis", "xlsx", "docx", sensitive=True),
            item("Ownership", "Legal entity chart and ownership changes", "pdf", "xlsx", sensitive=True),
            item("Equity", "Equity compensation, dividends, and capital transaction detail", "xlsx", "pdf", sensitive=True),
            item("Revenue", "Revenue detail by product, service, and jurisdiction", "xlsx"),
            item("Fixed assets", "Tax depreciation, additions, disposals, and repairs analysis", "xlsx", "pdf"),
            item("Payroll", "Payroll tax returns, W-2/W-3, and officer compensation", "pdf", "xlsx", sensitive=True),
            item("Deductions", "Meals, travel, auto, lobbying, penalties, and charitable contributions", "xlsx"),
            item("Deductions", "Accrued compensation, bonus, vacation, and other timing differences", "xlsx"),
            item("Debt", "Debt schedule, interest expense, and Section 163(j) support", "xlsx", "pdf"),
            item("State and local", "Apportionment data by state and legal entity", "xlsx", priority="high"),
            item("State and local", "State estimates, extensions, payments, notices, and NOL schedules", "pdf", "xlsx", sensitive=True),
            item("International", "Foreign entity, branch, owner, account, and transaction detail", "xlsx", "pdf", priority="high", sensitive=True),
            item("International", "Transfer-pricing reports and intercompany agreements", "pdf", sensitive=True),
            item("Credits", "Research and development credit study and wage/supply detail", "xlsx", "pdf"),
            item("Credits", "Energy, employment, and other business credit support", "xlsx", "pdf"),
            item("Transactions", "Acquisition, disposition, restructuring, and debt modification documents", "pdf", priority="high", sensitive=True),
            item("Compliance", "Forms 1099 filed and unclaimed-property reports", "pdf", "xlsx"),
            item("Compliance", "Tax authority correspondence and audit notices", "pdf", priority="high", sensitive=True),
            item("Elections", "Accounting method changes and tax elections", "pdf", "docx", sensitive=True),
        ),
    ),
    PbcTemplateDefinition(
        "Trust, estate, and gift tax return",
        "Fiduciary and transfer-tax organizer for Forms 1041, 706, and 709; tailor to the return type before sending.",
        "tax",
        (
            item("General", "Prior-year fiduciary, estate, and gift tax returns", "pdf", priority="high", sensitive=True),
            item("General", "Trust agreement, will, codicils, and amendments", "pdf", priority="high", sensitive=True),
            item("Identity", "Fiduciary, trustee, executor, beneficiary, and donor information", "xlsx", sensitive=True),
            item("Income", "Bank, brokerage, retirement, and other tax reporting forms", "pdf", sensitive=True),
            item("Income", "Schedule K-1 forms and business income records", "pdf", "xlsx", sensitive=True),
            item("Assets", "Beginning and ending asset inventory with tax basis and fair value", "xlsx", priority="high", sensitive=True),
            item("Assets", "Appraisals for real estate, businesses, securities, and personal property", "pdf", sensitive=True),
            item("Transactions", "Asset purchases, sales, exchanges, and basis support", "pdf", "xlsx", sensitive=True),
            item("Distributions", "Beneficiary distributions and allocation detail", "xlsx", "pdf", priority="high", sensitive=True),
            item("Expenses", "Fiduciary fees, legal fees, tax fees, and administration expenses", "xlsx", "pdf", sensitive=True),
            item("Gifts", "Gift detail by donor and recipient, including prior taxable gifts", "xlsx", "pdf", priority="high", sensitive=True),
            item("Gifts", "Valuation and ownership documents for gifted property", "pdf", sensitive=True),
            item("Estate", "Date-of-death asset and liability inventory", "xlsx", priority="high", sensitive=True),
            item("Estate", "Funeral, administration, debt, and charitable bequest support", "pdf", "xlsx", sensitive=True),
            item("Estimated taxes", "Federal and state estimates, extensions, and payments", "pdf", "xlsx", sensitive=True),
            item("Foreign reporting", "Foreign accounts, assets, trusts, beneficiaries, and taxes", "xlsx", "pdf", priority="high", sensitive=True),
            item("Other", "Tax notices, elections, disclaimers, and court documents", "pdf", sensitive=True),
            item("Completion", "Final accounting or beneficiary reporting", "pdf", "xlsx", sensitive=True),
        ),
    ),
    PbcTemplateDefinition(
        "Nonprofit Form 990",
        "Annual exempt-organization information return request list covering governance, programs, compensation, contributions, and tax compliance.",
        "tax",
        (
            item("General", "Prior-year Form 990 and all state charitable filings", "pdf", priority="high"),
            item("General", "Final trial balance and current-year financial statements", "xlsx", "pdf", priority="high"),
            item("Governance", "Current board and officer roster with titles and hours", "xlsx"),
            item("Governance", "Board minutes and changes to governing documents or policies", "pdf"),
            item("Governance", "Conflict-of-interest disclosures and related-party transactions", "pdf", "xlsx", sensitive=True),
            item("Programs", "Description and accomplishments for the three largest programs", "docx"),
            item("Revenue", "Contribution detail and donor-restriction summary", "xlsx", sensitive=True),
            item("Revenue", "Fundraising events, gaming, and noncash contribution detail", "xlsx", "pdf"),
            item("Revenue", "Program service revenue and unrelated business income detail", "xlsx"),
            item("Grants", "Grants and assistance paid to organizations and individuals", "xlsx", sensitive=True),
            item("Compensation", "Employee census and compensation by reportable component", "xlsx", priority="high", sensitive=True),
            item("Compensation", "Independent contractor payments and Forms 1099", "xlsx", "pdf", sensitive=True),
            item("Expenses", "Functional expense allocation by program, management, and fundraising", "xlsx", priority="high"),
            item("Assets", "Fixed asset, investment, endowment, and other asset schedules", "xlsx"),
            item("Liabilities", "Debt, leases, and other liability schedules", "xlsx", "pdf"),
            item("Foreign activity", "Foreign grants, offices, investments, and activities", "xlsx", "pdf", sensitive=True),
            item("Tax compliance", "Payroll, sales tax, unrelated business income, and excise tax filings", "pdf"),
            item("Tax compliance", "IRS and state correspondence", "pdf", priority="high", sensitive=True),
            item("Public support", "Donor and public-support computation detail", "xlsx", priority="high", sensitive=True),
            item("Other", "Significant transactions, joint ventures, and conservation easements", "docx", "pdf", sensitive=True),
        ),
    ),
    PbcTemplateDefinition(
        "Monthly bookkeeping and close",
        "Recurring monthly bookkeeping request list for bank feeds, revenue, expenses, payroll, reconciliations, and management reporting.",
        "bookkeeping",
        (
            item("Banking", "Bank statements for all operating, savings, and money-market accounts", "pdf", priority="high"),
            item("Banking", "Check images and explanations for unusual transfers or withdrawals", "pdf", "xlsx"),
            item("Credit cards", "Credit card statements and missing receipt support", "pdf", priority="high"),
            item("Revenue", "Sales reports and merchant processor statements", "xlsx", "pdf", priority="high"),
            item("Revenue", "Customer invoices, credits, refunds, and deposits not in the accounting system", "pdf", "xlsx"),
            item("Receivables", "Accounts receivable aging and bad-debt updates", "xlsx"),
            item("Expenses", "Vendor bills, reimbursements, and uncategorized transaction explanations", "pdf", "xlsx"),
            item("Payables", "Accounts payable aging and payment status updates", "xlsx"),
            item("Payroll", "Payroll register, payroll tax liabilities, and benefit deductions", "xlsx", "pdf", sensitive=True),
            item("Loans", "Loan and line-of-credit statements", "pdf"),
            item("Fixed assets", "Invoices for equipment, software, leasehold, or other capital purchases", "pdf"),
            item("Inventory", "Inventory movement, adjustments, and month-end count", "xlsx"),
            item("Equity", "Owner contributions, distributions, and personal charges", "xlsx", sensitive=True),
            item("Accruals", "Prepaid, deferred revenue, accrued expense, and other adjustment support", "xlsx"),
            item("Intercompany", "Intercompany charges and balance confirmations", "xlsx"),
            item("Close review", "Explanation of significant budget or prior-period variances", "docx", "xlsx"),
            item("Close review", "Approval of proposed adjusting entries", "xlsx", "pdf", priority="high"),
            item("Reporting", "Management reporting changes or one-time analysis requests", "docx"),
        ),
    ),
    PbcTemplateDefinition(
        "Year-end bookkeeping cleanup",
        "Year-end cleanup and write-up request list to prepare accurate books for financial reporting and tax return preparation.",
        "bookkeeping",
        (
            item("General", "Accounting file access or complete general ledger export", "csv", "xlsx", priority="high"),
            item("General", "Prior-year tax return and year-end adjusting entries", "pdf", "xlsx", priority="high", sensitive=True),
            item("Cash", "Year-end statements and reconciliations for all bank accounts", "pdf", "xlsx", priority="high"),
            item("Credit cards", "Year-end credit card statements and unreconciled item support", "pdf", "xlsx"),
            item("Receivables", "Year-end receivable aging and collectability assessment", "xlsx"),
            item("Revenue", "Annual sales by customer and reconciliation to Forms 1099-K", "xlsx", "pdf"),
            item("Inventory", "Year-end inventory count and valuation", "xlsx"),
            item("Fixed assets", "Asset purchases, disposals, trade-ins, and financing documents", "pdf", "xlsx"),
            item("Payables", "Year-end payable aging and unrecorded bills", "xlsx", "pdf"),
            item("Payroll", "Annual payroll registers and Forms 941, 940, W-2, and W-3", "pdf", "xlsx", sensitive=True),
            item("Contractors", "Contractor payments, Forms W-9, and Forms 1099 filed", "xlsx", "pdf", sensitive=True),
            item("Debt", "Year-end loan statements and new debt agreements", "pdf"),
            item("Leases", "New or modified lease agreements", "pdf"),
            item("Equity", "Owner contributions, distributions, draws, and personal expenses", "xlsx", sensitive=True),
            item("Taxes", "Sales, payroll, property, and income tax payments and notices", "pdf", "xlsx", sensitive=True),
            item("Accruals", "Prepaids, deposits, deferred revenue, and accrued liability support", "xlsx"),
            item("Classification", "Descriptions for uncategorized, suspense, and unusual transactions", "xlsx", priority="high"),
            item("Completion", "Approval of year-end adjusting entries", "xlsx", "pdf", priority="high"),
        ),
    ),
    PbcTemplateDefinition(
        "Client accounting services onboarding",
        "New recurring accounting client onboarding checklist for systems access, opening balances, workflows, payroll, and reporting expectations.",
        "bookkeeping",
        (
            item("Entity", "Formation documents, EIN letter, ownership, and contact roster", "pdf", "xlsx", priority="high", sensitive=True),
            item("Entity", "Prior-year tax returns and latest financial statements", "pdf", priority="high", sensitive=True),
            item("Systems", "Accounting platform administrator invitation", "pdf", priority="high", sensitive=True),
            item("Systems", "Chart of accounts and tracking-dimension requirements", "xlsx"),
            item("Banking", "Bank and credit card account list with read-only access", "xlsx", priority="high", sensitive=True),
            item("Banking", "Opening statements and latest reconciliations", "pdf", "xlsx"),
            item("Revenue", "Billing, point-of-sale, and merchant platform access", "pdf", sensitive=True),
            item("Expenses", "Accounts payable, expense, and corporate card workflows", "docx", "pdf"),
            item("Payroll", "Payroll platform access, employee census, and filing history", "xlsx", "pdf", sensitive=True),
            item("Payroll", "Benefit plans and payroll deduction setup", "pdf", "xlsx", sensitive=True),
            item("Vendors", "Vendor master, Forms W-9, and 1099 filing history", "xlsx", "pdf", sensitive=True),
            item("Assets and debt", "Fixed asset, loan, lease, and amortization schedules", "xlsx", "pdf"),
            item("Taxes", "Federal, state, and local registrations and filing calendar", "xlsx", "pdf", sensitive=True),
            item("Close", "Existing close checklist, deadlines, and approval owners", "xlsx", "docx"),
            item("Reporting", "Sample reports, KPI definitions, budget, and delivery list", "xlsx", "pdf"),
            item("Controls", "Approval limits, authorized users, and segregation-of-duties expectations", "xlsx", "docx", sensitive=True),
            item("Transition", "Open issues, outstanding filings, and prior accountant transition notes", "docx", "pdf", priority="high", sensitive=True),
        ),
    ),
    PbcTemplateDefinition(
        "Sales and use tax compliance",
        "Periodic sales and use tax compliance request list covering registrations, source data, exemptions, marketplaces, and notices.",
        "tax",
        (
            item("Profile", "Legal entity, nexus, registration, and filing-frequency matrix", "xlsx", priority="high", sensitive=True),
            item("Profile", "Prior-period returns and workpapers by jurisdiction", "pdf", "xlsx"),
            item("Sales", "Transaction-level sales data with ship-to location and tax charged", "csv", "xlsx", priority="high"),
            item("Sales", "General ledger revenue and sales tax liability detail", "xlsx", "csv", priority="high"),
            item("Sales", "Reconciliation of source data to the general ledger", "xlsx"),
            item("Exemptions", "Exempt customer and transaction listing", "xlsx"),
            item("Exemptions", "New or expired exemption certificates", "pdf", sensitive=True),
            item("Marketplaces", "Marketplace facilitator sales and tax reports", "xlsx", "pdf"),
            item("Adjustments", "Returns, credits, bad debts, and prior-period adjustment detail", "xlsx"),
            item("Purchases", "Purchases subject to use tax", "xlsx", "csv"),
            item("Payments", "Prepayments, credits, and prior-period overpayment support", "pdf", "xlsx"),
            item("Changes", "New products, locations, channels, acquisitions, or registrations", "docx", "xlsx", priority="high"),
            item("Notices", "Tax authority notices and correspondence", "pdf", priority="high", sensitive=True),
            item("Approval", "Return summary and payment authorization", "pdf", "xlsx", priority="high"),
        ),
    ),
    PbcTemplateDefinition(
        "Payroll and information return compliance",
        "Quarterly and annual payroll, Forms W-2/1099, and related information-return request list.",
        "tax",
        (
            item("Setup", "Federal and state payroll account numbers and filing frequencies", "xlsx", sensitive=True),
            item("Setup", "Prior-year Forms W-2, W-3, 1099, 1096, 940, and fourth-quarter 941", "pdf", sensitive=True),
            item("Payroll", "Payroll registers by pay date and legal entity", "xlsx", priority="high", sensitive=True),
            item("Payroll", "Quarterly Forms 941 and state payroll returns", "pdf", priority="high", sensitive=True),
            item("Payroll", "Payroll tax deposits and account transcripts", "pdf", "xlsx", sensitive=True),
            item("Employees", "Employee census with tax IDs, addresses, and work locations", "xlsx", priority="high", sensitive=True),
            item("Employees", "Taxable fringe benefits, group-term life, and imputed income", "xlsx", sensitive=True),
            item("Employees", "Retirement and health plan contribution reconciliation", "xlsx", sensitive=True),
            item("Contractors", "Vendor and contractor payment detail", "xlsx", priority="high", sensitive=True),
            item("Contractors", "Current Forms W-9 and foreign payee documentation", "pdf", priority="high", sensitive=True),
            item("Contractors", "Payment processor and corporate-card exclusion detail", "xlsx"),
            item("Equity", "Stock compensation exercises and taxable benefit detail", "xlsx", sensitive=True),
            item("Reconciliation", "Payroll expense and liability reconciliation to the general ledger", "xlsx", priority="high"),
            item("Changes", "Entity, state registration, payroll provider, or workforce changes", "docx", "xlsx"),
            item("Notices", "Federal and state payroll or information-return notices", "pdf", priority="high", sensitive=True),
            item("Approval", "Final W-2 and 1099 recipient statement approval", "pdf", "xlsx", priority="high", sensitive=True),
        ),
    ),
    PbcTemplateDefinition(
        "Budgeting and cash-flow advisory",
        "Management advisory request list for building a driver-based budget, cash forecast, scenarios, and KPI reporting package.",
        "advisory",
        (
            item("Historical", "Monthly trial balance and financial statements for the prior 24-36 months", "xlsx", "csv", priority="high"),
            item("Historical", "Current budget, forecast, and budget-to-actual reporting", "xlsx"),
            item("Revenue", "Revenue history by customer, product, channel, and geography", "xlsx", priority="high"),
            item("Revenue", "Sales pipeline, backlog, churn, and pricing assumptions", "xlsx"),
            item("Costs", "Headcount roster, compensation, open roles, and hiring plan", "xlsx", priority="high", sensitive=True),
            item("Costs", "Vendor spend, contracts, and committed purchase obligations", "xlsx", "pdf"),
            item("Working capital", "Receivable, payable, inventory, and deferred revenue detail", "xlsx"),
            item("Cash", "Current bank balances, restrictions, and minimum cash requirements", "xlsx", sensitive=True),
            item("Debt", "Debt schedule, covenants, rates, and availability", "xlsx", "pdf", priority="high", sensitive=True),
            item("Capital", "Capital expenditure plan and financing assumptions", "xlsx"),
            item("Taxes", "Expected income, payroll, sales, and property tax payment schedule", "xlsx", sensitive=True),
            item("Strategy", "Management goals, known initiatives, risks, and scenario definitions", "docx", "pdf", priority="high"),
            item("KPIs", "KPI definitions, source systems, targets, and owners", "xlsx"),
            item("Reporting", "Board, lender, and investor reporting requirements", "pdf", "docx", sensitive=True),
            item("Approval", "Approved model assumptions and scenario selections", "xlsx", "pdf", priority="high"),
        ),
    ),
    PbcTemplateDefinition(
        "Financial due diligence and quality of earnings",
        "Buy-side or sell-side financial diligence request list for quality of earnings, working capital, debt-like items, and deal analytics.",
        "advisory",
        (
            item("General", "Monthly trial balances and general ledgers for the historical period", "xlsx", "csv", priority="high", sensitive=True),
            item("General", "Audited, reviewed, or management financial statements", "pdf", "xlsx", priority="high", sensitive=True),
            item("General", "Budgets, forecasts, board decks, and lender reporting", "xlsx", "pdf", sensitive=True),
            item("Revenue", "Transaction-level revenue by customer, product, location, and channel", "csv", "xlsx", priority="high", sensitive=True),
            item("Revenue", "Top customer contracts, pricing, rebates, and renewal terms", "pdf", "xlsx", sensitive=True),
            item("Revenue", "Bookings, backlog, pipeline, churn, and cohort data", "xlsx", sensitive=True),
            item("Margins", "Product or service gross margin detail", "xlsx", priority="high", sensitive=True),
            item("Expenses", "Detailed operating expense and vendor spend", "xlsx", "csv", sensitive=True),
            item("Payroll", "Employee census, compensation, bonuses, contractors, and open roles", "xlsx", priority="high", sensitive=True),
            item("Adjustments", "Management-proposed EBITDA adjustments with support", "xlsx", "pdf", priority="high", sensitive=True),
            item("Working capital", "Monthly receivable, payable, inventory, and deferred revenue balances", "xlsx", priority="high", sensitive=True),
            item("Working capital", "Aging reports, reserves, write-offs, and seasonality analysis", "xlsx", sensitive=True),
            item("Debt-like items", "Debt, leases, deferred consideration, and other obligations", "xlsx", "pdf", priority="high", sensitive=True),
            item("Capital expenditures", "Historical and forecast capital expenditures", "xlsx"),
            item("Taxes", "Income, payroll, sales, and property tax returns and exposures", "pdf", "xlsx", sensitive=True),
            item("Legal", "Litigation, claims, commitments, guarantees, and regulatory matters", "pdf", "docx", sensitive=True, requires_redaction=True),
            item("Related parties", "Related-party revenue, expenses, balances, and normalization items", "xlsx", sensitive=True),
            item("Accounting", "Revenue recognition, inventory costing, capitalization, and reserve policies", "docx", "pdf"),
            item("Systems", "Accounting systems, data dictionaries, and reporting limitations", "docx", "xlsx"),
            item("Deal", "Purchase agreement, letter of intent, and definition of deal metrics", "pdf", priority="high", sensitive=True),
            item("Deal", "Management interview schedule and data-room index", "xlsx", "docx", sensitive=True),
            item("Completion", "Responses to open diligence questions and data reconciliations", "xlsx", "docx", priority="high", sensitive=True),
        ),
    ),
)


PBC_TEMPLATE_NAMES = tuple(definition.name for definition in PBC_TEMPLATE_LIBRARY)

