import { LegalPage, type LegalSection } from '@/components/marketing/LegalPage'
import { generateMetadata, pageMetadata } from '@/lib/metadata'

export const metadata = generateMetadata(pageMetadata.terms)

const sections: LegalSection[] = [
  { id: 'acceptance', title: 'Acceptance of terms', content: <><p>By accessing or using CPAAutomation&apos;s document processing services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p><p>These terms constitute a legal agreement between you and CPAAutomation regarding your use of our platform.</p></> },
  { id: 'service', title: 'Service description', content: <><h3>What we provide</h3><ul><li>AI-powered document data extraction services</li><li>Custom extraction rule creation and templates</li><li>Professional-grade processing developed by CPAs and lawyers</li><li>Export capabilities to Excel, Google Sheets, and CSV formats</li><li>API access for integration with your existing systems</li><li>Customer support and technical assistance</li></ul><p><strong>Service availability:</strong> We strive to maintain 99.9% uptime but cannot guarantee uninterrupted service. Scheduled maintenance will be announced in advance when possible.</p></> },
  { id: 'responsibilities', title: 'User responsibilities', content: <><h3>Account security</h3><ul><li>Maintain the confidentiality of your account credentials</li><li>Notify us immediately of any unauthorized account access</li><li>Use strong passwords and enable two-factor authentication</li><li>Do not share your API keys or account access</li></ul><h3>Document upload requirements</h3><ul><li>Only upload documents you own or have permission to process</li><li>Ensure documents do not contain malware or malicious code</li><li>Comply with all applicable laws regarding document processing</li><li>Do not upload documents containing illegal content</li></ul><h3>Acceptable use</h3><ul><li>Use the service only for legitimate business purposes</li><li>Do not attempt to reverse engineer our systems</li><li>Respect usage limits based on your subscription plan</li><li>Do not process documents for competitive analysis</li></ul></> },
  { id: 'billing', title: 'Billing and payments', content: <><h3>Subscription plans</h3><p>Monthly subscriptions are billed in advance on the same day each month. Annual plans are billed annually in advance.</p><ul><li>Basic plan: $9.99/month for 500 pages</li><li>Professional plan: $49.99/month for 5,000 pages</li><li>Enterprise plan: custom pricing with unlimited pages and users</li></ul><h3>Payment processing</h3><p>Payments are processed securely through our payment providers. We accept major credit cards and ACH transfers for enterprise accounts.</p><h3>Refunds and cancellations</h3><p>You may cancel your subscription at any time. Cancellations take effect at the end of your current billing period. We do not provide refunds for partial months or unused pages.</p><h3>Late payments</h3><p>Accounts with failed payments may be suspended after 7 days. Service will be restored upon successful payment.</p></> },
  { id: 'ip', title: 'Intellectual property', content: <><h3>Our rights</h3><p>CPAAutomation retains all rights to our software, algorithms, AI models, and extraction methodologies. Users receive a license to use our services but do not acquire ownership rights.</p><h3>Your rights</h3><p>You retain all rights to your uploaded documents and extracted data. We do not claim ownership of your content and will not use it for any purpose other than providing our services.</p><h3>License grant</h3><p>You grant us a limited license to process your documents solely for the purpose of providing extraction services. This license terminates when files are deleted from our systems.</p></> },
  { id: 'disclaimers', title: 'Important disclaimers', content: <><h3>Accuracy disclaimer</h3><p>While our AI extraction is designed and validated by CPAs and lawyers, we cannot guarantee 100% accuracy. Users should review and verify extracted data before using it for business decisions.</p><h3>Service availability</h3><p>We provide services on an “as is” basis and cannot guarantee uninterrupted access. Maintenance, updates, or technical issues may temporarily affect service availability.</p><h3>Limitation of liability</h3><p>Our liability is limited to the amount paid for services in the preceding 12 months. We are not liable for indirect, incidental, or consequential damages.</p></> },
  { id: 'termination', title: 'Termination', content: <><h3>User-initiated termination</h3><p>You may terminate your account at any time through your dashboard settings or by contacting support. Upon termination, your data will be deleted within 30 days.</p><h3>Service-initiated termination</h3><p>We may suspend or terminate accounts for violation of these terms, illegal activity, or non-payment. We will provide notice when possible before termination.</p><h3>Effect of termination</h3><p>Upon termination, your access to the service will cease immediately. You may export your data before termination, as we cannot guarantee data availability afterward.</p></> },
  { id: 'law', title: 'Governing law', content: <><p>These Terms of Service are governed by the laws of the United States. Any disputes will be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.</p><p>If any provision of these terms is found to be unenforceable, the remaining provisions will remain in full force and effect.</p></> },
  { id: 'questions', title: 'Questions about these terms?', content: <><p>If you have questions about these Terms of Service, please contact us:</p><ul><li>Email: <a className="ps-link" href="mailto:legal@CPAAutomation.ai">legal@CPAAutomation.ai</a></li><li>Address: United States (US-based legal team)</li></ul></> },
  { id: 'updates', title: 'Terms updates', content: <p>We may update these Terms of Service from time to time. Material changes will be communicated via email and posted on our website 30 days before taking effect. Continued use of our services after changes indicates acceptance of the updated terms.</p> },
]

export default function TermsPage() { return <LegalPage title="Terms of service" description="Legal terms and conditions for using CPAAutomation." lastUpdated="August 2025" sections={sections} /> }
