import Link from 'next/link'
import { ClawInstaller } from '@/components/marketing/ClawInstaller'
import { generateMetadata, pageMetadata } from '@/lib/metadata'

export const metadata = generateMetadata(pageMetadata.claw)

export default function ClawPage() { return <main id="main-content">
  <section className="ps-page-hero ps-page-hero--dark ps-grid-bg"><div className="ps-container ps-page-hero__split"><div><span className="ps-label">Now available · personalized setup</span><h1>Claw Series — digital workers, deployed your way</h1></div><div><p className="ps-kicker">AccountingClaw, FinanceClaw, and LegalClaw run hundreds of pre-built skills autonomously, with guardrails built for accounting, finance, and legal workflows. AccountingClaw and LegalClaw are available self-service today — deploy in your cloud or on your desktop, pick the model and skills, or let us configure everything for you.</p><div className="ps-button-row"><Link className="ps-button ps-button--light" href="/contact">Contact us to get started</Link><a className="ps-link" href="#installation">Install a digital worker</a></div></div></div></section>
  <section className="ps-section ps-dark" id="installation"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">Installation options</span><h2>Deploy your digital workers — cloud or desktop</h2></div><p>Run AccountingClaw or LegalClaw as a cloud digital worker with Docker, or as a desktop digital worker on the Hermes Desktop app. All installs unlock with the same personal activation key.</p></div><ClawInstaller /></div></section>
  <section className="ps-section"><div className="ps-container ps-showcase"><div><span className="ps-label">Claw Series</span><h2>Autonomous digital workers for accounting, finance & legal</h2><p className="ps-kicker">Not just tools you operate — digital workers you deploy. Each Claw runs hundreds of pre-built skills end-to-end, with guardrails designed for regulated environments.</p><ul className="ps-feature-list"><li>Automated bank reconciliations</li><li>Contract clause extraction and review</li><li>Tax form preparation and validation</li><li>Regulatory compliance checks</li></ul><Link className="ps-link" href="/demo">AccountingClaw Preview · Dual Agent Technical Accounting Memo · AI Skill for Browser Automation</Link></div><div className="ps-terminal"><div className="ps-window-bar"><span>claw_orchestrator</span><span>guardrails enabled</span></div><pre>REQUEST → PLAN → EXECUTE → REVIEW{`\n\n`}AccountingClaw{`\n`}  ↳ reconcile ledger{`\n`}  ↳ prepare journal entries{`\n`}  ↳ assemble working paper{`\n\n`}LegalClaw{`\n`}  ↳ classify agreement{`\n`}  ↳ extract clauses{`\n`}  ↳ draft review memo{`\n\n`}<span className="accent">Human approval required before release.</span></pre></div></div></section>
  <section className="ps-section ps-section--muted"><div className="ps-container"><div className="ps-section-head"><div><h2>Choose your stack, or let us choose it for you</h2></div><p>Tell us your preferences and we&apos;ll deploy AccountingClaw, FinanceClaw, and LegalClaw on the infrastructure and models you already trust.</p></div><div className="ps-card-grid"><article className="ps-info-card"><span className="ps-label">Cloud provider</span><h3>Run where you already work</h3><p>Run Claw on the cloud you already use, or keep everything inside your own VPC.</p><ul><li>Amazon Web Services (AWS)</li><li>Google Cloud Platform (GCP)</li><li>Microsoft Azure</li><li>Self-hosted in your VPC</li></ul></article><article className="ps-info-card"><span className="ps-label">AI model</span><h3>Pick the right foundation</h3><p>Pick the foundation model that fits your accuracy, latency, and data-residency requirements.</p><ul><li>Anthropic Claude</li><li>OpenAI GPT</li><li>Google Gemini</li><li>Open-source (Llama, Mistral)</li></ul></article><article className="ps-info-card"><span className="ps-label">Skill packages</span><h3>One Claw or all three</h3><p>Deploy one Claw or all three. Each comes with hundreds of domain-specific skills out of the box.</p><ul><li>AccountingClaw — Bank reconciliations, journal entries, month-end close</li><li>FinanceClaw (Coming Soon) — FP&A automations, flux analysis, reporting packs</li><li>LegalClaw — 1,251 legal skills across 24 practice areas — drafting, review, diligence, compliance</li></ul></article></div><p>Don&apos;t see your preferred provider or model? Tell us in your message — we can usually accommodate.</p></div></section>
  <section className="ps-section"><div className="ps-container ps-showcase"><div><span className="ps-label">White-glove setup</span><h2>Prefer white-glove setup?</h2><p className="ps-kicker">We&apos;ll pick the cloud, model, and skill mix based on your firm&apos;s size, compliance needs, and budget — then deploy, train your team, and stay on for ongoing tuning.</p><div className="ps-button-row"><Link className="ps-button" href="/contact">Talk to our team</Link><Link className="ps-link" href="/demo">View demo videos</Link></div></div><div className="ps-ui"><div className="ps-ui__bar"><span>personalized_setup.plan</span><span>ready to scope</span></div><div className="ps-ui__body"><div className="ps-pipeline"><article><span className="ps-label">01</span><strong>Cloud</strong><p>Your VPC</p></article><article><span className="ps-label">02</span><strong>Model</strong><p>Your choice</p></article><article><span className="ps-label">03</span><strong>Skills</strong><p>Configured for your firm</p></article></div></div></div></div></section>
  <section className="ps-cta"><div className="ps-container ps-cta__inner"><div><span className="ps-label">Ready when you are</span><h2>Deploy your first Claw in days, not months</h2><p>Reach out and we&apos;ll scope a setup tailored to your firm — including pricing, security review, and a deployment timeline.</p></div><div className="ps-button-row"><Link className="ps-button ps-button--light" href="/contact">Contact us</Link><Link className="ps-button ps-button--outline" href="/pricing">View pricing</Link></div></div></section>
</main> }
