import Link from 'next/link'

import { ProtectedAction } from '@/components/marketing/ProtectedAction'
import { generateMetadata, pageMetadata } from '@/lib/metadata'

export const metadata = generateMetadata(pageMetadata.caseStudyLFO)

export default function LfoCaseStudy() {
  return <main id="main-content">
    <section className="ps-page-hero ps-page-hero--dark ps-grid-bg"><div className="ps-container"><Link className="ps-link" href="/">← Back to home</Link><p className="ps-label">Leonardo Family Office case study</p><h1>How a leading family office firm automated investment statement processing and saved hundreds of hours annually.</h1></div></section>
    <section className="ps-section ps-section--tight"><div className="ps-container ps-metrics">{[['200+','Hours saved annually'],['100+','Portfolio companies — Processed quarterly'],['95%','Time reduction'],['$100K+','Annual savings']].map(([a,b])=><div key={b}><strong>{a}</strong><span>{b}</span></div>)}</div></section>
    <section className="ps-section ps-section--muted"><div className="ps-container ps-report-grid"><nav className="ps-report-nav" aria-label="Case study contents">{[['firm','The firm'],['challenge','The challenge'],['solution','The solution'],['results','Results & impact']].map(([id,label])=><a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="ps-report-body">
      <section id="firm"><span className="ps-label">01 · The firm</span><h2>About Leonardo Family Office</h2><p>Leonardo Family Office (LFO) is a leading ESG and technology-focused family office management firm.</p><ul><li>ESG & technology-focused family office</li><li>100+ portfolio companies</li><li>Quarterly reporting cycles</li><li>15+ investment professionals</li></ul><div className="ps-ui" role="img" aria-label="Investment team meeting"><div className="ps-ui__body"><div className="ps-system-map"><span>15+ investment professionals</span><span>100+ companies</span><span>Quarterly cycle</span><span>ESG & technology</span></div></div></div></section>
      <section id="challenge"><span className="ps-label">02 · The challenge</span><h2>The challenge</h2><p>LFO&apos;s investment team was spending an overwhelming amount of time manually processing quarterly financial statements from their portfolio companies.</p><h3>Key pain points</h3><ul><li>Manual extraction of financial metrics from 100+ portfolio companies quarterly</li><li>Inconsistent document formats from different companies</li><li>Time-sensitive quarterly reporting deadlines</li><li>Risk of human error in data transcription</li><li>Limited scalability for growing portfolio</li></ul></section>
      <section id="solution"><span className="ps-label">03 · The solution</span><h2>The solution</h2><p>Leonardo Family Office implemented our PDF extraction platform to automate their quarterly reporting workflow — with custom extraction templates for financial metrics and automated data validation.</p><ul><li>Custom extraction templates for revenue, equity, and valuation metrics</li><li>Automated classification of valuation types</li><li>Recognition of different foreign currencies used in statements</li><li>Quality assurance workflows for data validation</li></ul><div className="ps-ui" role="img" aria-label="Data extraction dashboard"><div className="ps-ui__bar"><span>Extraction results</span><span>99.8% verified</span></div><div className="ps-ui__body"><table className="ps-table"><thead><tr><th>Portfolio company</th><th>Revenue</th><th>Equity</th><th>Currency</th><th>Validation</th></tr></thead><tbody><tr><td>Technology portfolio 01</td><td>$12.5M</td><td>$42.8M</td><td>USD</td><td>Verified</td></tr><tr><td>ESG portfolio 07</td><td>€8.2M</td><td>€29.1M</td><td>EUR</td><td>Verified</td></tr></tbody></table></div></div></section>
      <section id="results"><span className="ps-label">04 · Results & impact</span><h2>Measurable outcomes</h2><blockquote>“Our team used to spend weeks manually extracting financial data from portfolio reports. Now we process quarterly statements from 100+ companies in just minutes with perfect accuracy. This transformation has allowed our investment professionals to focus on what they do best: identifying opportunities and supporting our portfolio companies.”<footer>C**** Leonardo — CFO · Leonardo Family Office</footer></blockquote><div className="ps-card-grid"><article className="ps-info-card"><h3>Time savings</h3><ul><li>Quarterly processing reduced from 3 days to 2 hours</li><li>Individual report processing: 30 min → 5 sec</li><li>95% reduction in manual data entry</li><li>Freed up 200+ hours annually</li></ul></article><article className="ps-info-card"><h3>Quality improvements</h3><ul><li>99.8% accuracy in data extraction</li><li>Eliminated transcription errors</li><li>Standardized data formats across portfolio</li><li>Real-time validation and error detection</li></ul></article></div></section>
    </div></div></section>
    <section className="ps-cta"><div className="ps-container ps-cta__inner"><div><span className="ps-label">Get started</span><h2>Ready to transform your document processing?</h2><p>See how our PDF extraction platform can help your organization save time and improve accuracy.</p></div><ProtectedAction destination="/dashboard" className="ps-button ps-button--light">Try it now</ProtectedAction></div></section>
  </main>
}
