/* Client-side GeoJSON built from bundled / static TopoJSON. No tile server or API key needed.
 *  - World: world-atlas countries-110m (bundled). Feature `id` = ISO 3166-1 numeric string (e.g. "840").
 *  - Sub-national: /geo/admin1/<ISO2>.json, generated by scripts/build-admin1.mjs from Natural Earth 1:10m
 *    admin-1 (see docs/geometry.md). Feature `id` = ISO 3166-2 code, which is also the API's jurisdiction code
 *    ("US-CA", "BR-SP", "JP-13"), so the choropleth joins on `code` with no lookup table. */
import { feature } from "topojson-client";
import type { Topology, GeometryCollection } from "topojson-specification";
import type { FeatureCollection, Geometry, Position } from "geojson";
import { US_STATE_METRICS, WORLD_METRICS as _WORLD_METRICS, defaultMetricId, metricsFor, type MetricDef } from "./rates";
import type { SubnationalCountry } from "./types";

export type Bounds = [[number, number], [number, number]];

export interface GeoProps {
  name: string;
  /** Join key: iso_numeric for countries, ISO 3166-2 code for sub-national features. */
  key: string;
  /** Legacy / alternative codes that also identify this feature (e.g. NE's IN-CT for IN-CG). */
  alt?: string[];
}
export type GeoFC = FeatureCollection<Geometry, GeoProps>;
export type JoinField = "iso_numeric" | "fips" | "code";

/* ------------------------------------------------------------------------------------------------
   Admin-1 manifest (public/geo/admin1/index.json). Written by the build script; lists every country with a
   geometry file. The SPA fallback answers unknown paths with index.html (HTTP 200), so "does this country have
   geometry" is read from the manifest rather than probed with fetch.
   ------------------------------------------------------------------------------------------------ */
export interface Admin1Entry {
  file: string;
  features: number;
  bytes: number;
  gzip: number;
  /** Build-time guess at the jurisdiction level; the API's value wins when it has one. */
  level: string;
  /** Camera fit ([[w, s], [e, n]]); equals bbox unless the build overrides it (US lower 48, FR metropolitan…). */
  bounds: Bounds;
  bbox: Bounds;
  codes: string[];
  remaps: Array<{ from: string; to: string }>;
}
export interface Admin1Manifest {
  version: string;
  generated_at: string;
  source: { name: string; version: string; url: string; etag?: string | null; license?: string };
  countries: Record<string, Admin1Entry>;
}

export const ADMIN1_BASE = "/taxatlas/geo/admin1";

let manifestCache: Promise<Admin1Manifest> | null = null;
export function loadAdmin1Manifest(): Promise<Admin1Manifest> {
  if (!manifestCache) {
    manifestCache = fetchJson<Admin1Manifest>(`${ADMIN1_BASE}/index.json`).catch((e) => {
      manifestCache = null; // allow a retry on the next call
      throw e;
    });
  }
  return manifestCache;
}

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url, { headers: { Accept: "application/json" } });
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  const type = res.headers.get("content-type") ?? "";
  // The SPA fallback returns index.html with 200 for unknown paths; refuse to parse it as geometry.
  if (!/json/i.test(type)) throw new Error(`${url}: not JSON (${type || "no content-type"})`);
  return (await res.json()) as T;
}

/** Describes a drillable country: what the API knows (children, metrics) merged with whether a geometry file
 *  exists. Built at runtime by buildDrillRegistry(); nothing here is hard-coded per country. */
export interface DrillLayer {
  parent: string;
  name: string;
  /** Jurisdiction level of the children ("state", "province", "region", …). */
  level: string;
  /** Active child jurisdictions per the API (0 when the API has none / is unreachable). */
  children: number;
  /** Metrics with sub-national coverage, in display (grouped) order. Empty = geography only. */
  metrics: MetricDef[];
  /** Metric the drill opens on (US: sales & use), or null when there are none. */
  defaultMetric: string | null;
  /** Geometry manifest entry, or null when only a list fallback is possible. */
  geometry: Admin1Entry | null;
  bounds: Bounds;
}

/** Preferred metric order per country (known labels, stable E2E contract). Anything else the API reports is
 *  appended by coverage. */
const PREFERRED_METRICS: Record<string, MetricDef[]> = { US: US_STATE_METRICS };

/** Merge /map/subnational with the geometry manifest. A country appears when either side knows it:
 *  API-only → list fallback in the drawer; geometry-only → drill renders geography with a "no rate data" legend. */
export function buildDrillRegistry(sub: SubnationalCountry[] | undefined, manifest: Admin1Manifest | null): Record<string, DrillLayer> {
  const out: Record<string, DrillLayer> = {};
  for (const s of sub ?? []) {
    const g = manifest?.countries[s.code] ?? null;
    const metrics = metricsFor(s.metrics, s.code);
    out[s.code] = {
      parent: s.code,
      name: s.name,
      level: s.level,
      children: s.children,
      metrics,
      defaultMetric: defaultMetricId(metrics, PREFERRED_METRICS[s.code] ?? []),
      geometry: g,
      bounds: g?.bounds ?? WORLD_BOUNDS,
    };
  }
  for (const [code, g] of Object.entries(manifest?.countries ?? {})) {
    if (out[code]) continue;
    out[code] = { parent: code, name: code, level: g.level, children: 0, metrics: [], defaultMetric: null, geometry: g, bounds: g.bounds };
  }
  return out;
}

/** "state" → "states", "territory" → "territories". */
export function pluralLevel(level: string): string {
  if (!level) return "sub-national jurisdictions";
  if (/y$/.test(level)) return level.replace(/y$/, "ies");
  if (/(s|x|ch|sh)$/.test(level)) return `${level}es`;
  return `${level}s`;
}

/* ------------------------------------------------------------------------------------------------ */

/** Unwrap rings that cross the antimeridian (consecutive vertices at +180/−180) so MapLibre does not
 *  tessellate a wedge across the whole map. A ring whose longitude span exceeds 180° is shifted so all
 *  vertices sit on the side where most of them already are (e.g. Chukotka → lon 190, Aleutians → lon −181).
 *  geojson-vt wraps out-of-range longitudes back into the primary world copy when tiling. */
function unwrapRing(ring: Position[]): Position[] {
  let min = Infinity;
  let max = -Infinity;
  let negatives = 0;
  for (const [lon] of ring) {
    if (lon < min) min = lon;
    if (lon > max) max = lon;
    if (lon < 0) negatives++;
  }
  if (max - min <= 180) return ring;
  const shiftNegatives = negatives < ring.length / 2;
  return ring.map(([lon, lat, ...rest]) => {
    if (shiftNegatives && lon < 0) return [lon + 360, lat, ...rest];
    if (!shiftNegatives && lon > 0) return [lon - 360, lat, ...rest];
    return [lon, lat, ...rest];
  });
}

export function unwrapGeometry(g: Geometry): Geometry {
  if (g.type === "Polygon") return { type: "Polygon", coordinates: g.coordinates.map(unwrapRing) };
  if (g.type === "MultiPolygon") return { type: "MultiPolygon", coordinates: g.coordinates.map((poly) => poly.map(unwrapRing)) };
  return g;
}

let worldCache: Promise<GeoFC> | null = null;
export function loadWorld(): Promise<GeoFC> {
  if (!worldCache) {
    worldCache = import("world-atlas/countries-110m.json").then((mod) => {
      const topo = (mod.default ?? mod) as unknown as Topology<{ countries: GeometryCollection<{ name: string }> }>;
      const fc = feature(topo, topo.objects.countries) as FeatureCollection<Geometry, { name: string }>;
      return {
        type: "FeatureCollection",
        features: fc.features
          .filter((f) => f.id !== undefined && f.id !== "010") // drop Antarctica entirely (no tax data, tessellation noise)
          .map((f) => ({
            type: "Feature",
            id: f.id,
            geometry: unwrapGeometry(f.geometry),
            properties: { name: f.properties?.name ?? "", key: String(f.id ?? "") },
          })),
      };
    });
  }
  return worldCache;
}

/** US states from us-atlas (FIPS ids). The map no longer uses this — the admin-1 pipeline covers the US with
 *  ISO codes — but the jurisdiction-detail locator (components/detail/MiniMap.tsx) still draws from it. */
let usCache: Promise<GeoFC> | null = null;
export function loadUsStates(): Promise<GeoFC> {
  if (!usCache) {
    usCache = import("us-atlas/states-10m.json").then((mod) => {
      const topo = (mod.default ?? mod) as unknown as Topology<{ states: GeometryCollection<{ name: string }> }>;
      const fc = feature(topo, topo.objects.states) as FeatureCollection<Geometry, { name: string }>;
      return {
        type: "FeatureCollection",
        features: fc.features.map((f) => ({
          type: "Feature",
          id: f.id,
          geometry: unwrapGeometry(f.geometry), // Aleutians cross the antimeridian
          properties: { name: f.properties?.name ?? "", key: String(f.id ?? "").padStart(2, "0") },
        })),
      };
    });
  }
  return usCache;
}

type Admin1Topology = Topology<{ admin1: GeometryCollection<{ name: string; alt?: string[] }> }>;
const admin1Cache = new Map<string, Promise<GeoFC>>();

/** Sub-national geometry for one country. The build script already unwrapped antimeridian rings, but the same
 *  rule is applied again so a hand-edited file cannot regress the world view. */
export function loadAdmin1(code: string, manifest: Admin1Manifest): Promise<GeoFC> {
  const entry = manifest.countries[code];
  if (!entry) return Promise.reject(new Error(`No sub-national geometry for ${code}`));
  let p = admin1Cache.get(code);
  if (!p) {
    p = fetchJson<Admin1Topology>(`${ADMIN1_BASE}/${entry.file}?v=${encodeURIComponent(manifest.version)}`)
      .then((topo) => {
        const fc = feature(topo, topo.objects.admin1) as FeatureCollection<Geometry, { name: string; alt?: string[] }>;
        return {
          type: "FeatureCollection" as const,
          features: fc.features.map((f) => ({
            type: "Feature" as const,
            id: f.id,
            geometry: unwrapGeometry(f.geometry),
            properties: { name: f.properties?.name ?? "", key: String(f.id ?? ""), ...(f.properties?.alt ? { alt: f.properties.alt } : {}) },
          })),
        };
      })
      .catch((e) => {
        admin1Cache.delete(code);
        throw e;
      });
    admin1Cache.set(code, p);
  }
  return p;
}

/** Country-level metrics (defined in rates.ts; re-exported so callers keep one import). */
export const WORLD_METRICS: MetricDef[] = _WORLD_METRICS;

// Latitude capped at ±~58/72 so the fit is width-driven on 16:10 screens (polar areas have no tax data anyway).
export const WORLD_BOUNDS: Bounds = [[-168, -56], [180, 72]];

/* ------------------------------------------------------------------------------------------------
   Legend bins. The choropleth uses k discrete classes (never a continuous ramp). Quantile by default
   so clustered distributions (VAT at 20 %, US sales tax 4–7 %) still spread across the palette;
   equal-interval is available for presentations where round edges read better.
   ------------------------------------------------------------------------------------------------ */
export type BinMethod = "quantile" | "equal";

export interface Bins {
  /** Lower edge of every bin, ascending. ticks.length === number of bins (k). ticks[0] === min. */
  ticks: number[];
  /** Jurisdictions per bin (same length as ticks). */
  counts: number[];
  min: number;
  max: number;
  /** Total values binned (those with data). */
  n: number;
  method: BinMethod;
}

/** Bin count rule from pages/map.md: 7 when n ≥ 20, else n − 1 (min 1), so a metric with 10 values gets 7
 *  and one with 3 values gets 2 instead of seven near-empty classes. */
export function binCount(n: number, max = 7): number {
  if (n <= 1) return 1;
  if (n >= 20) return max;
  return Math.max(1, Math.min(max, n - 1));
}

export function computeBins(values: number[], method: BinMethod = "quantile", maxBins = 7): Bins {
  const xs = values.filter((v) => Number.isFinite(v)).sort((a, b) => a - b);
  const n = xs.length;
  if (n === 0) return { ticks: [], counts: [], min: 0, max: 0, n: 0, method };
  const min = xs[0];
  const max = xs[n - 1];
  const k = binCount(n, maxBins);
  let edges: number[] = [min];
  if (k > 1 && max > min) {
    if (method === "equal") {
      const step = (max - min) / k;
      for (let i = 1; i < k; i++) edges.push(min + step * i);
    } else {
      // Lower edge of bin i is the value at quantile i/k (R-7 linear interpolation, as d3.quantile).
      for (let i = 1; i < k; i++) {
        const pos = ((n - 1) * i) / k;
        const lo = Math.floor(pos);
        const hi = Math.min(n - 1, lo + 1);
        edges.push(xs[lo] + (xs[hi] - xs[lo]) * (pos - lo));
      }
    }
    // Ties collapse duplicate edges: fewer, honest bins instead of empty classes with identical labels.
    edges = edges.filter((e, i, arr) => i === 0 || e > arr[i - 1] + 1e-9);
  }
  const counts = new Array<number>(edges.length).fill(0);
  xs.forEach((v) => counts[binIndex(v, edges)]++);
  return { ticks: edges, counts, min, max, n, method };
}

/** Index of the bin whose [lower, next-lower) range contains v; the last bin is open-ended. */
export function binIndex(v: number, ticks: number[]): number {
  let i = 0;
  while (i + 1 < ticks.length && v >= ticks[i + 1]) i++;
  return i;
}

/** Which of the 7 palette steps to use for k bins: always the two ends, evenly spaced in between. */
export function rampIndices(k: number, steps = 7): number[] {
  if (k <= 1) return [Math.floor(steps * 0.6)];
  return Array.from({ length: k }, (_, i) => Math.round((i * (steps - 1)) / (k - 1)));
}
