import Link from 'next/link'
import { ArrowRight, Check, LockKeyhole } from 'lucide-react'

import { Announcement } from '@/components/marketing/Announcement'
import { ProtectedAction } from '@/components/marketing/ProtectedAction'
import { Testimonials } from '@/components/marketing/Testimonials'
import { protectedDestinations } from '@/lib/marketing/config'
import { generateMetadata, pageMetadata } from '@/lib/metadata'

export const metadata = generateMetadata(pageMetadata.home)

const suite = [
  ['Universal Document Analysis', 'Extract, analyze, and automate any document type with AI precision.', '/features'],
  ['Form Fill', 'Auto-fill PDFs and Word documents from extraction results, uploaded sources, or saved templates.', '/#form-fill'],
  ['Inkwise', 'AI-powered writing with citation-grounded references from your own documents.', '/#inkwise'],
  ['Tasklytic', 'Plan projects, coordinate teams, track time, and automate the work that keeps engagements moving.', '/#tasklytic'],
  ['Prepared by Client (PBC)', 'Build request lists, collect files securely, review submissions, and package client evidence.', '/#pbc'],
  ['E-Signature', 'Prepare, send, sign, and track documents with reusable templates and completion evidence.', '/#e-signature'],
  ['Chrona', 'Automatic time tracking that syncs AI-built daily timelines from staff devices into your firm dashboard.', '/#chrona'],
  ['AccountingClaw / FinanceClaw / LegalClaw', 'Digital workers with hundreds of pre-built skills for regulated industries.', '/claw'],
  ['AI Analytics Suite', 'Variance & flux analysis, reconciliation, fixed assets, and distribution waterfalls — with IRS/GAAP research bots and a context-aware AI assistant.', '/#ai-analytics'],
] as const

const faq = [
  ['How accurate is the AI extraction?', 'Our AI achieves 99%+ accuracy on structured documents like invoices and financial statements. For complex documents, accuracy typically ranges from 95-99%. You can always review and edit results before export.'],
  ['What file types are supported?', 'We support PDF, DOCX, XLSX, PPTX, TXT, CSV, and most image formats (PNG, JPG, TIFF). We can also process scanned documents and handle multi-page files with complex layouts.'],
  ['How does email automation work?', 'Simply forward emails with PDF attachments to document@cpaautomation.ai. Our system matches your sender email to your account, applies your automation filters, and processes documents using your configured templates. Results are automatically exported to your chosen destination.'],
  ['Can I customize the extraction fields?', 'Absolutely! You can create custom fields with your own prompts, data types, and formatting rules. Add accounting codes, classification rules, or any business-specific logic. Templates can be saved and reused across projects.'],
  ['Is there a learning curve?', "CPAAutomation is designed for professionals who don't have time for complex training. Most users are extracting data within 10 minutes of signing up. Our CPA-designed interface follows familiar workflows."],
  ['What about data security and privacy?', 'Your data is encrypted in transit and at rest, hosted only in US data centers, and automatically deleted after processing. We never use your documents to train AI models. Our platform meets the security standards required by CPA firms and legal practices.'],
  ['What products are included in CPAAutomation?', 'CPAAutomation includes Universal Document Analysis (extraction & automations), Form Fill, Inkwise (AI writing with grounded citations), Tasklytic (projects, team coordination, time, forms & reporting), Prepared by Client (secure request lists and evidence collection), E-Signature, Chrona (time tracking), the Claw Series of AI digital workers, the AI Analytics Suite (variance, reconciliation, fixed assets, waterfalls & research bots), and a free CPE Tracker.'],
] as const

function WindowBar({ title, state }: { title: string; state: string }) {
  return <div className="ps-ui__bar"><span>{title}</span><span>{state}</span></div>
}

export default function HomePage() {
  return (
    <main id="main-content">
      <Announcement />
      <section className="ps-hero ps-grid-bg">
        <div className="ps-container ps-hero__grid">
          <div className="ps-hero__copy">
            <span className="ps-label">Built by CPAs, for professionals</span>
            <h1>Less busywork. More billable hours.</h1>
            <p>One platform for document intelligence, AI writing, e-signatures, time tracking, and autonomous agents — built for accounting, finance, and legal teams.</p>
            <div className="ps-button-row"><ProtectedAction destination="/dashboard">Get started free</ProtectedAction><Link className="ps-button ps-button--outline" href="/demo">Watch demo</Link></div>
            <div className="ps-supporting"><span><Check size={12} /> No credit card required</span><span><Check size={12} /> 100 free pages/month</span></div>
            <div className="ps-proof"><div><strong>99.2%</strong><span>accuracy</span></div><div><strong>95%</strong><span>faster</span></div><div><strong>100+</strong><span>doc types</span></div><div><strong>1</strong><span>connected platform</span></div></div>
          </div>
          <div className="ps-hero__visual ps-tech-window" aria-label="Document-to-data processing visualization">
            <div className="ps-window-bar"><span>universal_analysis.run</span><span className="ps-window-dots"><i /><i /><i /></span></div>
            <div className="ps-document-flow"><div className="ps-document"><i /><i /><b>Q4 PORTFOLIO<br />STATEMENT</b><i /><i /><i /></div><div className="ps-extraction-table"><div className="row"><span>portfolio_company</span><strong>TechFlow Inc</strong></div><div className="row"><span>quarter</span><strong>Q4 2024</strong></div><div className="row"><span>revenue</span><strong>$12.5M</strong></div><div className="row"><span>ebitda</span><strong>$3.2M</strong></div><div className="row"><span>valuation</span><strong>$85M</strong></div><p className="success">✓ 14 fields verified · 99.2%</p></div></div>
          </div>
        </div>
      </section>

      <section className="ps-section ps-section--muted" id="product-suite">
        <div className="ps-container">
          <div className="ps-section-head"><div><span className="ps-label">Full product suite</span><h2>One platform, every tool you need</h2></div><p>Purpose-built for accounting, finance, and legal teams — from document processing to autonomous AI agents.</p></div>
          <div className="ps-suite-grid">{suite.map(([title, description, href], index) => <Link href={href} className="ps-suite-card" key={title}><span className="ps-suite-card__number">0{index + 1}</span><h3>{title}</h3><p>{description}</p><footer><span className="ps-status">Available now</span><span>Explore →</span></footer></Link>)}</div>
          <div className="ps-system-map" aria-label="Connected platform system diagram">{['Documents', 'Writing', 'Workflow', 'Signing', 'Time', 'Agents', 'Analytics'].map((item) => <span key={item}>{item}</span>)}</div>
        </div>
      </section>

      <section className="ps-section" id="document-analysis">
        <div className="ps-container">
          <div className="ps-section-head"><div><span className="ps-label">Document Analysis</span><h2>Everything you need to extract data from any file</h2></div><p>No complex training required — just type in plain English.</p></div>
          <div className="ps-card-grid">
            {[['Data Extraction', 'Intelligently extract and structure key information from any document type with precision.', 'Financial statements · Contract documents · Medical records · Legal forms'], ['Table Extraction', 'Advanced table recognition that captures complex layouts and preserves data relationships.', 'Multi-page reports · Complex spreadsheets · Financial tables · Data matrices'], ['Custom Extraction', 'Create custom columns with self-defined formats and prompts. Classify data and add details like G/L codes.', 'Custom data formats · Classification rules · Accounting codes · Smart categorization']].map(([title, description, items], index) => <article className="ps-info-card" key={title}><span className="ps-label">0{index + 1}</span><h3>{title}</h3><p>{description}</p><small>{items}</small></article>)}
          </div>
          <div className="ps-showcase" style={{ marginTop: 70 }}>
            <div className="ps-showcase__copy"><span className="ps-label">Supports all document types</span><h2>Import from anywhere. Export everywhere.</h2><p>Google Drive, local upload, ZIP archives, or automated email attachments.</p><p>Excel, CSV, Google Drive auto-delivery, or direct download.</p><p><strong>PDF; DOCX; XLSX; PPTX; TXT; CSV; Images; Scanned Docs</strong></p><p>Even handles complex multi-page reports, scanned documents, and mixed layouts</p><div className="ps-button-row"><ProtectedAction destination="/dashboard">Try it free</ProtectedAction><Link className="ps-link" href="/features">Learn more</Link><Link className="ps-link" href="/demo">Watch the demo</Link></div><p><strong>CPE tracker included · Free bonus</strong><br />Automatically extract continuing-education credits from certificates and organize them by state requirement.</p></div>
            <div className="ps-ui"><WindowBar title="Investment statement extraction" state="6 fields · verified" /><div className="ps-ui__body"><table className="ps-table"><thead><tr>{['Portfolio Co.', 'Quarter', 'Revenue', 'EBITDA', 'Growth %', 'Valuation'].map(x => <th key={x}>{x}</th>)}</tr></thead><tbody><tr><td>TechFlow Inc</td><td>Q4 2024</td><td>$12.5M</td><td>$3.2M</td><td>23%</td><td>$85M</td></tr><tr><td>DataMind Corp</td><td>Q4 2024</td><td>$8.7M</td><td>$1.9M</td><td>31%</td><td>$62M</td></tr></tbody></table><h3>Invoice extraction & contract review</h3><p>Extract line items from invoices and review key contract terms automatically. Custom fields let you pull exactly the data points your workflow requires.</p></div></div>
          </div>
        </div>
      </section>

      <section className="ps-section ps-section--muted" id="automations"><div className="ps-container ps-showcase"><div className="ps-showcase__copy"><span className="ps-label">Automations</span><h2>Set it and forget it</h2><p>Email attachments → AI extraction → automated delivery. Zero manual work.</p><ul className="ps-feature-list"><li>Forward or send emails to document@cpaautomation.ai — Any email with PDF attachments automatically triggers processing.</li><li>AI extracts data using your templates — Custom fields, prompts, and rules you&apos;ve configured.</li><li>Results auto-exported to Google Drive — CSV and Excel files delivered exactly where you need them.</li></ul><h3>Try it live</h3><p>Send a sample invoice to document@cpaautomation.ai and watch it get processed in real-time.</p><ProtectedAction destination="/dashboard">Try automation now</ProtectedAction></div><div className="ps-ui"><WindowBar title="automation.pipeline" state="live" /><div className="ps-ui__body"><div className="ps-pipeline"><article><span className="ps-label">01</span><strong>Inbox</strong><p>subject:invoice has:attachment</p></article><article><span className="ps-label">02</span><strong>AI extraction</strong><p>from:vendor@company.com filename:pdf</p></article><article><span className="ps-label">03</span><strong>Google Drive</strong><p>subject:&quot;monthly report&quot; has:attachment</p></article></div></div></div></div></section>

      <section className="ps-section" id="form-fill"><div className="ps-container ps-showcase ps-showcase--reverse"><div className="ps-showcase__copy"><span className="ps-label">Document automation</span><h2>Form Fill: auto-fill documents from your data</h2><p>Upload supporting information and a PDF or DOCX target, and watch AI fill your form intelligently.</p><ul className="ps-feature-list"><li>Supports fillable PDFs, non-fillable PDFs, or any DOCX file</li><li>Use extraction results as a structured data source</li><li>Save and reuse Form Fill templates</li><li>Output as PDF or DOCX</li></ul><ProtectedAction destination={protectedDestinations.formFill}>Try Form Fill</ProtectedAction></div><div className="ps-ui"><WindowBar title="Form Fill" state="Filling…" /><div className="ps-ui__body"><p className="ps-label">Source data</p><h3>Q4 Extraction Result.json</h3><p className="ps-label">Target form</p><table className="ps-table"><tbody>{[['Client Name', 'Entity Name'], ['Tax ID', 'EIN'], ['Period End', 'Reporting Period'], ['Total Revenue', 'Gross Receipts'], ['Signature', '—']].map(([a,b]) => <tr key={a}><th>{a}</th><td>{b}</td></tr>)}</tbody></table><p>Fillable PDF · PDF Overlay · DOCX Placeholders</p><strong>Output: PDF</strong></div></div></div></section>

      <section className="ps-section ps-section--muted" id="inkwise"><div className="ps-container ps-showcase"><div className="ps-showcase__copy"><span className="ps-label">AI writing</span><h2>AI writing grounded in your documents — meet Inkwise</h2><p>The first multimodal retrieval-based writing tool in the market. Draft memos, reports, and analyses with AI that cites your own source materials.</p><ul className="ps-feature-list"><li>Citation-backed drafting grounded in your documents</li><li>PDF and Word document references</li><li>Image, video & audio references</li><li>Accounting, finance & legal templates included</li></ul><ProtectedAction destination={protectedDestinations.inkwise}>Try Inkwise</ProtectedAction></div><div className="ps-ui"><WindowBar title="Inkwise Editor" state="AI active" /><div className="ps-editor"><div className="ps-editor__paper"><span className="ps-label">Write with AI</span><h3>Quarterly Investment Review — Q4 2024</h3><p>Based on the portfolio statements provided, total AUM increased by 12.3% relative to the prior quarter. <sup>[1]</sup></p><p>The largest contributor to growth was the technology sector allocation, which returned 18.7% during the period. <sup>[2]</sup></p><p>Fixed-income allocations underperformed benchmark by 1.2%, driven by rising interest rate expectations. <sup>[3]</sup></p><small>AI suggestion: Consider noting the fixed-income underperformance highlighted in the Morgan Stanley report (Ref 3, p.12) and recommending a portfolio rebalance.</small></div><aside className="ps-editor__refs"><strong>References (3 sources)</strong><span>Q4 Portfolio Statement.pdf</span><span>Sector Analysis Report.docx</span><span>Morgan Stanley Review.pdf</span></aside></div></div></div></section>

      <section className="ps-section" id="tasklytic"><div className="ps-container ps-showcase ps-showcase--reverse"><div className="ps-showcase__copy"><span className="ps-label">Tasklytic</span><h2>Professional work, organized and accelerated</h2><p>Bring project management, team coordination, time tracking, forms, reporting, and AI assistance together in one connected workspace.</p><ul className="ps-feature-list"><li>Switch between list, board, timeline, and calendar views</li><li>Coordinate owners, due dates, dependencies, and team goals</li><li>Capture requests with forms and track time and budgets</li><li>Use AI to draft updates, suggest subtasks, and keep work moving</li></ul><ProtectedAction destination={protectedDestinations.tasklytic}>Open Tasklytic</ProtectedAction></div><div className="ps-ui"><WindowBar title="Tasklytic · Project Management" state="8 members" /><div className="ps-ui__body"><h3>July close</h3><p>9 of 13 tasks complete · 69%</p><div className="ps-progress"><i /></div><p>Board · List · Timeline</p><div className="ps-board">{[['To do','Collect client PBC files — Aug 1 — AM, JL','Map close dependencies — Aug 2 — RK'],['In progress','Review revenue schedules — Today — JL','Prepare variance notes — Aug 4 — AM'],['Complete','Confirm reporting scope — Completed — RK','Assign workstream owners — Completed — AM, JL']].map(([name,...tasks]) => <div className="ps-board__column" key={name}><h4>{name}</h4>{tasks.map(task => <div className="ps-task" key={task}>{task}</div>)}</div>)}</div><p><strong>AI update:</strong> July close is on track. Two tasks need attention today.</p></div></div></div></section>

      <section className="ps-section ps-section--muted" id="pbc"><div className="ps-container ps-showcase"><div className="ps-showcase__copy"><span className="ps-label">Prepared by Client</span><h2>Client evidence collection, without the spreadsheet chase</h2><p>Create a clear PBC request list, collect files through a secure client portal, and move every item from request to accepted evidence in one workspace.</p><ul className="ps-feature-list"><li>Build request lists from firm templates, spreadsheets, or AI suggestions</li><li>Give clients a secure, account-free portal for uploads and responses</li><li>Keep versioned evidence, comments, reminders, and review status together</li><li>Export a live tracker or a complete, audit-ready evidence package</li></ul><ProtectedAction destination={protectedDestinations.pbc}>Try PBC</ProtectedAction></div><div className="ps-ui"><WindowBar title="PBC · 2026 Financial Statement Audit" state="Secure portal active" /><div className="ps-ui__body"><h3>Acme Holdings, LLC</h3><p>Period ended December 31, 2025 · 68% complete</p><table className="ps-table"><thead><tr><th>Number</th><th>Request</th><th>Status</th></tr></thead><tbody>{[['PBC-001','Bank reconciliations — Cash · Alex Morgan','Accepted'],['PBC-002','Revenue support — Revenue · Jamie Lee','Submitted'],['PBC-003','Lease agreements — Leases · Taylor Kim','Needs changes'],['PBC-004','Legal representation letter — Legal · Unassigned','Open']].map(row => <tr key={row[0]}>{row.map(cell => <td key={cell}>{cell}</td>)}</tr>)}</tbody></table><p>AI completeness review: 1 item needs attention · Evidence package ready</p></div></div></div></section>

      <section className="ps-section" id="e-signature"><div className="ps-container ps-showcase ps-showcase--reverse"><div className="ps-showcase__copy"><span className="ps-label">E-Signature</span><h2>From prepared document to completed signature</h2><p>Prepare and send signature requests, guide every recipient through a secure signing flow, and track the complete envelope lifecycle in one workspace.</p><ul className="ps-feature-list"><li>Reusable templates, signing order, expiration dates, and reminders</li><li>Signature, initials, date, text, checkbox, attachment, and formula fields</li><li>Secure signing links for recipients — no CPAAutomation account required</li><li>Tamper-evident seals, audit trails, and certificates of completion</li></ul><div className="ps-button-row"><ProtectedAction destination={protectedDestinations.esign}>Try E-Signature</ProtectedAction><Link className="ps-link" href="/docs">Read the docs</Link></div></div><div className="ps-ui"><WindowBar title="E-Signature · Envelopes" state="New envelope" /><div className="ps-ui__body"><p>Track documents, recipients, and signing progress</p><p>Quick views · All 12 · Drafts 3 · In progress 4 · Completed 5</p><div className="ps-envelope-list">{[['2026 Engagement Letter','Maya Chen · Jordan Lee','2/2 signed'],['Q2 Representation Letter','Alex Rivera · Priya Shah','1/2 signed'],['Tax Organizer Consent','Sam Williams','Ready to send']].map(([a,b,c]) => <article key={a}><div><strong>{a}</strong><span>{b}</span></div><em>{c}</em></article>)}</div><p>Recipient routing · Audit trail · Digital seal</p></div></div></div></section>

      <section className="ps-section ps-section--muted" id="chrona"><div className="ps-container ps-showcase"><div className="ps-showcase__copy"><span className="ps-label">Time tracking</span><h2>Chrona: every hour, accounted for</h2><p>Automatic screen-based time tracking for accounting teams. AI reconstructs each workday into a structured timeline that syncs straight into your CPAAutomation dashboard — no timers, no end-of-week timesheet archaeology.</p><ul className="ps-feature-list"><li>Automatic Time Capture — AI turns screen activity into time-aligned cards — no timers, no manual entry</li><li>One-Code Device Pairing — Staff redeem a pairing code and their hours sync to your firm dashboard</li><li>Firm-Wide Visibility — Hours by category and by day across every paired device at your firm</li><li>Daily Timelines — Drill into any device&apos;s day to see exactly how time was spent</li><li>Billing-Ready Exports — Export tracked hours to CSV for timesheets, WIP review, and client billing</li><li>Local-First Privacy — Screenshots stay on each device — only structured activity summaries sync</li></ul><div className="ps-button-row"><a className="ps-button" href="https://github.com/ghost1034/chrona/releases/download/stable/Chrona-0.0.0-arm64.dmg">Download for Mac</a><a className="ps-button ps-button--outline" href="https://github.com/ghost1034/chrona/releases/download/stable/Chrona.Setup.0.0.0.exe">Download for Windows</a></div><details><summary>If you see that the app is “damaged and can’t be opened”</summary><ol><li>Open Terminal</li><li>Remove the quarantine flag</li><li>Type (don’t press Enter yet): <code>sudo xattr -dr com.apple.quarantine</code></li><li>Drag the damaged app into the Terminal window (this fills in the app’s path).</li><li>Press Enter.</li><li>Example: <code>sudo xattr -dr com.apple.quarantine /Applications/Chrona.app</code></li><li>Launch the app again</li></ol></details><p><strong>Chrona desktop app and the CPAAutomation Time Tracking dashboard are available now.</strong></p></div><div className="ps-ui"><WindowBar title="Chrona Demo" state="Today · 7h 42m" /><div className="ps-ui__body"><div className="ps-timeline"><article><time>09:00 — 10:24</time><strong>July close · Revenue review</strong><span>1h 24m</span></article><article><time>10:24 — 12:10</time><strong>Acme Holdings · Bank reconciliation</strong><span>1h 46m</span></article><article><time>13:00 — 15:32</time><strong>Investment report · Inkwise</strong><span>2h 32m</span></article><article><time>15:32 — 17:32</time><strong>Client work · Review and follow-up</strong><span>2h 00m</span></article></div></div></div></div></section>

      <section className="ps-section ps-dark ps-grid-bg" id="claw"><div className="ps-container ps-showcase ps-showcase--reverse"><div className="ps-showcase__copy"><span className="ps-label">Claw Series</span><h2>Claw Series: digital workers for accounting, finance & legal</h2><p className="ps-muted">AccountingClaw, FinanceClaw, and LegalClaw are AI agents that work autonomously — not just tools you operate, but digital workers you deploy. Hundreds of pre-built skills with guardrails designed for regulated environments.</p><ul className="ps-feature-list"><li>Automated bank reconciliations</li><li>Contract clause extraction and review</li><li>Tax form preparation and validation</li><li>Regulatory compliance checks</li></ul><p><strong>Accounting</strong> — Closes books, reconciles ledgers, and prepares working papers with audit-ready precision.</p><p><strong>Finance</strong> — Builds models, validates filings, and runs variance analysis across the close cycle.</p><p><strong>Legal</strong> — Drafts, reviews, and analyzes legal work product with 1,251 skills across 24 practice areas.</p><Link className="ps-button ps-button--light" href="/claw">Learn more about Claw Series</Link></div><div className="ps-terminal"><div className="ps-window-bar"><span>accountingclaw / close_agent</span><span>running</span></div><pre><span className="accent">agent@close</span>: reviewing ledger activity{`\n\n`}✓ imported bank statement{`\n`}✓ matched 284 of 291 transactions{`\n`}✓ prepared 4 adjustment entries{`\n`}→ investigating 7 exceptions{`\n\n`}Skill: automated_bank_reconciliation{`\n`}Guardrail: reviewer_approval_required{`\n`}Evidence: audit_trail_attached{`\n\n`}<span className="accent">Ready for reviewer.</span></pre></div></div></section>

      <section className="ps-section ps-dark" id="ai-analytics"><div className="ps-container ps-showcase"><div className="ps-showcase__copy"><span className="ps-label">Financial analysis</span><h2>Financial analysis, automated</h2><p className="ps-muted">Variance and flux analysis, reconciliation, fixed assets, and distribution waterfalls — plus research bots and a context-aware assistant, all connected to your clients and built for accounting and finance teams.</p><ul className="ps-feature-list"><li>Variance & Flux Analysis — Multi-period variance with AI-generated explanations of what drove each change</li><li>Reconciliation — Automated matching that surfaces breaks and unreconciled items for review</li><li>Fixed Assets & Amortization — Generate depreciation and amortization schedules from your asset data</li><li>Waterfall Analysis — Model distribution waterfalls and tier allocations across periods</li><li>IRS & GAAP Research Bots — Ask tax and accounting questions answered with web-grounded citations</li><li>Context-aware AI Assistant — A floating assistant that understands the client and report you are viewing</li></ul><ProtectedAction destination={protectedDestinations.analytics} className="ps-button ps-button--light">Open the Analytics Suite</ProtectedAction></div><div className="ps-analytics"><div><h4>Variance modules</h4>{['Revenue +12.4%','Operating expenses −3.1%','EBITDA +18.7%','Unreconciled items 7'].map(x => <p key={x}>{x}</p>)}</div><div><h4>12-month variance</h4><div className="ps-chart">{Array.from({length:8},(_,i)=><i key={i} />)}</div></div></div></div></section>

      <section className="ps-section ps-section--muted"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">Roadmap</span><h2>What&apos;s coming next</h2></div><p>We&apos;re building the tools professional services teams have been waiting for.</p></div><article className="ps-info-card"><span className="ps-label">Coming soon</span><h3>More productivity tools</h3><p>AI-powered month-end checklists, slide decks, and expense reimbursement workflows.</p><p>Month-end close checklists with progress tracking · AI-generated slide presentations from data · Expense reimbursement processing · Review and approval workflows</p></article></div></section>

      <section className="ps-section"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">Testimonials</span><h2>What our customers are saying</h2></div><p>A leading family office saves hundreds of hours per year processing investment statements.</p></div><Testimonials /><article className="ps-info-card" style={{ marginTop: 24 }}><h3>A leading family office saves hundreds of hours per year processing investment statements</h3><blockquote>“Our team used to spend weeks manually extracting financial data from portfolio reports. Now we process quarterly statements from 100+ companies in just minutes with perfect accuracy.”</blockquote></article><div className="ps-button-row"><Link className="ps-link" href="/case-study/LFO">Read the full case study</Link><Link className="ps-link" href="/demo">Watch our pitch</Link></div></div></section>

      <section className="ps-section ps-dark ps-grid-bg"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">Security & compliance</span><h2>Enterprise-grade security</h2></div><p>Your data security is our top priority. Built for the standards professional services demand.</p></div><div className="ps-card-grid">{[['TLS 1.3 encryption','All data transfers use the latest encryption protocols'],['US-only hosting','Google Cloud US regions with SOC 2 compliance'],['AES-256 at rest','Military-grade encryption for stored data'],['Zero data training','Your documents never train AI models'],['Audit-ready controls','Full audit logs for all activities'],['Professional standards','Meets CPA firm security requirements and legal industry standards']].map(([title,desc]) => <article className="ps-info-card" key={title}><LockKeyhole size={24}/><h3>{title}</h3><p>{desc}</p></article>)}</div><p className="ps-supporting">GDPR compliant · CCPA compliant · Automatic data deletion after processing</p><div className="ps-button-row"><span>Need enterprise security documentation or custom compliance requirements?</span><Link className="ps-button ps-button--light" href="/contact">Contact security team</Link></div></div></section>

      <section className="ps-section"><div className="ps-narrow"><div className="ps-section-head"><div><h2>Frequently asked questions</h2></div><p>Everything you need to know about CPAAutomation</p></div><div className="ps-faq">{faq.map(([q,a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div><p>Still have questions? We&apos;re here to help.</p><div className="ps-button-row"><Link className="ps-button ps-button--outline" href="/contact">Contact support</Link><ProtectedAction destination="/dashboard">Start free plan</ProtectedAction></div></div></section>

      <section className="ps-cta"><div className="ps-container ps-cta__inner"><div><h2>Ready to transform your workflow?</h2><p>Join accounting firms, legal teams, and investment funds already saving hundreds of hours with CPAAutomation.</p><div className="ps-supporting"><span>No credit card required</span><span>100 free pages/month</span><span>Setup in under 10 minutes</span></div></div><div className="ps-button-row"><ProtectedAction destination="/dashboard" className="ps-button ps-button--light">Get started free</ProtectedAction><Link className="ps-button ps-button--outline" href="/demo">See a demo <ArrowRight size={17}/></Link></div></div></section>
    </main>
  )
}
