import Link from 'next/link'
import { generateMetadata, pageMetadata } from '@/lib/metadata'

export const metadata = generateMetadata(pageMetadata.consulting)

const bring = [
  ['Strong technical skills', 'Senior engineers who have shipped AI in production — not researchers, not generalist consultants.', ['Full-stack engineering across web, data, and infra','LLM tool-use, agent design, and evaluation harnesses','Cloud-native builds on AWS, GCP, and Azure','Security, observability, and cost engineering built in']],
  ['Strong business skills', 'CPAs and operators on the team — we speak the language of the work, not just the language of the code.', ['Deep domain knowledge in accounting, finance, and legal','ROI framing and stakeholder alignment','Change management and team enablement','Audit, compliance, and data-residency expertise']],
  ['What we build', 'Bespoke AI tools tailored to your workflows — not a repackaged product or a one-size-fits-all template.', ['Custom AI workflows and document pipelines','Internal copilots wired into your systems','Agent integrations with ERPs, DMSs, and CRMs','Evaluation suites and human-in-the-loop tooling']],
] as const

export default function ConsultingPage() { return <main id="main-content">
  <section className="ps-page-hero ps-page-hero--dark ps-grid-bg"><div className="ps-container ps-page-hero__split"><div><span className="ps-label">Forward-Deployed Consulting</span><h1>Strong engineers. Strong operators. AI tools built for your business.</h1></div><div><p className="ps-kicker">Our platform is one way to work with us. Forward-Deployed Consulting is the other — a senior team that embeds with yours to design, build, and ship custom AI tools end-to-end. Combining strong technical skills with deep business expertise, we turn AI ambition into software your team actually uses.</p><div className="ps-button-row"><Link className="ps-button ps-button--light" href="/contact">Start a conversation</Link><a className="ps-link" href="#what-we-bring">What we bring</a></div></div></div></section>
  <section className="ps-section"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">Why forward-deployed?</span><h2>Engineers who sit with your team, ship working tools, and care about business outcomes</h2></div><p>Most AI consulting hands you a strategy deck. We hand you software running in your environment. The difference is who shows up — senior people who understand both the code and the business it serves.</p></div><div className="ps-card-grid">{[['Embedded with your team','We sit alongside your engineers, accountants, and operators — not at arm\'s length over a statement of work.'],['Working software, not slide decks','Every engagement ships running code into your environment. Prototypes in weeks, production in months.'],['We own outcomes, not hours','Success means the tool gets used and the business metric moves. We scope and price around that, not a billable timesheet.'],['Direct line to founders','You work with the people who built CPAAutomation. No layers, no handoffs, no rotating account managers.']].map(([a,b],i)=><article className="ps-info-card" key={a}><span className="ps-label">0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
  <section className="ps-section ps-dark" id="what-we-bring"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">What we bring</span><h2>Technical depth meets business fluency</h2></div><p>Two skill sets, on the same team. That&apos;s what makes an AI build ship — and what makes it keep working after we leave.</p></div><div className="ps-card-grid">{bring.map(([title,desc,items])=><article className="ps-info-card" key={title}><h3>{title}</h3><p>{desc}</p><ul>{items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div><p>Have a build in mind that spans more than one of these? That&apos;s usually the point — talk to us about scoping it together.</p></div></section>
  <section className="ps-section ps-section--muted"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">How we engage</span><h2>From first conversation to shipped software</h2></div><p>A predictable four-step shape — scoped tight at the start, with the option to keep going once the tool is in production.</p></div><div className="ps-pipeline">{[['Scope','A short discovery sprint to map your workflows, data, and constraints. You leave with a written plan and a fixed-scope proposal.'],['Prototype','A working prototype in your environment within weeks — not a slide deck. Real data, real users, real feedback.'],['Deploy','We harden the prototype, integrate it into your systems, and roll it out with training for the team that will use it.'],['Iterate','Optional ongoing partnership — we tune models, ship improvements, and keep the tool sharp as your business evolves.']].map(([a,b],i)=><article key={a}><span className="ps-label">0{i+1}</span><strong>{a}</strong><p>{b}</p></article>)}</div><div className="ps-info-card" style={{marginTop:30}}><h3>Not sure what to build yet?</h3><p>A short paid discovery sprint is often the right starting point. We&apos;ll map your workflows, identify the highest-leverage AI build, and hand you a written plan you can act on — with us or without us.</p><div className="ps-button-row"><Link className="ps-button" href="/contact">Book a discovery call</Link><Link className="ps-link" href="/about">Meet the team</Link></div></div></div></section>
  <section className="ps-cta"><div className="ps-container ps-cta__inner"><div><span className="ps-label">Forward-Deployed Consulting</span><h2>Bring us in to build what your team can&apos;t ship alone</h2><p>Tell us about the workflow you want to transform. We&apos;ll come back with a scoped plan, a timeline, and a fixed-price proposal — usually within a week.</p></div><div className="ps-button-row"><Link className="ps-button ps-button--light" href="/contact">Contact us</Link><Link className="ps-button ps-button--outline" href="/about">About our team</Link></div></div></section>
</main> }
