"""Important tax court decisions (US, EU, UK, India, Australia, Canada, other). source_url must be unique.

Audit 2026-08-22 (docs/data-audit.md): every citation, date, outcome and URL was checked against the court's own
site or an authoritative reporter. URL conventions that changed: supremecourt.gov slip PDFs for OT2020–OT2023 were
replaced by preliminary prints ({vol}us1r{n}_{hash}.pdf) or bound volumes; supremecourt.uk uses /cases/uksc-YYYY-NNNN
(no .html) keyed on the correct case ID; SCC item IDs were renumbered; US Tax Court OpinionViewer IDs are dead (use
DAWSON case-detail pages); main.sci.gov.in no longer resolves (use api.sci.gov.in). Sites that block automated
clients (Justia, mass.gov, BAILII, Federal Court of Australia, STF, domstol.dk) are noted in the summary text.
"""

from __future__ import annotations

from taxatlas.seed._helpers import case

C: list[dict] = []

# ---------------------------------------------------------------- US Supreme Court
C += [
    case(
        "US",
        "Supreme Court of the United States",
        "South Dakota v. Wayfair, Inc.",
        citation="585 U.S. 162 (2018)",
        docket="17-494",
        decided="2018-06-21",
        tax_types=["sales_use"],
        summary="South Dakota enacted a law requiring out-of-state sellers with more than USD 100,000 of in-state sales or 200 transactions to collect sales tax, deliberately conflicting with Quill's physical-presence requirement. The Court overruled Quill and National Bellas Hess.",
        holding="Physical presence is not required for a state to impose sales-tax collection obligations under the Commerce Clause; economic and virtual contacts establishing substantial nexus suffice, and South Dakota's thresholds and lack of retroactivity were not an undue burden.",
        significance="landmark",
        outcome="government",
        url="https://www.supremecourt.gov/opinions/17pdf/17-494_j4el.pdf",
        tags=["nexus", "remote-sellers", "commerce-clause", "quill-overruled"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Quill Corp. v. North Dakota",
        citation="504 U.S. 298 (1992)",
        docket="91-194",
        decided="1992-05-26",
        tax_types=["sales_use"],
        summary="North Dakota sought to require a mail-order retailer with no in-state employees or property to collect use tax. The Court reaffirmed the physical-presence rule of National Bellas Hess for Commerce Clause purposes while holding the Due Process Clause did not require physical presence.",
        holding="A vendor must have physical presence in a state before the state may require it to collect use tax (overruled by Wayfair in 2018).",
        significance="landmark",
        outcome="taxpayer",
        url="https://supreme.justia.com/cases/federal/us/504/298/",
        tags=["nexus", "physical-presence", "overruled"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Complete Auto Transit, Inc. v. Brady",
        citation="430 U.S. 274 (1977)",
        docket="76-29",
        decided="1977-03-07",
        tax_types=["sales_use", "other"],
        summary="Mississippi imposed a privilege tax on an interstate motor carrier transporting vehicles within the state. The Court abandoned the formalistic 'privilege of doing interstate business' rule.",
        holding="A state tax on interstate commerce is valid under the Commerce Clause if it (1) applies to an activity with substantial nexus, (2) is fairly apportioned, (3) does not discriminate against interstate commerce and (4) is fairly related to services provided by the state.",
        significance="landmark",
        outcome="government",
        url="https://supreme.justia.com/cases/federal/us/430/274/",
        tags=["commerce-clause", "four-part-test"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Comptroller of the Treasury of Maryland v. Wynne",
        citation="575 U.S. 542 (2015)",
        docket="13-485",
        decided="2015-05-18",
        tax_types=["personal_income"],
        summary="Maryland taxed residents' out-of-state income at both state and county level but allowed a credit for taxes paid to other states only against the state portion, creating double taxation of interstate income.",
        holding="Maryland's failure to credit county income tax for taxes paid to other states violates the dormant Commerce Clause because it fails the internal consistency test and discriminates against interstate commerce.",
        significance="landmark",
        outcome="taxpayer",
        url="https://www.supremecourt.gov/opinions/boundvolumes/575BV.pdf#page=626",
        tags=["commerce-clause", "internal-consistency", "double-taxation"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Moore v. United States",
        citation="602 U.S. 572 (2024)",
        docket="22-800",
        decided="2024-06-20",
        tax_types=["corporate_income", "personal_income"],
        summary="US shareholders of an Indian CFC challenged the TCJA's Section 965 mandatory repatriation tax as an unapportioned direct tax on unrealized income in violation of the Sixteenth Amendment.",
        holding="The MRT is constitutional: Congress may attribute an entity's realized and undistributed income to its shareholders and tax them on their share, as it long has for partnerships, S corporations and subpart F. The Court expressly declined to decide whether realization is constitutionally required.",
        significance="landmark",
        outcome="government",
        url="https://www.supremecourt.gov/opinions/23pdf/602us1r41_h3dj.pdf",
        tags=["section-965", "realization", "sixteenth-amendment", "wealth-tax"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Loper Bright Enterprises v. Raimondo",
        citation="603 U.S. 369 (2024)",
        docket="22-451",
        decided="2024-06-28",
        tax_types=["other"],
        summary="Fishing companies challenged a NMFS rule requiring them to pay for on-board observers. The Court used the case to revisit the Chevron doctrine of judicial deference to agency statutory interpretations.",
        holding="Chevron is overruled; courts must exercise independent judgment in deciding whether an agency has acted within its statutory authority and may not defer to an agency interpretation merely because a statute is ambiguous. Treasury regulations are now reviewed without Chevron deference (Skidmore-type respect only).",
        significance="landmark",
        outcome="taxpayer",
        url="https://www.supremecourt.gov/opinions/23pdf/22-451_7m58.pdf",
        tags=["chevron", "administrative-law", "treasury-regulations"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "CIC Services, LLC v. Internal Revenue Service",
        citation="593 U.S. 209 (2021)",
        docket="19-930",
        decided="2021-05-17",
        tax_types=["other"],
        summary="A material advisor sued to set aside IRS Notice 2016-66 (micro-captive reportable transactions) under the Administrative Procedure Act; the IRS argued the Anti-Injunction Act barred the suit because non-compliance penalties are treated as taxes.",
        holding="A pre-enforcement APA challenge to an IRS reporting requirement is not a suit 'for the purpose of restraining the assessment or collection of any tax' and is not barred by the Anti-Injunction Act, even though backed by tax penalties.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.supremecourt.gov/opinions/20pdf/593us1r34_mlho.pdf",
        tags=["anti-injunction-act", "apa", "micro-captive"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Boechler, P.C. v. Commissioner",
        citation="596 U.S. 199 (2022)",
        docket="20-1472",
        decided="2022-04-21",
        tax_types=["other"],
        summary="A law firm filed its Tax Court petition for review of a collection due process determination one day late; the Tax Court dismissed for lack of jurisdiction.",
        holding="The 30-day deadline in Section 6330(d)(1) is a non-jurisdictional claim-processing rule subject to equitable tolling.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.supremecourt.gov/opinions/21pdf/596us1r26_o6p1.pdf",
        tags=["procedure", "equitable-tolling", "tax-court"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Bittner v. United States",
        citation="598 U.S. 85 (2023)",
        docket="21-1195",
        decided="2023-02-28",
        tax_types=["other"],
        summary="A dual citizen failed to file FBARs for five years covering dozens of foreign accounts; the government assessed a USD 10,000 non-willful penalty per account (USD 2.72m) rather than per report.",
        holding="The Bank Secrecy Act's USD 10,000 maximum penalty for non-willful FBAR violations accrues per report, not per account.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.supremecourt.gov/opinions/22pdf/21-1195_h3ci.pdf",
        tags=["fbar", "penalties", "bsa"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Connelly v. United States",
        citation="602 U.S. 257 (2024)",
        docket="23-146",
        decided="2024-06-06",
        tax_types=["other"],
        summary="A closely held corporation received life insurance proceeds to redeem a deceased shareholder's shares under a buy-sell agreement; the estate argued the redemption obligation offset the proceeds in valuing the shares.",
        holding="A corporation's contractual obligation to redeem shares is not a liability that reduces the corporation's value for estate tax purposes; life insurance proceeds are included in the company's fair market value.",
        significance="significant",
        outcome="government",
        url="https://www.supremecourt.gov/opinions/23pdf/602us1r31_6537.pdf",
        tags=["estate-tax", "valuation", "buy-sell"],
    ),
    case(
        "US",
        "Supreme Court of the United States",
        "Learning Resources, Inc. v. Trump (with Trump v. V.O.S. Selections, Inc.)",
        citation="607 U.S. 229 (2026)",
        docket="24-1287 (with 25-250)",
        decided="2026-02-20",
        tax_types=["customs_tariff"],
        summary="Consolidated challenges to the 'reciprocal' and fentanyl/border tariffs imposed under the International Emergency Economic Powers Act. The Court granted certiorari before judgment in Learning Resources (D.D.C.) and certiorari in V.O.S. Selections (Federal Circuit en banc, 149 F.4th 1312), heard expedited argument on 5 November 2025 and decided the cases on 20 February 2026 (judgment issued 24 March 2026).",
        holding="6-3 (Roberts, C.J., for the Court as to Parts I, II-A-1 and II-B; plurality on the major-questions analysis; Thomas and Kavanaugh (joined by Thomas and Alito) dissenting): IEEPA's power to 'regulate ... importation' does not include the power to impose tariffs, which is a taxing power reserved to Congress and not delegated by IEEPA. The Federal Circuit's judgment invalidating the tariffs was affirmed; the D.D.C. judgment was vacated and remanded to dismiss because the Court of International Trade has exclusive jurisdiction. The Court did not address refund mechanics; EO 14389 (20 Feb 2026) ended collection from 24 Feb 2026 and CBP refunds followed CIT orders of 4 Mar and 17 Jul 2026.",
        significance="landmark",
        outcome="taxpayer",
        url="https://www.supremecourt.gov/opinions/25pdf/24-1287_4gcj.pdf",
        tags=["ieepa", "tariffs", "major-questions", "nondelegation"],
    ),
]

# ---------------------------------------------------------------- US appellate / Tax Court / trade courts
C += [
    case(
        "US",
        "U.S. Court of Appeals for the Ninth Circuit",
        "Altera Corp. v. Commissioner",
        citation="926 F.3d 1061 (9th Cir. 2019)",
        docket="16-70496",
        decided="2019-06-07",
        tax_types=["transfer_pricing"],
        summary="Altera challenged Treas. Reg. §1.482-7(d)(2), which requires related parties in a cost-sharing arrangement to share stock-based compensation costs. The Tax Court had invalidated the regulation unanimously under the APA.",
        holding="The 2003 cost-sharing regulation is valid: Treasury reasonably interpreted the commensurate-with-income standard to permit an internal allocation method not dependent on comparable uncontrolled transactions, and the rulemaking satisfied State Farm. Certiorari denied June 2020.",
        significance="landmark",
        outcome="government",
        url="https://cdn.ca9.uscourts.gov/datastore/opinions/2019/06/07/16-70496.pdf",
        tags=["cost-sharing", "stock-based-compensation", "apa", "arm's-length"],
    ),
    case(
        "US",
        "U.S. Court of Appeals for the Ninth Circuit",
        "Amazon.com, Inc. v. Commissioner",
        citation="934 F.3d 976 (9th Cir. 2019)",
        docket="17-72922",
        decided="2019-08-16",
        tax_types=["transfer_pricing"],
        summary="The IRS sought to include residual business assets such as workforce in place, goodwill and going-concern value in the buy-in payment for intangibles transferred to Amazon's Luxembourg subsidiary under a 2005 cost-sharing arrangement.",
        holding="Under the pre-2009 regulations, 'intangible' did not include residual business assets; the buy-in payment was limited to independently transferable assets. The 2009 temporary regulations and TCJA amendment to §936(h)(3)(B) changed the definition prospectively.",
        significance="significant",
        outcome="taxpayer",
        url="https://cdn.ca9.uscourts.gov/datastore/opinions/2019/08/16/17-72922.pdf",
        tags=["cost-sharing", "buy-in", "intangibles"],
    ),
    case(
        "US",
        "U.S. Tax Court",
        "The Coca-Cola Co. v. Commissioner",
        citation="155 T.C. 145 (2020); T.C. Memo. 2023-135",
        docket="31183-15",
        decided="2020-11-18",
        tax_types=["transfer_pricing"],
        summary="The IRS reallocated over USD 9bn of income from foreign concentrate-manufacturing affiliates ('supply points') to the US parent using a comparable profits method, rejecting the 10-50-50 method the parties had used since a 1996 closing agreement.",
        holding="The IRS's CPM allocation was reasonable and the supply points, as contract manufacturers without ownership of the trademarks, were overcompensated. The Tax Court entered decision on 2 August 2024 for about USD 2.7bn of deficiencies; Coca-Cola's appeal to the Eleventh Circuit (No. 24-13470) was argued on 25 June 2026 and remained undecided as of 22 August 2026.",
        significance="landmark",
        outcome="government",
        url="https://dawson.ustaxcourt.gov/case-detail/31183-15",
        tags=["transfer-pricing", "cpm", "intangibles", "appeal-pending"],
    ),
    case(
        "US",
        "U.S. Court of Appeals for the Eighth Circuit",
        "Medtronic, Inc. v. Commissioner",
        citation="900 F.3d 610 (8th Cir. 2018); T.C. Memo. 2022-84",
        docket="17-1866",
        decided="2018-08-16",
        tax_types=["transfer_pricing"],
        summary="Dispute over royalty rates paid by Medtronic's Puerto Rican manufacturing affiliate for device intangibles. The Tax Court used a comparable uncontrolled transaction method based on a Pacesetter settlement; the Eighth Circuit vacated for insufficient comparability analysis, and on remand (2022) the Tax Court applied an unspecified three-step method.",
        holding="The Tax Court must make findings on the comparability of the CUT before adopting it; on remand (T.C. Memo. 2022-84) the court rejected both parties' methods and fashioned a modified approach. On the second appeal (Nos. 23-3063/23-3281) the Eighth Circuit on 3 September 2025 again vacated the Tax Court's order and remanded (mandate 19 November 2025); the remand remains pending.",
        significance="significant",
        outcome="remanded",
        url="https://ecf.ca8.uscourts.gov/opndir/18/08/171866P.pdf",
        tags=["transfer-pricing", "cut", "remand"],
    ),
    case(
        "US",
        "U.S. Court of Appeals for the Eighth Circuit",
        "3M Co. v. Commissioner",
        citation="No. 23-3772 (8th Cir. Oct. 1, 2025), rev'g 160 T.C. No. 3 (2023)",
        docket="23-3772",
        decided="2025-10-01",
        tax_types=["transfer_pricing"],
        summary="Brazilian law capped royalties 3M's Brazilian subsidiary could pay its US parent; the IRS allocated additional royalty income to 3M under §482 notwithstanding the legal restriction, relying on the blocked-income regulation Treas. Reg. §1.482-1(h)(2). In a 9-8 reviewed opinion (160 T.C. No. 3, 9 Feb 2023) the Tax Court upheld the regulation under Chevron.",
        holding="Reversed (Stras, J., for a unanimous panel): §482 reaches only income the taxpayer actually controls or could receive, so Brazilian-law-blocked royalties cannot be allocated to 3M; after Loper Bright the blocked-income regulation cannot override the statute's text. Mandate issued 26 February 2026 and the Tax Court entered decision for 3M on remand on 4 August 2026.",
        significance="significant",
        outcome="taxpayer",
        url="https://ecf.ca8.uscourts.gov/opndir/25/10/233772P.pdf",
        tags=["blocked-income", "section-482", "loper-bright", "regulation-invalid"],
    ),
    case(
        "US",
        "U.S. Court of Appeals for the Tenth Circuit",
        "Liberty Global, Inc. v. United States",
        citation="174 F.4th 1208 (10th Cir. 2026)",
        docket="23-1410",
        decided="2026-04-21",
        tax_types=["corporate_income"],
        summary="Liberty Global executed 'Project Soy', a series of transactions designed to generate a USD 2.4bn dividends-received deduction under §245A by exploiting a gap between the TCJA's effective date and the GILTI regime. The district court (D. Colo. 2023) disallowed the deduction under the economic substance doctrine.",
        holding="Affirmed (Murphy, J.; Eid, J., dissenting): the economic substance doctrine applies without a threshold 'relevance' inquiry; the transactions lacked economic substance and the §245A deduction was properly disallowed. Rehearing en banc denied 17 August 2026.",
        significance="significant",
        outcome="government",
        url="https://www.ca10.uscourts.gov/sites/ca10/files/opinions/010111421660.pdf",
        tags=["economic-substance", "section-245a", "tcja-gap"],
    ),
    case(
        "US",
        "U.S. Tax Court",
        "Varian Medical Systems, Inc. v. Commissioner",
        citation="163 T.C. No. 4 (2024)",
        docket="8435-23",
        decided="2024-08-26",
        tax_types=["corporate_income"],
        summary="For a fiscal year straddling the TCJA effective dates, Varian claimed a §245A dividends-received deduction for dividends from CFCs that were also subject to the §78 gross-up, which the statute did not yet exclude from §245A treatment.",
        holding="The plain text governed: the §78 gross-up amount was eligible for the §245A deduction for the gap period, and Treasury's regulation denying it was invalid as contrary to the statute. The court also held §78 dividends were not excluded from foreign tax credit computations. A follow-on opinion (166 T.C. No. 8, 8 Apr 2026) resolved the computation and a stipulated decision was entered on 15 June 2026; no notice of appeal was on the docket as of 22 August 2026.",
        significance="significant",
        outcome="taxpayer",
        url="https://dawson.ustaxcourt.gov/case-detail/8435-23",
        tags=["section-245a", "section-78", "tcja-gap", "regulation-invalid"],
    ),
    case(
        "US",
        "U.S. District Court for the Western District of Tennessee",
        "FedEx Corp. v. United States",
        citation="No. 2:20-cv-02794 (W.D. Tenn. 2023)",
        docket="2:20-cv-02794",
        decided="2023-03-31",
        tax_types=["corporate_income"],
        summary="FedEx claimed foreign tax credits on the §965 transition tax with respect to 'offset earnings' of CFCs with deficits; Treas. Reg. §1.965-5(c)(1)(ii) disallowed credits for taxes attributable to those earnings.",
        holding="The regulation contradicted the unambiguous text of §965 and §960 and was invalid; FedEx was entitled to the credits. The government's appeal to the Sixth Circuit (No. 25-5694, docketed 1 Aug 2025) was fully briefed by May 2026 and remained pending as of 22 August 2026.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.govinfo.gov/app/details/USCOURTS-tnwd-2_20-cv-02794",
        tags=["section-965", "foreign-tax-credit", "regulation-invalid"],
    ),
    case(
        "US",
        "U.S. Court of International Trade",
        "V.O.S. Selections, Inc. v. United States",
        citation="772 F. Supp. 3d 1350 (Ct. Int'l Trade 2025)",
        docket="25-00066",
        decided="2025-05-28",
        tax_types=["customs_tariff"],
        summary="Importers and twelve states challenged the 'Liberation Day' reciprocal tariffs and the Canada/Mexico/China trafficking tariffs imposed under IEEPA. A three-judge panel granted summary judgment to the plaintiffs.",
        holding="IEEPA does not authorise the worldwide and retaliatory tariffs (unbounded in scope and duration) or the trafficking tariffs (which do not 'deal with' the declared emergencies); the orders were vacated and enforcement permanently enjoined, with the injunction stayed pending appeal.",
        significance="landmark",
        outcome="taxpayer",
        url="https://www.cit.uscourts.gov/sites/cit/files/25-66.pdf",
        tags=["ieepa", "tariffs", "reciprocal-tariffs"],
    ),
    case(
        "US",
        "U.S. Court of Appeals for the Federal Circuit (en banc)",
        "V.O.S. Selections, Inc. v. Trump",
        citation="149 F.4th 1312 (Fed. Cir. 2025) (en banc)",
        docket="2025-1812",
        decided="2025-08-29",
        tax_types=["customs_tariff"],
        summary="On expedited en banc review of the CIT decision, the Federal Circuit considered whether IEEPA's power to 'regulate ... importation' includes tariffs.",
        holding="By a 7-4 vote the court affirmed that IEEPA does not authorise the reciprocal and trafficking tariffs, but vacated the universal injunction for reconsideration under Trump v. CASA and stayed its mandate pending Supreme Court review, which was granted on 9 September 2025. Affirmed by the Supreme Court in Learning Resources, Inc. v. Trump, 607 U.S. 229 (20 Feb 2026).",
        significance="landmark",
        outcome="taxpayer",
        url="https://www.cafc.uscourts.gov/opinions-orders/25-1812.OPINION.8-29-2025_2566151.pdf",
        tags=["ieepa", "tariffs", "en-banc"],
    ),
]

# ---------------------------------------------------------------- US state courts
C += [
    case(
        "US-MD",
        "Supreme Court of Maryland",
        "Comptroller of Maryland v. Comcast of California/Maryland/Pennsylvania/Virginia/West Virginia LLC",
        citation="484 Md. 222, 297 A.3d 1211 (2023)",
        docket="No. 32, Sept. Term 2022",
        decided="2023-07-12",
        tax_types=["digital_services"],
        summary="Comcast and Verizon obtained a circuit court declaration that Maryland's Digital Advertising Gross Revenues Tax violated the Internet Tax Freedom Act, the dormant Commerce Clause and the First Amendment. The Comptroller appealed on exhaustion grounds; the Supreme Court of Maryland reversed by per curiam order on 9 May 2023 (483 Md. 485) and issued its opinion (Fader, C.J.) on 12 July 2023.",
        holding="The taxpayers were required to exhaust administrative remedies before the Maryland Tax Court before seeking judicial review; the circuit court judgment invalidating the tax was vacated without reaching the merits. Subsequent history: the Fourth Circuit held the tax's pass-through prohibition violates the First Amendment (Chamber of Commerce v. Lierman, No. 24-1727, 15 Aug 2025), and on 14 Aug 2026 the Maryland Tax Court ruled for Apple, Google and Peacock TV that the tax violates the ITFA, dormant Commerce Clause and Due Process, ordering refunds; the Comptroller has announced judicial review.",
        significance="significant",
        outcome="government",
        url="https://www.mdcourts.gov/data/opinions/coa/2023/32a22.pdf",
        tags=["digital-advertising", "itfa", "exhaustion"],
    ),
    case(
        "US-MD",
        "U.S. Court of Appeals for the Fourth Circuit",
        "Chamber of Commerce of the United States v. Lierman",
        citation="No. 24-1727 (4th Cir. Aug. 15, 2025)",
        docket="24-1727",
        decided="2025-08-15",
        tax_types=["digital_services"],
        summary="Trade associations challenged the provision of Maryland's Digital Advertising Gross Revenues Tax that prohibits taxpayers from passing the tax through to customers by means of a separate fee, surcharge or line item, as a restriction on speech.",
        holding="Reversed and remanded (Richardson, J., unanimous): the pass-through prohibition regulates what a seller may tell its customers about the tax and is a content-based restriction that fails First Amendment scrutiny; the tax itself was not before the court and remains subject to the Maryland Tax Court proceedings.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.ca4.uscourts.gov/opinions/241727.P.pdf",
        tags=["digital-advertising", "first-amendment", "pass-through"],
    ),
    case(
        "US-PA",
        "Commonwealth Court of Pennsylvania",
        "Online Merchants Guild v. Hassell",
        citation="288 A.3d 951 (Pa. Cmwlth. 2022)",
        docket="179 M.D. 2021",
        decided="2022-09-09",
        tax_types=["sales_use"],
        summary="Pennsylvania sought to compel Amazon FBA merchants to respond to business activity questionnaires and pay back sales tax on the theory that inventory stored in Amazon warehouses in the state created nexus.",
        holding="The Department of Revenue lacked authority to demand the questionnaires and had not shown that the mere presence of inventory under Amazon's control established sufficient nexus for retroactive collection; merchants were not required to respond.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.pacourts.us/assets/opinions/Commonwealth/out/179MD21_9-9-22.pdf",
        tags=["marketplace", "fba", "nexus", "wayfair-follow-on"],
    ),
    case(
        "US-MA",
        "Massachusetts Supreme Judicial Court",
        "U.S. Auto Parts Network, Inc. v. Commissioner of Revenue",
        citation="491 Mass. 393 (2022)",
        docket="SJC-13283",
        decided="2022-12-22",
        tax_types=["sales_use"],
        summary="Massachusetts applied its 2017 'cookie nexus' regulation to require an online retailer to collect sales tax for periods before Wayfair, arguing that software and cookies on in-state customers' devices constituted physical presence.",
        holding="Wayfair applies prospectively only from its date; the presence of apps and cookies on customers' devices did not satisfy Quill's physical-presence requirement for pre-Wayfair periods, so the assessment was abated.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.mass.gov/doc/us-auto-parts-network-inc-v-commissioner-of-revenue/download",
        tags=["wayfair-follow-on", "cookie-nexus", "retroactivity"],
    ),
]

# ---------------------------------------------------------------- CJEU / EU General Court
C += [
    case(
        "EU",
        "Court of Justice of the European Union (Grand Chamber)",
        "Commission v Ireland and Apple (Apple State aid)",
        citation="C-465/20 P, ECLI:EU:C:2024:724",
        docket="C-465/20 P",
        decided="2024-09-10",
        tax_types=["corporate_income"],
        summary="The Commission's 2016 decision found that Irish tax rulings allocating almost all of Apple Sales International's and Apple Operations Europe's profits to stateless 'head offices' constituted EUR 13bn of unlawful State aid. The General Court annulled the decision in 2020.",
        holding="The Court of Justice set aside the General Court judgment and gave final judgment upholding the Commission decision: Ireland granted Apple unlawful aid that must be recovered (approximately EUR 13bn plus interest). The escrow fund (about EUR 14.2bn including interest) was transferred to the Irish Exchequer between September 2024 and May 2025.",
        significance="landmark",
        outcome="government",
        url="https://curia.europa.eu/juris/liste.jsf?num=C-465/20",
        tags=["state-aid", "tax-rulings", "apple", "ireland"],
    ),
    case(
        "EU",
        "Court of Justice of the European Union (Grand Chamber)",
        "Fiat Chrysler Finance Europe v Commission",
        citation="C-885/19 P and C-898/19 P, ECLI:EU:C:2022:859",
        docket="C-885/19 P",
        decided="2022-11-08",
        tax_types=["transfer_pricing", "corporate_income"],
        summary="The Commission found a Luxembourg transfer pricing ruling for Fiat's financing company to be State aid by reference to an OECD-style arm's-length principle not contained in Luxembourg law at the time.",
        holding="The Commission erred in law by applying an arm's-length principle distinct from the one defined in Luxembourg national law as the reference framework; the Commission decision was annulled. Only national law determines the 'normal' taxation against which selectivity is assessed.",
        significance="landmark",
        outcome="taxpayer",
        url="https://curia.europa.eu/juris/liste.jsf?num=C-885/19",
        tags=["state-aid", "arm's-length", "reference-framework"],
    ),
    case(
        "EU",
        "Court of Justice of the European Union",
        "Commission v Amazon and Luxembourg",
        citation="C-457/21 P, ECLI:EU:C:2023:985",
        docket="C-457/21 P",
        decided="2023-12-14",
        tax_types=["transfer_pricing", "corporate_income"],
        summary="The Commission found that a 2003 Luxembourg ruling approving a royalty paid by Amazon EU Sàrl to a Luxembourg partnership conferred EUR 250m of State aid. The General Court annulled the decision in 2021.",
        holding="The Commission's appeal was dismissed: following Fiat, the Commission wrongly relied on the OECD Transfer Pricing Guidelines rather than Luxembourg law as the reference framework, so the decision was vitiated regardless of the General Court's reasoning.",
        significance="significant",
        outcome="taxpayer",
        url="https://curia.europa.eu/juris/liste.jsf?num=C-457/21",
        tags=["state-aid", "transfer-pricing", "luxembourg"],
    ),
    case(
        "EU",
        "Court of Justice of the European Union (Grand Chamber)",
        "Luxembourg and Engie v Commission",
        citation="C-451/21 P and C-454/21 P, ECLI:EU:C:2023:948",
        docket="C-451/21 P",
        decided="2023-12-05",
        tax_types=["corporate_income"],
        summary="The Commission found Luxembourg rulings allowing a hybrid ZORA financing structure to produce a deduction with no corresponding inclusion, and not applying the national anti-abuse rule, to be State aid of around EUR 120m.",
        holding="The General Court judgment upholding the Commission was set aside and the Commission decision annulled: the Commission erred in identifying a narrow reference framework and in requiring Luxembourg to apply its GAAR in a way not established by national administrative practice.",
        significance="significant",
        outcome="taxpayer",
        url="https://curia.europa.eu/juris/liste.jsf?num=C-451/21",
        tags=["state-aid", "hybrid", "gaar"],
    ),
    case(
        "EU",
        "General Court of the European Union",
        "Netherlands and Starbucks v Commission",
        citation="T-760/15 and T-636/16, ECLI:EU:T:2019:669",
        docket="T-760/15",
        decided="2019-09-24",
        tax_types=["transfer_pricing", "corporate_income"],
        summary="The Commission found that a Dutch APA accepting a TNMM-based remuneration for Starbucks Manufacturing EMEA and a royalty to a UK partnership granted State aid of EUR 20–30m.",
        holding="The Commission was entitled to use the arm's-length principle as a tool to check selectivity but failed to demonstrate that the methodological choices in the APA produced an advantage; the decision was annulled. Not appealed.",
        significance="significant",
        outcome="taxpayer",
        url="https://curia.europa.eu/juris/liste.jsf?num=T-760/15",
        tags=["state-aid", "apa", "tnmm"],
    ),
    case(
        "EU",
        "Court of Justice of the European Union",
        "Skandia America Corp. (USA), filial Sverige v Skatteverket",
        citation="C-7/13, ECLI:EU:C:2014:2225",
        docket="C-7/13",
        decided="2014-09-17",
        tax_types=["vat"],
        summary="A US company supplied externally purchased IT services to its Swedish branch, which was a member of a Swedish VAT group.",
        holding="Supplies from a head office in a third country to a branch that belongs to a VAT group in a Member State are taxable supplies to the VAT group, and the group is liable for VAT under the reverse charge.",
        significance="landmark",
        outcome="government",
        url="https://curia.europa.eu/juris/liste.jsf?num=C-7/13",
        tags=["vat-grouping", "branch", "head-office"],
    ),
    case(
        "EU",
        "Court of Justice of the European Union (Grand Chamber)",
        "N Luxembourg 1 and others (Danish beneficial ownership cases)",
        citation="C-115/16, C-118/16, C-119/16, C-299/16, ECLI:EU:C:2019:134",
        docket="C-115/16",
        decided="2019-02-26",
        tax_types=["withholding"],
        summary="Danish companies paid interest (and, in the parallel T Danmark cases C-116/16 and C-117/16, dividends) to EU intermediate holding companies that passed them on to investors outside the EU, claiming exemption under the Interest and Royalties and Parent-Subsidiary Directives.",
        holding="Member States must deny directive benefits where there is an abusive arrangement, even without a domestic anti-abuse provision; conduit companies that pass on income shortly after receipt are not beneficial owners, and indicators of abuse include the absence of economic activity and back-to-back flows.",
        significance="landmark",
        outcome="government",
        url="https://curia.europa.eu/juris/liste.jsf?num=C-115/16",
        tags=["beneficial-ownership", "abuse", "interest-royalties-directive", "conduit"],
    ),
    case(
        "EU",
        "Court of Justice of the European Union",
        "Lexel AB v Skatteverket",
        citation="C-484/19, ECLI:EU:C:2021:34",
        docket="C-484/19",
        decided="2021-01-20",
        tax_types=["corporate_income"],
        summary="Sweden denied Lexel a deduction for interest paid to a French group company under a targeted interest-limitation rule because the debt was considered predominantly tax-motivated, even though the transaction was at arm's length.",
        holding="Denying deduction of arm's-length interest paid to an associated company in another Member State, while the same payment would be deductible domestically (through group contribution), restricts freedom of establishment and cannot be justified by combating abuse because arm's-length transactions are not wholly artificial.",
        significance="significant",
        outcome="taxpayer",
        url="https://curia.europa.eu/juris/liste.jsf?num=C-484/19",
        tags=["interest-limitation", "freedom-of-establishment", "arm's-length"],
    ),
    case(
        "EU",
        "Court of Justice of the European Union (Grand Chamber)",
        "Commission v Hungary (advertisement tax)",
        citation="C-596/19 P, ECLI:EU:C:2021:202",
        docket="C-596/19 P",
        decided="2021-03-16",
        tax_types=["digital_services", "other"],
        summary="The Commission found Hungary's steeply progressive turnover-based advertisement tax to be State aid favouring smaller undertakings. The General Court annulled the decision.",
        holding="Progressive turnover-based taxes are within Member States' fiscal autonomy and not inherently selective; absent evidence of manifestly discriminatory design, the Commission cannot treat a progressive structure as aid (decided alongside Commission v Poland, C-562/19 P, on the retail tax).",
        significance="significant",
        outcome="taxpayer",
        url="https://curia.europa.eu/juris/liste.jsf?num=C-596/19",
        tags=["state-aid", "turnover-tax", "progressive-tax"],
    ),
]

# ---------------------------------------------------------------- United Kingdom
C += [
    case(
        "GB",
        "UK Supreme Court",
        "HMRC v Fisher and another",
        citation="[2023] UKSC 44",
        docket="UKSC/2021/0212 (with UKSC/2021/0213)",
        decided="2023-11-21",
        tax_types=["personal_income"],
        summary="UK-resident shareholders transferred a telebetting business from a UK company to a Gibraltar company they controlled; HMRC assessed them under the transfer of assets abroad rules (s.739 ICTA) as transferors.",
        holding="The transfer of assets abroad code applies only to individuals who are the transferor or procure the transfer; minority shareholders of a transferring company are not 'quasi-transferors'. Appeals allowed for the taxpayers.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.supremecourt.uk/cases/uksc-2021-0212",
        tags=["transfer-of-assets-abroad", "anti-avoidance"],
    ),
    case(
        "GB",
        "UK Supreme Court",
        "Hurstwood Properties (A) Ltd and others v Rossendale Borough Council",
        citation="[2021] UKSC 16",
        docket="UKSC/2019/0071",
        decided="2021-05-14",
        tax_types=["property"],
        summary="Landlords of empty commercial properties granted short leases to special purpose vehicles that were then dissolved or put into liquidation to exploit business rates exemptions.",
        holding="On a purposive construction of the 'owner' provisions, the SPVs were not entitled to possession in the relevant sense and the landlords remained liable for business rates; the Ramsay principle applies to rating legislation. Piercing the corporate veil was not available.",
        significance="significant",
        outcome="government",
        url="https://www.supremecourt.uk/cases/uksc-2019-0071",
        tags=["business-rates", "ramsay", "avoidance"],
    ),
    case(
        "GB",
        "UK Supreme Court",
        "News Corp UK & Ireland Ltd v HMRC",
        citation="[2023] UKSC 7",
        docket="UKSC/2021/0047",
        decided="2023-02-22",
        tax_types=["vat"],
        summary="News Corp claimed that digital editions of The Times and The Sun were 'newspapers' zero-rated under Group 3 of Schedule 8 VATA 1994 for 2010–2016, before the law was amended in 2020 to zero-rate e-publications.",
        holding="The 'always speaking' principle did not extend 'newspapers' to digital editions: the zero-rating provision, subject to the EU standstill, must be construed narrowly and the term denotes printed goods. Appeal dismissed.",
        significance="significant",
        outcome="government",
        url="https://www.supremecourt.uk/cases/uksc-2021-0047",
        tags=["vat", "zero-rating", "digital-publications"],
    ),
    case(
        "GB",
        "UK Supreme Court",
        "Centrica Overseas Holdings Ltd v HMRC",
        citation="[2024] UKSC 25",
        docket="UKSC/2022/0183",
        decided="2024-07-16",
        tax_types=["corporate_income"],
        summary="An intermediate holding company sought to deduct GBP 2.5m of professional fees incurred in connection with the disposal of its Dutch subsidiary as management expenses.",
        holding="Expenses of management are subject to the same capital/revenue distinction as trading expenses; fees incurred once the decision in principle to sell had been made were capital in nature and not deductible.",
        significance="significant",
        outcome="government",
        url="https://www.supremecourt.uk/cases/uksc-2022-0183",
        tags=["management-expenses", "capital-revenue"],
    ),
    case(
        "GB",
        "UK Supreme Court",
        "HMRC v NCL Investments Ltd and Smith & Williamson Corporate Services Ltd",
        citation="[2022] UKSC 9",
        docket="UKSC/2020/0125",
        decided="2022-03-23",
        tax_types=["corporate_income"],
        summary="Companies claimed deductions for IFRS 2 accounting debits recognised for share options granted to employees by an employee benefit trust, where no cash was paid.",
        holding="The accounting debits were deductible in computing trading profits: they were incurred wholly and exclusively for the trade and the statutory rules did not require an actual outgoing; the Court affirmed the primacy of GAAP accounting absent a specific override.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.supremecourt.uk/cases/uksc-2020-0125",
        tags=["ifrs2", "share-options", "gaap"],
    ),
    case(
        "GB",
        "UK Supreme Court",
        "Royal Bank of Canada v HMRC",
        citation="[2025] UKSC 2",
        docket="UKSC/2023/0101",
        decided="2025-02-12",
        tax_types=["corporate_income"],
        summary="RBC received payments from Sulpetro's successor calculated by reference to oil produced from the Buchan field under a 1980s loan workout; HMRC taxed them as UK-source income under the Canada–UK treaty's Article 6(2) 'right to work' oil extension and the UK ring-fence rules.",
        holding="Appeal allowed for the taxpayer (4-1): the payments were not consideration for a right to work the Buchan field, because RBC never held any such right and the payments derived from a contractual debt; the treaty gave the UK no taxing right. The decision narrows the scope of the immovable-property article for derivative payment streams.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.supremecourt.uk/cases/uksc-2023-0101",
        tags=["treaty", "oil-and-gas", "immovable-property"],
    ),
    case(
        "GB",
        "UK Supreme Court",
        "Prudential Assurance Co Ltd v HMRC",
        citation="[2025] UKSC 34",
        docket="UKSC/2024/0065",
        decided="2025-09-11",
        tax_types=["vat"],
        summary="Silverfleet supplied investment-management services to Prudential while both were members of the same VAT group; performance fees for those services were invoiced and paid years later, after Silverfleet had left the group.",
        holding="Appeal dismissed for HMRC (3-2): for continuous supplies of services the time-of-supply rules fix the supply at the date of invoice/payment, so the performance fees were consideration for a supply made when the parties were no longer in the same VAT group and were subject to VAT. The VAT grouping disregard does not override the time-of-supply rules.",
        significance="significant",
        outcome="government",
        url="https://www.supremecourt.uk/cases/uksc-2024-0065",
        tags=["vat-grouping", "time-of-supply", "continuous-supplies"],
    ),
    case(
        "GB",
        "Court of Appeal (Civil Division)",
        "BlackRock HoldCo 5 LLC v HMRC",
        citation="[2024] EWCA Civ 330",
        docket="CA-2022-001918",
        decided="2024-04-11",
        tax_types=["corporate_income", "transfer_pricing"],
        summary="BlackRock financed its acquisition of Barclays Global Investors through USD 4bn of intra-group loans to a UK LLC; HMRC denied interest deductions under the transfer pricing rules and the unallowable purpose rule. The Upper Tribunal found for HMRC and BlackRock appealed.",
        holding="Appeal dismissed: on transfer pricing the Court of Appeal found for BlackRock (independent lenders would have lent on the terms agreed once third-party covenants were hypothesised, so the TP rules did not restrict the interest), but on the unallowable purpose rule it found for HMRC — the loans had a tax main purpose and, on a just and reasonable apportionment, all of the interest was attributable to it. The Supreme Court refused permission to appeal on 13 October 2024 (UKSC/2024/0070). BAILII blocks automated clients; the National Archives case-law copy is linked.",
        significance="significant",
        outcome="government",
        url="https://caselaw.nationalarchives.gov.uk/ewca/civ/2024/330",
        tags=["unallowable-purpose", "transfer-pricing", "intra-group-debt"],
    ),
    case(
        "GB",
        "Court of Appeal (Civil Division)",
        "Hargreaves Property Holdings Ltd v HMRC",
        citation="[2024] EWCA Civ 365",
        docket="CA-2023-001517",
        decided="2024-04-15",
        tax_types=["withholding"],
        summary="A UK property group structured intra-group loan interest payments through a UK company interposed to claim the 'beneficially entitled' UK-company exemption from withholding tax on yearly interest.",
        holding="The interposed UK company was not beneficially entitled to the interest as it was obliged to pass it on; the interest was 'yearly interest' and subject to withholding. Appeal dismissed (judgment handed down 15 April 2024). BAILII blocks automated clients; the National Archives case-law copy is linked.",
        significance="significant",
        outcome="government",
        url="https://caselaw.nationalarchives.gov.uk/ewca/civ/2024/365",
        tags=["withholding", "beneficial-entitlement", "yearly-interest"],
    ),
]

# ---------------------------------------------------------------- India
C += [
    case(
        "IN",
        "Supreme Court of India",
        "Vodafone International Holdings B.V. v. Union of India",
        citation="(2012) 6 SCC 613",
        docket="Civil Appeal No. 733 of 2012",
        decided="2012-01-20",
        tax_types=["capital_gains", "withholding"],
        summary="The Indian tax authority sought USD 2bn of withholding tax from Vodafone on its 2007 acquisition of a Cayman company holding an indirect 67% interest in Hutchison Essar, an Indian telecom operator.",
        holding="The transfer of shares in a foreign company was not a transfer of a capital asset situated in India; the 'look-at' approach applies to holding structures and India lacked jurisdiction to tax the offshore transaction. Parliament responded with retrospective indirect-transfer amendments in 2012, later prospectively limited in 2021.",
        significance="landmark",
        outcome="taxpayer",
        url="https://api.sci.gov.in/jonew/judis/39003.pdf",
        tags=["indirect-transfer", "capital-gains", "look-at"],
    ),
    case(
        "IN",
        "Supreme Court of India",
        "Engineering Analysis Centre of Excellence Pvt. Ltd. v. Commissioner of Income Tax",
        citation="(2021) 432 ITR 471 (SC)",
        docket="Civil Appeal Nos. 8733-8734 of 2018",
        decided="2021-03-02",
        tax_types=["withholding"],
        summary="Indian distributors and end-users of shrink-wrapped and embedded software were assessed for failing to withhold tax on payments to non-resident vendors treated as royalties.",
        holding="Payments for the purchase of software (including licences without transfer of copyright) are not royalties under the relevant DTAAs; the OECD Commentary is persuasive, the domestic retrospective amendment cannot override treaties, and no withholding under s.195 was required.",
        significance="landmark",
        outcome="taxpayer",
        url="https://api.sci.gov.in/supremecourt/2011/38137/38137_2011_33_1501_26629_Judgement_02-Mar-2021.pdf",
        tags=["software-royalty", "dtaa", "withholding"],
    ),
    case(
        "IN",
        "Supreme Court of India",
        "Assessing Officer Circle (International Taxation) v. Nestlé SA (MFN clause)",
        citation="2023 INSC 928",
        docket="Civil Appeal No. 1420 of 2023",
        decided="2023-10-19",
        tax_types=["withholding"],
        summary="Taxpayers from the Netherlands, France and Switzerland claimed the benefit of lower withholding rates via most-favoured-nation clauses in Indian treaties triggered by India's later treaties with Slovenia, Lithuania and Colombia, which became OECD members after signing.",
        holding="An MFN clause is not self-executing in India: it requires a notification under s.90 of the Income-tax Act, and the third state must have been an OECD member at the time its treaty with India was signed. Revenue's appeals allowed. Review petitions were dismissed on 6 August 2024 and a curative petition on 16 September 2025 (secondary sources).",
        significance="landmark",
        outcome="government",
        url="https://api.sci.gov.in/supremecourt/2022/6394/6394_2022_8_1502_47832_Judgement_19-Oct-2023.pdf",
        tags=["mfn", "treaty", "notification"],
    ),
    case(
        "IN",
        "Supreme Court of India",
        "Chief Commissioner of CGST v. Safari Retreats Pvt. Ltd.",
        citation="2024 INSC 756",
        docket="Civil Appeal No. 2948 of 2023",
        decided="2024-10-03",
        tax_types=["gst"],
        summary="A shopping-mall developer claimed GST input tax credit on construction inputs used to build a mall let out to tenants, which the revenue denied under s.17(5)(c)/(d) CGST Act as credit for construction of immovable property 'on own account'.",
        holding="Section 17(5)(d) is constitutionally valid but a building may qualify as 'plant' under the functionality test, in which case ITC is available; each case turns on whether the building is essential to the supply of services. Parliament retrospectively amended 'plant or machinery' to 'plant and machinery' (Finance Act 2025 s.119, with effect from 1 July 2017) to neutralise the ruling; the revenue's review petition was dismissed on 20 May 2025.",
        significance="landmark",
        outcome="mixed",
        url="https://api.sci.gov.in/supremecourt/2019/37367/37367_2019_6_1501_56233_Judgement_03-Oct-2024.pdf",
        tags=["gst", "input-tax-credit", "immovable-property"],
    ),
]

# ---------------------------------------------------------------- Australia
C += [
    case(
        "AU",
        "Full Federal Court of Australia",
        "Commissioner of Taxation v Glencore Investment Pty Ltd",
        citation="[2020] FCAFC 187",
        docket="NSD 1636, 1637 and 1639 of 2019",
        decided="2020-11-06",
        tax_types=["transfer_pricing"],
        summary="Glencore's Australian copper mine sold concentrate to its Swiss parent under a price-sharing agreement with a fixed 23% treatment and refining charge; the Commissioner argued independent parties would have used benchmark terms.",
        holding="The taxpayer's pricing fell within an arm's-length range; the transfer pricing rules require pricing the actual transaction (not a hypothetical different one) and the Commissioner's reconstruction was rejected except for a minor freight adjustment. Special leave to appeal refused by the High Court in 2021.",
        significance="landmark",
        outcome="taxpayer",
        url="https://www.judgments.fedcourt.gov.au/judgments/Judgments/fca/full/2020/2020fcafc0187",
        tags=["transfer-pricing", "commodities", "arm's-length"],
    ),
    case(
        "AU",
        "High Court of Australia",
        "Commissioner of Taxation v PepsiCo, Inc.",
        citation="[2025] HCA 30",
        docket="M98–M103/2024",
        decided="2025-08-13",
        tax_types=["withholding", "other"],
        summary="PepsiCo granted Schweppes Australia the right to use its trademarks under exclusive bottling agreements while selling it concentrate; the Commissioner argued part of the concentrate price was an embedded royalty subject to withholding tax or, alternatively, diverted profits tax.",
        holding="By a 4-3 majority (Gordon, Edelman, Steward and Gleeson JJ; Gageler CJ, Jagot and Beech-Jones JJ dissenting) the High Court held that payments by Schweppes for concentrate were not royalties (no part was consideration for use of IP) and not 'paid to' PepsiCo, so no royalty withholding tax arose, and the diverted profits tax did not apply. Commissioner's appeal dismissed.",
        significance="landmark",
        outcome="taxpayer",
        url="https://eresources.hcourt.gov.au/showCase/2025/HCA/30",
        tags=["embedded-royalty", "withholding", "diverted-profits-tax"],
    ),
    case(
        "AU",
        "High Court of Australia",
        "Commissioner of Taxation v Bendel",
        citation="[2026] HCA 18",
        docket="S128/2025",
        decided="2026-06-10",
        tax_types=["corporate_income", "other"],
        summary="A private company beneficiary left its entitlement to trust income unpaid (an unpaid present entitlement); the Commissioner treated the UPE as a 'loan' by the company to the trust under Division 7A, giving rise to a deemed dividend.",
        holding="By a 5-2 majority the High Court dismissed the Commissioner's appeal from the Full Federal Court: an unpaid present entitlement is not a 'loan' within the extended definition in s 109D(3) ITAA 1936 because there is no obligation to repay an amount advanced; Division 7A therefore does not apply to UPEs as such. The ATO's long-standing administrative position (TD 2022/11) is displaced. Details as reported by the High Court judgment summary; verify the special leave docket reference before reliance.",
        significance="landmark",
        outcome="taxpayer",
        url="https://eresources.hcourt.gov.au/showCase/2026/HCA/18",
        tags=["division-7a", "trusts", "deemed-dividend"],
    ),
    case(
        "AU",
        "Federal Court of Australia",
        "Mylan Australia Holding Pty Ltd v Commissioner of Taxation (No 2)",
        citation="[2024] FCA 253",
        docket="VID 770 of 2021; VID 526 of 2022",
        decided="2024-03-20",
        tax_types=["corporate_income"],
        summary="The Commissioner applied Part IVA to deny interest deductions on AUD 923m of related-party debt used to fund Mylan's 2007 acquisition of Alphapharm, alleging a dominant purpose of obtaining a tax benefit.",
        holding="Part IVA did not apply: the debt-funded acquisition structure was commercially explicable and the Commissioner's counterfactuals of equity funding were not reasonable alternatives. The Commissioner did not appeal.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.judgments.fedcourt.gov.au/judgments/Judgments/fca/single/2024/2024fca0253",
        tags=["part-iva", "debt-funding", "anti-avoidance"],
    ),
    case(
        "AU",
        "Full Federal Court of Australia",
        "Minerva Financial Group Pty Ltd v Commissioner of Taxation",
        citation="[2024] FCAFC 28",
        docket="VID 662 of 2022",
        decided="2024-03-08",
        tax_types=["corporate_income"],
        summary="A securitisation group restructured so that income flowed through a trust silo to a Singapore-resident unitholder rather than a corporate silo taxed at 30%; the Commissioner applied Part IVA to the trustee's distribution decisions.",
        holding="Part IVA did not apply: the scheme's dominant purpose was commercial, and the exercise of a discretion in the manner the trust deed contemplated did not amount to a scheme entered into for the dominant purpose of a tax benefit. Taxpayer's appeal allowed.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.judgments.fedcourt.gov.au/judgments/Judgments/fca/full/2024/2024fcafc0028",
        tags=["part-iva", "trusts", "stapled-structures"],
    ),
]

# ---------------------------------------------------------------- Canada
C += [
    case(
        "CA",
        "Supreme Court of Canada",
        "Canada v. Alta Energy Luxembourg S.A.R.L.",
        citation="2021 SCC 49",
        docket="39113",
        decided="2021-11-26",
        tax_types=["capital_gains", "corporate_income"],
        summary="A Luxembourg company with no substantive presence claimed the Canada–Luxembourg treaty exemption on a CAD 380m gain from selling shares of a Canadian shale company; the Minister invoked the GAAR, alleging treaty shopping.",
        holding="The GAAR did not apply: the treaty's text and the negotiated carve-out reflected a deliberate choice to exempt such gains, and treaty shopping was not itself abusive absent a departure from the object, spirit and purpose of the provisions. 6-3 for the taxpayer.",
        significance="landmark",
        outcome="taxpayer",
        url="https://decisions.scc-csc.ca/scc-csc/scc-csc/en/item/19089/index.do",
        tags=["gaar", "treaty-shopping", "luxembourg"],
    ),
    case(
        "CA",
        "Supreme Court of Canada",
        "Canada v. Loblaw Financial Holdings Inc.",
        citation="2021 SCC 51",
        docket="39220",
        decided="2021-12-03",
        tax_types=["corporate_income"],
        summary="Loblaw's Barbados bank subsidiary earned income from managing the group's funds; the Minister argued it conducted business principally with non-arm's-length persons so its income was FAPI rather than exempt foreign bank income.",
        holding="The 'arm's length' requirement in the financial institution exception is assessed on the bank's business conducted with its customers (receipt of funds, not capital contributions and corporate oversight); the subsidiary qualified and its income was not FAPI. Unanimous for the taxpayer.",
        significance="significant",
        outcome="taxpayer",
        url="https://decisions.scc-csc.ca/scc-csc/scc-csc/en/item/19096/index.do",
        tags=["fapi", "foreign-affiliate", "barbados"],
    ),
    case(
        "CA",
        "Supreme Court of Canada",
        "Deans Knight Income Corp. v. Canada",
        citation="2023 SCC 16",
        docket="39869",
        decided="2023-05-26",
        tax_types=["corporate_income"],
        summary="A corporation with CAD 90m of unused losses was acquired through a structure that avoided de jure control (and thus the loss-restriction rule in s.111(5)) while giving the investor functional control.",
        holding="The GAAR applied: the transactions frustrated the object, spirit and purpose of s.111(5), which targets changes in who effectively controls the corporation and its loss monetisation; the loss deductions were denied. 7-1 for the Crown.",
        significance="landmark",
        outcome="government",
        url="https://decisions.scc-csc.ca/scc-csc/scc-csc/en/item/19939/index.do",
        tags=["gaar", "loss-trading", "de-facto-control"],
    ),
    case(
        "CA",
        "Supreme Court of Canada",
        "Dow Chemical Canada ULC v. Canada",
        citation="2024 SCC 23",
        docket="40276",
        decided="2024-06-28",
        tax_types=["transfer_pricing"],
        summary="Dow sought a downward transfer pricing adjustment under s.247(10) ITA; the question was whether the Tax Court or the Federal Court has jurisdiction to review the Minister's discretionary refusal.",
        holding="The Minister's decision under s.247(10) is a discretionary decision reviewable only by the Federal Court on judicial review, not by the Tax Court on appeal from the assessment. 4-3 for the Crown.",
        significance="significant",
        outcome="government",
        url="https://decisions.scc-csc.ca/scc-csc/scc-csc/en/item/20518/index.do",
        tags=["transfer-pricing", "jurisdiction", "downward-adjustment"],
    ),
]

# ---------------------------------------------------------------- Continental Europe, Brazil, Switzerland
C += [
    case(
        "FR",
        "Conseil d'État",
        "Ministre de l'Action et des Comptes publics c/ Société Conversant International Ltd (Valueclick)",
        citation="CE, plén. fisc., 11 déc. 2020, n° 420174",
        docket="420174",
        decided="2020-12-11",
        tax_types=["corporate_income", "vat"],
        summary="An Irish company sold online advertising to French clients through a French affiliate that negotiated contracts formally concluded in Ireland; the tax authority asserted a French permanent establishment.",
        holding="A dependent agent PE exists where the French affiliate habitually decided on transactions that the foreign principal merely rubber-stamped, even if contracts were formally signed abroad; the case was remanded and the PE finding upheld. A landmark alignment with the BEPS Action 7 approach. The litigation ended with CE 4 Apr 2025, n° 461220, rejecting Conversant's remaining claims.",
        significance="landmark",
        outcome="government",
        url="https://www.conseil-etat.fr/fr/arianeweb/CE/decision/2020-12-11/420174",
        tags=["permanent-establishment", "dependent-agent", "digital"],
    ),
    case(
        "DE",
        "Bundesfinanzhof (Federal Fiscal Court)",
        "BFH, Urteil v. 10.11.2021 – I R 27/19 (Anti-treaty-shopping §50d Abs. 3 EStG)",
        citation="BFH I R 27/19",
        docket="I R 27/19",
        decided="2021-11-10",
        tax_types=["withholding"],
        summary="Following the CJEU's Deister Holding / Juhler Holding (C-504/16 and C-613/16) and GS (C-440/17) judgments, the BFH considered the German anti-treaty-shopping rule (§50d(3) EStG, 2012 version) denying withholding tax relief to foreign holding companies without sufficient substance. (The decision previously seeded here, I R 94/15 of 13 Jun 2018, concerns CFC/hidden-contribution issues under the AStG, not §50d(3).)",
        holding="§50d(3) EStG in its 2012 version infringes the Parent-Subsidiary Directive and freedom of establishment where it operates as a general presumption of abuse without allowing the taxpayer to prove non-tax reasons; the provision must be applied in conformity with EU law and the foreign parent is entitled to the refund of German dividend withholding tax. Germany rewrote the rule in 2021 (AbzStEntModG).",
        significance="significant",
        outcome="taxpayer",
        url="https://www.bundesfinanzhof.de/de/entscheidung/entscheidungen-online/detail/STRE202250076/",
        tags=["anti-treaty-shopping", "withholding", "parent-subsidiary-directive"],
    ),
    case(
        "NL",
        "Hoge Raad (Supreme Court of the Netherlands)",
        "Hoge Raad 16 juli 2021, ECLI:NL:HR:2021:1152 (Hunkemöller / private equity interest deduction)",
        citation="ECLI:NL:HR:2021:1152",
        docket="19/02596",
        decided="2021-07-16",
        tax_types=["corporate_income"],
        summary="A private-equity acquisition of Hunkemöller was financed with shareholder loans from French FCPR funds through Dutch intermediaries, generating interest deductions in the Netherlands with no corresponding taxation. (ECLI:NL:HR:2020:21, previously cited here, is an unrelated art. 17(3)(b) Vpb case.)",
        holding="Interest deduction was denied under fraus legis (abuse of law): the financing structure was artificial and primarily tax-motivated, and the Court confirmed the deduction limitation did not infringe EU law. The decision reinforced Dutch anti-base-erosion doctrine for leveraged acquisitions and was applied again in HR 19 Dec 2025, ECLI:NL:HR:2025:1960.",
        significance="significant",
        outcome="government",
        url="https://uitspraken.rechtspraak.nl/details?id=ECLI:NL:HR:2021:1152",
        tags=["fraus-legis", "interest-deduction", "private-equity"],
    ),
    case(
        "DK",
        "Højesteret (Supreme Court of Denmark)",
        "Skatteministeriet v. TDC / NetApp (beneficial ownership — dividend cases)",
        citation="U.2023.1575 H (sager 69/2021, 70/2021 and 79/2021)",
        docket="69/2021, 70/2021, 79/2021",
        decided="2023-01-09",
        tax_types=["withholding"],
        summary="Following the CJEU's 2019 Danish cases, the Supreme Court decided whether dividends paid by Danish companies to Luxembourg and Cyprus intermediate holding companies and passed on to investors outside the EU were exempt from Danish withholding tax. (Cases 116/2021 and 117/2021, previously cited here, are the Takeda/NTC interest cases decided 4 May 2023.)",
        holding="The intermediate companies were conduits and not beneficial owners; withholding tax was due on the dividends (NetApp was partially successful where onward distribution to a US parent would have qualified for treaty exemption). Confirmed the beneficial-ownership doctrine in Danish law. domstol.dk blocks automated clients.",
        significance="landmark",
        outcome="mixed",
        url="https://www.domstol.dk/hoejesteret/aktuelt/2023/1/beneficial-owner-sager/",
        tags=["beneficial-ownership", "withholding", "conduit"],
    ),
    case(
        "IT",
        "Corte Suprema di Cassazione",
        "Cass. civ., Sez. V, 21 dicembre 2018, nn. 33234 e 33235 (Dolce & Gabbana / Gado — esterovestizione)",
        citation="Cass. civ. nn. 33234 and 33235/2018",
        docket="33234/2018; 33235/2018",
        decided="2018-12-21",
        tax_types=["corporate_income", "transfer_pricing"],
        summary="After the criminal acquittal of the Dolce & Gabbana founders (Cass. pen. n. 43809, deposited 30 Oct 2015) on charges of fictitiously relocating trademark ownership to a Luxembourg company (Gado Sàrl), the civil tax proceedings on esterovestizione and the valuation of the trademark transfer continued. (Cass. n. 32255/2021, previously cited here, is unrelated.)",
        holding="The Court of Cassation quashed the lower judgments with remand (cassata con rinvio): foreign incorporation of a subsidiary whose strategic direction comes from an Italian parent does not per se establish fictitious residence; the tax authority must prove that the foreign entity is an artificial arrangement without genuine economic activity, consistent with CJEU Cadbury Schweppes. ItalGiure deep links are session-bound; the search portal is linked.",
        significance="significant",
        outcome="taxpayer",
        url="https://www.italgiure.giustizia.it/sncass/",
        tags=["esterovestizione", "residence", "trademarks"],
    ),
    case(
        "BR",
        "Supremo Tribunal Federal",
        "RE 574.706/PR – Exclusão do ICMS da base de cálculo do PIS e da COFINS",
        citation="RE 574.706, Tema 69",
        docket="RE 574.706",
        decided="2017-03-15",
        tax_types=["vat", "other"],
        summary="Taxpayers argued that ICMS (state VAT) collected on sales is not revenue and should be excluded from the gross revenue base of the federal PIS and COFINS contributions.",
        holding="ICMS does not form part of the taxpayer's revenue and must be excluded from the PIS/COFINS base (the 'thesis of the century'). In 2021 the STF modulated the effects to 15 March 2017 and confirmed that the ICMS shown on the invoice is the amount to exclude, creating refunds estimated at over BRL 250bn.",
        significance="landmark",
        outcome="taxpayer",
        url="https://portal.stf.jus.br/processos/detalhe.asp?incidente=2585258",
        tags=["icms", "pis-cofins", "tax-base"],
    ),
    case(
        "BR",
        "Superior Tribunal de Justiça",
        "Tema 1125 – Exclusão do ICMS-ST da base de cálculo do PIS e da COFINS",
        citation="REsp 1.896.678 e REsp 1.958.265",
        docket="REsp 1.896.678",
        decided="2023-12-13",
        tax_types=["vat", "other"],
        summary="Following the STF's Tema 69, taxpayers that pay ICMS under the tax-substitution regime (ICMS-ST) sought to exclude that amount from the PIS/COFINS base of the substituted taxpayer.",
        holding="ICMS-ST borne by the substituted taxpayer must also be excluded from the PIS/COFINS base; applying the same principle as RE 574.706, the STJ held the effects run from 15 March 2017.",
        significance="significant",
        outcome="taxpayer",
        url="https://processo.stj.jus.br/repetitivos/temas_repetitivos/pesquisa.jsp?novaConsulta=true&tipo_pesquisa=T&cod_tema_inicial=1125&cod_tema_final=1125",
        tags=["icms-st", "pis-cofins", "repetitive-theme"],
    ),
    case(
        "CH",
        "Swiss Federal Supreme Court (Bundesgericht)",
        "BGer 2C_880/2018 (Beneficial ownership – UK bank dividend arbitrage)",
        citation="BGer 2C_880/2018 (unpublished)",
        docket="2C_880/2018",
        decided="2020-05-19",
        tax_types=["withholding"],
        summary="A UK bank claimed a refund of Swiss withholding tax under the Switzerland–UK treaty on dividends from Swiss shares acquired around the dividend date and hedged through total return swaps; the Federal Tax Administration denied the refund for lack of beneficial ownership. (The earlier Danish-bank case on futures hedging is BGer 2C_895/2012 of 5 May 2015.)",
        holding="The bank was not the beneficial owner because the swap arrangements obliged it to pass on the dividend economically; the treaty refund was denied. The judgment consolidates the Swiss approach to beneficial ownership in dividend arbitrage.",
        significance="significant",
        outcome="government",
        url="https://www.bger.ch/ext/eurospider/live/de/php/aza/http/index.php?highlight_docid=aza%3A%2F%2F19-05-2020-2C_880-2018&lang=de&type=show_document",
        tags=["beneficial-ownership", "withholding", "dividend-arbitrage"],
    ),
]

# ---------------------------------------------------------------- WTO
C += [
    case(
        None,
        "WTO Dispute Settlement Panel",
        "United States — Certain Measures on Steel and Aluminium Products (DS544, DS552, DS556, DS564)",
        citation="WT/DS544/R",
        docket="DS544",
        decided="2022-12-09",
        tax_types=["customs_tariff"],
        summary="China, Norway, Switzerland and Türkiye challenged the 2018 Section 232 tariffs of 25% on steel and 10% on aluminium, which the US defended as security measures under GATT Article XXI.",
        holding="The panels found the measures were not 'taken in time of war or other emergency in international relations' and were inconsistent with GATT Articles I and II; Article XXI(b)(iii) did not justify them. The US appealed 'into the void', so the reports were not adopted.",
        significance="landmark",
        outcome="mixed",
        url="https://www.wto.org/english/tratop_e/dispu_e/cases_e/ds544_e.htm",
        tags=["section-232", "national-security", "gatt-xxi"],
    ),
    case(
        None,
        "WTO Dispute Settlement Panel",
        "United States — Tariff Measures on Certain Goods from China (DS543)",
        citation="WT/DS543/R",
        docket="DS543",
        decided="2020-09-15",
        tax_types=["customs_tariff"],
        summary="China challenged the Section 301 tariffs on Lists 1 and 2 (USD 34bn and USD 16bn of imports) imposed in 2018 in response to alleged forced technology transfer and IP theft.",
        holding="The additional duties were prima facie inconsistent with GATT Articles I:1 and II:1 and the US failed to justify them under the public morals exception of Article XX(a). The US appealed in October 2020 to the non-functioning Appellate Body; the report remains unadopted.",
        significance="significant",
        outcome="mixed",
        url="https://www.wto.org/english/tratop_e/dispu_e/cases_e/ds543_e.htm",
        tags=["section-301", "china", "gatt"],
    ),
]

COURT_DECISIONS: list[dict] = C
