"""Discovered sources — Asia-Pacific (2026-08-25 discovery pass).

Same shape as ``app.seed.sources.SOURCES``; merged into the registry by the extension hook at the bottom of
``sources.py``. Every URL below was probed on 2026-08-25 with the TaxAtlas user agent and trialled twice
against a scratch database (``DATABASE_URL=sqlite:////tmp/apac.db``); a source had to return HTTP 200 and keep
>= 3 relevant items to be enabled.

Conventions
- ``authority`` is the local-language name; ``authority_en`` the English rendering when they differ.
- **Backstop** rows are keyword searches over aggregated press (``adapter="news"``, ``url="news://<slug>"``; the
  adapter tries GDELT, then Bing News, then Google News — Google answers 503 from GCP egress, see docs/sources.md
  "Backstops") in the local language when the official site is bot-blocked, JS-only or unreachable from outside the
  country. They are ``category="news"`` with ``tax_filter`` on and ``include_keywords`` so only tax/customs items
  survive, and their note carries the official URL that was found so the row can be repointed once a browser adapter
  or a working listing exists.
- Blocked officials are kept as ``adapter="html", enabled=False`` with a ``note`` (``needs browser adapter`` when a
  headless browser would fix it) so the gap is visible in the admin UI and ``check-urls`` can re-probe them.
- Sub-national rows use ISO 3166-2 codes that exist in ``jurisdictions.py`` (IN-MH, CN-SH, JP-13, AU-QLD ...).

Schedule policy (as in sources.py): courts daily, regulators every 6h, tariff/trade every 4h, news every 6h or
4x daily; minutes are staggered so the scheduler never fires every job at once.
"""

from __future__ import annotations

from taxatlas.models.enums import TaxType as T

_ALL_INCOME = [T.CORPORATE_INCOME, T.PERSONAL_INCOME]
_CORE = [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME]
_GST_CORE = [T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME]


def _backstop(
    slug: str,
    name: str,
    jurisdiction: str,
    query: str,
    hl: str,
    gl: str,
    include: list[str],
    official: str,
    reason: str,
    cron: str,
    tax_types: list[T] | None = None,
    authority: str = "Google News (aggregated press)",
    lang: str | None = None,  # kept for call-site compatibility; the news adapter derives Google's ceid from `hl`
) -> dict:
    """Keyword-search backstop over aggregated press (adapter="news": GDELT -> Bing -> Google News, see adapters/news.py).

    `gl` was the Google News edition; when it differs from the jurisdiction's country it is kept as `google_country`
    so the Google provider keeps the edition that answered on 2026-08-25 while GDELT/Bing search the jurisdiction itself.
    """
    country = jurisdiction.split("-")[0]
    cfg: dict = {"query": query, "lang": hl, "country": country}
    if gl and gl != country:
        cfg["google_country"] = gl
    cfg.update(
        {
            "tax_filter": True,
            "include_keywords": include,
            "max_items": 40,
            "note": f"backstop: Google News ({hl}). Official site {official} — {reason}",
        }
    )
    return {
        "slug": slug,
        "name": name,
        "url": f"news://{slug}",
        "jurisdiction_code": jurisdiction,
        "tax_types": tax_types or _CORE,
        "category": "news",
        "adapter": "news",
        "config": cfg,
        "schedule_cron": cron,
        "enabled": True,
        "authority": authority,
    }


def _blocked(
    slug: str,
    name: str,
    url: str,
    jurisdiction: str,
    category: str,
    note: str,
    cron: str,
    authority: str,
    tax_types: list[T] | None = None,
    authority_en: str | None = None,
    court: str | None = None,
) -> dict:
    cfg: dict = {"item_selector": "article", "note": note}
    if court:
        cfg["court"] = court
    row = {
        "slug": slug,
        "name": name,
        "url": url,
        "jurisdiction_code": jurisdiction,
        "tax_types": tax_types or _CORE,
        "category": category,
        "adapter": "html",
        "config": cfg,
        "schedule_cron": cron,
        "enabled": False,
        "authority": authority,
    }
    if authority_en:
        row["authority_en"] = authority_en
    return row


SOURCES: list[dict] = [
    # ====================================================================================
    # SOUTH ASIA
    # ====================================================================================
    {
        "slug": "pk-fbr-press",
        "name": "Pakistan FBR — press releases",
        "url": "https://www.fbr.gov.pk/pr",
        "jurisdiction_code": "PK",
        "tax_types": [T.PERSONAL_INCOME, T.CORPORATE_INCOME, T.VAT, T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "div.caption",
            "title_selector": "h4",
            "date_selector": "span.btn",
            "base_url": "https://www.fbr.gov.pk/",
            "max_items": 40,
        },
        "schedule_cron": "7 1,7,13,19 * * *",
        "enabled": True,
        "authority": "Federal Board of Revenue",
    },
    {
        "slug": "bd-nbr-vat-sros",
        "name": "Bangladesh NBR — VAT SROs",
        "url": "https://nbr.gov.bd/regulations/sros/vat-sros/eng",
        "jurisdiction_code": "BD",
        "tax_types": [T.VAT, T.EXCISE],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "table tbody tr",
            "title_selector": "td:nth-child(4)",
            "link_selector": "td:nth-child(2) a",
            "date_selector": "td:nth-child(3)",
            "date_dayfirst": True,
            "extra_selectors": {"sro_no": "td:nth-child(2)", "amended_by": "td:nth-child(5)"},
            "base_url": "https://nbr.gov.bd/",
            "max_items": 40,
        },
        "schedule_cron": "13 2,8,14,20 * * *",
        "enabled": True,
        "authority": "জাতীয় রাজস্ব বোর্ড",
        "authority_en": "National Board of Revenue",
    },
    {
        "slug": "bd-nbr-income-tax-sros",
        "name": "Bangladesh NBR — income tax SROs",
        "url": "https://nbr.gov.bd/regulations/sros/income-tax-sros/eng",
        "jurisdiction_code": "BD",
        "tax_types": _ALL_INCOME + [T.WITHHOLDING],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "table tbody tr",
            "title_selector": "td:nth-child(4)",
            "link_selector": "td:nth-child(2) a",
            "date_selector": "td:nth-child(3)",
            "date_dayfirst": True,
            "extra_selectors": {"sro_no": "td:nth-child(2)", "amended_by": "td:nth-child(5)"},
            "base_url": "https://nbr.gov.bd/",
            "max_items": 40,
        },
        "schedule_cron": "19 2,8,14,20 * * *",
        "enabled": True,
        "authority": "জাতীয় রাজস্ব বোর্ড",
        "authority_en": "National Board of Revenue",
    },
    {
        "slug": "lk-customs-news",
        "name": "Sri Lanka Customs — news (RSS)",
        "url": "https://www.customs.gov.lk/feed/",
        "jurisdiction_code": "LK",
        "tax_types": [T.CUSTOMS_TARIFF, T.VAT, T.EXCISE],
        "category": "news",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "23 */6 * * *",
        "enabled": True,
        "authority": "Sri Lanka Customs",
    },
    _blocked(
        "lk-ird-news",
        "Sri Lanka Inland Revenue — news",
        "https://www.ird.gov.lk/",
        "LK",
        "news",
        "SharePoint site renders the news list client-side (5 anchors server-side). needs browser adapter",
        "29 */6 * * *",
        "Inland Revenue Department",
    ),
    {
        "slug": "np-ird-notices",
        "name": "Nepal IRD — notices (सूचना)",
        "url": "https://ird.gov.np/",
        "jurisdiction_code": "NP",
        "tax_types": _CORE + [T.EXCISE],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "a.single__row-wrapper",
            "title_selector": "h4",
            "date_selector": "div.date",
            "base_url": "https://ird.gov.np/",
            "tax_filter": True,
            "max_items": 60,
            "note": "Dates are Bikram Sambat (e.g. ४ भदौ, २०८३) and are not converted; tax_filter drops procurement notices.",
        },
        "schedule_cron": "31 3,9,15,21 * * *",
        "enabled": True,
        "authority": "आन्तरिक राजस्व विभाग",
        "authority_en": "Inland Revenue Department",
    },
    {
        "slug": "bt-drc-notifications",
        "name": "Bhutan DRC — public notifications (RSS)",
        "url": "https://www.drc.gov.bt/feed/",
        "jurisdiction_code": "BT",
        "tax_types": _GST_CORE,
        "category": "regulation",
        "adapter": "rss",
        "config": {},
        "schedule_cron": "37 3,9,15,21 * * *",
        "enabled": True,
        "authority": "Department of Revenue and Customs",
    },
    _blocked(
        "mv-mira-news",
        "Maldives MIRA — news",
        "https://www.mira.gov.mv/News",
        "MV",
        "news",
        "Cloudflare challenge (403 'Just a moment'). needs browser adapter",
        "41 */6 * * *",
        "Maldives Inland Revenue Authority",
        tax_types=[T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
    ),
    _backstop(
        "mv-gnews-tax",
        "Maldives — tax news (Google News backstop)",
        "MV",
        "Maldives MIRA tax",
        "en",
        "MV",
        ["tax", "gst", "mira", "duty", "customs"],
        "https://www.mira.gov.mv/",
        "Cloudflare challenge.",
        "43 */6 * * *",
        tax_types=[T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
    ),
    {
        "slug": "af-mof-news",
        "name": "Afghanistan Ministry of Finance — news (Pashto)",
        "url": "https://mof.gov.af/ps/news",
        "jurisdiction_code": "AF",
        "tax_types": _CORE + [T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "div.card",
            "title_selector": "h2.card-title",
            "base_url": "https://mof.gov.af/",
            "tax_filter": True,
            "max_items": 40,
            "note": "Only 3 undated cards are server-rendered and none passed the tax gate on 2026-08-25; ard.gov.af (Revenue Department) announcement list has no server-side item anchors. Disabled, see af-gnews-tax.",
        },
        "schedule_cron": "47 */6 * * *",
        "enabled": False,
        "authority": "د مالیې وزارت",
        "authority_en": "Ministry of Finance",
    },
    _backstop(
        "af-gnews-tax",
        "Afghanistan — tax news (Google News backstop)",
        "AF",
        "Afghanistan tax OR customs OR revenue",
        "en",
        "AF",
        ["afghanistan", "afghan"],
        "https://mof.gov.af/ps/news",
        "3-item undated list; the fa-AF Google News edition returns no results.",
        "49 */6 * * *",
        tax_types=_CORE + [T.CUSTOMS_TARIFF],
    ),
    # ====================================================================================
    # SOUTHEAST ASIA
    # ====================================================================================
    {
        "slug": "mm-ird-announcements",
        "name": "Myanmar IRD — announcements (ကြေညာချက်များ)",
        "url": "https://www.ird.gov.mm/announcement-lists",
        "jurisdiction_code": "MM",
        "tax_types": _CORE,
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "div.course__item-2",
            "title_selector": "h3.blog__title a",
            "date_selector": "div.blog__meta span",
            "base_url": "https://www.ird.gov.mm/",
            "tax_filter": True,
            "max_items": 40,
        },
        "schedule_cron": "51 */6 * * *",
        "enabled": True,
        "authority": "ပြည်တွင်းအခွန်များဦးစီးဌာန",
        "authority_en": "Internal Revenue Department",
    },
    {
        "slug": "kh-gdt-news",
        "name": "Cambodia GDT — news (ព័ត៌មាន)",
        "url": "https://www.tax.gov.kh/",
        "jurisdiction_code": "KH",
        "tax_types": _CORE,
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "div.mv2-card",
            "title_selector": "a.news-title",
            "date_selector": "div.mv2-date",
            "base_url": "https://www.tax.gov.kh/",
            "tax_filter": True,
            "max_items": 40,
            "note": "/kh/news is paginated client-side; the home page cards are server-rendered.",
        },
        "schedule_cron": "55 */6 * * *",
        "enabled": True,
        "authority": "អគ្គនាយកដ្ឋានពន្ធដារ",
        "authority_en": "General Department of Taxation",
    },
    {
        "slug": "la-mof-news",
        "name": "Laos Ministry of Finance — news (ຂ່າວ)",
        "url": "https://www.mof.gov.la/news",
        "jurisdiction_code": "LA",
        "tax_types": _CORE + [T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "article.post",
            "title_selector": "h3.post-title a",
            "base_url": "https://www.mof.gov.la/",
            "tax_filter": True,
            "max_items": 40,
            "note": "tax.gov.la (Tax Department) does not resolve; the ministry list is mostly protocol news (1 of 9 items tax-relevant on 2026-08-25). Disabled, see la-gnews-tax.",
        },
        "schedule_cron": "3 1,7,13,19 * * *",
        "enabled": False,
        "authority": "ກະຊວງການເງິນ",
        "authority_en": "Ministry of Finance",
    },
    _backstop(
        "la-gnews-tax",
        "Laos — tax news (Google News backstop)",
        "LA",
        "Laos tax OR Lao PDR VAT OR customs",
        "en",
        "LA",
        ["laos", "lao pdr", "lao ", "vientiane"],
        "https://www.mof.gov.la/news",
        "ministry list is mostly protocol news; tax.gov.la does not resolve.",
        "5 1,7,13,19 * * *",
        tax_types=_CORE + [T.CUSTOMS_TARIFF],
    ),
    {
        "slug": "bn-mofe-news",
        "name": "Brunei MOFE — news (RSS)",
        "url": "https://www.mofe.gov.bn/feed/",
        "jurisdiction_code": "BN",
        "tax_types": [T.CORPORATE_INCOME, T.CUSTOMS_TARIFF, T.EXCISE],
        "category": "news",
        "adapter": "rss",
        "config": {
            "tax_filter": True,
            "note": "Feed is dominated by tender notices (1 of 10 items tax-relevant on 2026-08-25). Disabled, see bn-gnews-tax.",
        },
        "schedule_cron": "9 1,7,13,19 * * *",
        "enabled": False,
        "authority": "Kementerian Kewangan dan Ekonomi",
        "authority_en": "Ministry of Finance and Economy",
    },
    _backstop(
        "bn-gnews-tax",
        "Brunei — tax news (Google News backstop)",
        "BN",
        "Brunei tax OR cukai OR customs",
        "en",
        "BN",
        ["brunei"],
        "https://www.mofe.gov.bn/feed/",
        "official feed is tender notices.",
        "11 1,7,13,19 * * *",
        tax_types=[T.CORPORATE_INCOME, T.CUSTOMS_TARIFF, T.EXCISE],
    ),
    _backstop(
        "tl-gnews-tax",
        "Timor-Leste — tax news (Google News backstop)",
        "TL",
        "Timor-Leste tax OR imposto",
        "en",
        "TL",
        ["tax", "imposto", "customs", "alfândega", "duty"],
        "https://www.mof.gov.tl/",
        "client-rendered (0 anchors, /feed/ returns the same shell).",
        "15 1,7,13,19 * * *",
    ),
    {
        "slug": "th-rd-english-news",
        "name": "Thailand Revenue Department — English news",
        "url": "https://www.rd.go.th/english/",
        "jurisdiction_code": "TH",
        "tax_types": _CORE + [T.PILLAR_TWO],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "div.standard-news",
            "title_selector": "p[itemprop=headline]",
            "date_selector": "time",
            "base_url": "https://www.rd.go.th/english/",
            "max_items": 30,
            "note": "Thai news.html returns HTTP 500; the English home page carries a dated 'News Update' list (PDF links).",
        },
        "schedule_cron": "21 1,7,13,19 * * *",
        "enabled": True,
        "authority": "กรมสรรพากร",
        "authority_en": "The Revenue Department",
    },
    _blocked(
        "th-dft-trade-remedies",
        "Thailand DFT — trade remedies",
        "https://www.dft.go.th/",
        "TH",
        "tariff",
        "dft.go.th connect-timeouts from outside Thailand; thaitr.go.th does not resolve.",
        "27 */4 * * *",
        "กรมการค้าต่างประเทศ",
        tax_types=[T.CUSTOMS_TARIFF],
        authority_en="Department of Foreign Trade",
    ),
    _backstop(
        "th-gnews-trade",
        "Thailand — trade remedy news (Google News backstop)",
        "TH",
        "ตอบโต้การทุ่มตลาด OR มาตรการปกป้อง OR อากรขาเข้า",
        "th",
        "TH",
        ["ทุ่มตลาด", "มาตรการปกป้อง", "อากร", "ศุลกากร", "ภาษีนำเข้า"],
        "https://www.dft.go.th/",
        "connect-timeouts.",
        "33 */4 * * *",
        tax_types=[T.CUSTOMS_TARIFF],
    ),
    _backstop(
        "vn-gnews-tax",
        "Vietnam — tax news (Google News backstop)",
        "VN",
        "Cục Thuế OR thuế giá trị gia tăng OR thuế thu nhập",
        "vi",
        "VN",
        ["thuế", "hải quan"],
        "https://mof.gov.vn/",
        "Ministry of Finance / Tax Department portals are client-rendered (0 anchors) and gdt.gov.vn times out.",
        "39 */6 * * *",
    ),
    _blocked(
        "vn-pvtm-cases",
        "Vietnam Trade Remedies Authority — domestic investigations",
        "https://pvtm.gov.vn/default.aspx?page=news&do=browse&category_id=91b07cf1-3658-4f39-b688-73b9e8ff8a05",
        "VN",
        "tariff",
        "Category list is loaded by script (only a notice slider is server-rendered). needs browser adapter",
        "45 */4 * * *",
        "Cục Phòng vệ thương mại",
        tax_types=[T.CUSTOMS_TARIFF],
        authority_en="Trade Remedies Authority of Viet Nam",
    ),
    _backstop(
        "vn-gnews-trade",
        "Vietnam — trade remedy news (Google News backstop)",
        "VN",
        "phòng vệ thương mại OR chống bán phá giá",
        "vi",
        "VN",
        ["phòng vệ thương mại", "chống bán phá giá", "chống trợ cấp", "tự vệ", "thuế nhập khẩu"],
        "https://pvtm.gov.vn/",
        "list is script-rendered.",
        "51 */4 * * *",
        tax_types=[T.CUSTOMS_TARIFF],
    ),
    {
        "slug": "ph-dof-news",
        "name": "Philippines Department of Finance — news (RSS)",
        "url": "https://www.dof.gov.ph/feed/",
        "jurisdiction_code": "PH",
        "tax_types": _CORE + [T.EXCISE],
        "category": "news",
        "adapter": "rss",
        "config": {
            "tax_filter": True,
            "note": "bir.gov.ph is a client-rendered SPA; DOF carries BIR and BOC revenue news.",
        },
        "schedule_cron": "57 */6 * * *",
        "enabled": True,
        "authority": "Department of Finance",
    },
    {
        "slug": "ph-boc-news",
        "name": "Philippines Bureau of Customs — news (RSS)",
        "url": "https://customs.gov.ph/feed/",
        "jurisdiction_code": "PH",
        "tax_types": [T.CUSTOMS_TARIFF, T.EXCISE],
        "category": "news",
        "adapter": "rss",
        "config": {
            "tax_filter": True,
            "exclude_keywords": [
                "NOTICE TO FILE",
                "NOTICE TO LODGE",
                "NOTICE OF HEARING",
                "NOTICE OF PUBLIC AUCTION",
                "SEIZURE IDENTIFICATION",
                "Destroys",
                "destruction",
                "condemn",
            ],
            "note": "Feed is mostly seizure / entry notices; after exclusions only 2 of 4 items passed on 2026-08-25. Disabled; ph-dof-news carries BOC revenue news.",
        },
        "schedule_cron": "5 2,8,14,20 * * *",
        "enabled": False,
        "authority": "Bureau of Customs",
    },
    _blocked(
        "ph-cta-decisions",
        "Philippines Court of Tax Appeals — decisions",
        "https://cta.judiciary.gov.ph/",
        "PH",
        "court",
        "TLS certificate chain is incomplete (CERTIFICATE_VERIFY_FAILED); unreachable with a verifying client.",
        "10 6 * * *",
        "Court of Tax Appeals",
        court="Court of Tax Appeals",
    ),
    # ====================================================================================
    # CENTRAL ASIA / MONGOLIA / MACAU
    # ====================================================================================
    _blocked(
        "mn-mta-news",
        "Mongolia MTA — news",
        "https://mta.gov.mn/news",
        "MN",
        "news",
        "Ant Design SPA; the news list is fetched by script (16 anchors server-side). needs browser adapter",
        "11 */6 * * *",
        "Татварын Ерөнхий Газар",
        authority_en="General Department of Taxation",
    ),
    _backstop(
        "mn-gnews-tax",
        "Mongolia — tax news (Google News backstop)",
        "MN",
        "Mongolia tax OR VAT OR customs",
        "en",
        "MN",
        ["mongolia"],
        "https://mta.gov.mn/",
        "SPA; Google News has no mn edition (redirects to ru with 0 results), so the English edition is used.",
        "17 */6 * * *",
    ),
    {
        "slug": "kz-kgd-news",
        "name": "Kazakhstan State Revenue Committee — news (RSS)",
        "url": "https://kgd.gov.kz/ru/rss.xml",
        "jurisdiction_code": "KZ",
        "tax_types": _CORE + [T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "27 */6 * * *",
        "enabled": True,
        "authority": "Комитет государственных доходов",
        "authority_en": "State Revenue Committee (Ministry of Finance)",
    },
    _blocked(
        "uz-soliq-news",
        "Uzbekistan Tax Committee — news",
        "https://soliq.uz/press-center/news",
        "UZ",
        "news",
        "soliq.uz connect-timeouts from outside Uzbekistan on every path probed.",
        "29 */6 * * *",
        "Soliq qo'mitasi",
        authority_en="Tax Committee",
    ),
    _backstop(
        "uz-gnews-tax",
        "Uzbekistan — tax news (Google News backstop)",
        "UZ",
        "soliq qo'mitasi OR soliq",
        "uz",
        "UZ",
        ["soliq", "bojxona", "qqs", "налог", "таможен"],
        "https://soliq.uz/",
        "connect-timeouts.",
        "35 */6 * * *",
    ),
    {
        "slug": "kg-sti-news",
        "name": "Kyrgyzstan State Tax Service — news (Новости)",
        "url": "https://sti.gov.kg/news",
        "jurisdiction_code": "KG",
        "tax_types": _CORE,
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "div.col-md-12.border-bottom",
            "title_selector": "h5.card-title a",
            "date_selector": "p.main-text span",
            "base_url": "https://sti.gov.kg/",
            "tax_filter": True,
            "max_items": 40,
        },
        "schedule_cron": "41 */6 * * *",
        "enabled": True,
        "authority": "Государственная налоговая служба",
        "authority_en": "State Tax Service",
    },
    _blocked(
        "tj-andoz-news",
        "Tajikistan Tax Committee — news",
        "https://andoz.tj/",
        "TJ",
        "news",
        "TLS certificate chain fails verification (CERTIFICATE_VERIFY_FAILED).",
        "47 */6 * * *",
        "Кумитаи андоз",
        authority_en="Tax Committee",
    ),
    _backstop(
        "tj-gnews-tax",
        "Tajikistan — tax news (Google News backstop)",
        "TJ",
        "Таджикистан налог OR андоз",
        "ru",
        "TJ",
        ["налог", "андоз", "таможен", "гумрук"],
        "https://andoz.tj/",
        "TLS chain failure.",
        "53 */6 * * *",
    ),
    {
        "slug": "tm-fineconomic-news",
        "name": "Turkmenistan Ministry of Finance and Economy — news (RSS)",
        "url": "https://fineconomic.gov.tm/rssfeed",
        "jurisdiction_code": "TM",
        "tax_types": _CORE,
        "category": "news",
        "adapter": "rss",
        "config": {
            "tax_filter": True,
            "note": "Feed entries carry titles but no links (adapter parses 0 items) and are general government news. Disabled, see tm-gnews-tax.",
        },
        "schedule_cron": "59 */6 * * *",
        "enabled": False,
        "authority": "Türkmenistanyň Maliýe we ykdysadyýet ministrligi",
        "authority_en": "Ministry of Finance and Economy",
    },
    _backstop(
        "tm-gnews-tax",
        "Turkmenistan — tax news (Google News backstop)",
        "TM",
        "Туркменистан налог",
        "ru",
        "TM",
        ["налог", "таможен", "salgyt"],
        "https://fineconomic.gov.tm/rssfeed",
        "official RSS is general government news with few fiscal items.",
        "1 */6 * * *",
    ),
    {
        "slug": "mo-dsf-news",
        "name": "Macau DSF — latest news (最新消息)",
        "url": "https://www.dsf.gov.mo/zh-hant",
        "jurisdiction_code": "MO",
        "tax_types": [T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.PROPERTY, T.EXCISE],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "li.list-b-border",
            "title_selector": "p:nth-of-type(2)",
            "date_selector": "p.font-bold",
            "base_url": "https://www.dsf.gov.mo/",
            "tax_filter": True,
            "max_items": 40,
            "note": "Home page list (the /latestnews/newslist page is 2.3 MB). Some items link to WeChat posts.",
        },
        "schedule_cron": "7 */6 * * *",
        "enabled": True,
        "authority": "財政局",
        "authority_en": "Financial Services Bureau (DSF)",
    },
    # ====================================================================================
    # PACIFIC
    # ====================================================================================
    _blocked(
        "pg-irc-news",
        "Papua New Guinea IRC — news",
        "https://irc.gov.pg/",
        "PG",
        "news",
        "HTTP 403 for the TaxAtlas user agent on every path. needs browser adapter",
        "13 */6 * * *",
        "Internal Revenue Commission",
        tax_types=[T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
    ),
    _backstop(
        "pg-gnews-tax",
        "Papua New Guinea — tax news (Google News backstop)",
        "PG",
        "Papua New Guinea IRC tax",
        "en",
        "PG",
        ["tax", "gst", "irc", "customs", "duty"],
        "https://irc.gov.pg/",
        "HTTP 403.",
        "19 */6 * * *",
        tax_types=[T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
    ),
    {
        "slug": "fj-frcs-news",
        "name": "Fiji FRCS — news (WordPress API)",
        "url": "https://frcs.org.fj/wp-json/wp/v2/posts?per_page=30&_fields=id,date,link,title,excerpt",
        "jurisdiction_code": "FJ",
        "tax_types": _CORE + [T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "json",
        "config": {
            "items_path": "",
            "title_path": "title.rendered",
            "url_path": "link",
            "date_path": "date",
            "summary_path": "excerpt.rendered",
            "tax_filter": True,
            "note": "/feed/ redirects to the home page; the WP REST API is open.",
        },
        "schedule_cron": "25 */6 * * *",
        "enabled": True,
        "authority": "Fiji Revenue and Customs Service",
    },
    {
        "slug": "ws-mcr-news",
        "name": "Samoa Ministry for Customs and Revenue — news (RSS)",
        "url": "https://revenue.gov.ws/feed/",
        "jurisdiction_code": "WS",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "31 */6 * * *",
        "enabled": True,
        "authority": "Ministry for Customs and Revenue",
    },
    _blocked(
        "to-mrc-news",
        "Tonga Ministry of Revenue and Customs — news",
        "https://www.revenue.gov.to/",
        "TO",
        "news",
        "TLS certificate chain fails verification (CERTIFICATE_VERIFY_FAILED).",
        "37 */6 * * *",
        "Ministry of Revenue and Customs",
    ),
    _backstop(
        "to-gnews-tax",
        "Tonga — tax news (Google News backstop)",
        "TO",
        "Tonga tax OR customs",
        "en",
        "TO",
        ["tonga"],
        "https://www.revenue.gov.to/",
        "TLS chain failure.",
        "45 */6 * * *",
    ),
    _blocked(
        "vu-dcir-news",
        "Vanuatu Customs and Inland Revenue — news",
        "https://customsinlandrevenue.gov.vu/",
        "VU",
        "news",
        "Host does not resolve (customsinlandrevenue.gov.vu, with and without www).",
        "49 */6 * * *",
        "Department of Customs and Inland Revenue",
    ),
    _backstop(
        "vu-gnews-tax",
        "Vanuatu — tax news (Google News backstop)",
        "VU",
        "Vanuatu tax OR customs OR VAT",
        "en",
        "VU",
        ["vanuatu"],
        "https://customsinlandrevenue.gov.vu/",
        "host does not resolve.",
        "9 */6 * * *",
    ),
    {
        "slug": "sb-ird-news",
        "name": "Solomon Islands IRD — news (RSS)",
        "url": "https://www.ird.gov.sb/feed/",
        "jurisdiction_code": "SB",
        "tax_types": [T.SALES_USE, T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.WITHHOLDING],
        "category": "news",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "2 1,7,13,19 * * *",
        "enabled": True,
        "authority": "Inland Revenue Division",
    },
    _backstop(
        "ki-gnews-tax",
        "Kiribati — tax news (Google News backstop)",
        "KI",
        "Kiribati tax OR VAT OR customs",
        "en",
        "KI",
        ["kiribati"],
        "https://www.mfed.gov.ki/news",
        "news page lists documents without dates and has no feed.",
        "8 1,7,13,19 * * *",
    ),
    {
        "slug": "fm-dofa-news",
        "name": "Micronesia Department of Finance — news (RSS)",
        "url": "https://dofa.gov.fm/feed/",
        "jurisdiction_code": "FM",
        "tax_types": [T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "rss",
        "config": {
            "tax_filter": True,
            "note": "WordPress feed is valid but has 0 entries (2026-08-25). Disabled, see fm-gnews-tax.",
        },
        "schedule_cron": "14 1,7,13,19 * * *",
        "enabled": False,
        "authority": "Department of Finance and Administration",
    },
    _backstop(
        "fm-gnews-tax",
        "Micronesia — tax news (Google News backstop)",
        "FM",
        "Micronesia FSM tax",
        "en",
        "FM",
        ["micronesia", "fsm"],
        "https://dofa.gov.fm/feed/",
        "feed has 0 entries.",
        "16 1,7,13,19 * * *",
        tax_types=[T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.CUSTOMS_TARIFF],
    ),
    _backstop(
        "mh-gnews-tax",
        "Marshall Islands — tax news (Google News backstop)",
        "MH",
        "Marshall Islands tax OR customs",
        "en",
        "MH",
        ["marshall islands"],
        "https://rmi-mof.com/",
        "host does not resolve.",
        "20 1,7,13,19 * * *",
    ),
    {
        "slug": "pw-gov-news",
        "name": "Palau national government — news (RSS)",
        "url": "https://www.palaugov.pw/feed/",
        "jurisdiction_code": "PW",
        "tax_types": [T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "news",
        "adapter": "rss",
        "config": {
            "tax_filter": True,
            "note": "Government-wide feed; tax_filter keeps the Bureau of Revenue and Taxation items (4 of 10 on 2026-08-25).",
        },
        "schedule_cron": "26 1,7,13,19 * * *",
        "enabled": True,
        "authority": "Bureau of Revenue and Taxation (Ministry of Finance)",
    },
    _backstop(
        "pw-gnews-tax",
        "Palau — tax news (Google News backstop)",
        "PW",
        "Palau tax OR PGST",
        "en",
        "PW",
        ["palau"],
        "https://www.palaugov.pw/",
        "government-wide feed carries few tax items.",
        "28 1,7,13,19 * * *",
        tax_types=[T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
    ),
    _backstop(
        "nr-gnews-tax",
        "Nauru — tax news (Google News backstop)",
        "NR",
        "Nauru tax OR revenue",
        "en",
        "NR",
        ["nauru"],
        "https://nauru.gov.nr/",
        "returns a 150-byte script shell.",
        "32 1,7,13,19 * * *",
    ),
    _backstop(
        "tv-gnews-tax",
        "Tuvalu — tax news (Google News backstop)",
        "TV",
        "Tuvalu tax",
        "en",
        "TV",
        ["tuvalu"],
        "(none found)",
        "no official Inland Revenue website could be located.",
        "38 1,7,13,19 * * *",
    ),
    # ====================================================================================
    # COURTS / TRIBUNALS
    # ====================================================================================
    _blocked(
        "in-itat-orders",
        "India ITAT — tribunal orders",
        "https://itat.gov.in/",
        "IN",
        "court",
        "TLS certificate chain fails verification (CERTIFICATE_VERIFY_FAILED); orders search is a script-driven form. needs browser adapter",
        "15 5 * * *",
        "Income Tax Appellate Tribunal",
        tax_types=_ALL_INCOME + [T.TRANSFER_PRICING],
        court="Income Tax Appellate Tribunal",
    ),
    _blocked(
        "in-sci-judgments",
        "India Supreme Court — judgments",
        "https://www.sci.gov.in/judgements-judgement-date/",
        "IN",
        "court",
        "Akamai 'Access Denied' (403) for non-browser clients; judgments.ecourts.gov.in is a client-rendered search app. needs browser adapter",
        "20 5 * * *",
        "Supreme Court of India",
        tax_types=_ALL_INCOME + [T.GST, T.CUSTOMS_TARIFF],
        court="Supreme Court of India",
    ),
    {
        "slug": "jp-kfs-saiketsu",
        "name": "Japan National Tax Tribunal — published rulings (公表裁決事例)",
        "url": "https://www.kfs.go.jp/service/JP/index.html",
        "jurisdiction_code": "JP",
        "tax_types": _CORE + [T.EXCISE, T.PROPERTY],
        "category": "court",
        "adapter": "html",
        "config": {
            "court": "国税不服審判所",
            "item_selector": "td.t_Title",
            "encoding": "shift_jis",
            "base_url": "https://www.kfs.go.jp/service/JP/",
            "max_items": 200,
            "note": "One item per quarterly 裁決事例集 issue (undated in the index; each issue page lists the individual rulings). courts.go.jp 裁判例検索 is a script-driven search app.",
        },
        "schedule_cron": "25 5 * * *",
        "enabled": True,
        "authority": "国税不服審判所",
        "authority_en": "National Tax Tribunal",
    },
    _blocked(
        "jp-courts-hanrei",
        "Japan Courts — case law search (裁判例検索)",
        "https://www.courts.go.jp/app/hanrei_jp/search1",
        "JP",
        "court",
        "Search results are rendered by script; list endpoints (list1..list7) return 404 without a session. needs browser adapter",
        "30 5 * * *",
        "裁判所",
        authority_en="Courts of Japan",
        court="裁判所",
    ),
    _blocked(
        "kr-tt-decisions",
        "Korea Tax Tribunal — recent decisions (최근 심판결정례)",
        "https://www.tt.go.kr/mUser/dem/newDemList.do",
        "KR",
        "court",
        "Decision titles are server-rendered but every link is href='#none' with an onclick handler. needs browser adapter",
        "35 5 * * *",
        "조세심판원",
        authority_en="Tax Tribunal",
        court="조세심판원",
    ),
    _blocked(
        "hk-bor-decisions",
        "Hong Kong Board of Review — decisions",
        "https://www.info.gov.hk/bor/en/",
        "HK",
        "court",
        "Site content (menus, decision lists) is injected from js/data/*.js; the HTML shell has one anchor. needs browser adapter",
        "40 5 * * *",
        "Board of Review (Inland Revenue Ordinance)",
        tax_types=[T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.PROPERTY],
        court="Board of Review (Inland Revenue Ordinance)",
    ),
    _blocked(
        "nz-tra-decisions",
        "New Zealand Taxation Review Authority — decisions",
        "https://www.justice.govt.nz/tribunals/taxation-review-authority/decisions/",
        "NZ",
        "court",
        "justice.govt.nz answers HTTP 405 'Human Verification'; IR Tax Technical case summaries are a Coveo (script) search. needs browser adapter",
        "45 5 * * *",
        "Taxation Review Authority",
        tax_types=[T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        court="Taxation Review Authority",
    ),
    _blocked(
        "au-art-decisions",
        "Australia Administrative Review Tribunal — decisions",
        "https://www.art.gov.au/",
        "AU",
        "court",
        "art.gov.au read-timeouts on every path probed (2026-08-22 and 2026-08-25).",
        "50 5 * * *",
        "Administrative Review Tribunal",
        tax_types=[T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        court="Administrative Review Tribunal",
    ),
    _blocked(
        "id-pengadilan-pajak-risalah",
        "Indonesia Tax Court — decision summaries (Risalah Putusan)",
        "https://setpp.kemenkeu.go.id/risalah",
        "ID",
        "court",
        "Kendo grid fed by /risalah/Risalah_Read, which returns an empty body without the browser session. needs browser adapter",
        "55 5 * * *",
        "Pengadilan Pajak",
        tax_types=[T.VAT, T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        authority_en="Tax Court",
        court="Pengadilan Pajak",
    ),
    {
        "slug": "id-pengadilan-pajak-berita",
        "name": "Indonesia Tax Court — news (Berita Pengadilan Pajak)",
        "url": "https://setpp.kemenkeu.go.id/",
        "jurisdiction_code": "ID",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "#tabBerita td p",
            "base_url": "https://setpp.kemenkeu.go.id/",
            "tax_filter": True,
            "max_items": 20,
        },
        "schedule_cron": "0 6 * * *",
        "enabled": True,
        "authority": "Sekretariat Pengadilan Pajak",
        "authority_en": "Secretariat of the Tax Court",
    },
    _blocked(
        "tw-judicial-tax-judgments",
        "Taiwan Judicial Yuan — administrative court judgments (tax)",
        "https://law.judicial.gov.tw/",
        "TW",
        "court",
        "law.judicial.gov.tw refuses connections from outside Taiwan; the judgment search is a script-driven form with session tokens. needs browser adapter",
        "5 6 * * *",
        "司法院",
        authority_en="Judicial Yuan",
        court="最高行政法院",
    ),
    # ====================================================================================
    # TRADE / TARIFF BODIES
    # ====================================================================================
    {
        "slug": "id-kadi-news",
        "name": "Indonesia KADI — anti-dumping news (RSS)",
        "url": "https://kadi.kemendag.go.id/rss.xml",
        "jurisdiction_code": "ID",
        "tax_types": [T.CUSTOMS_TARIFF],
        "category": "tariff",
        "adapter": "rss",
        "config": {},
        "schedule_cron": "11 */4 * * *",
        "enabled": True,
        "authority": "Komite Anti Dumping Indonesia",
        "authority_en": "Indonesian Anti-Dumping Committee",
    },
    {
        "slug": "tw-customs-notices",
        "name": "Taiwan Customs Administration — business notices (最新業務公告, RSS)",
        "url": "https://web.customs.gov.tw/Rss/698",
        "jurisdiction_code": "TW",
        "tax_types": [T.CUSTOMS_TARIFF],
        "category": "tariff",
        "adapter": "rss",
        "config": {
            "max_items": 60,
            "note": "Mostly port-level service notices; the trade gate keeps the tariff/classification items (3 of 60 on 2026-08-25).",
        },
        "schedule_cron": "17 */4 * * *",
        "enabled": True,
        "authority": "財政部關務署",
        "authority_en": "Customs Administration, Ministry of Finance",
    },
    {
        "slug": "tw-customs-press",
        "name": "Taiwan Customs Administration — press releases (新聞稿, RSS)",
        "url": "https://web.customs.gov.tw/Rss/2222",
        "jurisdiction_code": "TW",
        "tax_types": [T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "33 */6 * * *",
        "enabled": True,
        "authority": "財政部關務署",
        "authority_en": "Customs Administration, Ministry of Finance",
    },
    {
        "slug": "tw-mof-news-zh",
        "name": "Taiwan Ministry of Finance — news (本部新聞, RSS)",
        "url": "https://www.mof.gov.tw/Rss/384fb3077bb349ea973e7fc6f13b6974",
        "jurisdiction_code": "TW",
        "tax_types": _CORE + [T.PROPERTY],
        "category": "news",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "29 */6 * * *",
        "enabled": True,
        "authority": "財政部",
        "authority_en": "Ministry of Finance",
    },
    {
        "slug": "jp-meti-press",
        "name": "Japan METI — press releases (Atom)",
        "url": "https://www.meti.go.jp/ml_index_release_atom.xml",
        "jurisdiction_code": "JP",
        "tax_types": [T.CUSTOMS_TARIFF],
        "category": "tariff",
        "adapter": "rss",
        "config": {
            "include_keywords": ["関税", "不当廉売", "相殺関税", "セーフガード", "貿易救済", "輸入"],
            "note": "meti.go.jp answers 403 for the TaxAtlas user agent on the Atom feed and /press/. needs browser adapter",
        },
        "schedule_cron": "35 */4 * * *",
        "enabled": False,
        "authority": "経済産業省",
        "authority_en": "Ministry of Economy, Trade and Industry",
    },
    # ====================================================================================
    # SUB-NATIONAL — India (state GST / commercial tax departments)
    # ====================================================================================
    *[
        _backstop(
            f"in-{code.lower()}-gnews-gst",
            f"{state} — state GST / commercial tax news (Google News backstop)",
            f"IN-{code}",
            f"{state} GST",
            "en-IN",
            "IN",
            ["gst", "tax", "vat", "excise", "stamp duty"],
            official,
            reason,
            cron,
            tax_types=[T.GST, T.EXCISE, T.PROPERTY],
            lang="en",
        )
        for code, state, official, reason, cron in [
            ("MH", "Maharashtra", "https://mahagst.gov.in/", "connect-timeouts.", "4 */6 * * *"),
            (
                "KA",
                "Karnataka",
                "https://gst.kar.nic.in/",
                "host does not resolve; ctax.kar.nic.in times out.",
                "10 */6 * * *",
            ),
            ("TN", "Tamil Nadu", "https://ctd.tn.gov.in/", "connect-timeouts.", "16 */6 * * *"),
            ("GJ", "Gujarat", "https://commercialtax.gujarat.gov.in/", "TLS chain fails verification.", "22 */6 * * *"),
            ("UP", "Uttar Pradesh", "https://comtax.up.nic.in/", "frameset shell with 0 anchors.", "28 */6 * * *"),
            ("WB", "West Bengal", "https://wbcomtax.gov.in/", "connect-timeouts.", "34 */6 * * *"),
            ("DL", "Delhi", "https://dtt.delhi.gov.in/", "host does not resolve.", "40 */6 * * *"),
            ("TS", "Telangana", "https://tgct.gov.in/", "305-byte script redirect shell.", "46 */6 * * *"),
        ]
    ],
    # ====================================================================================
    # SUB-NATIONAL — China (STA provincial bureaus)
    # ====================================================================================
    {
        "slug": "cn-sh-tax-policies",
        "name": "Shanghai Tax Service — policy documents (政策法规库)",
        "url": "https://shanghai.chinatax.gov.cn/zcfw/zcfgk/index.html",
        "jurisdiction_code": "CN-SH",
        "tax_types": _CORE + [T.PROPERTY, T.EXCISE],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "ul#zcfglist li",
            "title_selector": "div.title",
            "date_selector": "div.time",
            "extra_selectors": {"document_no": "div.wh"},
            "base_url": "https://shanghai.chinatax.gov.cn/zcfw/zcfgk/",
            "max_items": 40,
        },
        "schedule_cron": "52 */6 * * *",
        "enabled": True,
        "authority": "国家税务总局上海市税务局",
        "authority_en": "Shanghai Municipal Tax Service, State Taxation Administration",
    },
    {
        "slug": "cn-gd-tax-documents",
        "name": "Guangdong Tax Service — latest documents (最新文件)",
        "url": "https://guangdong.chinatax.gov.cn/",
        "jurisdiction_code": "CN-GD",
        "tax_types": _CORE + [T.PROPERTY, T.EXCISE],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "li.zxfb_zxwj",
            "title_selector": "h4 a",
            "date_selector": "span.time",
            "base_url": "https://guangdong.chinatax.gov.cn/",
            "max_items": 30,
            "note": "The /gdsw/zjfg/ list page returns 404; the home page carries the same items (duplicated across two tabs, de-duplicated by URL).",
        },
        "schedule_cron": "58 */6 * * *",
        "enabled": True,
        "authority": "国家税务总局广东省税务局",
        "authority_en": "Guangdong Provincial Tax Service, State Taxation Administration",
    },
    {
        "slug": "cn-zj-tax-news",
        "name": "Zhejiang Tax Service — tax news (税务新闻)",
        "url": "https://zhejiang.chinatax.gov.cn/",
        "jurisdiction_code": "CN-ZJ",
        "tax_types": _CORE,
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "td li",
            "title_selector": "a",
            "date_selector": "span",
            "base_url": "https://zhejiang.chinatax.gov.cn/",
            "tax_filter": True,
            "max_items": 40,
            "note": "The column page (col/col13226) wraps its list in XML CDATA records; the home page list is plain HTML.",
        },
        "schedule_cron": "6 1,7,13,19 * * *",
        "enabled": True,
        "authority": "国家税务总局浙江省税务局",
        "authority_en": "Zhejiang Provincial Tax Service, State Taxation Administration",
    },
    _blocked(
        "cn-bj-tax-news",
        "Beijing Tax Service — news",
        "https://beijing.chinatax.gov.cn/",
        "CN-BJ",
        "news",
        "beijing.chinatax.gov.cn connect-timeouts from outside China on every probe.",
        "12 1,7,13,19 * * *",
        "国家税务总局北京市税务局",
        authority_en="Beijing Municipal Tax Service, State Taxation Administration",
    ),
    _backstop(
        "cn-bj-gnews-tax",
        "Beijing — tax news (Google News backstop)",
        "CN-BJ",
        "北京市税务局",
        "zh-CN",
        "CN",
        ["税", "关税"],
        "https://beijing.chinatax.gov.cn/",
        "connect-timeouts.",
        "18 1,7,13,19 * * *",
        lang="zh-Hans",
    ),
    _blocked(
        "cn-js-tax-news",
        "Jiangsu Tax Service — news",
        "https://jiangsu.chinatax.gov.cn/",
        "CN-JS",
        "news",
        "jiangsu.chinatax.gov.cn connect-timeouts from outside China on every probe.",
        "24 1,7,13,19 * * *",
        "国家税务总局江苏省税务局",
        authority_en="Jiangsu Provincial Tax Service, State Taxation Administration",
    ),
    _backstop(
        "cn-js-gnews-tax",
        "Jiangsu — tax news (Google News backstop)",
        "CN-JS",
        "江苏省税务局",
        "zh-CN",
        "CN",
        ["税", "关税"],
        "https://jiangsu.chinatax.gov.cn/",
        "connect-timeouts.",
        "30 1,7,13,19 * * *",
        lang="zh-Hans",
    ),
    # ====================================================================================
    # SUB-NATIONAL — Japan (都道府県 tax bureaus)
    # ====================================================================================
    {
        "slug": "jp-13-tokyo-tax-press",
        "name": "Tokyo Bureau of Taxation — press releases (報道発表, RSS)",
        "url": "https://www.tax.metro.tokyo.lg.jp/index.html/-/asset_publisher/gawg/rss",
        "jurisdiction_code": "JP-13",
        "tax_types": [T.CORPORATE_INCOME, T.PROPERTY, T.EXCISE],
        "category": "regulation",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "36 1,7,13,19 * * *",
        "enabled": True,
        "authority": "東京都主税局",
        "authority_en": "Tokyo Metropolitan Government Bureau of Taxation",
    },
    {
        "slug": "jp-13-tokyo-tax-updates",
        "name": "Tokyo Bureau of Taxation — site updates (更新情報, RSS)",
        "url": "https://www.tax.metro.tokyo.lg.jp/index.html/-/asset_publisher/ncfw/rss",
        "jurisdiction_code": "JP-13",
        "tax_types": [T.CORPORATE_INCOME, T.PROPERTY, T.EXCISE],
        "category": "news",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "42 1,7,13,19 * * *",
        "enabled": True,
        "authority": "東京都主税局",
        "authority_en": "Tokyo Metropolitan Government Bureau of Taxation",
    },
    _backstop(
        "jp-27-osaka-gnews-tax",
        "Osaka — prefectural tax news (Google News backstop)",
        "JP-27",
        "大阪府 府税",
        "ja",
        "JP",
        ["税"],
        "https://www.pref.osaka.lg.jp/soshikikarasagasu/zei/index.html",
        "the 税政課 pages are static brochures without a dated list or feed.",
        "48 1,7,13,19 * * *",
        tax_types=[T.CORPORATE_INCOME, T.PROPERTY, T.EXCISE],
    ),
    # ====================================================================================
    # SUB-NATIONAL — Australia (state revenue offices)
    # ====================================================================================
    {
        "slug": "au-qld-qro-news",
        "name": "Queensland Revenue Office — news (RSS)",
        "url": "https://qro.qld.gov.au/feed/",
        "jurisdiction_code": "AU-QLD",
        "tax_types": [T.PROPERTY, T.PAYROLL_SOCIAL, T.EXCISE],
        "category": "regulation",
        "adapter": "rss",
        "config": {"tax_filter": True},
        "schedule_cron": "54 1,7,13,19 * * *",
        "enabled": True,
        "authority": "Queensland Revenue Office",
    },
    {
        "slug": "au-wa-treasury-announcements",
        "name": "WA Department of Treasury and Finance — announcements (RevenueWA)",
        "url": "https://www.wa.gov.au/organisation/department-of-treasury-and-finance",
        "jurisdiction_code": "AU-WA",
        "tax_types": [T.PROPERTY, T.PAYROLL_SOCIAL, T.EXCISE],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "article.news-card",
            "title_selector": "h3, h2, .news-card__title",
            "date_selector": "time",
            "base_url": "https://www.wa.gov.au/",
            "tax_filter": True,
            "max_items": 20,
            "note": "RevenueWA has no page of its own after the 2025 machinery-of-government change; the department card list is short (4 items) and the filtered announcements page is script-rendered. Trial 2026-08-25 kept < 3 — disabled, see au-wa-gnews-tax.",
        },
        "schedule_cron": "0 2,8,14,20 * * *",
        "enabled": False,
        "authority": "RevenueWA (Department of Treasury and Finance)",
    },
    _backstop(
        "au-wa-gnews-tax",
        "Western Australia — state tax news (Google News backstop)",
        "AU-WA",
        'RevenueWA OR "Western Australia" payroll tax OR land tax OR stamp duty',
        "en-AU",
        "AU",
        ["revenuewa", "western australia", "wa "],
        "https://www.wa.gov.au/organisation/department-of-treasury-and-finance",
        "announcement list is script-rendered.",
        "6 2,8,14,20 * * *",
        tax_types=[T.PROPERTY, T.PAYROLL_SOCIAL, T.EXCISE],
        lang="en",
    ),
    _blocked(
        "au-sa-revenuesa-news",
        "RevenueSA — news",
        "https://www.revenuesa.sa.gov.au/news",
        "AU-SA",
        "news",
        "Cloudflare challenge (403 'Just a moment'). needs browser adapter",
        "12 2,8,14,20 * * *",
        "RevenueSA",
        tax_types=[T.PROPERTY, T.PAYROLL_SOCIAL, T.EXCISE],
    ),
    _backstop(
        "au-sa-gnews-tax",
        "South Australia — state tax news (Google News backstop)",
        "AU-SA",
        'RevenueSA OR "South Australia" payroll tax OR land tax OR stamp duty',
        "en-AU",
        "AU",
        ["revenuesa", "south australia", "sa "],
        "https://www.revenuesa.sa.gov.au/",
        "Cloudflare challenge.",
        "18 2,8,14,20 * * *",
        tax_types=[T.PROPERTY, T.PAYROLL_SOCIAL, T.EXCISE],
        lang="en",
    ),
]

__all__ = ["SOURCES"]
