"""Discovered sources — Americas (Central America, Caribbean, South America, courts, trade, sub-national).

Same shape as app.seed.sources.SOURCES. Every URL was probed on 2026-08-25 with the TaxAtlas user agent and trialled
twice against a scratch database (`python -m app.crawler run --source <slug> --force-network`); a source had to return
200 and keep >= 3 relevant items to be enabled. Where the official site exposes no parseable listing (client-rendered
portals, SharePoint without feeds, TLS-chain failures, timeouts) the row is kept disabled with a ``config["note"]`` and
a Google News RSS backstop (``…-news-backstop``) is registered next to it — the note names the official URL so the
backstop can be retired when the site becomes reachable.

Schedule policy mirrors sources.py: courts daily, regulators/news 4x daily, tariff/trade every 4h; minutes staggered.
"""

from __future__ import annotations

from taxatlas.models.enums import TaxType as T

BROWSER_NOTE = "needs browser adapter"


def _backstop(
    slug: str,
    code: str,
    country: str,
    query: str,
    hl: str,
    official: str,
    tax_types: list,
    minute: int,
    authority: str,
    authority_en: str | None = None,
    category: str = "news",
    extra_config: dict | None = None,
) -> dict:
    """Keyword-search backstop over aggregated press (adapter="news": GDELT -> Bing -> Google News, adapters/news.py)."""
    cfg = {
        "query": query,
        "lang": hl,
        "country": code.split("-")[0],
        "note": f"backstop: Google News ({hl}). Official site: {official}",
        "max_items": 40,
    }
    cfg.update(extra_config or {})
    spec = {
        "slug": slug,
        "name": f"{country} — tax news (Google News backstop)",
        "url": f"news://{slug}",
        "jurisdiction_code": code,
        "tax_types": tax_types,
        "category": category,
        "adapter": "news",
        "config": cfg,
        "schedule_cron": f"{minute} 3,9,15,21 * * *",
        "enabled": True,
        "authority": authority,
    }
    if authority_en:
        spec["authority_en"] = authority_en
    return spec


_ES = "es-419"
_PT = "pt-BR"
_FR = "fr"
_EN = "en"

SOURCES: list[dict] = [
    # ====================================================================================
    # Central America
    # ====================================================================================
    {
        "slug": "gt-sat-noticias",
        "name": "Guatemala SAT — noticias (RSS)",
        "url": "https://portal.sat.gob.gt/portal/categoria/noticias/feed/",
        "jurisdiction_code": "GT",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "rss",
        "config": {},
        "schedule_cron": "7 2,8,14,20 * * *",
        "enabled": True,
        "authority": "Superintendencia de Administración Tributaria",
        "authority_en": "Tax Administration Superintendency (SAT)",
    },
    {
        "slug": "hn-sar-noticias",
        "name": "Honduras SAR — noticias (RSS)",
        "url": "https://www.sar.gob.hn/feed/",
        "jurisdiction_code": "HN",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "news",
        "adapter": "rss",
        "config": {},
        "schedule_cron": "12 2,8,14,20 * * *",
        "enabled": True,
        "authority": "Servicio de Administración de Rentas",
        "authority_en": "Revenue Administration Service (SAR)",
    },
    {
        "slug": "sv-mh-noticias",
        "name": "El Salvador Ministerio de Hacienda — noticias (RSS)",
        "url": "https://www.mh.gob.sv/feed/",
        "jurisdiction_code": "SV",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "news",
        "adapter": "rss",
        "config": {
            "note": "Feed carries only the 3 newest posts and the /noticias page is client-rendered. Trial 2026-08-25: "
            "3 found / 2 kept (below the 3-item bar). Disabled; see sv-news-backstop."
        },
        "schedule_cron": "17 2,8,14,20 * * *",
        "enabled": False,
        "authority": "Ministerio de Hacienda",
        "authority_en": "Ministry of Finance",
    },
    _backstop(
        "sv-news-backstop",
        "SV",
        "El Salvador",
        '"Ministerio de Hacienda" El Salvador impuestos OR IVA OR DGII',
        _ES,
        "https://www.mh.gob.sv/feed/ (3-post feed; see sv-mh-noticias)",
        [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        19,
        "Ministerio de Hacienda",
        "Ministry of Finance",
    ),
    _backstop(
        "ni-dgi-news-backstop",
        "NI",
        "Nicaragua",
        "DGI impuestos Nicaragua",
        _ES,
        "https://www.dgi.gob.ni/ (no news listing; /noticias 404)",
        [T.VAT, T.CORPORATE_INCOME],
        22,
        "Dirección General de Ingresos",
        "General Directorate of Revenue (DGI)",
    ),
    {
        "slug": "cr-hacienda-comunicados",
        "name": "Costa Rica Ministerio de Hacienda — comunicados de prensa",
        "url": "https://www.hacienda.go.cr/",
        "jurisdiction_code": "CR",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "div.card",
            "title_selector": "span.card-title a",
            "date_selector": "p.card-text",
            "date_dayfirst": True,
            "base_url": "https://www.hacienda.go.cr/",
            "note": "Home-page cards; each comunicado links to its PDF (docs/CP-NN-YYYY…pdf).",
        },
        "schedule_cron": "27 2,8,14,20 * * *",
        "enabled": True,
        "authority": "Ministerio de Hacienda",
        "authority_en": "Ministry of Finance",
    },
    {
        "slug": "pa-mef-noticias",
        "name": "Panama MEF — noticias (RSS; includes DGI items)",
        "url": "https://www.mef.gob.pa/feed/",
        "jurisdiction_code": "PA",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "news",
        "adapter": "rss",
        "config": {"note": "dgi.mef.gob.pa has no listing (comunicados redirect to a maintenance page)."},
        "schedule_cron": "32 2,8,14,20 * * *",
        "enabled": True,
        "authority": "Ministerio de Economía y Finanzas",
        "authority_en": "Ministry of Economy and Finance (MEF)",
    },
    {
        "slug": "bz-bts-news",
        "name": "Belize Tax Service — news",
        "url": "https://bts.gov.bz/news/",
        "jurisdiction_code": "BZ",
        "tax_types": [T.GST, T.CORPORATE_INCOME],
        "category": "news",
        "adapter": "html",
        "config": {"item_selector": "article", "note": f"1.2 KB client-rendered shell, no RSS. {BROWSER_NOTE}."},
        "schedule_cron": "37 2,8,14,20 * * *",
        "enabled": False,
        "authority": "Belize Tax Service",
    },
    _backstop(
        "bz-news-backstop",
        "BZ",
        "Belize",
        'Belize Tax Service GST OR "business tax"',
        _EN,
        "https://bts.gov.bz/",
        [T.GST, T.CORPORATE_INCOME],
        42,
        "Belize Tax Service",
    ),
    # ====================================================================================
    # Caribbean
    # ====================================================================================
    {
        "slug": "do-dgii-noticias",
        "name": "Dominican Republic DGII — noticias",
        "url": "https://dgii.gov.do/noticias/Paginas/default.aspx",
        "jurisdiction_code": "DO",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "a.news-teaser",
            "title_selector": "h4.news-teaser-title",
            "date_selector": "object.news-teaser-category",
            "date_dayfirst": True,
            "base_url": "https://dgii.gov.do/",
            "note": "SharePoint page but the teaser list is server-rendered; the masterpage RSS is 404.",
        },
        "schedule_cron": "47 2,8,14,20 * * *",
        "enabled": True,
        "authority": "Dirección General de Impuestos Internos",
        "authority_en": "General Directorate of Internal Taxes (DGII)",
    },
    _backstop(
        "cu-onat-news-backstop",
        "CU",
        "Cuba",
        "ONAT impuestos Cuba",
        _ES,
        "https://www.onat.gob.cu/ (server drops the connection on every probe)",
        [T.PERSONAL_INCOME, T.CORPORATE_INCOME],
        52,
        "Oficina Nacional de Administración Tributaria",
        "National Tax Administration Office (ONAT)",
    ),
    {
        "slug": "jm-taj-news",
        "name": "Jamaica TAJ — news",
        "url": "https://www.jamaicatax.gov.jm/",
        "jurisdiction_code": "JM",
        "tax_types": [T.GST, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "div.entry.approved",
            "title_selector": "div.entry-title h2 a",
            "date_selector": "div.entry-date",
            "summary_selector": "div.entry-body",
            "note": "Liferay blog portlet on the home page (5 newest posts); /news is 404 and the blogs RSS needs a session.",
        },
        "schedule_cron": "57 2,8,14,20 * * *",
        "enabled": True,
        "authority": "Tax Administration Jamaica",
    },
    {
        "slug": "tt-ird-notices",
        "name": "Trinidad and Tobago IRD — public notices",
        "url": "https://www.ird.gov.tt/",
        "jurisdiction_code": "TT",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "li.content-item-summary",
            "title_selector": "h5 a",
            "base_url": "https://www.ird.gov.tt/",
            "note": "Notice list carries no dates; published_date stays empty.",
        },
        "schedule_cron": "3 3,9,15,21 * * *",
        "enabled": True,
        "authority": "Inland Revenue Division, Ministry of Finance",
    },
    {
        "slug": "tt-finance-news",
        "name": "Trinidad and Tobago Ministry of Finance — media releases (RSS)",
        "url": "https://www.finance.gov.tt/feed/",
        "jurisdiction_code": "TT",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PROPERTY],
        "category": "news",
        "adapter": "rss",
        "config": {},
        "schedule_cron": "8 3,9,15,21 * * *",
        "enabled": True,
        "authority": "Ministry of Finance",
    },
    {
        "slug": "bs-dir-news",
        "name": "Bahamas Department of Inland Revenue — news (RSS)",
        "url": "https://inlandrevenue.finance.gov.bs/feed/",
        "jurisdiction_code": "BS",
        "tax_types": [T.VAT, T.PROPERTY],
        "category": "regulation",
        "adapter": "rss",
        "config": {"note": "Low-volume feed (last post Nov 2025 at probe time); feedparser flags a minor XML bozo."},
        "schedule_cron": "13 3,9,15,21 * * *",
        "enabled": True,
        "authority": "Department of Inland Revenue",
    },
    {
        "slug": "bb-bra-press",
        "name": "Barbados Revenue Authority — press releases",
        "url": "https://bra.gov.bb/",
        "jurisdiction_code": "BB",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PROPERTY],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "div.entry",
            "title_selector": "div.entry-title h3 a",
            "date_selector": "div.entry-meta li",
            "base_url": "https://bra.gov.bb/",
            "note": "Home-page press list (8 newest); /feed and /rss are 404.",
        },
        "schedule_cron": "18 3,9,15,21 * * *",
        "enabled": True,
        "authority": "Barbados Revenue Authority",
    },
    {
        "slug": "ht-dgi-actualites",
        "name": "Haiti DGI — actualités (RSS)",
        "url": "https://dgi.gouv.ht/feed/",
        "jurisdiction_code": "HT",
        "tax_types": [T.PERSONAL_INCOME, T.CORPORATE_INCOME, T.VAT],
        "category": "news",
        "adapter": "rss",
        "config": {"note": "Mostly institutional posts; the strict tax gate keeps only fiscal items."},
        "schedule_cron": "23 3,9,15,21 * * *",
        "enabled": True,
        "authority": "Direction Générale des Impôts",
        "authority_en": "General Directorate of Taxes (DGI)",
    },
    _backstop(
        "ht-news-backstop",
        "HT",
        "Haiti",
        "DGI impôts Haïti",
        _FR,
        "https://dgi.gouv.ht/ (official feed is low-volume)",
        [T.PERSONAL_INCOME, T.CORPORATE_INCOME, T.VAT],
        28,
        "Direction Générale des Impôts",
        "General Directorate of Taxes (DGI)",
    ),
    {
        "slug": "pr-hacienda-news",
        "name": "Puerto Rico Departamento de Hacienda — comunicados",
        "url": "https://hacienda.pr.gov/",
        "jurisdiction_code": "PR",
        "tax_types": [T.SALES_USE, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "li.views-row",
            "note": "Drupal site; every press/determinations/cartas-circulares path redirects to 'pagina-no-encontrada' and "
            "the home page lists only static guidance links. Disabled.",
        },
        "schedule_cron": "33 3,9,15,21 * * *",
        "enabled": False,
        "authority": "Departamento de Hacienda de Puerto Rico",
        "authority_en": "Puerto Rico Treasury Department",
    },
    _backstop(
        "pr-news-backstop",
        "PR",
        "Puerto Rico",
        "Hacienda Puerto Rico contribuciones OR IVU OR planillas",
        _ES,
        "https://hacienda.pr.gov/",
        [T.SALES_USE, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        38,
        "Departamento de Hacienda de Puerto Rico",
        "Puerto Rico Treasury Department",
    ),
    {
        "slug": "bm-gov-news",
        "name": "Government of Bermuda — news (tax items)",
        "url": "https://www.gov.bm/news",
        "jurisdiction_code": "BM",
        "tax_types": [T.PAYROLL_SOCIAL, T.CUSTOMS_TARIFF, T.CORPORATE_INCOME],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "h3.public-news-collection-title",
            "note": "Listing cards are client-hydrated skeletons (animate-pulse placeholders); only 9 title anchors are "
            f"server-rendered and carry no dates. {BROWSER_NOTE}.",
        },
        "schedule_cron": "43 3,9,15,21 * * *",
        "enabled": False,
        "authority": "Government of Bermuda",
    },
    _backstop(
        "bm-news-backstop",
        "BM",
        "Bermuda",
        'Bermuda "payroll tax" OR "corporate income tax" OR "customs duty"',
        _EN,
        "https://www.gov.bm/news",
        [T.PAYROLL_SOCIAL, T.CUSTOMS_TARIFF, T.CORPORATE_INCOME],
        48,
        "Government of Bermuda",
    ),
    {
        "slug": "ky-gov-press",
        "name": "Cayman Islands Government — press releases (tax items)",
        "url": "https://gov.ky/news",
        "jurisdiction_code": "KY",
        "tax_types": [T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "div.govky-article-card",
            "title_selector": "h5 a",
            "date_selector": "span[data-lfr-editable-id='published-date']",
            "note": "General government newsroom. Trial 2026-08-25: 10 found / 0 tax items. Disabled; see "
            "ky-news-backstop.",
        },
        "schedule_cron": "53 3,9,15,21 * * *",
        "enabled": False,
        "authority": "Cayman Islands Government",
    },
    _backstop(
        "ky-news-backstop",
        "KY",
        "Cayman Islands",
        '"Cayman Islands" tax OR duty OR "economic substance" OR "Pillar Two"',
        _EN,
        "https://gov.ky/news (general newsroom; 0 tax items in trial)",
        [T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        56,
        "Cayman Islands Government",
    ),
    _backstop(
        "vg-news-backstop",
        "VG",
        "British Virgin Islands",
        '"British Virgin Islands" tax OR duty OR "economic substance"',
        _EN,
        "https://bvi.gov.vg/media-centre (404 on every path probed)",
        [T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        58,
        "Government of the Virgin Islands",
    ),
    {
        "slug": "aw-impuesto-nieuws",
        "name": "Aruba Departamento di Impuesto — nieuws",
        "url": "https://www.impuesto.aw/nieuws",
        "jurisdiction_code": "AW",
        "tax_types": [T.VAT, T.PERSONAL_INCOME, T.CORPORATE_INCOME],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "div[class*='itemContent']",
            "title_selector": "div[class*='threeColumnsTitle'] a",
            "date_selector": "time",
            "base_url": "https://www.impuesto.aw/",
            "note": "Papiamento/Dutch titles (…belasting). CSS-module class names are hashed; selectors use substrings.",
        },
        "schedule_cron": "4 4,10,16,22 * * *",
        "enabled": True,
        "authority": "Departamento di Impuesto",
        "authority_en": "Aruba Tax Department",
    },
    {
        "slug": "cw-belastingdienst-nieuws",
        "name": "Curaçao Belastingdienst — nieuws (RSS)",
        "url": "https://belastingdienst.cw/feed/",
        "jurisdiction_code": "CW",
        "tax_types": [T.VAT, T.PERSONAL_INCOME, T.CORPORATE_INCOME],
        "category": "regulation",
        "adapter": "rss",
        "config": {"note": "Dutch. Low volume (5 posts in the feed)."},
        "schedule_cron": "9 4,10,16,22 * * *",
        "enabled": True,
        "authority": "Belastingdienst Curaçao",
        "authority_en": "Curaçao Tax Administration",
    },
    _backstop(
        "sx-news-backstop",
        "SX",
        "Sint Maarten",
        '"Sint Maarten" belasting OR tax OR "turnover tax"',
        _EN,
        "https://www.sintmaartengov.org/news/Pages/Ministry-News.aspx?ministry-id=6 (SharePoint list is client-rendered)",
        [T.VAT, T.PERSONAL_INCOME, T.CORPORATE_INCOME],
        14,
        "Government of Sint Maarten — Ministry of Finance",
    ),
    {
        "slug": "ag-ird-news",
        "name": "Antigua and Barbuda IRD — news",
        "url": "https://ird.gov.ag/",
        "jurisdiction_code": "AG",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PROPERTY],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "article",
            "note": "TLS handshake fails (incomplete certificate chain) over https and http redirects to it. Disabled.",
        },
        "schedule_cron": "19 4,10,16,22 * * *",
        "enabled": False,
        "authority": "Inland Revenue Department",
    },
    _backstop(
        "ag-news-backstop",
        "AG",
        "Antigua and Barbuda",
        'Antigua "Inland Revenue" OR ABST tax',
        _EN,
        "https://ird.gov.ag/",
        [T.VAT, T.CORPORATE_INCOME, T.PROPERTY],
        24,
        "Inland Revenue Department",
    ),
    _backstop(
        "lc-news-backstop",
        "LC",
        "Saint Lucia",
        '"Saint Lucia" OR "St. Lucia" "Inland Revenue" OR VAT tax',
        _EN,
        "https://www.irdstlucia.gov.lc/ (TLS hostname mismatch)",
        [T.VAT, T.CORPORATE_INCOME, T.PROPERTY],
        29,
        "Inland Revenue Department",
    ),
    _backstop(
        "gd-news-backstop",
        "GD",
        "Grenada",
        'Grenada "Inland Revenue" OR VAT tax',
        _EN,
        "https://www.gov.gd/ (IRD pages 404)",
        [T.VAT, T.CORPORATE_INCOME, T.PROPERTY],
        34,
        "Inland Revenue Division",
    ),
    _backstop(
        "vc-news-backstop",
        "VC",
        "Saint Vincent and the Grenadines",
        '"St Vincent" OR "Saint Vincent" "Inland Revenue" OR VAT tax',
        _EN,
        "https://ird.gov.vc/ (Joomla feed returns 0 entries)",
        [T.VAT, T.CORPORATE_INCOME, T.PROPERTY],
        39,
        "Inland Revenue Department",
    ),
    {
        "slug": "kn-ird-news",
        "name": "St. Kitts and Nevis IRD — news (RSS)",
        "url": "https://www.sknird.com/feed/",
        "jurisdiction_code": "KN",
        "tax_types": [T.VAT, T.PROPERTY, T.CORPORATE_INCOME],
        "category": "regulation",
        "adapter": "rss",
        "config": {},
        "schedule_cron": "44 4,10,16,22 * * *",
        "enabled": True,
        "authority": "Inland Revenue Department",
    },
    _backstop(
        "dm-news-backstop",
        "DM",
        "Dominica",
        'Dominica "Inland Revenue" OR VAT tax',
        _EN,
        "http://ird.gov.dm/ (Joomla feed returns 0 entries)",
        [T.VAT, T.CORPORATE_INCOME, T.PROPERTY],
        49,
        "Inland Revenue Division",
    ),
    # ====================================================================================
    # South America
    # ====================================================================================
    {
        "slug": "uy-dgi-noticias",
        "name": "Uruguay DGI — noticias",
        "url": "https://www.gub.uy/direccion-general-impositiva/comunicacion/noticias",
        "jurisdiction_code": "UY",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "li.Media",
            "title_selector": "h3.Media-title a",
            "date_selector": "span.Box-info",
            "date_dayfirst": True,
            "summary_selector": "div.Media-body p",
            "base_url": "https://www.gub.uy/",
            "note": "gub.uy Drupal listing; no RSS exposed.",
        },
        "schedule_cron": "54 4,10,16,22 * * *",
        "enabled": True,
        "authority": "Dirección General Impositiva",
        "authority_en": "General Tax Directorate (DGI)",
    },
    {
        "slug": "py-dnit-noticias",
        "name": "Paraguay DNIT — noticias",
        "url": "https://www.dnit.gov.py/web/portal-institucional/noticias",
        "jurisdiction_code": "PY",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "article.novedad__item",
            "title_selector": "h2.novedad__title",
            "link_selector": "a.novedad__link",
            "date_selector": "span.novedad__date",
            "note": "Liferay listing (500+ teaser cards; only the 50 newest are read). Some cards carry an empty 'Leer "
            "más' href and are skipped; no RSS. Trial 2026-08-25: 50 found / 18 kept.",
        },
        "schedule_cron": "59 4,10,16,22 * * *",
        "enabled": True,
        "authority": "Dirección Nacional de Ingresos Tributarios",
        "authority_en": "National Directorate of Tax Revenue (DNIT)",
    },
    {
        "slug": "bo-sin-comunicados",
        "name": "Bolivia SIN — comunicados de prensa",
        "url": "https://www.impuestos.gob.bo/index.php/comunicados-de-prensa/",
        "jurisdiction_code": "BO",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "div.card.h-100",
            "title_selector": "h5.card-title",
            "link_selector": "div.card-footer a",
            "date_selector": "p.card-text small",
            "date_dayfirst": True,
            "note": "WordPress theme without a working feed (/feed returns the home page).",
        },
        "schedule_cron": "10 5,11,17,23 * * *",
        "enabled": True,
        "authority": "Servicio de Impuestos Nacionales",
        "authority_en": "National Tax Service (SIN)",
    },
    {
        "slug": "ec-sri-noticias",
        "name": "Ecuador SRI — noticias",
        "url": "https://www.sri.gob.ec/web/intersri/noticias",
        "jurisdiction_code": "EC",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "article",
            "note": f"Liferay portal; the news portlet is client-rendered and /noticias redirects to the home. {BROWSER_NOTE}.",
        },
        "schedule_cron": "15 5,11,17,23 * * *",
        "enabled": False,
        "authority": "Servicio de Rentas Internas",
        "authority_en": "Internal Revenue Service (SRI)",
    },
    _backstop(
        "ec-news-backstop",
        "EC",
        "Ecuador",
        "SRI impuestos OR IVA Ecuador",
        _ES,
        "https://www.sri.gob.ec/web/intersri/noticias",
        [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        20,
        "Servicio de Rentas Internas",
        "Internal Revenue Service (SRI)",
    ),
    _backstop(
        "ve-news-backstop",
        "VE",
        "Venezuela",
        "SENIAT impuestos OR IVA",
        _ES,
        "http://www.seniat.gob.ve/ (connect timeout on every probe)",
        [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        25,
        "Servicio Nacional Integrado de Administración Aduanera y Tributaria",
        "National Integrated Customs and Tax Administration Service (SENIAT)",
    ),
    {
        "slug": "gy-gra-news",
        "name": "Guyana Revenue Authority — news (RSS)",
        "url": "https://gra.gov.gy/feed/",
        "jurisdiction_code": "GY",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.CUSTOMS_TARIFF],
        "category": "regulation",
        "adapter": "rss",
        "config": {},
        "schedule_cron": "30 5,11,17,23 * * *",
        "enabled": True,
        "authority": "Guyana Revenue Authority",
    },
    {
        "slug": "sr-belastingdienst-nieuws",
        "name": "Suriname Belastingdienst — nieuws (RSS)",
        "url": "https://belastingdienst.sr/feed/",
        "jurisdiction_code": "SR",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "news",
        "adapter": "rss",
        "config": {
            "note": "Dutch. Many posts are service notices ('Storing'); the tax gate keeps BTW/belasting items."
        },
        "schedule_cron": "35 5,11,17,23 * * *",
        "enabled": True,
        "authority": "Belastingdienst Suriname",
        "authority_en": "Suriname Tax Administration",
    },
    _backstop(
        "co-dian-news-backstop",
        "CO",
        "Colombia",
        'DIAN impuestos OR IVA OR "declaración de renta"',
        _ES,
        "https://www.dian.gov.co/Prensa/Paginas/Noticias.aspx (SharePoint list is client-rendered; every press/normativa "
        "path re-probed 2026-08-25 is 404)",
        [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        40,
        "Dirección de Impuestos y Aduanas Nacionales",
        "National Tax and Customs Directorate (DIAN)",
    ),
    # ====================================================================================
    # Courts
    # ====================================================================================
    {
        "slug": "cl-tta-noticias",
        "name": "Chile Tribunales Tributarios y Aduaneros — noticias y fallos (RSS)",
        "url": "https://www.tta.cl/feed/",
        "jurisdiction_code": "CL",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.CUSTOMS_TARIFF],
        "category": "court",
        "adapter": "rss",
        "config": {
            "court": "Tribunales Tributarios y Aduaneros",
            "include_keywords": ["con sii", "con servicio de impuestos", "aduana"],
            "note": "Feed mixes case notes ('X con SII Dirección Regional …') with administrative posts; "
            "include_keywords keeps the case notes (the court name alone would satisfy the gate).",
        },
        "schedule_cron": "35 6 * * *",
        "enabled": True,
        "authority": "Tribunales Tributarios y Aduaneros",
        "authority_en": "Tax and Customs Courts (TTA)",
    },
    {
        "slug": "br-stf-stj-tax-backstop",
        "name": "Brazil STF/STJ — tax rulings in the legal press (Google News backstop)",
        "url": "news://br-stf-stj-tax-backstop",
        "jurisdiction_code": "BR",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PAYROLL_SOCIAL],
        "category": "court",
        "adapter": "news",
        "config": {
            "query": "STF OR STJ tributário OR ICMS OR PIS OR Cofins decisão",
            "lang": "pt-BR",
            "country": "BR",
            "court": "Supremo Tribunal Federal / Superior Tribunal de Justiça",
            "max_items": 40,
            "note": "backstop: Google News (pt-BR). Official: portal.stf.jus.br (TLS chain fails) and stj.jus.br "
            "(403 to non-browser clients); CARF publishes agendas, not decisions.",
        },
        "schedule_cron": "40 6 * * *",
        "enabled": True,
        "authority": "Supremo Tribunal Federal / Superior Tribunal de Justiça",
        "authority_en": "Federal Supreme Court / Superior Court of Justice",
    },
    {
        "slug": "mx-scjn-rss",
        "name": "Mexico SCJN — RSS",
        "url": "https://www.scjn.gob.mx/rss.xml",
        "jurisdiction_code": "MX",
        "tax_types": [T.VAT, T.CORPORATE_INCOME],
        "category": "court",
        "adapter": "rss",
        "config": {
            "court": "Suprema Corte de Justicia de la Nación",
            "note": "Feed carries session notices and daily 'Síntesis' PDFs (0 tax matters identifiable); TFJA "
            "(tfja.gob.mx) has no feed and its comunicados paths are 404. Disabled.",
        },
        "schedule_cron": "45 6 * * *",
        "enabled": False,
        "authority": "Suprema Corte de Justicia de la Nación",
        "authority_en": "Supreme Court of Justice of the Nation",
    },
    {
        "slug": "mx-courts-tax-backstop",
        "name": "Mexico SCJN/TFJA — tax rulings in the press (Google News backstop)",
        "url": "news://mx-courts-tax-backstop",
        "jurisdiction_code": "MX",
        "tax_types": [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        "category": "court",
        "adapter": "news",
        "config": {
            "query": "SCJN OR TFJA fiscal OR impuestos OR SAT sentencia OR amparo",
            "lang": "es-419",
            "country": "MX",
            "court": "Suprema Corte de Justicia de la Nación / Tribunal Federal de Justicia Administrativa",
            "max_items": 40,
            "note": "backstop: Google News (es-419). Official: scjn.gob.mx/rss.xml (no tax signal), tfja.gob.mx (no feed).",
        },
        "schedule_cron": "50 6 * * *",
        "enabled": True,
        "authority": "Suprema Corte de Justicia de la Nación / Tribunal Federal de Justicia Administrativa",
        "authority_en": "Supreme Court of Justice / Federal Court of Administrative Justice",
    },
    {
        "slug": "ar-csjn-novedades",
        "name": "Argentina CSJN — novedades",
        "url": "https://www.csjn.gov.ar/",
        "jurisdiction_code": "AR",
        "tax_types": [T.CORPORATE_INCOME, T.SALES_USE, T.PERSONAL_INCOME],
        "category": "court",
        "adapter": "html",
        "config": {
            "item_selector": "a.icon-box",
            "title_selector": "h6",
            "date_selector": "p.text-secondary.text-left",
            "summary_selector": "article p.text-secondary:not(.text-left)",
            "base_url": "https://www.csjn.gov.ar/",
            "court": "Corte Suprema de Justicia de la Nación",
            "note": "Home-page novedades (institutional news). Trial 2026-08-25: 24 found / 0 tax rulings; the "
            "sentencias search (sj.csjn.gov.ar) is a JS app. Disabled; see ar-csjn-tax-backstop.",
        },
        "schedule_cron": "55 6 * * *",
        "enabled": False,
        "authority": "Corte Suprema de Justicia de la Nación",
        "authority_en": "Supreme Court of Justice of the Nation",
    },
    {
        "slug": "ar-csjn-tax-backstop",
        "name": "Argentina CSJN — tax rulings in the press (Google News backstop)",
        "url": "news://ar-csjn-tax-backstop",
        "jurisdiction_code": "AR",
        "tax_types": [T.CORPORATE_INCOME, T.SALES_USE, T.PERSONAL_INCOME],
        "category": "court",
        "adapter": "news",
        "config": {
            "query": '"Corte Suprema" fallo impuesto OR tributario OR "ingresos brutos" OR ARCA',
            "lang": "es-419",
            "country": "AR",
            "court": "Corte Suprema de Justicia de la Nación",
            "max_items": 40,
            "note": "backstop: Google News (es-419). Official novedades page rarely covers tax rulings.",
        },
        "schedule_cron": "0 7 * * *",
        "enabled": True,
        "authority": "Corte Suprema de Justicia de la Nación",
        "authority_en": "Supreme Court of Justice of the Nation",
    },
    {
        "slug": "co-consejo-estado-noticias",
        "name": "Colombia Consejo de Estado — noticias",
        "url": "https://www.consejodeestado.gov.co/noticias/",
        "jurisdiction_code": "CO",
        "tax_types": [T.VAT, T.CORPORATE_INCOME],
        "category": "court",
        "adapter": "html",
        "config": {
            "item_selector": "div.card.mb-4",
            "title_selector": "h5.card-title",
            "link_selector": "a[href]",
            "date_selector": "h6.card-subtitle",
            "summary_selector": "p.card-text",
            "base_url": "https://www.consejodeestado.gov.co/noticias/",
            "court": "Consejo de Estado — Sección Cuarta",
            "note": "2.5 MB page of 641 news cards (newest first; 50 read); each card links a 'Ver Documento' PDF. The "
            "site RSS (feed/index.htm.rss) lists 2021 judge biographies. The court gate keeps tax (Sección Cuarta) "
            "rulings.",
        },
        "schedule_cron": "5 7 * * *",
        "enabled": True,
        "authority": "Consejo de Estado",
        "authority_en": "Council of State",
    },
    {
        "slug": "co-consejo-estado-tax-backstop",
        "name": "Colombia Consejo de Estado — tax rulings in the press (Google News backstop)",
        "url": "news://co-consejo-estado-tax-backstop",
        "jurisdiction_code": "CO",
        "tax_types": [T.VAT, T.CORPORATE_INCOME],
        "category": "court",
        "adapter": "news",
        "config": {
            "query": '"Consejo de Estado" impuesto OR tributario OR DIAN OR "Sección Cuarta"',
            "lang": "es-419",
            "country": "CO",
            "court": "Consejo de Estado — Sección Cuarta",
            "max_items": 40,
            "note": "backstop: Google News (es-419). Official: consejodeestado.gov.co/noticias (cards without links).",
        },
        "schedule_cron": "10 7 * * *",
        "enabled": True,
        "authority": "Consejo de Estado",
        "authority_en": "Council of State",
    },
    # ====================================================================================
    # Trade
    # ====================================================================================
    {
        "slug": "mx-se-prensa-archivo",
        "name": "Mexico Secretaría de Economía — prensa (archive listing)",
        "url": "https://www.gob.mx/se/archivo/prensa",
        "jurisdiction_code": "MX",
        "tax_types": [T.CUSTOMS_TARIFF],
        "category": "tariff",
        "adapter": "html",
        "config": {
            "item_selector": "article",
            "title_selector": "h2",
            "link_selector": "a.small-link",
            "date_selector": "time",
            "base_url": "https://www.gob.mx/",
            "note": "Server-rendered archive (9 comunicados per page). UPCI resolutions are published only in the DOF "
            "(dof.gob.mx: TLS hostname mismatch; sidof.segob.gob.mx lists notices without a stable listing). Trial "
            "2026-08-25: 9 found, 0 trade measures. Disabled; re-probe during tariff actions.",
        },
        "schedule_cron": "25 */4 * * *",
        "enabled": False,
        "authority": "Secretaría de Economía",
        "authority_en": "Ministry of Economy",
    },
    {
        "slug": "mx-trade-news-backstop",
        "name": "Mexico — trade remedies and tariff news (Google News backstop)",
        "url": "news://mx-trade-news-backstop",
        "jurisdiction_code": "MX",
        "tax_types": [T.CUSTOMS_TARIFF],
        "category": "tariff",
        "adapter": "news",
        "config": {
            "query": '"cuota compensatoria" OR arancel OR antidumping México "Secretaría de Economía" OR UPCI',
            "lang": "es-419",
            "country": "MX",
            "max_items": 40,
            "note": "backstop: Google News (es-419). Official: DOF (TLS hostname mismatch) / gob.mx/se comunicados (no "
            "trade measures in the listing).",
        },
        "schedule_cron": "30 */4 * * *",
        "enabled": True,
        "authority": "Secretaría de Economía — UPCI",
        "authority_en": "Ministry of Economy — International Trade Practices Unit",
    },
    {
        "slug": "br-mdic-noticias",
        "name": "Brazil MDIC/Secex — notícias (RSS, trade items)",
        "url": "https://www.gov.br/mdic/pt-br/assuntos/noticias/ultimas-noticias-defeso-2026/RSS",
        "jurisdiction_code": "BR",
        "tax_types": [T.CUSTOMS_TARIFF],
        "category": "tariff",
        "adapter": "rss",
        "config": {
            "note": "The folder RSS at /assuntos/noticias/RSS lists sub-folders only; the 2026 election-period folder "
            "('defeso-2026') carries the items. Trial 2026-08-25: 15 found / 1 trade measure (the rest is trade-balance "
            "and programme news). Disabled; br-gecex-resolucoes (sources.py) carries Brazil's tariff acts. Secex "
            "normativas and Camex RSS feeds list folders by year, not acts.",
        },
        "schedule_cron": "35 */4 * * *",
        "enabled": False,
        "authority": "Ministério do Desenvolvimento, Indústria, Comércio e Serviços",
        "authority_en": "Ministry of Development, Industry, Trade and Services (MDIC)",
    },
    {
        "slug": "ar-cnce-noticias",
        "name": "Argentina CNCE — noticias (dumping / subsidy investigations)",
        "url": "https://www.argentina.gob.ar/cnce/noticias",
        "jurisdiction_code": "AR",
        "tax_types": [T.CUSTOMS_TARIFF],
        "category": "tariff",
        "adapter": "html",
        "config": {
            "item_selector": "div.col-xs-12.col-sm-3",
            "title_selector": "h3",
            "date_selector": "time",
            "summary_selector": "div.panel-body p:not(.text-muted)",
            "base_url": "https://www.argentina.gob.ar/",
            "note": "Each card is one investigation step (apertura / cierre de examen). The /cnce/noticias/rss feed "
            "exists but carries 4 entries and a malformed header; the HTML listing shows 16.",
        },
        "schedule_cron": "40 */4 * * *",
        "enabled": True,
        "authority": "Comisión Nacional de Comercio Exterior",
        "authority_en": "National Foreign Trade Commission (CNCE)",
    },
    # ====================================================================================
    # Sub-national — Brazil states
    # ====================================================================================
    {
        "slug": "br-sp-sefaz-noticias",
        "name": "São Paulo Sefaz — notícias",
        "url": "https://portal.fazenda.sp.gov.br/Noticias",
        "jurisdiction_code": "BR-SP",
        "tax_types": [T.VAT],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "article",
            "note": f"SharePoint page; the news web part is client-rendered (39 anchors, none to articles). {BROWSER_NOTE}.",
        },
        "schedule_cron": "45 5,11,17,23 * * *",
        "enabled": False,
        "authority": "Secretaria da Fazenda e Planejamento do Estado de São Paulo",
        "authority_en": "São Paulo State Finance and Planning Secretariat",
    },
    _backstop(
        "br-sp-news-backstop",
        "BR-SP",
        "São Paulo (state)",
        'Sefaz SP ICMS OR "Secretaria da Fazenda" "São Paulo"',
        _PT,
        "https://portal.fazenda.sp.gov.br/Noticias",
        [T.VAT],
        50,
        "Secretaria da Fazenda e Planejamento do Estado de São Paulo",
        "São Paulo State Finance and Planning Secretariat",
    ),
    {
        "slug": "br-rj-sefaz-noticias",
        "name": "Rio de Janeiro Sefaz — notícias",
        "url": "https://portal.fazenda.rj.gov.br/noticias/",
        "jurisdiction_code": "BR-RJ",
        "tax_types": [T.VAT],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "article",
            "note": "Server answers with an illegal HTTP header ('Connection: close\\x00') on the home page and a 1.5 KB "
            "redirect shell on /noticias/. Disabled.",
        },
        "schedule_cron": "55 5,11,17,23 * * *",
        "enabled": False,
        "authority": "Secretaria de Estado de Fazenda do Rio de Janeiro",
        "authority_en": "Rio de Janeiro State Finance Secretariat",
    },
    _backstop(
        "br-rj-news-backstop",
        "BR-RJ",
        "Rio de Janeiro (state)",
        'Sefaz RJ ICMS OR "Secretaria de Fazenda" "Rio de Janeiro"',
        _PT,
        "https://portal.fazenda.rj.gov.br/",
        [T.VAT],
        0,
        "Secretaria de Estado de Fazenda do Rio de Janeiro",
        "Rio de Janeiro State Finance Secretariat",
    ),
    _backstop(
        "br-mg-news-backstop",
        "BR-MG",
        "Minas Gerais",
        'SEF MG ICMS OR "Secretaria de Fazenda" "Minas Gerais"',
        _PT,
        "https://www.fazenda.mg.gov.br/ (no news listing; /noticias paths 404)",
        [T.VAT],
        6,
        "Secretaria de Estado de Fazenda de Minas Gerais",
        "Minas Gerais State Finance Secretariat",
    ),
    {
        "slug": "br-rs-receita-noticias",
        "name": "Rio Grande do Sul Receita Estadual — notícias",
        "url": "https://receita.fazenda.rs.gov.br/inicial",
        "jurisdiction_code": "BR-RS",
        "tax_types": [T.VAT],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "div.lista-publicacoes-modular-2__item",
            "title_selector": "h4 a",
            "date_selector": "self",
            "date_dayfirst": True,
            "base_url": "https://receita.fazenda.rs.gov.br/",
            "tax_filter": True,
            "note": "Home-page publication tiles mix news ('24/08/2026 - …') with service links; the tax gate drops the "
            "latter. No dedicated list page (/noticias 404).",
        },
        "schedule_cron": "11 5,11,17,23 * * *",
        "enabled": True,
        "authority": "Receita Estadual do Rio Grande do Sul",
        "authority_en": "Rio Grande do Sul State Revenue",
    },
    {
        "slug": "br-pr-sefa-noticias",
        "name": "Paraná Sefa — notícias",
        "url": "https://www.fazenda.pr.gov.br/Noticias",
        "jurisdiction_code": "BR-PR",
        "tax_types": [T.VAT],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "article.item.item-news",
            "title_selector": "h3 a",
            "summary_selector": "p",
            "base_url": "https://www.fazenda.pr.gov.br/",
            "note": "Listing parses (50 items) but every title reads 'Conteúdo indisponível devido ao período eleitoral' "
            "with an empty href until the 2026 election blackout ends (Oct 2026). Disabled; re-enable then.",
        },
        "schedule_cron": "16 5,11,17,23 * * *",
        "enabled": False,
        "authority": "Secretaria de Estado da Fazenda do Paraná",
        "authority_en": "Paraná State Finance Secretariat",
    },
    _backstop(
        "br-pr-news-backstop",
        "BR-PR",
        "Paraná",
        'Sefa PR ICMS OR "Receita Estadual" Paraná',
        _PT,
        "https://www.fazenda.pr.gov.br/Noticias (election blackout)",
        [T.VAT],
        21,
        "Secretaria de Estado da Fazenda do Paraná",
        "Paraná State Finance Secretariat",
    ),
    # ====================================================================================
    # Sub-national — Mexico states
    # ====================================================================================
    {
        "slug": "mx-cmx-finanzas-noticias",
        "name": "Ciudad de México SAF — comunicados",
        "url": "https://www.finanzas.cdmx.gob.mx/",
        "jurisdiction_code": "MX-CMX",
        "tax_types": [T.PROPERTY, T.PAYROLL_SOCIAL],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "div.g-news-pro-item",
            "title_selector": "h4.g-news-pro-title a",
            "date_selector": "div.g-news-pro-desc",
            "summary_selector": "div.g-news-pro-desc",
            "base_url": "https://www.finanzas.cdmx.gob.mx/",
            "note": "Home-page news module (6 items); /comunicacion/comunicados is 404 and there is no RSS. Trial "
            "2026-08-25: 6 found / 1 tax item. Disabled; see mx-cmx-news-backstop.",
        },
        "schedule_cron": "26 5,11,17,23 * * *",
        "enabled": False,
        "authority": "Secretaría de Administración y Finanzas de la Ciudad de México",
        "authority_en": "Mexico City Secretariat of Administration and Finance",
    },
    _backstop(
        "mx-cmx-news-backstop",
        "MX-CMX",
        "Ciudad de México",
        '"Ciudad de México" predial OR "impuesto sobre nóminas" OR tenencia Finanzas',
        _ES,
        "https://www.finanzas.cdmx.gob.mx/ (home-page module; 1 tax item in trial)",
        [T.PROPERTY, T.PAYROLL_SOCIAL],
        28,
        "Secretaría de Administración y Finanzas de la Ciudad de México",
        "Mexico City Secretariat of Administration and Finance",
    ),
    {
        "slug": "mx-jal-hacienda-noticias",
        "name": "Jalisco Secretaría de la Hacienda Pública — noticias",
        "url": "https://hacienda.jalisco.gob.mx/noticias",
        "jurisdiction_code": "MX-JAL",
        "tax_types": [T.PROPERTY, T.PAYROLL_SOCIAL],
        "category": "news",
        "adapter": "html",
        "config": {"item_selector": "article", "note": f"Single-page app (0 anchors server-side). {BROWSER_NOTE}."},
        "schedule_cron": "31 5,11,17,23 * * *",
        "enabled": False,
        "authority": "Secretaría de la Hacienda Pública de Jalisco",
        "authority_en": "Jalisco Public Treasury Secretariat",
    },
    _backstop(
        "mx-jal-news-backstop",
        "MX-JAL",
        "Jalisco",
        '"Hacienda Pública" Jalisco impuesto OR nómina OR predial',
        _ES,
        "https://hacienda.jalisco.gob.mx/noticias",
        [T.PROPERTY, T.PAYROLL_SOCIAL],
        36,
        "Secretaría de la Hacienda Pública de Jalisco",
        "Jalisco Public Treasury Secretariat",
    ),
    _backstop(
        "mx-nle-news-backstop",
        "MX-NLE",
        "Nuevo León",
        '"Nuevo León" impuesto OR nómina OR predial Tesorería',
        _ES,
        "https://www.nl.gob.mx/es (finance secretariat pages 404; state RSS carries one 2023 item)",
        [T.PROPERTY, T.PAYROLL_SOCIAL],
        41,
        "Secretaría de Finanzas y Tesorería General del Estado de Nuevo León",
        "Nuevo León Secretariat of Finance and State Treasury",
    ),
    # ====================================================================================
    # Sub-national — Argentina
    # ====================================================================================
    {
        "slug": "ar-b-arba-noticias",
        "name": "Buenos Aires Province ARBA — noticias",
        "url": "https://www.arba.gov.ar/",
        "jurisdiction_code": "AR-B",
        "tax_types": [T.SALES_USE, T.PROPERTY],
        "category": "regulation",
        "adapter": "html",
        "config": {
            "item_selector": "article",
            "note": f"87-byte JS bootstrap; /Informacion/Noticias.asp 404. {BROWSER_NOTE}.",
        },
        "schedule_cron": "46 5,11,17,23 * * *",
        "enabled": False,
        "authority": "Agencia de Recaudación de la Provincia de Buenos Aires",
        "authority_en": "Buenos Aires Province Revenue Agency (ARBA)",
    },
    _backstop(
        "ar-b-news-backstop",
        "AR-B",
        "Buenos Aires Province",
        'ARBA "ingresos brutos" OR impuesto inmobiliario OR automotor',
        _ES,
        "https://www.arba.gov.ar/",
        [T.SALES_USE, T.PROPERTY],
        51,
        "Agencia de Recaudación de la Provincia de Buenos Aires",
        "Buenos Aires Province Revenue Agency (ARBA)",
    ),
    {
        "slug": "ar-c-agip-novedades",
        "name": "Ciudad de Buenos Aires AGIP — novedades",
        "url": "https://www.agip.gob.ar/novedades",
        "jurisdiction_code": "AR-C",
        "tax_types": [T.SALES_USE, T.PROPERTY],
        "category": "regulation",
        "adapter": "html",
        "config": {"item_selector": "article", "note": f"1.7 KB Angular shell on every path. {BROWSER_NOTE}."},
        "schedule_cron": "56 5,11,17,23 * * *",
        "enabled": False,
        "authority": "Administración Gubernamental de Ingresos Públicos",
        "authority_en": "Buenos Aires City Revenue Administration (AGIP)",
    },
    _backstop(
        "ar-c-news-backstop",
        "AR-C",
        "Buenos Aires City",
        'AGIP "ingresos brutos" OR ABL OR impuesto "Ciudad de Buenos Aires"',
        _ES,
        "https://www.agip.gob.ar/novedades",
        [T.SALES_USE, T.PROPERTY],
        1,
        "Administración Gubernamental de Ingresos Públicos",
        "Buenos Aires City Revenue Administration (AGIP)",
    ),
    # ====================================================================================
    # Sub-national — Canada
    # ====================================================================================
    _backstop(
        "ca-on-news-backstop",
        "CA-ON",
        "Ontario",
        'Ontario "Ministry of Finance" tax OR HST OR "corporate tax" OR "land transfer tax"',
        _EN,
        "https://news.ontario.ca/mof/en (client-rendered; /rss and api paths return the 1.5 KB shell — see "
        "ca-on-finance-news)",
        [T.VAT, T.CORPORATE_INCOME, T.PERSONAL_INCOME],
        2,
        "Ontario Ministry of Finance",
    ),
    {
        "slug": "ca-bc-finance-news",
        "name": "British Columbia Ministry of Finance — news (RSS)",
        "url": "https://news.gov.bc.ca/ministries/finance/feed",
        "jurisdiction_code": "CA-BC",
        "tax_types": [T.SALES_USE, T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.PROPERTY],
        "category": "news",
        "adapter": "rss",
        "config": {
            "note": "Ministry newsroom (10 newest). Trial 2026-08-25: 10 found / 0 tax items (statements, appointments). "
            "Disabled; see ca-bc-news-backstop."
        },
        "schedule_cron": "7 5,11,17,23 * * *",
        "enabled": False,
        "authority": "British Columbia Ministry of Finance",
    },
    _backstop(
        "ca-bc-news-backstop",
        "CA-BC",
        "British Columbia",
        '"British Columbia" PST OR "carbon tax" OR "property tax" OR "income tax" Finance',
        _EN,
        "https://news.gov.bc.ca/ministries/finance/feed (0 tax items in trial)",
        [T.SALES_USE, T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.PROPERTY],
        9,
        "British Columbia Ministry of Finance",
    ),
    {
        "slug": "ca-ab-announcements",
        "name": "Alberta — government announcements (tax items)",
        "url": "https://www.alberta.ca/announcements.cfm?xMinistry=Treasury%20Board%20and%20Finance",
        "jurisdiction_code": "CA-AB",
        "tax_types": [T.CORPORATE_INCOME, T.PERSONAL_INCOME, T.EXCISE],
        "category": "news",
        "adapter": "html",
        "config": {
            "item_selector": "ul.goa-news > li",
            "title_selector": "div.goa-title a",
            "date_selector": "div.goa-date",
            "summary_selector": "div.goa-text",
            "base_url": "https://www.alberta.ca/",
            "note": "announcements.cfm is server-rendered (60 items; the xMinistry filter is ignored by the server, so "
            "the list is government-wide and the tax gate does the filtering). /rss/news.xml is 404.",
        },
        "schedule_cron": "12 5,11,17,23 * * *",
        "enabled": True,
        "authority": "Alberta Treasury Board and Finance",
    },
]

__all__ = ["SOURCES"]
