"""Trade measures (tariffs, safeguards, retaliation, CBAM).

Audit 2026-08-22 (docs/data-audit.md): every row was checked against the Federal Register / govinfo, whitehouse.gov,
USTR, EUR-Lex, national gazettes or (where those block automated clients) law-firm/press reports. The IEEPA block
reflects the Supreme Court's judgment in Learning Resources, Inc. v. Trump (20 Feb 2026) and EO 14389; successor
Section 122 / 301 / 338 measures are seeded as separate rows. Federal Register documents are linked via govinfo
mirrors because federalregister.gov rate-limits automated clients.
"""

from __future__ import annotations

from taxatlas.seed._helpers import tariff

T: list[dict] = []

USTR_301 = "https://ustr.gov/trade-topics/enforcement/section-301-investigations/section-301-china-technology-transfer/china-section-301-tariff-actions-and-exclusion-process/four-year-review"
USTR_4YR = USTR_301
BIS_232 = "https://www.bis.gov/232"
CBP_IEEPA = "https://www.cbp.gov/trade/programs-administration/trade-remedies/ieepa-duty-refunds"
WH_RECIP = "https://www.whitehouse.gov/presidential-actions/2025/04/regulating-imports-with-a-reciprocal-tariff-to-rectify-trade-practices-that-contribute-to-large-and-persistent-annual-united-states-goods-trade-deficits/"
WH_JUL31 = "https://www.whitehouse.gov/presidential-actions/2025/07/further-modifying-the-reciprocal-tariff-rates/"
FR_EO14389 = "https://www.govinfo.gov/content/pkg/FR-2026-02-25/html/2026-03832.htm"
FR_PROC11012 = "https://www.govinfo.gov/content/pkg/FR-2026-02-25/html/2026-03824.htm"
FR_301_FL = "https://www.govinfo.gov/content/pkg/FR-2026-07-28/html/2026-15274.htm"
FR_METALS_2026 = "https://www.govinfo.gov/content/pkg/FR-2026-04-09/html/2026-06960.htm"
SCOTUS_IEEPA = "https://www.supremecourt.gov/opinions/25pdf/24-1287_4gcj.pdf"
IEEPA_NOTE = (
    "IEEPA tariff authority struck down: the Supreme Court held in Learning Resources, Inc. v. Trump, 607 U.S. 229 (20 Feb 2026; 6-3) "
    "that IEEPA does not authorise the President to impose tariffs. EO 14389 (20 Feb 2026, 91 FR 9437) terminated the tariff provisions of "
    "EOs 14193/14194/14195/14257/14323/14329 and collection ceased at 12:01 a.m. EST 24 Feb 2026. Refunds of IEEPA duties are processed by CBP "
    "(CAPE, from 20 Apr 2026) under CIT orders of 4 Mar and 17 Jul 2026. Replaced by a Section 122 10% surcharge (24 Feb – 24 Jul 2026) and, "
    "from 24 Jul 2026, the Section 301 forced-labour action (see separate rows)."
)

# ---------------------------------------------------------------- United States: MFN and Section 232
T += [
    tariff(
        "US",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (MFN)",
        value=3.3,
        basis="Harmonized Tariff Schedule of the United States; WTO World Tariff Profiles",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/US_e.pdf",
        notes="Simple average applied MFN rate (WTO World Tariff Profiles 2026, 2025 data); trade-weighted 2.2%. The effective applied rate rose well above the MFN average in 2025–2026 with Section 232, IEEPA (to Feb 2026), Section 122 and Section 301 measures.",
    ),
    tariff(
        "US",
        None,
        "Steel and steel articles",
        "section_232",
        scope="All origins (UK 25% on Annex I-A / 15% on I-B; EU/JP/KR/TW minimum 15% on certain derivatives)",
        hs="72, 73",
        value=50,
        basis="Proclamation 9705 (2018) as amended by Proclamations 10896 (Feb 2025), 10947 (Jun 2025), 11021 (2 Apr 2026, 91 FR 18201) and 11032 (1 Jun 2026, 91 FR 34085)",
        frm="2025-06-04",
        url=FR_METALS_2026,
        notes="25% from 23 Mar 2018; country exemptions and quota deals ended 12 Mar 2025; raised to 50% on 4 Jun 2025. Restructured from 6 Apr 2026 (Procl. 11021): 50% on Annex I-A steel on full customs value, derivative articles at a flat 25% with products of ≤15% metal content exempt; Procl. 11032 cut agricultural/HVAC/mobile-equipment derivatives to 15% from 8 Jun 2026. Unaffected by the IEEPA judgment.",
    ),
    tariff(
        "US",
        None,
        "Steel and steel articles (2018–Jun 2025 rate)",
        "section_232",
        scope="All origins (with country exemptions/quotas 2018–Mar 2025)",
        hs="72, 73",
        value=25,
        basis="Proclamation 9705 (8 Mar 2018)",
        status="expired",
        frm="2018-03-23",
        to="2025-06-03",
        url="https://www.federalregister.gov/documents/2018/03/15/2018-05478/adjusting-imports-of-steel-into-the-united-states",
        notes="Superseded by the 50% rate on 4 Jun 2025.",
    ),
    tariff(
        "US",
        None,
        "Aluminum and aluminum articles",
        "section_232",
        scope="All origins (UK at 25%)",
        hs="76",
        value=50,
        basis="Proclamation 9704 (2018) as amended by Proclamations 10895 (Feb 2025), 10947 (Jun 2025), 11021 (Apr 2026) and 11045 (20 Jul 2026, 91 FR 46635)",
        frm="2025-06-04",
        url="https://www.govinfo.gov/content/pkg/FR-2026-07-23/html/2026-14990.htm",
        notes="10% from Mar 2018; raised to 25% on 12 Mar 2025 and to 50% on 4 Jun 2025. Restructured with steel/copper from 6 Apr 2026 (derivatives at flat 25%). Procl. 11045 (Jul 2026) lets companies building US smelters import primary aluminum at half the rate. Russian aluminum at 200% since Mar 2023.",
    ),
    tariff(
        "US",
        None,
        "Aluminum and aluminum articles (2018–Mar 2025 rate)",
        "section_232",
        scope="All origins (with exemptions)",
        hs="76",
        value=10,
        basis="Proclamation 9704 (8 Mar 2018)",
        status="expired",
        frm="2018-03-23",
        to="2025-03-11",
        url="https://www.federalregister.gov/documents/2018/03/15/2018-05477/adjusting-imports-of-aluminum-into-the-united-states",
        notes="Raised to 25% on 12 Mar 2025 and 50% on 4 Jun 2025.",
    ),
    tariff(
        "US",
        None,
        "Passenger vehicles and light trucks",
        "section_232",
        scope="All origins (USMCA: US-content carve-out; EU/JP/KR 15% under frameworks; UK 10% quota)",
        hs="8703, 8704",
        value=25,
        basis="Proclamation 10908 (26 Mar 2025); Procl. 14346 (EU) and EO 14345 (Japan), Sep 2025; Commerce/USTR notice 90 FR 55964 (Korea, Dec 2025)",
        frm="2025-04-03",
        url="https://www.federalregister.gov/documents/2025/04/03/2025-05930/adjusting-imports-of-automobiles-and-automobile-parts-into-the-united-states",
        notes="25% on autos from 3 Apr 2025 and on key parts from 3 May 2025. Framework deals reduce the rate to 15% (EU and Japan from Sep 2025; Korea retroactive to 1 Nov 2025) and 10% for the first 100,000 UK vehicles. Offset of 3.75% of MSRP for US-assembled vehicles (2025–2030). Section 232 measures were unaffected by the Feb 2026 IEEPA judgment; no amending proclamation found through Aug 2026.",
    ),
    tariff(
        "US",
        None,
        "Automobile parts (engines, transmissions, powertrain, electrical components)",
        "section_232",
        scope="All origins (USMCA-compliant parts exempt pending process)",
        hs="8407, 8408, 8708 and others",
        value=25,
        basis="Proclamation 10908 (26 Mar 2025)",
        frm="2025-05-03",
        url="https://www.federalregister.gov/documents/2025/04/03/2025-05930/adjusting-imports-of-automobiles-and-automobile-parts-into-the-united-states",
        notes="Annex I parts list; inclusion process for additional parts launched Jun 2025.",
    ),
    tariff(
        "US",
        None,
        "Copper (semi-finished products and intensive derivatives)",
        "section_232",
        scope="All origins",
        hs="7407–7419 (semi-finished), derivatives",
        value=50,
        basis="Proclamation 10962 (30 Jul 2025) as amended by Proclamation 11021 (2 Apr 2026)",
        frm="2025-08-01",
        url="https://www.federalregister.gov/documents/2025/08/05/2025-14913/adjusting-imports-of-copper-into-the-united-states",
        notes="Applies to semi-finished copper and copper-intensive derivative products; refined copper cathodes, ores and scrap excluded (phased cathode tariff considered for 2027). From 6 Apr 2026: 50% on Annex I-A copper articles on full value, copper-intensive derivatives at 25%.",
    ),
    tariff(
        "US",
        None,
        "Softwood timber and lumber",
        "section_232",
        scope="All origins (UK 10%, EU/JP 15% caps under frameworks)",
        hs="4403, 4407",
        value=10,
        basis="Proclamation of 29 Sep 2025 (Adjusting Imports of Timber, Lumber, and Their Derivative Products); Proclamation 11000 (31 Dec 2025, 91 FR 1039)",
        frm="2025-10-14",
        url="https://www.whitehouse.gov/presidential-actions/2025/09/adjusting-imports-of-timber-lumber-and-their-derivative-products-into-the-united-states/",
        notes="10% on softwood timber and lumber, unchanged by Procl. 11000 (Dec 2025); stacks with Canadian AD/CVD (~35% combined).",
    ),
    tariff(
        "US",
        None,
        "Upholstered furniture, kitchen cabinets and vanities (wood)",
        "section_232",
        scope="All origins",
        hs="9401, 9403",
        value=25,
        basis="Proclamation of 29 Sep 2025 (timber, lumber and derivatives); Proclamation 11000 (31 Dec 2025, 91 FR 1039)",
        frm="2025-10-14",
        url="https://www.govinfo.gov/content/pkg/FR-2026-01-09/html/2026-00327.htm",
        notes="25% on upholstered wooden furniture, kitchen cabinets and vanities from 14 Oct 2025. The scheduled increase to 30%/50% on 1 Jan 2026 was deferred to 1 Jan 2027 by Procl. 11000 (EU/JP capped at 15%, UK 10%).",
    ),
    tariff(
        "US",
        None,
        "Heavy-duty trucks (Class 3–8) and parts; buses",
        "section_232",
        scope="All origins (USMCA content carve-out)",
        hs="8701, 8704, 8702",
        value=25,
        basis="Proclamation of 17 Oct 2025 (Adjusting Imports of Medium- and Heavy-Duty Vehicles and Their Parts, and Buses); FR doc 2025-19639",
        frm="2025-11-01",
        url="https://www.whitehouse.gov/presidential-actions/2025/10/adjusting-imports-of-medium-and-heavy-duty-vehicles-medium-and-heavy-duty-vehicle-parts-and-buses-into-the-united-states/",
        notes="25% on medium/heavy trucks and parts, 10% on buses from 1 Nov 2025; no change found through Aug 2026.",
    ),
    tariff(
        "US",
        None,
        "Patented pharmaceutical products, APIs and key starting materials",
        "section_232",
        scope="All origins (20% with an approved onshoring plan; EU/JP/KR/CH/LI 15%; UK 10%; generics 0%)",
        hs="30, 29 (Annex)",
        value=100,
        basis="Proclamation 11020 (2 Apr 2026, 91 FR 18183) following the Section 232 investigation initiated 1 Apr 2025",
        frm="2026-07-31",
        url="https://www.govinfo.gov/content/pkg/FR-2026-04-09/html/2026-06956.htm",
        notes="Announced 25 Sep 2025, proclaimed 2 Apr 2026. 100% on patented pharmaceuticals, APIs and KSMs; 20% for companies with Commerce-approved US onshoring plans (through 1 Apr 2030); framework caps 15% (EU, Japan, Korea, Switzerland, Liechtenstein) and 10% (UK); generics excluded. Effective 31 Jul 2026 for the 17 Annex III companies and 29 Sep 2026 for all others (CBP CSMS #69395344).",
    ),
    tariff(
        "US",
        None,
        "Advanced semiconductors (narrow set of logic chips) and derivative products",
        "section_232",
        scope="All origins; broad end-use exemptions (US data centres, R&D, etc.)",
        hs="8471.50, 8471.80, 8473.30 (meeting performance thresholds)",
        value=25,
        basis="Proclamation 11002 (14 Jan 2026, 91 FR 2443) following the Section 232 investigation initiated 1 Apr 2025",
        frm="2026-01-15",
        url="https://www.govinfo.gov/content/pkg/FR-2026-01-20/html/2026-01052.htm",
        notes="Phase 1: 25% on a narrow set of advanced logic chips (e.g., NVIDIA H200, AMD MI325X) from 15 Jan 2026 with extensive end-use exemptions. A broader Phase 2 tariff on semiconductors and SME remains under negotiation/review.",
    ),
    tariff(
        "US",
        None,
        "Polysilicon and polysilicon derivatives",
        "section_232",
        scope="All origins",
        hs="2804.61, derivatives",
        value=15,
        basis="Proclamation 11052 (6 Aug 2026, 91 FR 51975)",
        frm="2026-12-04",
        url="https://www.bis.gov/232",
        rate_text="15% ad valorem plus minimum import prices",
        notes="Proclaimed 6 Aug 2026; takes effect 4 Dec 2026. Seeded from the proclamation (govinfo FR-2026-08-11 expected); BIS Section 232 hub linked.",
    ),
    tariff(
        "US",
        None,
        "Unmanned aircraft systems (drones) and components",
        "section_232",
        scope="All origins (EU/JP/KR/TW/CH capped at 15%; UK 10%)",
        hs="8806, 8807",
        value=100,
        basis="Proclamation 11055 (13 Aug 2026, 91 FR 53699)",
        frm="2026-09-03",
        url="https://www.bis.gov/232",
        rate_text="100% on drones; 25% on components",
        notes="Proclaimed 13 Aug 2026; takes effect 3 Sep 2026. Other 2026 Section 232 proclamations imposed no tariff yet: critical minerals (Procl. 11001, 14 Jan 2026 — negotiations) and commercial aircraft/engines (Procl. 11040, 9 Jul 2026).",
    ),
]

# ---------------------------------------------------------------- United States: Section 301 China
T += [
    tariff(
        "US",
        "CN",
        "List 1 — USD 34bn of industrial machinery, electronics, vehicles",
        "section_301",
        hs="84, 85, 87, 88, 90 (818 lines)",
        value=25,
        basis="Section 301 (Docket USTR-2018-0005); 83 FR 28710",
        frm="2018-07-06",
        url=USTR_301,
        notes="Maintained after the 2024 four-year review; 178 exclusions extended to 10 Nov 2026 (USTR, Dec 2025). A second statutory four-year review opened 6 May 2026. From 24 Jul 2026 the Section 301 forced-labour action (12.5% for China) stacks on top.",
    ),
    tariff(
        "US",
        "CN",
        "List 2 — USD 16bn of semiconductors, plastics, chemicals, rail",
        "section_301",
        hs="279 lines",
        value=25,
        basis="Section 301; 83 FR 40823",
        frm="2018-08-23",
        url=USTR_301,
        notes="Maintained after the 2024 four-year review.",
    ),
    tariff(
        "US",
        "CN",
        "List 3 — USD 200bn of consumer and intermediate goods",
        "section_301",
        hs="5,745 lines",
        value=25,
        basis="Section 301; 83 FR 47974 (10%), raised to 25% by 84 FR 20459",
        frm="2019-05-10",
        url=USTR_301,
        notes="Imposed at 10% on 24 Sep 2018; increased to 25% on 10 May 2019.",
    ),
    tariff(
        "US",
        "CN",
        "List 4A — USD 120bn of consumer goods (apparel, footwear, electronics)",
        "section_301",
        hs="3,229 lines",
        value=7.5,
        basis="Section 301; 84 FR 43304, reduced by 85 FR 3741 (Phase One deal)",
        frm="2020-02-14",
        url=USTR_301,
        notes="Imposed at 15% on 1 Sep 2019; reduced to 7.5% on 14 Feb 2020 under the Phase One agreement. List 4B (15%) was suspended indefinitely in Dec 2019.",
    ),
    tariff(
        "US",
        "CN",
        "Electric vehicles",
        "section_301",
        hs="8703.80",
        value=100,
        basis="Section 301 four-year review; 89 FR 76581",
        frm="2024-09-27",
        url=USTR_4YR,
        notes="Raised from 25% to 100% following the May 2024 four-year review.",
    ),
    tariff(
        "US",
        "CN",
        "Solar cells and modules",
        "section_301",
        hs="8541.42, 8541.43",
        value=50,
        basis="Section 301 four-year review; 89 FR 76581",
        frm="2024-09-27",
        url=USTR_4YR,
        notes="Raised from 25% to 50%; polysilicon and wafers raised to 50% from 1 Jan 2025.",
    ),
    tariff(
        "US",
        "CN",
        "Semiconductors",
        "section_301",
        hs="8541, 8542",
        value=50,
        basis="Section 301 four-year review; 89 FR 76581",
        frm="2025-01-01",
        url=USTR_4YR,
        notes="Raised from 25% to 50% effective 1 Jan 2025.",
    ),
    tariff(
        "US",
        "CN",
        "Lithium-ion EV batteries",
        "section_301",
        hs="8507.60",
        value=25,
        basis="Section 301 four-year review; 89 FR 76581",
        frm="2024-09-27",
        url=USTR_4YR,
        notes="Raised from 7.5% to 25%; non-EV lithium-ion batteries rose from 7.5% to 25% on 1 Jan 2026 as scheduled.",
    ),
    tariff(
        "US",
        "CN",
        "Steel and aluminum products (Section 301 scope)",
        "section_301",
        hs="72, 73, 76 (selected)",
        value=25,
        basis="Section 301 four-year review; 89 FR 76581",
        frm="2024-09-27",
        url=USTR_4YR,
        notes="Raised from 0–7.5% to 25%; stacks with Section 232 duties.",
    ),
    tariff(
        "US",
        "CN",
        "Ship-to-shore cranes",
        "section_301",
        hs="8426.19",
        value=25,
        basis="Section 301 four-year review; 89 FR 76581",
        frm="2024-09-27",
        url=USTR_4YR,
        notes="Raised from 0% to 25%. The separate Section 301 maritime/shipbuilding action (port fees and crane duties) was suspended for one year from 10 Nov 2025 (FR doc 2025-19873) under the Busan arrangement.",
    ),
    tariff(
        "US",
        "CN",
        "Medical products — syringes and needles",
        "section_301",
        hs="9018.31, 9018.32",
        value=100,
        basis="Section 301 four-year review; 89 FR 76581",
        frm="2024-09-27",
        url=USTR_4YR,
        notes="Raised from 0% to 50% in 2024 and to 100% from 1 Jan 2025; facemasks rose to 50% and medical gloves to 100% on 1 Jan 2026 as scheduled.",
    ),
    tariff(
        "US",
        "CN",
        "Natural graphite, permanent magnets and certain critical minerals",
        "section_301",
        hs="2504, 8505.11",
        value=25,
        basis="Section 301 four-year review; 89 FR 76581",
        frm="2026-01-01",
        url=USTR_4YR,
        status="in_force",
        notes="Increase from 0% to 25% took effect 1 Jan 2026 as scheduled.",
    ),
    tariff(
        "US",
        "BR",
        "All goods — Section 301 action on Brazil (digital trade, ethanol, IP, deforestation practices)",
        "section_301",
        value=25,
        basis="Section 301 investigation initiated 15 Jul 2025; USTR notice of action 15 Jul 2026 (91 FR 45619)",
        frm="2026-07-22",
        url="https://www.govinfo.gov/content/pkg/FR-2026-07-20/html/2026-14654.htm",
        notes="Successor to the IEEPA 40% Brazil tariff struck down in Feb 2026. 25% additional duty from 22 Jul 2026; product exclusions follow the Nov 2025 IEEPA carve-outs. Whether the Section 301 forced-labour 12.5% also applies to Brazil is reported inconsistently (unverified).",
    ),
    tariff(
        "US",
        None,
        "All goods — Section 301 action on forced-labour practices (~60 economies)",
        "section_301",
        scope="~60 economies in four tiers (10%/12.5%, additive or MFN-inclusive; see notes); FTA-qualifying goods and Section 232 articles exempt",
        value=12.5,
        basis="Presidential Memorandum and USTR determinations under Section 301 (91 FR 47717, 28 Jul 2026)",
        frm="2026-07-24",
        url=FR_301_FL,
        rate_text="10% or 12.5% depending on partner tier; 'inclusive' tiers are net of the MFN duty",
        notes="Successor regime to the IEEPA reciprocal tariffs after Learning Resources v. Trump; replaced the temporary Section 122 surcharge when it lapsed on 24 Jul 2026. Partner tiers reflect the 2025 framework agreements (EU, Japan, Korea, UK, Switzerland). Tiers: 10% additive (UK, India, Canada, Mexico, Argentina, Bangladesh, Cambodia, Ecuador, El Salvador, Guatemala, Honduras, Indonesia, Jordan, Malaysia, Pakistan, Sri Lanka, Trinidad and Tobago); 10% inclusive of MFN (EU, Taiwan); 12.5% inclusive of MFN (Japan, Korea, Switzerland); 12.5% additive (all others incl. China, Vietnam).",
    ),
    tariff(
        "US",
        None,
        "All goods — Section 122 balance-of-payments import surcharge",
        "other",
        scope="All origins except USMCA-originating goods, Section 232 articles, CAFTA-DR textiles and an Annex of exempt products",
        value=10,
        basis="Proclamation 11012 (20 Feb 2026, 91 FR 9339) under Section 122 of the Trade Act of 1974",
        status="expired",
        frm="2026-02-24",
        to="2026-07-24",
        url=FR_PROC11012,
        notes="Temporary 10% surcharge for the 150-day statutory maximum after the IEEPA tariffs were struck down; an announced increase to 15% was never implemented. The CIT held the surcharge unlawful on 7 May 2026 (Oregon v. United States; Burlap and Barrel), stayed by the Federal Circuit on 12 May 2026 with relief limited to the named plaintiffs. Replaced by the Section 301 forced-labour action from 24 Jul 2026.",
    ),
    tariff(
        "US",
        "CA",
        "Selected Canadian goods (~USD 20bn) — Section 338 discriminatory-treatment tariff",
        "other",
        scope="Non-USMCA-originating goods in the Annex lists",
        value=50,
        basis="Proclamations 11046, 11047 and 11048 (20 Jul 2026; 91 FR 46639, 46653, 46663) under Section 338 of the Tariff Act of 1930",
        frm="2026-08-19",
        url="https://www.govinfo.gov/content/pkg/FR-2026-07-23/html/2026-14997.htm",
        notes="Imposed in response to Canada's retained counter-tariffs (SOR/2025-118) after US–Canada talks collapsed. The proclamations state an effective date of 19 Aug 2026; press reports a three-day delay to 22 Aug 2026 (no Federal Register instrument located for the delay — unverified). Canada announced dollar-for-dollar retaliation from 8 Sep 2026.",
    ),
]

# ---------------------------------------------------------------- United States: IEEPA tariffs
T += [
    tariff(
        "US",
        None,
        "All goods — baseline 'reciprocal' tariff",
        "ieepa",
        scope="All origins except Canada/Mexico (separate IEEPA orders) and Annex II exclusions (energy, pharma, semiconductors, copper, lumber, bullion, certain minerals); Section 232 goods excluded",
        value=10,
        basis="Executive Order 14257 (2 Apr 2025) under IEEPA; terminated by EO 14389 (20 Feb 2026)",
        status="revoked",
        frm="2025-04-05",
        to="2026-02-23",
        url=WH_RECIP,
        notes="10% baseline from 5 Apr 2025. Country-specific higher rates took effect 9 Apr 2025 and were suspended to 10% for 90 days (EO 14266), then replaced by the 31 Jul 2025 schedule effective 7 Aug 2025. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "EU",
        "All goods — EU reciprocal rate (all-inclusive 15% framework)",
        "ieepa",
        value=15,
        basis="EO 14326 (31 Jul 2025); US–EU Framework Agreement (27 Jul 2025); terminated by EO 14389",
        status="revoked",
        frm="2025-08-07",
        to="2026-02-23",
        url=WH_JUL31,
        notes="15% ceiling inclusive of MFN duty for most EU goods; exemptions for aircraft, generic pharma, certain chemicals. The Section 232 elements of the framework (autos 15%, Procl. 14346) survive. From 24 Jul 2026 the EU pays the Section 301 forced-labour rate of 10% inclusive of MFN; the EU eliminated duties on US industrial goods from 1 Jul 2026 (OJ L 2026/1455). No post-judgment US instrument re-creating an 'all-inclusive 15%' was found. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "JP",
        "All goods — Japan reciprocal rate",
        "ieepa",
        value=15,
        basis="EO 14326 (31 Jul 2025); US–Japan agreement (22 Jul 2025); EO 14345 (4 Sep 2025); terminated by EO 14389",
        status="revoked",
        frm="2025-08-07",
        to="2026-02-23",
        url=WH_JUL31,
        notes="15% all-inclusive (no stacking on MFN above 15%); autos at 15% from 16 Sep 2025 in exchange for a USD 550bn investment commitment. The Section 232 auto rate survives; from 24 Jul 2026 Japan pays the Section 301 forced-labour rate of 12.5% inclusive of MFN. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "GB",
        "All goods — UK reciprocal rate",
        "ieepa",
        value=10,
        basis="EO 14257; US–UK Economic Prosperity Deal (8 May 2025); terminated by EO 14389",
        status="revoked",
        frm="2025-04-05",
        to="2026-02-23",
        url="https://www.whitehouse.gov/fact-sheets/2025/05/fact-sheet-u-s-uk-reach-historic-trade-deal/",
        notes="Baseline 10% retained; EPD Section 232 terms survive (100,000-vehicle quota at 10%, steel/aluminum at 25%/15%, pharma 10%, drones 10%). From 24 Jul 2026 the UK pays the Section 301 forced-labour rate of 10% additive. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "VN",
        "All goods — Vietnam reciprocal rate",
        "ieepa",
        value=20,
        basis="EO 14326 (31 Jul 2025); US–Vietnam framework (2 Jul 2025); terminated by EO 14389",
        status="revoked",
        frm="2025-08-07",
        to="2026-02-23",
        url=WH_JUL31,
        notes="Reduced from the 46% announced on 2 Apr 2025; 40% rate on goods deemed transshipped (EO 14326). From 24 Jul 2026 Vietnam pays the Section 301 forced-labour rate of 12.5% additive. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "IN",
        "All goods — India reciprocal rate plus Russia-oil penalty",
        "ieepa",
        value=50,
        basis="EO 14326 (25%, 31 Jul 2025) + EO 14329 (additional 25%, 6 Aug 2025); EO 14384 (6 Feb 2026, 91 FR 6501); EO 14389",
        status="revoked",
        frm="2025-08-27",
        to="2026-02-23",
        url="https://www.whitehouse.gov/presidential-actions/2025/08/addressing-threats-to-the-united-states-by-the-government-of-the-russian-federation/",
        notes="25% reciprocal from 7 Aug 2025 plus an additional 25% from 27 Aug 2025 for purchases of Russian oil (50% total). The Russia-oil 25% was removed by EO 14384 effective 7 Feb 2026 (interim framework of 2 Feb 2026 at 18%); the remaining 25% ended 24 Feb 2026. From 24 Jul 2026 India pays the Section 301 forced-labour rate of 10% additive. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "BR",
        "All goods — Brazil reciprocal rate plus additional 40%",
        "ieepa",
        value=50,
        basis="EO 14257 (10%) + EO 14323 (additional 40%, 30 Jul 2025); narrowed by Procl. 14361 (20 Nov 2025); terminated by EO 14389",
        status="revoked",
        frm="2025-08-06",
        to="2026-02-23",
        url="https://www.whitehouse.gov/presidential-actions/2025/07/addressing-threats-to-the-us/",
        notes="10% baseline plus 40% under a separate national emergency citing the prosecution of former president Bolsonaro; ~700 product exclusions (aircraft, orange juice, energy). In Nov 2025 many agricultural goods (beef, coffee) were exempted. Replaced by a Section 301 action at 25% from 22 Jul 2026 (see section_301 row). "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "CH",
        "All goods — Switzerland reciprocal rate",
        "ieepa",
        value=39,
        basis="EO 14326 (31 Jul 2025); reduced by FR doc 2025-23316 (18 Dec 2025); terminated by EO 14389",
        status="revoked",
        frm="2025-08-07",
        to="2026-02-23",
        url=WH_JUL31,
        notes="39% from 7 Aug 2025; cut to 15% retroactive to 14 Nov 2025 under the US–Switzerland framework (FR doc 2025-23316, 18 Dec 2025). From 24 Jul 2026 Switzerland pays the Section 301 forced-labour rate of 12.5% inclusive of MFN. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "KR",
        "All goods — Korea reciprocal rate",
        "ieepa",
        value=15,
        basis="EO 14326 (31 Jul 2025); US–Korea agreement; terminated by EO 14389",
        status="revoked",
        frm="2025-08-07",
        to="2026-02-23",
        url=WH_JUL31,
        notes="15% including autos after the Oct/Nov 2025 implementation of the investment framework; Section 232 autos at 15% (90 FR 55964) survive. From 24 Jul 2026 Korea pays the Section 301 forced-labour rate of 12.5% inclusive of MFN. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "CN",
        "All goods — 'fentanyl' emergency tariff",
        "ieepa",
        value=10,
        basis="EO 14195 (1 Feb 2025) as amended; EO 14357 (4 Nov 2025, 90 FR 50725); terminated by EO 14389",
        status="revoked",
        frm="2025-11-10",
        to="2026-02-23",
        url="https://www.whitehouse.gov/presidential-actions/2025/02/imposing-duties-to-address-the-synthetic-opioid-supply-chain-in-the-peoples-republic-of-china/",
        notes="10% from 4 Feb 2025, 20% from 4 Mar 2025, reduced to 10% from 10 Nov 2025 following the Trump–Xi Busan meeting. Applied to Hong Kong and Macau origin goods too. China now faces Section 301 lists plus the 12.5% forced-labour action (37.5% on List 1–3 goods) and Section 232 duties. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "CN",
        "All goods — 'fentanyl' emergency tariff (Mar–Nov 2025 rate)",
        "ieepa",
        value=20,
        basis="EO 14228 (3 Mar 2025)",
        status="expired",
        frm="2025-03-04",
        to="2025-11-09",
        url="https://www.whitehouse.gov/presidential-actions/2025/03/further-amendment-to-duties-addressing-the-synthetic-opioid-supply-chain-in-the-peoples-republic-of-china/",
        notes="Superseded by 10% on 10 Nov 2025.",
    ),
    tariff(
        "US",
        "CN",
        "All goods — China reciprocal tariff (suspended portion)",
        "ieepa",
        value=10,
        basis="EO 14257; EO 14298 (12 May 2025, Geneva); extended by EO of Aug 2025 and EO 14358 (4 Nov 2025, 90 FR 50729); terminated by EO 14389",
        status="revoked",
        frm="2025-05-14",
        to="2026-02-23",
        url="https://www.whitehouse.gov/presidential-actions/2025/05/modifying-reciprocal-tariff-rates-to-reflect-discussions-with-the-peoples-republic-of-china/",
        notes="34% country rate escalated to 125% in April 2025; under the Geneva arrangement 24 points were suspended leaving 10%, extended 90 days in Aug 2025 and to 10 Nov 2026 after the Busan meeting (EO 14358). Terminated with all IEEPA tariffs on 24 Feb 2026. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "CN",
        "All goods — China reciprocal tariff peak (Apr–May 2025)",
        "ieepa",
        value=125,
        basis="EO 14259 and EO 14266 (Apr 2025)",
        status="expired",
        frm="2025-04-10",
        to="2025-05-13",
        url="https://www.whitehouse.gov/presidential-actions/2025/04/modifying-reciprocal-tariff-rates-to-reflect-trading-partner-retaliation-and-alignment/",
        notes="Escalation sequence 34% → 84% → 125% in response to Chinese retaliation; reduced to 10% (with 24% suspended) from 14 May 2025.",
    ),
    tariff(
        "US",
        "CA",
        "All goods — Canada IEEPA tariff (non-USMCA goods)",
        "ieepa",
        value=35,
        basis="EO 14193 (1 Feb 2025) as amended by EO 14325 (31 Jul 2025); terminated by EO 14389",
        status="revoked",
        frm="2025-08-01",
        to="2026-02-23",
        url="https://www.whitehouse.gov/presidential-actions/2025/07/amendment-to-duties-to-address-the-flow-of-illicit-drugs-across-our-northern-border/",
        notes="25% from 4 Mar 2025, raised to 35% on 1 Aug 2025; USMCA-compliant goods exempt (~85%+ of trade); energy and potash at 10%. After termination, non-USMCA Canadian goods paid the Section 122 surcharge and then the 10% Section 301 forced-labour rate; a Section 338 50% tariff on ~USD 20bn of Canadian goods followed in Aug 2026 (see 'other' row). "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        "MX",
        "All goods — Mexico IEEPA tariff (non-USMCA goods)",
        "ieepa",
        value=25,
        basis="EO 14194 (1 Feb 2025) as amended; terminated by EO 14389",
        status="revoked",
        frm="2025-03-04",
        to="2026-02-23",
        url="https://www.whitehouse.gov/presidential-actions/2025/02/imposing-duties-to-address-the-situation-at-our-southern-border/",
        notes="25% on non-USMCA-compliant goods; a planned increase to 30% on 1 Aug 2025 was deferred by successive 90-day extensions. After termination, non-USMCA Mexican goods paid the Section 122 surcharge and then the 10% Section 301 forced-labour rate. "
        + IEEPA_NOTE,
    ),
    tariff(
        "US",
        None,
        "Low-value shipments — suspension of de minimis duty-free entry",
        "ieepa",
        scope="All origins (China/HK from 2 May 2025; worldwide from 29 Aug 2025)",
        basis="EO 14324 (30 Jul 2025) suspending 19 U.S.C. 1321(a)(2)(C); continued by EO 14388 (20 Feb 2026, 91 FR 9433); CBP interim final rule 24 Jun 2026 (91 FR 37789)",
        frm="2025-08-29",
        url="https://www.govinfo.gov/content/pkg/FR-2026-06-24/html/2026-12670.htm",
        rate_text="Applicable MFN/Section 122/301/232 duties; postal items: ad valorem rate or per-item amounts during the transition",
        notes="USD 800 de minimis exemption ended for China/Hong Kong on 2 May 2025 and for all countries on 29 Aug 2025. Not disturbed by the IEEPA judgment: EO 14388 continued the suspension from 24 Feb 2026 (citing IEEPA/NEA and Section 604) and CBP's interim final rule of 24 Jun 2026 codifies an indefinite suspension for non-postal entries under 19 U.S.C. 1321(b). OBBBA (P.L. 119-21) repeals de minimis statutorily from 1 Jul 2027.",
    ),
]

# ---------------------------------------------------------------- Retaliation against the US
T += [
    tariff(
        "CN",
        "US",
        "All US-origin goods — retaliatory tariff (post-Geneva level)",
        "retaliatory",
        value=10,
        basis="State Council Tariff Commission Announcements No. 4–6 (2025); Geneva Joint Statement 12 May 2025; Tariff Commission announcement of 5 Nov 2025",
        frm="2025-05-14",
        url="https://gss.mof.gov.cn/gzdt/zhengcefabu/",
        notes="34% announced 4 Apr 2025, escalated to 84% and 125%; reduced to 10% (24 points suspended) from 14 May 2025, with the suspension extended to 10 Nov 2026 after the Oct 2025 Busan meeting. Still in force in Aug 2026 — no Chinese removal following the US IEEPA termination was found. Agricultural retaliation (10–15% from Mar 2025) lifted from 10 Nov 2025. gss.mof.gov.cn returned HTTP 502 during the audit; announcement numbers for the Nov 2025 action unverified.",
    ),
    tariff(
        "CN",
        "US",
        "US agricultural products (soybeans, pork, beef, chicken, wheat, corn, cotton)",
        "retaliatory",
        hs="02, 10, 12, 52",
        value=15,
        basis="State Council Tariff Commission Announcement No. 2 (2025)",
        status="revoked",
        frm="2025-03-10",
        to="2025-11-09",
        url="https://gss.mof.gov.cn/gzdt/zhengcefabu/",
        notes="10%–15% additional tariffs on US agricultural goods in response to the fentanyl tariff; removed from 10 Nov 2025 under the Busan arrangement (a 10% general retaliatory tariff remains).",
    ),
    tariff(
        "CN",
        "US",
        "US coal, LNG, crude oil, agricultural machinery, large-displacement cars",
        "retaliatory",
        hs="27, 8429, 8703",
        value=15,
        basis="State Council Tariff Commission Announcement No. 1 (2025)",
        frm="2025-02-10",
        url="https://gss.mof.gov.cn/gzdt/zhengcefabu/",
        notes="15% on coal and LNG; 10% on crude, machinery, pickups and large cars — the first 2025 retaliatory round. Status unverified as of Aug 2026: the Nov 2025 Busan de-escalation lifted the Mar 2025 agricultural round but no source confirming removal of this Feb 2025 round was found.",
    ),
    tariff(
        "CA",
        "US",
        "US-origin goods — first counter-tariff package (C$30bn)",
        "retaliatory",
        hs="Various consumer goods (orange juice, appliances, apparel, motorcycles, paper)",
        value=25,
        basis="United States Surtax Order (2025-1)",
        status="revoked",
        frm="2025-03-04",
        to="2025-08-31",
        url="https://www.canada.ca/en/department-finance/news/2025/03/list-of-products-from-the-united-states-subject-to-25-per-cent-tariffs-effective-february-4-2025.html",
        notes="25% counter-tariffs on C$30bn of US goods from 4 Mar 2025 (with a further C$29.8bn on steel/aluminum/autos from 13 Mar and 9 Apr). Removed for USMCA-compliant goods on 1 Sep 2025 (announced 22 Aug 2025); retained on US steel, aluminum and autos.",
    ),
    tariff(
        "CA",
        "US",
        "US steel, aluminum and non-USMCA autos — retained counter-tariffs",
        "retaliatory",
        hs="72, 73, 76, 8703",
        value=25,
        basis="United States Surtax Order (Steel and Aluminum 2025); United States Surtax Order (Motor Vehicles 2025) (SOR/2025-118)",
        frm="2025-03-13",
        url="https://www.canada.ca/en/department-finance/programs/international-trade-finance-policy/canadas-response-us-tariffs.html",
        notes="Counter-tariffs on US steel and aluminum (from 13 Mar 2025) and non-USMCA-compliant US vehicles (from 9 Apr 2025) were retained when the consumer-goods package was removed on 1 Sep 2025, and remain in force in Aug 2026 (remission orders for steel to 31 Jan 2026 and for auto/aerospace inputs to 30 Jun 2026). Cited by the US as the basis for its Section 338 tariffs; Canada announced a new dollar-for-dollar retaliation package from 8 Sep 2026 after talks collapsed on 22 Aug 2026. canada.ca blocks automated clients (page marked archived in search indexes).",
    ),
    tariff(
        "EU",
        "US",
        "US-origin goods — rebalancing measures (EUR 93bn package)",
        "retaliatory",
        hs="Annex lists: agricultural, industrial, steel/aluminum products",
        value=25,
        basis="Implementing Regulation (EU) 2025/1564 (24 Jul 2025) under Enforcement Regulation (EU) 654/2014; suspended by (EU) 2025/1565, extended by (EU) 2026/295 and (EU) 2026/1893",
        status="suspended",
        frm="2025-08-07",
        url="https://policy.trade.ec.europa.eu/news/eu-extends-suspension-eu-rebalancing-measures-against-united-states-2026-07-31_en",
        notes="The EU adopted counter-measures on EUR 21bn (April 2025) later merged into a EUR 93bn list, suspended them for six months on 5 Aug 2025 following the 27 Jul 2025 US–EU framework, extended the suspension to 6 Aug 2026 (Reg. 2026/295) and then indefinitely on 30 Jul 2026 (Reg. 2026/1893).",
    ),
    tariff(
        "MX",
        "US",
        "US-origin goods — retaliation",
        "retaliatory",
        basis="Announced Mar 2025; never implemented",
        status="expired",
        frm="2025-03-04",
        to="2026-02-23",
        url="https://www.gob.mx/se",
        rate_text="Not implemented",
        notes="Mexico repeatedly announced but deferred retaliation pending negotiations; no counter-tariffs were ever in force and the IEEPA trigger disappeared on 24 Feb 2026. Mexico's 2026 non-FTA tariff decrees are general measures, not US retaliation.",
    ),
]

# ---------------------------------------------------------------- European Union
T += [
    tariff(
        "EU",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (MFN)",
        value=4.9,
        basis="Common Customs Tariff (Regulation (EEC) 2658/87)",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/CE_e.pdf",
        notes="Simple average applied MFN rate (WTO World Tariff Profiles 2026, 2025 data; was 5.1% in the 2024 edition); trade-weighted 2.9%.",
    ),
    tariff(
        "EU",
        None,
        "Passenger cars",
        "mfn",
        scope="All WTO members (MFN); US-origin cars duty-free from 1 Jul 2026",
        hs="8703",
        value=10,
        basis="Common Customs Tariff",
        frm="2000-01-01",
        url="https://taxation-customs.ec.europa.eu/customs-4/calculation-customs-duties/customs-tariff/eu-customs-tariff-taric_en",
        notes="Under the 2025 US–EU framework the EU legislated the elimination of duties on US industrial goods, including cars, from 1 Jul 2026 (OJ L 2026/1455 and 2026/1461).",
    ),
    tariff(
        "EU",
        "CN",
        "Battery electric vehicles — countervailing duties",
        "countervailing",
        hs="8703.80",
        value=35.3,
        basis="Implementing Regulation (EU) 2024/2754",
        frm="2024-10-30",
        url="https://eur-lex.europa.eu/eli/reg_impl/2024/2754/oj",
        rate_text="7.8% (Tesla) to 35.3% (SAIC and non-cooperating), on top of 10% MFN; BYD 17.0%, Geely 18.8%",
        notes="Definitive CVDs for five years following the 2023 anti-subsidy investigation. The Commission issued guidance on price undertakings on 12 Jan 2026 and accepted the first undertaking (Volkswagen Anhui / CUPRA Tavascan) on 10 Feb 2026 (Impl. Decision OJ L 2026/328); other exporters continue to pay the duties.",
    ),
    tariff(
        "EU",
        None,
        "Steel products — safeguard tariff-rate quota",
        "safeguard",
        scope="All origins except developing countries below 3% share (and EEA)",
        hs="72, 73 (26 product categories)",
        value=25,
        basis="Implementing Regulation (EU) 2019/159 as prolonged by (EU) 2024/1782",
        status="expired",
        frm="2019-02-02",
        to="2026-06-30",
        url="https://www.tradecomplianceresourcehub.com/2026/06/26/eu-steel-regulation-published-key-features-application-dates-and-what-to-do-next/",
        rate_text="25% out-of-quota duty",
        notes="Quota liberalisation cut to 0.1% and tightened in 2025. Expired 30 Jun 2026 (WTO eight-year maximum) and replaced by the permanent TRQ regime of Regulation (EU) 2026/1384 from 1 Jul 2026. The Commission's steel-safeguard topic page was removed in 2026; a compliance summary is linked.",
    ),
    tariff(
        "EU",
        None,
        "Steel — permanent tariff-rate quota regime (post-safeguard)",
        "safeguard",
        scope="All origins except EEA; FTA partners receive country allocations",
        hs="72, 73",
        value=50,
        basis="Regulation (EU) 2026/1384 (OJ 24 Jun 2026; in force 25 Jun 2026; applies from 1 Jul 2026)",
        frm="2026-07-01",
        url="https://eur-lex.europa.eu/eli/reg/2026/1384/oj",
        rate_text="50% out-of-quota duty",
        notes="Adopted from the Commission's Oct 2025 proposal: tariff-rate quotas of 18,345,922 tonnes (≈47% below the safeguard quotas) with a 50% out-of-quota duty; 'melt and pour' origin rules from 1 Oct 2026.",
    ),
    tariff(
        "EU",
        None,
        "CBAM — cement, iron and steel, aluminium, fertilisers, electricity, hydrogen (definitive period)",
        "cbam",
        scope="All non-EU origins except EEA/Switzerland and countries linked to the EU ETS",
        hs="2523, 72, 73, 76, 31, 2716, 2804.10",
        basis="Regulation (EU) 2023/956 as amended by Regulation (EU) 2025/2083 (OJ 17 Oct 2025, in force 20 Oct 2025)",
        frm="2026-01-01",
        url="https://taxation-customs.ec.europa.eu/carbon-border-adjustment-mechanism_en",
        rate_text="Certificate price = weekly average EU ETS allowance price × embedded emissions (minus carbon price paid abroad and free-allocation benchmark)",
        notes="Transitional reporting period 1 Oct 2023 – 31 Dec 2025. Definitive period confirmed live from 1 Jan 2026: authorised CBAM declarants must surrender certificates for 2026 imports, with certificate sales starting 1 Feb 2027; 50-tonne annual de minimis per importer (Omnibus).",
    ),
    tariff(
        "EU",
        "RU",
        "Russian and Belarusian cereals, oilseeds and derived products",
        "other",
        hs="10, 12, 15, 23",
        value=50,
        basis="Regulation (EU) 2024/1652 (prohibitive tariffs); extended by Regulation (EU) 2025/1227",
        frm="2024-07-01",
        url="https://eur-lex.europa.eu/eli/reg/2024/1652/oj",
        rate_text="EUR 95/tonne for cereals, 50% ad valorem for oilseeds and derived products",
        notes="Prohibitive tariffs on agricultural imports from Russia and Belarus (Reg. 2024/1652; the previously cited 2024/1782 is the steel-safeguard prolongation); extended in 2025 to remaining agricultural goods and fertilisers (Regulation (EU) 2025/1227, phased duties from 1 Jul 2025).",
    ),
    tariff(
        "EU",
        "UA",
        "Ukrainian agricultural products — revised DCFTA tariff-rate quotas",
        "preferential",
        hs="02, 04, 07, 10, 11, 17",
        basis="EU–Ukraine DCFTA Article 29 revision (Oct 2025), replacing the Autonomous Trade Measures",
        frm="2025-10-29",
        url="https://policy.trade.ec.europa.eu/eu-trade-relationships-country-and-region/countries-and-regions/ukraine_en",
        rate_text="Duty-free within enlarged TRQs; MFN above quota",
        notes="Autonomous Trade Measures (full liberalisation) expired 5 Jun 2025; the revised DCFTA sets higher permanent quotas for sugar, poultry, eggs, wheat, maize and honey with MFN duties above quota.",
    ),
]

# ---------------------------------------------------------------- China
T += [
    tariff(
        "CN",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (MFN)",
        value=7.5,
        basis="Customs Tariff Law of the PRC (2024); 2025 Tariff Adjustment Plan",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/CN_e.pdf",
        notes="Simple average applied MFN (WTO World Tariff Profiles 2026, 2025 data); trade-weighted 3.0%. Zero tariffs extended to all 53 African countries with diplomatic relations from 2025.",
    ),
    tariff(
        "CN",
        "CA",
        "Canadian canola oil, oil cake and peas",
        "retaliatory",
        hs="1514, 2306, 0713",
        value=100,
        basis="State Council Tariff Commission Announcement (8 Mar 2025); Canada–China arrangement of 16 Jan 2026",
        frm="2025-03-20",
        url="https://www.international.gc.ca/news-nouvelles/2026/2026-01-16-china-chine.aspx?lang=eng",
        notes="100% on canola oil/meal and peas, 25% on pork and aquatic products, in response to Canada's Oct 2024 surtaxes on Chinese EVs, steel and aluminum. Under the 16 Jan 2026 Canada–China arrangement the duties on canola meal, peas (100%) and lobster/crab (25%) are suspended 1 Mar – 31 Dec 2026; canola oil (100%) and pork (25%) remain.",
    ),
    tariff(
        "CN",
        "CA",
        "Canadian canola seed — provisional anti-dumping duty",
        "antidumping",
        hs="1205",
        value=75.8,
        basis="MOFCOM Announcement No. 42 (2025)",
        status="expired",
        frm="2025-08-14",
        to="2026-02-28",
        url="https://www.mofcom.gov.cn/",
        notes="Provisional AD deposit of 75.8% following the investigation opened Sep 2024; superseded by the definitive 5.9% duty from 1 Mar 2026.",
    ),
    tariff(
        "CN",
        "CA",
        "Canadian canola seed — definitive anti-dumping duty",
        "antidumping",
        hs="1205",
        value=5.9,
        basis="MOFCOM final ruling of 28 Feb 2026 (announcement number unverified)",
        frm="2026-03-01",
        to="2031-02-28",
        url="https://www.mofcom.gov.cn/",
        notes="Definitive AD duty of 5.9% for five years from 1 Mar 2026 (≈15% combined with the 9% MFN duty), following the Jan 2026 Canada–China arrangement. MOFCOM site content not retrievable from the audit environment; figure from press reports.",
    ),
    tariff(
        "CN",
        "EU",
        "EU brandy — anti-dumping duties",
        "antidumping",
        hs="2208.20",
        value=34.9,
        basis="MOFCOM Announcement No. 36 (2025)",
        frm="2025-07-05",
        url="https://www.mofcom.gov.cn/",
        rate_text="27.7%–34.9% (price undertakings accepted for major cognac houses)",
        notes="Definitive AD duties on EU brandy (widely seen as a response to EU BEV duties); most large producers avoid duties via minimum-price undertakings.",
    ),
    tariff(
        "CN",
        "US",
        "Rare earth and critical mineral export controls",
        "export_control",
        hs="2805.30, 2846, 8505",
        basis="MOFCOM/GAC Announcements No. 18 (Apr 2025) and No. 61–62 (Oct 2025)",
        status="suspended",
        frm="2025-04-04",
        url="https://www.mofcom.gov.cn/",
        rate_text="Licensing requirement (not a tariff)",
        notes="Export licensing on seven rare earth elements from Apr 2025; the expanded Oct 2025 controls (extraterritorial 0.1% content rule) were suspended for one year under the Nov 2025 Busan arrangement. Recorded here as a non-tariff trade measure.",
    ),
]

# ---------------------------------------------------------------- India, UK, Japan, Korea, Canada, Mexico, Brazil, Türkiye
T += [
    tariff(
        "IN",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (MFN)",
        value=16.0,
        basis="Customs Tariff Act 1975; Union Budget 2025-26 rationalisation",
        frm="2025-02-02",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/IN_e.pdf",
        notes="Simple average applied MFN 16.0% (WTO World Tariff Profiles 2026, 2025 data; 17.0% in the 2024 edition); trade-weighted 7.9%. Budget 2025-26 cut the number of tariff slabs to eight and capped the effective rate on most industrial goods at 70%.",
    ),
    tariff(
        "IN",
        None,
        "Completely built electric vehicles (CIF > USD 40,000)",
        "mfn",
        scope="All origins (reduced 15% rate under the 2024 EV manufacturing scheme for investors)",
        hs="8703.80",
        value=110,
        basis="Customs Tariff Act; Notification 50/2017-Customs; SPMEPCI scheme (Mar 2024)",
        frm="2024-03-15",
        url="https://www.cbic.gov.in/",
        rate_text="110% (CIF > USD 40,000); 70% (CIF ≤ USD 40,000); 15% for approved investors under SPMEPCI",
        notes="Scheme to Promote Manufacturing of Electric Passenger Cars allows import of up to 8,000 EVs/year at 15% for manufacturers committing INR 41.5bn investment (secondary sources give the SPMEPCI CIF floor as USD 35,000 — unverified). EVs excluded from the 2026 US–India and EU–India trade deals.",
    ),
    tariff(
        "IN",
        None,
        "Flat steel products — safeguard duty (provisional and year 1)",
        "safeguard",
        scope="All origins except developing countries below 3% share",
        hs="7208–7212, 7225, 7226",
        value=12,
        basis="Notification No. 01/2025-Customs (SG) (provisional, 21 Apr 2025); Notification No. 02/2025-Customs (SG) (definitive, 30 Dec 2025)",
        status="expired",
        frm="2025-04-21",
        to="2026-04-20",
        url="https://www.dgtr.gov.in/",
        notes="Provisional 12% safeguard from 21 Apr 2025 for 200 days; the definitive three-year duty (Notification 02/2025-Customs (SG), 30 Dec 2025, following DGTR final findings) applies 12% for 21 Apr 2025 – 20 Apr 2026, 11.5% for 21 Apr 2026 – 20 Apr 2027 and 11% for 21 Apr 2027 – 20 Apr 2028.",
    ),
    tariff(
        "IN",
        None,
        "Flat steel products — safeguard duty (year 2)",
        "safeguard",
        scope="All origins except developing countries below 3% share",
        hs="7208–7212, 7225, 7226",
        value=11.5,
        basis="Notification No. 02/2025-Customs (SG), 30 Dec 2025",
        frm="2026-04-21",
        to="2027-04-20",
        url="https://www.cbic.gov.in/",
        notes="Year-2 rate of the definitive safeguard; falls to 11% on 21 Apr 2027 and expires 20 Apr 2028.",
    ),
    tariff(
        "GB",
        None,
        "All goods — UK Global Tariff (simple average applied, statistical)",
        "mfn",
        scope="All WTO members (MFN)",
        value=3.7,
        basis="Taxation (Cross-border Trade) Act 2018; UK Global Tariff",
        frm="2025-01-01",
        url="https://www.gov.uk/guidance/tariffs-on-goods-imported-into-the-uk",
        notes="Simple average applied MFN 3.7% (WTO World Tariff Profiles 2026, 2025 data; 3.8% in the 2024 edition); trade-weighted 3.4%; ~47% of lines duty-free. UK suspended tariffs on 89 product lines through 2027 (Apr 2025).",
    ),
    tariff(
        "GB",
        None,
        "Passenger cars",
        "mfn",
        scope="All WTO members (MFN)",
        hs="8703",
        value=10,
        basis="UK Global Tariff",
        frm="2021-01-01",
        url="https://www.trade-tariff.service.gov.uk/",
        notes="10% MFN; zero under UK FTAs (EU TCA, Japan, etc.) subject to rules of origin.",
    ),
    tariff(
        "GB",
        None,
        "Steel products — safeguard tariff-rate quota",
        "safeguard",
        scope="All origins except developing countries below 3% share",
        hs="72, 73 (15 categories)",
        value=25,
        basis="Trade Remedies Authority; Taxation Notice 2024 (extension to June 2026)",
        status="expired",
        frm="2021-01-01",
        to="2026-06-30",
        url="https://www.trade-remedies.service.gov.uk/",
        rate_text="25% out-of-quota duty",
        notes="Rolled over from the EU safeguard; extended to 30 Jun 2026 (WTO maximum) and expired. Replaced by the UK steel trade measure from 1 Jul 2026. The TRA public site redirects automated clients to a login page.",
    ),
    tariff(
        "GB",
        None,
        "Steel products — UK steel trade measure (tariff-rate quotas, 50% out-of-quota)",
        "quota",
        scope="All origins except Ukraine; 20 product categories",
        hs="72, 73 (20 categories)",
        value=50,
        basis="Taxation (Cross-border Trade) Act 2018; UK steel trade measure notice (Jun 2026)",
        frm="2026-07-01",
        to="2027-06-30",
        url="https://www.gov.uk/government/publications/uks-steel-trade-measure-from-1-july-2026/uks-steel-trade-measure-from-1-july-2026",
        rate_text="50% out-of-quota duty",
        notes="Successor to the expired safeguard: quotas cut by ~51%, out-of-quota duty raised from 25% to 50%, Ukraine excluded; initial period 1 Jul 2026 – 30 Jun 2027.",
    ),
    tariff(
        "JP",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (MFN)",
        value=3.7,
        basis="Customs Tariff Law; WTO World Tariff Profiles",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/JP_e.pdf",
        notes="Simple average applied MFN (WTO World Tariff Profiles 2026, 2025 data); trade-weighted 2.0%; ~0% on passenger cars, high specific duties on rice and dairy.",
    ),
    tariff(
        "KR",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (MFN)",
        value=13.5,
        basis="Customs Act; WTO World Tariff Profiles",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/KR_e.pdf",
        notes="Simple average applied MFN 13.5% (WTO World Tariff Profiles 2026, 2025 data; 13.4% in the 2024 edition) inflated by agricultural peaks; trade-weighted 8.0%; 8% general rate on most industrial goods; 0% under KORUS for US-origin goods.",
    ),
    tariff(
        "CA",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (MFN)",
        value=3.7,
        basis="Customs Tariff (S.C. 1997, c. 36)",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/CA_e.pdf",
        notes="Simple average applied MFN 3.7% (WTO World Tariff Profiles 2026, 2025 data; 3.8% in the 2024 edition); trade-weighted 3.6%; supply-managed dairy/poultry over-quota rates exceed 200%.",
    ),
    tariff(
        "CA",
        "CN",
        "Chinese-made electric vehicles — surtax",
        "other",
        hs="8703.80, 8702.40, 8704.60",
        value=100,
        basis="China Surtax Order (2024) under s.53 Customs Tariff; s.3/Schedule 1 repealed by SOR/2026-32",
        status="revoked",
        frm="2024-10-01",
        to="2026-02-28",
        url="https://gazette.gc.ca/rp-pr/p2/2026/2026-03-11/html/sor-dors32-eng.html",
        notes="100% surtax on Chinese EVs (including Tesla made in Shanghai) from 1 Oct 2024; prompted Chinese retaliation on canola. Repealed from 1 Mar 2026 under the 16 Jan 2026 Canada–China arrangement: Chinese EVs moved to the Import Control List with an annual quota of 49,000 units (+6.5%/yr; 24,500 for 1 Mar – 31 Aug 2026) at the 6.1% MFN rate. The 25% surtax on Chinese steel and aluminum (from 22 Oct 2024) remains, with expanded remission to end-2026.",
    ),
    tariff(
        "CA",
        None,
        "Steel — tariff-rate quotas and 50% surtax (non-FTA and FTA partners)",
        "quota",
        scope="All origins except US (separate measures); USMCA/FTA partners get larger quotas",
        hs="72, 73",
        value=50,
        basis="Order Imposing a Surtax on the Importation of Certain Steel Goods (Jun/Jul 2025, amended Aug and Dec 2025); Customs Notice Serial No. 1163 (Jun 2026)",
        frm="2025-06-27",
        url="https://www.canada.ca/en/department-finance/news/2025/07/canada-strengthens-steel-tariff-measures.html",
        rate_text="50% surtax above TRQ and 25% surtax on steel melted and poured in China; 25% surtax on steel derivatives from 26 Dec 2025",
        notes="Measures announced 19 Jun and 16 Jul 2025 to counter diversion from the US market; TRQs tightened from 1 Aug 2025 and again on 26 Dec 2025 (20% of 2024 volumes for non-FTA, 75% for non-CUSMA FTA partners); year-2 quotas run 28 Jun 2026 – 27 Jun 2027.",
    ),
    tariff(
        "MX",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (MFN; USMCA and other FTA partners preferential)",
        value=8.5,
        basis="Ley de los Impuestos Generales de Importación y de Exportación (LIGIE)",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/MX_e.pdf",
        notes="Simple average applied MFN 8.5% (WTO World Tariff Profiles 2026, 2025 data; 6.8% in the 2024 edition, before the 2024–2025 non-FTA increases); trade-weighted 5.6%. Most imports enter duty-free under 14 FTAs.",
    ),
    tariff(
        "MX",
        None,
        "Steel, textiles, footwear, autos, plastics and ~1,460 other lines from non-FTA countries",
        "mfn",
        scope="Countries without an FTA with Mexico (principally China, India, Korea, Vietnam, Indonesia, Thailand)",
        hs="72, 73, 61–64, 8703, 39 and others",
        value=50,
        basis="Decreto que modifica la LIGIE (DOF 29 Dec 2025, per press; 15 Dec 2025 per one compliance source) and second decree (DOF 23 Apr 2026)",
        frm="2026-01-01",
        url="https://www.dof.gob.mx/",
        rate_text="5%–50% (35% on most; 50% on autos and some steel/textiles); Apr 2026 decree adds 185 lines at 5%–35%",
        notes="Builds on the Apr 2024 (5%–50% on 544 lines) and Dec 2024 (35% on textiles) decrees; the Dec 2025 decree (1,463 lines) took effect 1 Jan 2026 and a second decree of 23 Apr 2026 (185 lines, effective 24 Apr 2026) extended it, framed as Plan México and USMCA-review alignment. DOF publication date could not be confirmed (dof.gob.mx unreachable from the audit environment).",
    ),
    tariff(
        "MX",
        "CN",
        "Chinese e-commerce low-value imports (courier shipments)",
        "other",
        scope="Countries without an FTA (de facto China)",
        basis="Reglas Generales de Comercio Exterior 2025 (Rule 3.7.35) as amended Aug 2025",
        frm="2025-08-15",
        url="https://www.sat.gob.mx/",
        rate_text="33.5% general import duty on courier shipments from non-FTA countries (19% for USMCA origin above the USD 117 de minimis)",
        notes="Replaced the simplified 16%-VAT-only regime in Jan 2025 (19%) to curb Temu/Shein imports; the non-FTA courier rate was raised to 33.5% from 15 Aug 2025.",
    ),
    tariff(
        "MX",
        "CN",
        "Chinese e-commerce low-value imports (courier shipments) — Jan–Aug 2025 rate",
        "other",
        scope="Countries without an FTA (de facto China)",
        basis="Reglas Generales de Comercio Exterior 2025 (Rule 3.7.35)",
        status="expired",
        frm="2025-01-01",
        to="2025-08-14",
        url="https://www.sat.gob.mx/",
        rate_text="19% general import duty on courier shipments from non-FTA countries (17% for USMCA above de minimis)",
        notes="Superseded by the 33.5% rate on 15 Aug 2025.",
    ),
    tariff(
        "BR",
        None,
        "Mercosur Common External Tariff (simple average, statistical)",
        "mfn",
        scope="All WTO members (MFN; Mercosur members 0%)",
        value=12.0,
        basis="Mercosur Decision CMC 31/2021 and national list of exceptions (LETEC)",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/BR_e.pdf",
        notes="Simple average applied MFN 12.0% (WTO World Tariff Profiles 2026, 2025 data; 11.2% in the 2024 edition); trade-weighted 9.4%. CET ranges 0%–35%; Brazil raised duties on 11 steel products to 25% with quotas in Jun 2024 (extended 2025) and on EVs in steps to 35% by Jul 2026. MDIC's TEC page moved (former URL 404).",
    ),
    tariff(
        "BR",
        None,
        "Electric and hybrid vehicles — phased restoration of import duty",
        "mfn",
        scope="All origins (Mercosur/Mexico preferential)",
        hs="8703.40, 8703.60, 8703.80",
        value=35,
        basis="Camex Resolution 553/2023 (Gecex); Gecex resolutions of Jun 2026",
        frm="2026-07-01",
        url="https://www.gov.br/mdic/pt-br/assuntos/camex",
        rate_text="10% (Jan 2024) → 18% (Jul 2024) → 25% (Jul 2025) → 35% (Jul 2026)",
        notes="Gradual end of the 0% duty on EVs introduced in 2015; 35% reached 1 Jul 2026 as scheduled. Gecex kept CKD kits at 14% to Dec 2026 (35% from Jan 2027) and opened a six-month zero-rate CKD/SKD quota (USD 463m) from 1 Jul 2026.",
    ),
    tariff(
        "TR",
        None,
        "All goods — simple average MFN applied tariff (statistical)",
        "mfn",
        scope="All WTO members (EU Customs Union for industrial goods)",
        value=17.3,
        basis="Import Regime Decree; EU–Türkiye Customs Union",
        frm="2025-01-01",
        url="https://www.wto.org/english/res_e/statis_e/daily_update_e/tariff_profiles/TR_e.pdf",
        notes="Simple average applied MFN 17.3% (WTO World Tariff Profiles 2026, 2025 data; 16.8% in the 2024 edition) inflated by agriculture; trade-weighted 9.8%; industrial goods aligned with the EU Common Customs Tariff under the 1995 Customs Union.",
    ),
    tariff(
        "TR",
        "CN",
        "Chinese passenger vehicles (ICE, hybrid and electric) — additional customs duty",
        "other",
        hs="8703",
        value=40,
        basis="Presidential Decision No. 8639 (Jun 2024); revoked by Presidential Decision No. 10436 (OG 22 Sep 2025)",
        status="revoked",
        frm="2024-07-07",
        to="2025-09-21",
        url="https://www.resmigazete.gov.tr/",
        rate_text="Additional 40% or USD 7,000 per vehicle, whichever is higher (on top of 10% MFN)",
        notes="Extended the 2023 EV duty to all Chinese-made cars; exemptions for manufacturers investing in Türkiye (e.g., BYD plant announced Jul 2024). Replaced on 22 Sep 2025 by an all-origin additional duty (see separate row).",
    ),
    tariff(
        "TR",
        None,
        "Passenger vehicles — additional customs duty (all origins outside the EU Customs Union / FTAs)",
        "other",
        scope="All origins not covered by the EU Customs Union or an FTA",
        hs="8703",
        value=30,
        basis="Presidential Decision No. 10436 (OG 22 Sep 2025)",
        frm="2025-09-22",
        url="https://www.resmigazete.gov.tr/",
        rate_text="Additional 25% (min USD 6,000) on ICE/hybrid cars; 30% (min USD 7,000 PHEV / USD 8,500 BEV) on plug-in and battery EVs",
        notes="Replaced the China-specific 40% duty with a blanket additional duty; investors with Turkish production remain exempt. Resmî Gazete blocks automated TLS clients; dates from EY/press.",
    ),
    tariff(
        "TR",
        "US",
        "US-origin goods — additional duties (2018 retaliation)",
        "retaliatory",
        hs="Passenger cars, alcohol, tobacco, cosmetics, rice, coal",
        value=60,
        basis="Presidential Decision No. 2018/11973 (doubled Aug 2018); rescinded by Presidential Decision No. 10435 (OG 22 Sep 2025)",
        status="revoked",
        frm="2018-06-21",
        to="2025-09-21",
        url="https://www.resmigazete.gov.tr/",
        rate_text="Up to 140% on alcoholic beverages, 120% on cars, 60% on tobacco (after Aug 2018 doubling)",
        notes="Retaliation against US Section 232 steel/aluminum tariffs; removed by Presidential Decision No. 10435 published and effective 22 Sep 2025 (not Apr 2025 as previously seeded) alongside the new blanket car duty.",
    ),
]

TARIFFS: list[dict] = T
