/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current user information - returns existing user or creates minimal profile
         */
        get: operations["get_current_user_api_users_me_get"];
        /**
         * Update Current User
         * @description Update current user's profile
         */
        put: operations["update_current_user_api_users_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync User Profile
         * @description Sync user profile with data from frontend
         *     Frontend sends complete user profile data
         */
        post: operations["sync_user_profile_api_users_me_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Initiate Job
         * @description Step 1: Initiate a new extraction job and get pre-signed upload URLs
         */
        post: operations["initiate_job_api_jobs_initiate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Job
         * @description Step 2: Start job processing with field configuration and task definitions
         */
        post: operations["start_job_api_jobs__job_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Details
         * @description Get detailed information about a specific job
         */
        get: operations["get_job_details_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Job
         * @description Delete a job and all its data
         */
        delete: operations["delete_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List jobs for the current user with pagination and filtering
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Progress
         * @description Get job progress information for real-time updates
         */
        get: operations["get_job_progress_api_jobs__job_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Files
         * @description Get flat list of files in a job
         */
        get: operations["get_job_files_api_jobs__job_id__files_get"];
        put?: never;
        /**
         * Add Files To Job
         * @description Add more files to an existing job
         *     Immediately extracts ZIP files via ARQ workers
         */
        post: operations["add_files_to_job_api_jobs__job_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove File From Job
         * @description Remove a file from a job (synchronous deletion for now)
         */
        delete: operations["remove_file_from_job_api_jobs__job_id__files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Job Events
         * @description Simplified Server-Sent Events stream for real-time job updates
         */
        get: operations["stream_job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Job Events
         * @description Stream real-time events for a job using Server-Sent Events
         */
        get: operations["stream_job_events_api_jobs__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/create-checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout Session
         * @description Create a Stripe checkout session
         */
        post: operations["create_checkout_session_api_stripe_create_checkout_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/create-portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Portal Session
         * @description Create a Stripe customer portal session
         */
        post: operations["create_portal_session_api_stripe_create_portal_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/subscription-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subscription Status
         * @description Get user's subscription status
         */
        get: operations["get_subscription_status_api_stripe_subscription_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Files
         * @description Upload files temporarily to server storage
         */
        post: operations["upload_files_api_extraction_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/extract-from-uploaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Data From Uploaded Files
         * @description Extract data from previously uploaded files
         */
        post: operations["extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Data From Pdfs
         * @description Extract structured data from PDF files using AI
         */
        post: operations["extract_data_from_pdfs_api_extraction_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Results To Csv
         * @description Export extraction results to CSV format
         */
        post: operations["export_results_to_csv_api_extraction_export_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Results To Excel
         * @description Export extraction results to Excel format
         */
        post: operations["export_results_to_excel_api_extraction_export_excel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/cleanup-temp-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup Temp Files
         * @description Manually trigger cleanup of old temporary files (admin endpoint - GCS lifecycle policies handle automatic cleanup)
         */
        post: operations["cleanup_temp_files_api_extraction_cleanup_temp_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/cleanup/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cleanup Uploaded File
         * @description Delete a specific uploaded file from storage and cache
         */
        delete: operations["cleanup_uploaded_file_api_extraction_cleanup__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/cleanup-multiple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cleanup Multiple Files
         * @description Delete multiple uploaded files from storage and cache
         */
        delete: operations["cleanup_multiple_files_api_extraction_cleanup_multiple_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Templates
         * @description Get user's extraction templates
         */
        get: operations["get_user_templates_api_templates__get"];
        put?: never;
        /**
         * Create Template
         * @description Create a new extraction template
         */
        post: operations["create_template_api_templates__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Get a specific template
         */
        get: operations["get_template_api_templates__template_id__get"];
        /**
         * Update Template
         * @description Update an existing template
         */
        put: operations["update_template_api_templates__template_id__put"];
        post?: never;
        /**
         * Delete Template
         * @description Delete a template
         */
        delete: operations["delete_template_api_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/public/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Templates
         * @description Get publicly available templates
         */
        get: operations["get_public_templates_api_templates_public_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Types
         * @description Get all available data types
         */
        get: operations["get_data_types_api_data_types__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_add_files_to_job_api_jobs__job_id__files_post */
        Body_add_files_to_job_api_jobs__job_id__files_post: {
            /** Files */
            files: string[];
        };
        /** Body_extract_data_from_pdfs_api_extraction_extract_post */
        Body_extract_data_from_pdfs_api_extraction_extract_post: {
            /**
             * Files
             * @description PDF files to process
             */
            files: string[];
            /**
             * Fields
             * @description JSON string of field configurations
             */
            fields: string;
            /**
             * Extract Multiple Rows
             * @description Extract multiple rows
             * @default false
             */
            extract_multiple_rows: boolean;
        };
        /** Body_extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post */
        Body_extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post: {
            /** File Ids */
            file_ids: string[];
            /** Fields */
            fields: string;
            /**
             * Extract Multiple Rows
             * @default false
             */
            extract_multiple_rows: boolean;
        };
        /** Body_upload_files_api_extraction_upload_post */
        Body_upload_files_api_extraction_upload_post: {
            /** Files */
            files: string[];
        };
        /**
         * CreateCheckoutSessionRequest
         * @description Request to create a Stripe checkout session
         */
        CreateCheckoutSessionRequest: {
            /**
             * Price Id
             * @description Stripe price ID for the subscription
             */
            price_id: string;
            /**
             * Success Url
             * Format: uri
             * @description URL to redirect to on successful payment
             */
            success_url: string;
            /**
             * Cancel Url
             * Format: uri
             * @description URL to redirect to on cancelled payment
             */
            cancel_url: string;
        };
        /**
         * CreatePortalSessionRequest
         * @description Request to create a Stripe customer portal session
         */
        CreatePortalSessionRequest: {
            /**
             * Return Url
             * Format: uri
             * @description URL to return to from the portal
             */
            return_url: string;
        };
        /**
         * DataTypeResponse
         * @description Data type response model
         */
        DataTypeResponse: {
            /** Id */
            id: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string;
            /** Base Json Type */
            base_json_type: string;
            /** Json Format */
            json_format?: string | null;
            /** Display Order */
            display_order: number;
        };
        /** ExtractionResponse */
        ExtractionResponse: {
            /** Success */
            success: boolean;
            /** Files Processed */
            files_processed: components["schemas"]["ProcessedFile"][];
            extraction_result: components["schemas"]["ExtractionResult"];
            /** Pages Used */
            pages_used: number;
            /** Total Processing Time */
            total_processing_time: number;
            /** Error */
            error?: string | null;
        };
        /** ExtractionResult */
        ExtractionResult: {
            /** Success */
            success: boolean;
            /** Data */
            data?: unknown | null;
            /** Error */
            error?: string | null;
            /** Rows Extracted */
            rows_extracted?: number | null;
            /** Ai Model */
            ai_model?: string | null;
            /** Raw Response */
            raw_response?: string | null;
            /** Processing Time */
            processing_time?: number | null;
            /** By Document */
            by_document?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** FieldConfig */
        FieldConfig: {
            /**
             * Name
             * @description Name of the field to extract
             */
            name: string;
            /**
             * Data Type
             * @description Expected data type (Text, Number, Date, etc.)
             */
            data_type: string;
            /**
             * Prompt
             * @description Instruction for AI on what to extract
             */
            prompt: string;
        };
        /**
         * FileStatus
         * @description File status enumeration
         * @enum {string}
         */
        FileStatus: "uploading" | "uploaded" | "ready" | "unpacking" | "unpacked" | "failed";
        /**
         * FileUploadInfo
         * @description Information about a file to be uploaded
         */
        FileUploadInfo: {
            /**
             * Filename
             * @description Original filename
             */
            filename: string;
            /**
             * Path
             * @description Relative path within upload structure
             */
            path: string;
            /**
             * Size
             * @description File size in bytes
             */
            size: number;
            /**
             * Type
             * @description MIME type
             */
            type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobDetailsResponse
         * @description Detailed job information
         */
        JobDetailsResponse: {
            /**
             * Id
             * @description Job identifier
             */
            id: string;
            /**
             * Name
             * @description Job name
             */
            name?: string | null;
            /** @description Current job status */
            status: components["schemas"]["JobStatus"];
            /**
             * Persist Data
             * @description Data persistence setting
             */
            persist_data: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Completed At
             * @description Completion timestamp
             */
            completed_at?: string | null;
            /**
             * Job Fields
             * @description Field configuration
             */
            job_fields: components["schemas"]["JobFieldInfo"][];
        };
        /**
         * JobFieldConfig
         * @description Field configuration for a job (snapshot from template)
         */
        JobFieldConfig: {
            /**
             * Field Name
             * @description Name of the field
             */
            field_name: string;
            /**
             * Data Type Id
             * @description Data type identifier
             */
            data_type_id: string;
            /**
             * Ai Prompt
             * @description AI extraction prompt
             */
            ai_prompt: string;
            /**
             * Display Order
             * @description Display order
             * @default 0
             */
            display_order: number;
        };
        /**
         * JobFieldInfo
         * @description Information about a job field
         */
        JobFieldInfo: {
            /**
             * Field Name
             * @description Field name
             */
            field_name: string;
            /**
             * Data Type Id
             * @description Data type
             */
            data_type_id: string;
            /**
             * Ai Prompt
             * @description AI prompt
             */
            ai_prompt: string;
            /**
             * Display Order
             * @description Display order
             */
            display_order: number;
        };
        /**
         * JobFileInfo
         * @description Information about a file in a job
         */
        JobFileInfo: {
            /**
             * Id
             * @description File identifier
             */
            id: string;
            /**
             * Original Path
             * @description Original file path
             */
            original_path: string;
            /**
             * Original Filename
             * @description Original filename
             */
            original_filename: string;
            /**
             * File Size Bytes
             * @description File size
             */
            file_size_bytes: number;
            /** @description File processing status */
            status: components["schemas"]["FileStatus"];
        };
        /**
         * JobFilesResponse
         * @description Response for job files listing
         */
        JobFilesResponse: {
            /**
             * Files
             * @description List of files in the job
             */
            files: components["schemas"]["JobFileInfo"][];
        };
        /**
         * JobInitiateRequest
         * @description Request to initiate a new job
         */
        JobInitiateRequest: {
            /**
             * Files
             * @description List of files to upload
             */
            files: components["schemas"]["FileUploadInfo"][];
            /**
             * Name
             * @description Job name
             */
            name?: string | null;
        };
        /**
         * JobInitiateResponse
         * @description Response for job initiation
         */
        JobInitiateResponse: {
            /**
             * Job Id
             * @description Unique job identifier
             */
            job_id: string;
            /**
             * Files
             * @description Upload URLs for each file
             */
            files: components["schemas"]["models__job__FileUploadResponse"][];
        };
        /**
         * JobListItem
         * @description Job list item for job listing
         */
        JobListItem: {
            /**
             * Id
             * @description Job identifier
             */
            id: string;
            /**
             * Name
             * @description Job name
             */
            name?: string | null;
            /** @description Job status */
            status: components["schemas"]["JobStatus"];
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * File Count
             * @description Number of files
             */
            file_count: number;
        };
        /**
         * JobListResponse
         * @description Response for job listing
         */
        JobListResponse: {
            /**
             * Jobs
             * @description List of jobs
             */
            jobs: components["schemas"]["JobListItem"][];
            /**
             * Total
             * @description Total number of jobs
             */
            total: number;
        };
        /**
         * JobProgressResponse
         * @description Job progress information
         */
        JobProgressResponse: {
            /**
             * Total Tasks
             * @description Total number of tasks
             */
            total_tasks: number;
            /**
             * Completed
             * @description Completed tasks
             */
            completed: number;
            /**
             * Failed
             * @description Failed tasks
             */
            failed: number;
            /** @description Overall job status */
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobStartRequest
         * @description Request to start job processing
         */
        JobStartRequest: {
            /**
             * Name
             * @description User-friendly job name
             */
            name?: string | null;
            /**
             * Template Id
             * @description Template ID to use
             */
            template_id?: string | null;
            /**
             * Persist Data
             * @description Whether to persist data
             * @default true
             */
            persist_data: boolean;
            /**
             * Fields
             * @description Field configuration
             */
            fields: components["schemas"]["JobFieldConfig"][];
            /**
             * Task Definitions
             * @description Processing definitions
             */
            task_definitions: components["schemas"]["TaskDefinition"][];
        };
        /**
         * JobStartResponse
         * @description Response for job start
         */
        JobStartResponse: {
            /**
             * Message
             * @description Success message
             */
            message: string;
            /**
             * Job Id
             * @description Job identifier
             */
            job_id: string;
        };
        /**
         * JobStatus
         * @description Job status enumeration
         * @enum {string}
         */
        JobStatus: "pending_configuration" | "processing" | "completed" | "failed" | "cancelled";
        /** ProcessedFile */
        ProcessedFile: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Num Pages */
            num_pages: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ProcessingMode
         * @description File processing mode enumeration
         * @enum {string}
         */
        ProcessingMode: "individual" | "combined";
        /**
         * SubscriptionStatus
         * @description User's subscription status information
         */
        SubscriptionStatus: {
            /** Has Subscription */
            has_subscription: boolean;
            /**
             * Plan
             * @description Plan name (free, starter, professional, enterprise)
             */
            plan: string;
            /**
             * Status
             * @description Stripe subscription status
             */
            status?: string | null;
            /**
             * Current Period End
             * @description Unix timestamp of period end
             */
            current_period_end?: number | null;
        };
        /**
         * TaskDefinition
         * @description Definition of how files should be processed
         */
        TaskDefinition: {
            /**
             * Path
             * @description Folder path to process
             */
            path: string;
            /** @description Processing mode for this path */
            mode: components["schemas"]["ProcessingMode"];
        };
        /** TemplateCreateRequest */
        TemplateCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Fields */
            fields: components["schemas"]["FieldConfig"][];
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
        };
        /** TemplateUpdateRequest */
        TemplateUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Fields */
            fields?: components["schemas"]["FieldConfig"][] | null;
            /** Is Public */
            is_public?: boolean | null;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * UploadedFileInfo
         * @description Information about an uploaded file
         */
        UploadedFileInfo: {
            /** File Id */
            file_id: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Is Zip
             * @default false
             */
            is_zip: boolean;
            /**
             * Extracted Count
             * @default 1
             */
            extracted_count: number;
            /** Upload Time */
            upload_time: number;
            /** Extracted Files */
            extracted_files?: {
                [key: string]: unknown;
            }[];
        };
        /** UserResponse */
        UserResponse: {
            /** Uid */
            uid: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserSyncRequest */
        UserSyncRequest: {
            /** Display Name */
            display_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * FileUploadResponse
         * @description Response for file upload preparation
         */
        models__job__FileUploadResponse: {
            /**
             * Original Path
             * @description Original file path
             */
            original_path: string;
            /**
             * Upload Url
             * @description Pre-signed URL for upload
             */
            upload_url: string;
        };
        /**
         * FileUploadResponse
         * @description Response from file upload endpoint
         */
        models__upload__FileUploadResponse: {
            /** Success */
            success: boolean;
            /** Uploaded Files */
            uploaded_files: components["schemas"]["UploadedFileInfo"][];
            /** Total Files */
            total_files: number;
            /** Message */
            message: string;
            /** Error */
            error?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_user_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_current_user_api_users_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_user_profile_api_users_me_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    initiate_job_api_jobs_initiate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobInitiateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInitiateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_api_jobs__job_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_details_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                /** @description Number of jobs to return */
                limit?: number;
                /** @description Number of jobs to skip */
                offset?: number;
                /** @description Filter by job status */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_progress_api_jobs__job_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobProgressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_files_api_jobs__job_id__files_get: {
        parameters: {
            query?: {
                /** @description Only return files that can be processed for data extraction (excludes ZIP files) */
                processable?: boolean;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobFilesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_files_to_job_api_jobs__job_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_files_to_job_api_jobs__job_id__files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_file_from_job_api_jobs__job_id__files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_events_api_jobs__job_id__events_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_job_events_api_jobs__job_id__stream_get: {
        parameters: {
            query: {
                /** @description Authentication token */
                token: string;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_session_api_stripe_create_checkout_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portal_session_api_stripe_create_portal_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePortalSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_status_api_stripe_subscription_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatus"];
                };
            };
        };
    };
    upload_files_api_extraction_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_files_api_extraction_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["models__upload__FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_data_from_pdfs_api_extraction_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_data_from_pdfs_api_extraction_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_results_to_csv_api_extraction_export_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_results_to_excel_api_extraction_export_excel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_temp_files_api_extraction_cleanup_temp_files_post: {
        parameters: {
            query?: {
                max_age_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_uploaded_file_api_extraction_cleanup__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_multiple_files_api_extraction_cleanup_multiple_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_templates_api_templates__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_template_api_templates__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_templates_api_templates_public_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_data_types_api_data_types__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataTypeResponse"][];
                };
            };
        };
    };
}
