/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Get current user information and create if doesn't exist
         */
        get: operations["get_current_user_api_users_me_get"];
        /**
         * Update Current User
         * @description Update current user's profile
         */
        put: operations["update_current_user_api_users_me_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Usage
         * @description Get user's usage statistics
         */
        get: operations["get_user_usage_api_users_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/create-checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout Session
         * @description Create a Stripe checkout session
         */
        post: operations["create_checkout_session_api_stripe_create_checkout_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/create-portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Portal Session
         * @description Create a Stripe customer portal session
         */
        post: operations["create_portal_session_api_stripe_create_portal_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stripe/subscription-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Subscription Status
         * @description Get user's subscription status
         */
        get: operations["get_subscription_status_api_stripe_subscription_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Files
         * @description Upload files temporarily to server storage
         */
        post: operations["upload_files_api_extraction_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/extract-from-uploaded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Data From Uploaded Files
         * @description Extract data from previously uploaded files
         */
        post: operations["extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Data From Pdfs
         * @description Extract structured data from PDF files using AI
         */
        post: operations["extract_data_from_pdfs_api_extraction_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/export/csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Results To Csv
         * @description Export extraction results to CSV format
         */
        post: operations["export_results_to_csv_api_extraction_export_csv_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/export/excel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Results To Excel
         * @description Export extraction results to Excel format
         */
        post: operations["export_results_to_excel_api_extraction_export_excel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/cleanup-temp-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cleanup Temp Files
         * @description Manually trigger cleanup of old temporary files (admin endpoint - GCS lifecycle policies handle automatic cleanup)
         */
        post: operations["cleanup_temp_files_api_extraction_cleanup_temp_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/cleanup/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cleanup Uploaded File
         * @description Delete a specific uploaded file from storage and cache
         */
        delete: operations["cleanup_uploaded_file_api_extraction_cleanup__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/extraction/cleanup-multiple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cleanup Multiple Files
         * @description Delete multiple uploaded files from storage and cache
         */
        delete: operations["cleanup_multiple_files_api_extraction_cleanup_multiple_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Templates
         * @description Get user's extraction templates
         */
        get: operations["get_user_templates_api_templates__get"];
        put?: never;
        /**
         * Create Template
         * @description Create a new extraction template
         */
        post: operations["create_template_api_templates__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Get a specific template
         */
        get: operations["get_template_api_templates__template_id__get"];
        /**
         * Update Template
         * @description Update an existing template
         */
        put: operations["update_template_api_templates__template_id__put"];
        post?: never;
        /**
         * Delete Template
         * @description Delete a template
         */
        delete: operations["delete_template_api_templates__template_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates/public/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Public Templates
         * @description Get publicly available templates
         */
        get: operations["get_public_templates_api_templates_public_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_data_from_pdfs_api_extraction_extract_post */
        Body_extract_data_from_pdfs_api_extraction_extract_post: {
            /**
             * Files
             * @description PDF files to process
             */
            files: string[];
            /**
             * Fields
             * @description JSON string of field configurations
             */
            fields: string;
            /**
             * Extract Multiple Rows
             * @description Extract multiple rows
             * @default false
             */
            extract_multiple_rows: boolean;
        };
        /** Body_extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post */
        Body_extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post: {
            /** File Ids */
            file_ids: string[];
            /** Fields */
            fields: string;
            /**
             * Extract Multiple Rows
             * @default false
             */
            extract_multiple_rows: boolean;
        };
        /** Body_upload_files_api_extraction_upload_post */
        Body_upload_files_api_extraction_upload_post: {
            /** Files */
            files: string[];
        };
        /**
         * CreateCheckoutSessionRequest
         * @description Request to create a Stripe checkout session
         */
        CreateCheckoutSessionRequest: {
            /**
             * Price Id
             * @description Stripe price ID for the subscription
             */
            price_id: string;
            /**
             * Success Url
             * Format: uri
             * @description URL to redirect to on successful payment
             */
            success_url: string;
            /**
             * Cancel Url
             * Format: uri
             * @description URL to redirect to on cancelled payment
             */
            cancel_url: string;
        };
        /**
         * CreatePortalSessionRequest
         * @description Request to create a Stripe customer portal session
         */
        CreatePortalSessionRequest: {
            /**
             * Return Url
             * Format: uri
             * @description URL to return to from the portal
             */
            return_url: string;
        };
        /** ExtractionResponse */
        ExtractionResponse: {
            /** Success */
            success: boolean;
            /** Files Processed */
            files_processed: components["schemas"]["ProcessedFile"][];
            extraction_result: components["schemas"]["ExtractionResult"];
            /** Pages Used */
            pages_used: number;
            /** Total Processing Time */
            total_processing_time: number;
            /** Error */
            error?: string | null;
        };
        /** ExtractionResult */
        ExtractionResult: {
            /** Success */
            success: boolean;
            /** Data */
            data?: unknown | null;
            /** Error */
            error?: string | null;
            /** Rows Extracted */
            rows_extracted?: number | null;
            /** Ai Model */
            ai_model?: string | null;
            /** Raw Response */
            raw_response?: string | null;
            /** Processing Time */
            processing_time?: number | null;
            /** By Document */
            by_document?: {
                [key: string]: unknown;
            }[] | null;
        };
        /** FieldConfig */
        FieldConfig: {
            /**
             * Name
             * @description Name of the field to extract
             */
            name: string;
            /**
             * Data Type
             * @description Expected data type (Text, Number, Date, etc.)
             */
            data_type: string;
            /**
             * Prompt
             * @description Instruction for AI on what to extract
             */
            prompt: string;
        };
        /**
         * FileUploadResponse
         * @description Response from file upload endpoint
         */
        FileUploadResponse: {
            /** Success */
            success: boolean;
            /** Uploaded Files */
            uploaded_files: components["schemas"]["UploadedFileInfo"][];
            /** Total Files */
            total_files: number;
            /** Message */
            message: string;
            /** Error */
            error?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProcessedFile */
        ProcessedFile: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Num Pages */
            num_pages: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SubscriptionStatus
         * @description User's subscription status information
         */
        SubscriptionStatus: {
            /** Has Subscription */
            has_subscription: boolean;
            /**
             * Plan
             * @description Plan name (free, starter, professional, enterprise)
             */
            plan: string;
            /**
             * Status
             * @description Stripe subscription status
             */
            status?: string | null;
            /**
             * Current Period End
             * @description Unix timestamp of period end
             */
            current_period_end?: number | null;
        };
        /** TemplateCreateRequest */
        TemplateCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Fields */
            fields: components["schemas"]["FieldConfig"][];
            /**
             * Is Public
             * @default false
             */
            is_public: boolean;
        };
        /** TemplateUpdateRequest */
        TemplateUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Fields */
            fields?: components["schemas"]["FieldConfig"][] | null;
            /** Is Public */
            is_public?: boolean | null;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * UploadedFileInfo
         * @description Information about an uploaded file
         */
        UploadedFileInfo: {
            /** File Id */
            file_id: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Is Zip
             * @default false
             */
            is_zip: boolean;
            /**
             * Extracted Count
             * @default 1
             */
            extracted_count: number;
            /** Upload Time */
            upload_time: number;
            /** Extracted Files */
            extracted_files?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * UsageStats
         * @description User usage statistics
         */
        UsageStats: {
            /** Pages Used */
            pages_used: number;
            /** Pages Limit */
            pages_limit: number;
            /** Subscription Status */
            subscription_status: string;
            /** Usage Percentage */
            usage_percentage: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Uid */
            uid: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Stripe Customer Id */
            stripe_customer_id?: string | null;
            /**
             * Subscription Status
             * @default free
             */
            subscription_status: string;
            /**
             * Pages Used
             * @default 0
             */
            pages_used: number;
            /**
             * Pages Limit
             * @default 10
             */
            pages_limit: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_user_api_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_current_user_api_users_me_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_usage_api_users_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageStats"];
                };
            };
        };
    };
    create_checkout_session_api_stripe_create_checkout_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portal_session_api_stripe_create_portal_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePortalSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subscription_status_api_stripe_subscription_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionStatus"];
                };
            };
        };
    };
    upload_files_api_extraction_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_files_api_extraction_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_extract_data_from_uploaded_files_api_extraction_extract_from_uploaded_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_data_from_pdfs_api_extraction_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_data_from_pdfs_api_extraction_extract_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_results_to_csv_api_extraction_export_csv_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_results_to_excel_api_extraction_export_excel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_temp_files_api_extraction_cleanup_temp_files_post: {
        parameters: {
            query?: {
                max_age_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_uploaded_file_api_extraction_cleanup__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cleanup_multiple_files_api_extraction_cleanup_multiple_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_templates_api_templates__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_template_api_templates__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_templates__template_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_public_templates_api_templates_public_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
