import type { Metadata } from 'next'

interface PageMetadata {
  title: string
  description: string
  canonical?: string
  keywords?: string[]
  openGraph?: {
    title?: string
    description?: string
    images?: Array<{
      url: string
      width: number
      height: number
      alt: string
    }>
  }
}

// Default share image: the branded card generated by app/opengraph-image.tsx,
// served at /opengraph-image (resolved against metadataBase to an absolute URL).
// A page's openGraph.openGraph object shallow-overwrites the root layout's, so the
// image must be (re)declared here rather than relying on the file-based convention.
const DEFAULT_OG_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
}

export function generateMetadata(page: PageMetadata): Metadata {
  const images = page.openGraph?.images || [
    { ...DEFAULT_OG_IMAGE, alt: page.title },
  ]

  return {
    title: page.title,
    description: page.description,
    keywords: page.keywords,
    alternates: {
      canonical: page.canonical,
    },
    openGraph: {
      title: page.openGraph?.title || page.title,
      description: page.openGraph?.description || page.description,
      url: page.canonical,
      images,
    },
    twitter: {
      card: 'summary_large_image',
      title: page.openGraph?.title || page.title,
      description: page.openGraph?.description || page.description,
      images: images.map(img => img.url),
    },
  }
}

// Page-specific metadata configurations
export const pageMetadata = {
  home: {
    title: 'CPAAutomation - The AI Platform for Accounting, Finance & Legal Professionals',
    description: 'From document intelligence to AI writing, time tracking, and autonomous agents — one AI platform built by CPAs for accounting, finance, and legal professionals.',
    canonical: 'https://cpaautomation.ai',
    keywords: [
      'CPA automation',
      'accounting AI platform',
      'AI for accountants',
      'AI for finance',
      'AI for legal',
      'document extraction',
      'AI writing',
      'time tracking',
      'AI agents',
      'legal automation',
      'accounting automation'
    ],
  },
  about: {
    title: 'About Us - Founded for Professional Use by CPAs',
    description: 'Learn about CPAAutomation\'s mission to empower accounting, finance, and legal professionals with an AI platform built by CPAs. Founded by Ian Stewart and validated by industry experts.',
    canonical: 'https://cpaautomation.ai/about',
    keywords: [
      'CPA founders',
      'accounting AI platform history',
      'Ian Stewart',
      'professional validation',
      'CPA expertise'
    ],
  },
  pricing: {
    title: 'Pricing Plans - AI Platform for Accounting Professionals',
    description: 'Choose the perfect plan for your practice. Starting with 100 free pages per month. Transparent pricing for the AI platform built for accounting, finance, and legal work.',
    canonical: 'https://cpaautomation.ai/pricing',
    keywords: [
      'CPA automation pricing',
      'accounting AI platform pricing',
      'professional plans',
      'free trial',
      'AI software pricing'
    ],
  },
  features: {
    title: 'Features - AI Tools for Accounting, Finance & Legal',
    description: 'Discover CPAAutomation\'s features: document extraction, AI writing with citations, time tracking, AI agents, custom fields, and seamless integrations. Built for professional use.',
    canonical: 'https://cpaautomation.ai/features',
    keywords: [
      'AI platform features',
      'document extraction',
      'AI writing',
      'time tracking',
      'AI agents',
      'professional integrations'
    ],
  },
  claw: {
    title: 'Claw Series - Personalized AI Digital Workers for Accounting, Finance & Legal',
    description: 'Download the AccountingClaw or LegalClaw Docker image or request personalized setup for Claw Series AI digital workers deployed on the cloud and model of your choice.',
    canonical: 'https://cpaautomation.ai/claw',
    keywords: [
      'AccountingClaw',
      'AccountingClaw Docker image',
      'FinanceClaw',
      'LegalClaw',
      'LegalClaw Docker image',
      'AI legal skills',
      'AI digital workers',
      'AI agents for accounting',
      'Hermes Agent accounting skills',
      'AI agents for legal',
      'private cloud AI deployment',
      'self-hosted AI agents'
    ],
  },
  consulting: {
    title: 'Forward-Deployed Consulting — Custom AI Builds for Accounting, Finance & Legal',
    description: 'Engineers and operators who embed with your team to build bespoke AI tools. Strong technical skills meet deep business expertise — custom AI workflows, copilots, and agents shipped end-to-end.',
    canonical: 'https://cpaautomation.ai/consulting',
    keywords: [
      'forward-deployed consulting',
      'AI consulting for accounting',
      'custom AI tools',
      'AI for finance',
      'AI for legal',
      'AI engineering services',
      'bespoke AI builds',
      'AI agent consulting',
    ],
  },
  llmGovernance: {
    title: 'LLM Governance Operating Model — Consulting for Accounting, Finance & Legal',
    description: 'An interactive briefing on the LLM governance operating model for professional firms: governance councils, decision rights, risk tiers, policy controls, approval workflows, and a deployment roadmap.',
    canonical: 'https://cpaautomation.ai/consulting/llm-governance',
    keywords: [
      'LLM governance',
      'AI governance for accounting',
      'AI governance operating model',
      'LLM risk management',
      'AI policy controls',
      'AI governance consulting',
      'LLM approval workflow',
    ],
  },
  demo: {
    title: 'Demo - Try the CPAAutomation AI Platform',
    description: 'Experience CPAAutomation\'s AI platform in action. Try document extraction, AI writing, and more — see how the platform automates your most time-consuming work.',
    canonical: 'https://cpaautomation.ai/demo',
    keywords: [
      'AI platform demo',
      'document extraction demo',
      'try CPA automation',
      'AI writing demo',
      'free trial'
    ],
  },
  contact: {
    title: 'Contact Us - Get in Touch with Our Team',
    description: 'Contact CPAAutomation for enterprise solutions, custom integrations, or technical support. We\'re here to help optimize your accounting, finance, and legal workflows.',
    canonical: 'https://cpaautomation.ai/contact',
    keywords: [
      'contact CPA automation',
      'enterprise support',
      'custom integrations',
      'technical support',
      'professional services'
    ],
  },
  caseStudyLFO: {
    title: 'Case Study: Family Office Success',
    description: 'See how a leading family office saves hundreds of hours annually processing investment statements with the CPAAutomation AI platform.',
    canonical: 'https://cpaautomation.ai/case-study/LFO',
    keywords: [
      'family office automation',
      'investment statement processing',
      'CPA case study',
      'AI platform success',
      'financial processing'
    ],
  },
  privacy: {
    title: 'Privacy Policy - Data Protection & Security',
    description: 'Learn about CPAAutomation\'s commitment to data privacy and security. Our privacy policy outlines how we protect your sensitive financial and legal documents.',
    canonical: 'https://cpaautomation.ai/privacy',
    keywords: [
      'data privacy',
      'document security',
      'CPA data protection',
      'privacy policy',
      'secure processing'
    ],
  },
  terms: {
    title: 'Terms of Service - Platform Usage Agreement',
    description: 'Review CPAAutomation\'s terms of service and usage agreement. Understand your rights and responsibilities when using our AI platform.',
    canonical: 'https://cpaautomation.ai/terms',
    keywords: [
      'terms of service',
      'usage agreement',
      'platform terms',
      'service agreement',
      'legal terms'
    ],
  },
}
