'use client'

import { Cookie, Mail } from 'lucide-react'

import { useCookieConsentContext } from '@/components/privacy/CookieConsentProvider'
import { PageHero } from '../ui'

function LegalSection({ title, children, tone }: { title: string; children: React.ReactNode; tone?: 'notice' | 'warning' }) {
  return <section className={tone ? `ps-legal-section ps-legal-section--${tone}` : 'ps-legal-section'}><h2>{title}</h2><div>{children}</div></section>
}

export function PublicPrivacy() {
  const { openPreferences } = useCookieConsentContext()
  return (
    <>
      <PageHero eyebrow="Last updated · August 2025" title="Privacy policy" description="How we protect and handle your data at CPAAutomation." actions={<button type="button" className="ps-legal-cookie" onClick={openPreferences}><Cookie />Manage cookie preferences</button>} />
      <div className="ps-legal-wrap">
        <LegalSection title="Our commitment to privacy" tone="notice"><p>At CPAAutomation, we understand that your documents contain sensitive financial and legal information. We are committed to protecting your privacy and maintaining the highest standards of data security.</p><p>This privacy policy explains how we collect, use, and protect your information when you use our document extraction services.</p></LegalSection>
        <LegalSection title="Information we collect"><h3>Document data</h3><ul><li>Files you upload for processing (opt-out option provided)</li><li>Extracted data and results from your documents</li><li>Custom extraction rules and templates</li><li>Processing metadata</li></ul><h3>Account information</h3><ul><li>Name, email, and company information</li><li>Subscription plan and billing information</li><li>Usage statistics and feature preferences</li><li>Support communication and feedback</li></ul><h3>Technical data</h3><ul><li>IP address and browser information</li><li>Device type and operating system</li><li>API usage logs and error reports</li><li>Performance and analytics data</li></ul></LegalSection>
        <LegalSection title="How we protect your data"><h3>Immediate file deletion</h3><p>Uploaded documents are automatically deleted from our processing servers immediately after extraction is complete, unless you explicitly choose to retain them.</p><h3>US-only data centers</h3><p>All data processing and storage occurs exclusively in the United States, ensuring your data remains within US jurisdiction and subject to US privacy laws.</p><h3>AES-256 encryption</h3><p>All data is encrypted using industry-standard AES-256 encryption both in transit and at rest.</p><h3>Access controls</h3><p>Strict access controls limit data access to authorized personnel only, with comprehensive audit logs of system access and activities.</p></LegalSection>
        <LegalSection title="How we use your information"><h3>Service provision</h3><p>We use your data solely to provide document extraction services, including processing your files, delivering results, and maintaining your account.</p><h3>Service improvement</h3><p>Anonymous, aggregated usage data helps us improve our AI models and service quality. No personally identifiable information is used for this purpose.</p><h3>Customer support</h3><p>We may access your account information to provide technical support, resolve issues, and respond to your inquiries.</p><h3>Legal compliance</h3><p>We may process data as required by law, regulation, or legal process, but will notify you when legally permitted to do so.</p></LegalSection>
        <LegalSection title="Data sharing and third parties" tone="warning"><h3>We do not sell your data</h3><p>CPAAutomation does not sell, rent, or trade your personal information or document data to third parties for marketing or any other commercial purposes.</p><h3>Limited third-party services</h3><p>We may use trusted third-party services for specific functions such as payment processing, email delivery, and hosting infrastructure. These providers are contractually bound to protect your data.</p><h3>Business transfers</h3><p>In the event of a merger, acquisition, or sale of assets, your information may be transferred as part of the business transaction, subject to the same privacy protections.</p></LegalSection>
        <LegalSection title="Your rights and choices"><h3>Access and portability</h3><p>You have the right to access your account data and export your extraction templates and results in a portable format at any time.</p><h3>Correction and updates</h3><p>You can update your account information, preferences, and settings through your dashboard or by contacting our support team.</p><h3>Account deletion</h3><p>You may delete your account at any time. Upon deletion, all your data will be permanently removed from our systems within 30 days.</p></LegalSection>
        <LegalSection title="Policy updates"><p>We may update this privacy policy from time to time. We will notify you of any material changes by email and by posting the updated policy on our website. Your continued use of CPAAutomation after such changes constitutes acceptance of the updated policy.</p></LegalSection>
        <LegalSection title="Questions about your privacy?"><p>If you have questions about this privacy policy or how we handle your data, please contact us.</p><p><Mail /> privacy@CPAAutomation.ai<br />United States (US-based support team)</p></LegalSection>
      </div>
    </>
  )
}

export function PublicTerms() {
  return (
    <>
      <PageHero eyebrow="Last updated · August 2025" title="Terms of service" description="Legal terms and conditions for using CPAAutomation." />
      <div className="ps-legal-wrap">
        <LegalSection title="Acceptance of terms" tone="notice"><p>By accessing or using CPAAutomation&apos;s document processing services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p><p>These terms constitute a legal agreement between you and CPAAutomation regarding your use of our platform.</p></LegalSection>
        <LegalSection title="Service description"><h3>What we provide</h3><ul><li>AI-powered document data extraction services</li><li>Custom extraction rule creation and templates</li><li>Professional-grade processing developed by CPAs and lawyers</li><li>Export capabilities to Excel, Google Sheets, and CSV formats</li><li>API access for integration with your existing systems</li><li>Customer support and technical assistance</li></ul><p><strong>Service availability:</strong> We strive to maintain 99.9% uptime but cannot guarantee uninterrupted service. Scheduled maintenance will be announced in advance when possible.</p></LegalSection>
        <LegalSection title="User responsibilities"><h3>Account security</h3><ul><li>Maintain the confidentiality of your account credentials</li><li>Notify us immediately of unauthorized account access</li><li>Use strong passwords and enable two-factor authentication</li><li>Do not share API keys or account access</li></ul><h3>Document upload requirements</h3><ul><li>Only upload documents you own or have permission to process</li><li>Ensure documents do not contain malware or malicious code</li><li>Comply with applicable laws regarding document processing</li><li>Do not upload documents containing illegal content</li></ul><h3>Acceptable use</h3><ul><li>Use the service only for legitimate business purposes</li><li>Do not attempt to reverse engineer our systems</li><li>Respect usage limits based on your subscription plan</li><li>Do not process documents for competitive analysis</li></ul></LegalSection>
        <LegalSection title="Billing and payments"><h3>Subscription plans</h3><p>Monthly subscriptions are billed in advance on the same day each month. Annual plans are billed annually in advance.</p><ul><li>Basic plan: $9.99/month for 500 pages</li><li>Professional plan: $49.99/month for 5,000 pages</li><li>Enterprise plan: custom pricing with unlimited pages and users</li></ul><h3>Payment processing</h3><p>Payments are processed securely through our payment providers. We accept major credit cards and ACH transfers for enterprise accounts.</p><h3>Refunds and cancellations</h3><p>You may cancel your subscription at any time. Cancellations take effect at the end of your current billing period. We do not provide refunds for partial months or unused pages.</p><h3>Late payments</h3><p>Accounts with failed payments may be suspended after 7 days. Service will be restored upon successful payment.</p></LegalSection>
        <LegalSection title="Intellectual property"><h3>Our rights</h3><p>CPAAutomation retains all rights to our software, algorithms, AI models, and extraction methodologies. Users receive a license to use our services but do not acquire ownership rights.</p><h3>Your rights</h3><p>You retain all rights to your uploaded documents and extracted data. We do not claim ownership of your content and will not use it for any purpose other than providing our services.</p><h3>License grant</h3><p>You grant us a limited license to process your documents solely for the purpose of providing extraction services. This license terminates when files are deleted from our systems.</p></LegalSection>
        <LegalSection title="Important disclaimers" tone="warning"><h3>Accuracy disclaimer</h3><p>While our AI extraction is designed and validated by CPAs and lawyers, we cannot guarantee 100% accuracy. Users should review and verify extracted data before using it for business decisions.</p><h3>Service availability</h3><p>We provide services on an “as is” basis and cannot guarantee uninterrupted access. Maintenance, updates, or technical issues may temporarily affect service availability.</p><h3>Limitation of liability</h3><p>Our liability is limited to the amount paid for services in the preceding 12 months. We are not liable for indirect, incidental, or consequential damages.</p></LegalSection>
        <LegalSection title="Termination"><h3>User-initiated termination</h3><p>You may terminate your account at any time through your dashboard settings or by contacting support. Upon termination, your data will be deleted within 30 days.</p><h3>Service-initiated termination</h3><p>We may suspend or terminate accounts for violation of these terms, illegal activity, or non-payment. We will provide notice when possible before termination.</p><h3>Effect of termination</h3><p>Upon termination, your access to the service will cease immediately. You may export your data before termination, as we cannot guarantee data availability afterward.</p></LegalSection>
        <LegalSection title="Governing law"><p>These Terms of Service are governed by the laws of the United States. Any disputes will be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.</p><p>If any provision of these terms is found to be unenforceable, the remaining provisions will remain in full force and effect.</p></LegalSection>
        <LegalSection title="Terms updates"><p>We may update these Terms of Service from time to time. Material changes will be communicated via email and posted on our website 30 days before taking effect. Continued use of our services after changes indicates acceptance of the updated terms.</p></LegalSection>
        <LegalSection title="Questions about these terms?"><p>If you have questions about these Terms of Service, contact legal@CPAAutomation.ai. Address: United States (US-based legal team).</p></LegalSection>
      </div>
    </>
  )
}
