"""Add the tenant-scoped FirmCRM module.

Revision ID: 079_firmcrm_module
Revises: 078_taxatlas_module
"""
from alembic import op
import sqlalchemy as sa

revision = '079_firmcrm_module'
down_revision = '078_taxatlas_module'
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firmcrm_practice_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('discipline', sa.String(length=30), nullable=False),
    sa.Column('clearance_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'name')
    )
    op.create_index(op.f('ix_firmcrm_practice_areas_firm_id'), 'firmcrm_practice_areas', ['firm_id'], unique=False)
    op.create_table('firmcrm_pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'name')
    )
    op.create_index(op.f('ix_firmcrm_pipelines_firm_id'), 'firmcrm_pipelines', ['firm_id'], unique=False)
    op.create_table('firmcrm_accounts',
    sa.Column('shared_client_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.String(length=500), nullable=True),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('entity_kind', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('revenue_band', sa.String(length=40), nullable=True),
    sa.Column('employee_band', sa.String(length=40), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('originating_partner_id', sa.String(length=128), nullable=True),
    sa.Column('referral_account_id', sa.Integer(), nullable=True),
    sa.Column('referral_contact_id', sa.Integer(), nullable=True),
    sa.Column('client_since', sa.Date(), nullable=True),
    sa.Column('risk_rating', sa.String(length=10), nullable=True),
    sa.Column('is_public_company', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['originating_partner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referral_account_id'], ['firmcrm_accounts.id'], ),
    sa.ForeignKeyConstraint(['shared_client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_client_id')
    )
    op.create_index(op.f('ix_firmcrm_accounts_is_archived'), 'firmcrm_accounts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_firmcrm_accounts_name'), 'firmcrm_accounts', ['name'], unique=False)
    op.create_index(op.f('ix_firmcrm_accounts_firm_id'), 'firmcrm_accounts', ['firm_id'], unique=False)
    op.create_table('firmcrm_ethical_walls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_id', sa.String(length=128), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deactivated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firmcrm_ix_ethical_walls_entity', 'firmcrm_ethical_walls', ['firm_id', 'entity_type', 'entity_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_firmcrm_ethical_walls_firm_id'), 'firmcrm_ethical_walls', ['firm_id'], unique=False)
    op.create_index('firmcrm_uq_active_wall', 'firmcrm_ethical_walls', ['firm_id', 'entity_type', 'entity_id'], unique=True, postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    op.create_table('firmcrm_import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('created_rows', sa.Integer(), nullable=False),
    sa.Column('updated_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmcrm_import_jobs_firm_id'), 'firmcrm_import_jobs', ['firm_id'], unique=False)
    op.create_table('firmcrm_audit_log',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmcrm_audit_log_account_id'), 'firmcrm_audit_log', ['account_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_audit_log_at'), 'firmcrm_audit_log', ['at'], unique=False)
    op.create_index(op.f('ix_firmcrm_audit_log_firm_id'), 'firmcrm_audit_log', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_audit_log_opportunity_id'), 'firmcrm_audit_log', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_audit_log_entity_type'), 'firmcrm_audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_firmcrm_audit_log_contact_id'), 'firmcrm_audit_log', ['contact_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_audit_log_entity_id'), 'firmcrm_audit_log', ['entity_id'], unique=False)
    op.create_table('firmcrm_settings',
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('access_revision', sa.Integer(), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('stale_opportunity_days', sa.Integer(), nullable=False),
    sa.Column('conflict_match_threshold', sa.Float(), nullable=False),
    sa.Column('admin_bypasses_walls', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('firm_id')
    )
    op.create_table('firmcrm_members',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_area_id'], ['firmcrm_practice_areas.id'], ),
    sa.PrimaryKeyConstraint('id', 'firm_id')
    )
    op.create_table('firmcrm_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['firmcrm_pipelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'pipeline_id', 'name')
    )
    op.create_index(op.f('ix_firmcrm_stages_firm_id'), 'firmcrm_stages', ['firm_id'], unique=False)
    op.create_table('firmcrm_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('lifecycle', sa.String(length=20), nullable=False),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['firmcrm_accounts.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firmcrm_uq_contacts_email_active', 'firmcrm_contacts', ['firm_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL AND is_archived = false'), sqlite_where=sa.text('email IS NOT NULL AND is_archived = 0'))
    op.create_index(op.f('ix_firmcrm_contacts_firm_id'), 'firmcrm_contacts', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_contacts_last_name'), 'firmcrm_contacts', ['last_name'], unique=False)
    op.create_index(op.f('ix_firmcrm_contacts_is_archived'), 'firmcrm_contacts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_firmcrm_contacts_email'), 'firmcrm_contacts', ['email'], unique=False)
    op.create_table('firmcrm_campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_area_id'], ['firmcrm_practice_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmcrm_campaigns_is_archived'), 'firmcrm_campaigns', ['is_archived'], unique=False)
    op.create_index(op.f('ix_firmcrm_campaigns_firm_id'), 'firmcrm_campaigns', ['firm_id'], unique=False)
    op.create_table('firmcrm_ethical_wall_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wall_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('added_by_id', sa.String(length=128), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wall_id'], ['firmcrm_ethical_walls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'wall_id', 'user_id')
    )
    op.create_index(op.f('ix_firmcrm_ethical_wall_members_user_id'), 'firmcrm_ethical_wall_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_ethical_wall_members_firm_id'), 'firmcrm_ethical_wall_members', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_ethical_wall_members_wall_id'), 'firmcrm_ethical_wall_members', ['wall_id'], unique=False)
    op.create_table('firmcrm_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('referral_contact_id', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('need_summary', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('unqualified_reason', sa.String(length=200), nullable=True),
    sa.Column('converted_account_id', sa.Integer(), nullable=True),
    sa.Column('converted_contact_id', sa.Integer(), nullable=True),
    sa.Column('converted_opportunity_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['firmcrm_campaigns.id'], ),
    sa.ForeignKeyConstraint(['converted_account_id'], ['firmcrm_accounts.id'], ),
    sa.ForeignKeyConstraint(['converted_contact_id'], ['firmcrm_contacts.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_area_id'], ['firmcrm_practice_areas.id'], ),
    sa.ForeignKeyConstraint(['referral_contact_id'], ['firmcrm_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmcrm_leads_firm_id'), 'firmcrm_leads', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_leads_is_archived'), 'firmcrm_leads', ['is_archived'], unique=False)
    op.create_table('firmcrm_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('primary_contact_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('originating_partner_id', sa.String(length=128), nullable=True),
    sa.Column('responsible_partner_id', sa.String(length=128), nullable=True),
    sa.Column('referral_contact_id', sa.Integer(), nullable=True),
    sa.Column('referral_account_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_close', sa.Date(), nullable=True),
    sa.Column('proposal_due', sa.Date(), nullable=True),
    sa.Column('engagement_letter_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('lost_reason', sa.String(length=60), nullable=True),
    sa.Column('competitor', sa.String(length=120), nullable=True),
    sa.Column('adverse_parties', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('next_step', sa.String(length=255), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['firmcrm_accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['firmcrm_campaigns.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['originating_partner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['firmcrm_pipelines.id'], ),
    sa.ForeignKeyConstraint(['practice_area_id'], ['firmcrm_practice_areas.id'], ),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['firmcrm_contacts.id'], ),
    sa.ForeignKeyConstraint(['referral_account_id'], ['firmcrm_accounts.id'], ),
    sa.ForeignKeyConstraint(['referral_contact_id'], ['firmcrm_contacts.id'], ),
    sa.ForeignKeyConstraint(['responsible_partner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['firmcrm_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firmcrm_ix_opportunities_status_stage', 'firmcrm_opportunities', ['status', 'stage_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_opportunities_name'), 'firmcrm_opportunities', ['name'], unique=False)
    op.create_index('firmcrm_ix_opportunities_owner_status', 'firmcrm_opportunities', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_firmcrm_opportunities_firm_id'), 'firmcrm_opportunities', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_opportunities_is_archived'), 'firmcrm_opportunities', ['is_archived'], unique=False)
    op.create_table('firmcrm_campaign_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['firmcrm_campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['firmcrm_contacts.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firm_id', 'campaign_id', 'contact_id')
    )
    op.create_index(op.f('ix_firmcrm_campaign_members_firm_id'), 'firmcrm_campaign_members', ['firm_id'], unique=False)
    op.create_table('firmcrm_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.String(length=128), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('days_in_previous', sa.Float(), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['firmcrm_stages.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['firmcrm_opportunities.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['firmcrm_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmcrm_stage_history_firm_id'), 'firmcrm_stage_history', ['firm_id'], unique=False)
    op.create_table('firmcrm_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['firmcrm_accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['firmcrm_contacts.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['firmcrm_leads.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['firmcrm_opportunities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmcrm_activities_lead_id'), 'firmcrm_activities', ['lead_id'], unique=False)
    op.create_index('firmcrm_ix_activities_owner_kind_completed', 'firmcrm_activities', ['owner_id', 'kind', 'completed_at'], unique=False)
    op.create_index(op.f('ix_firmcrm_activities_contact_id'), 'firmcrm_activities', ['contact_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_activities_firm_id'), 'firmcrm_activities', ['firm_id'], unique=False)
    op.create_index('firmcrm_ix_activities_occurred', 'firmcrm_activities', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_firmcrm_activities_opportunity_id'), 'firmcrm_activities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_activities_account_id'), 'firmcrm_activities', ['account_id'], unique=False)
    op.create_table('firmcrm_conflict_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=20), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.String(length=128), nullable=True),
    sa.Column('parties', sa.JSON(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('independence_attestation', sa.JSON(), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['firmcrm_accounts.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['firmcrm_opportunities.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmcrm_conflict_checks_account_id'), 'firmcrm_conflict_checks', ['account_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_conflict_checks_firm_id'), 'firmcrm_conflict_checks', ['firm_id'], unique=False)
    op.create_index(op.f('ix_firmcrm_conflict_checks_opportunity_id'), 'firmcrm_conflict_checks', ['opportunity_id'], unique=False)
    op.create_table('firmcrm_engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('responsible_partner_id', sa.String(length=128), nullable=True),
    sa.Column('originating_partner_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('annual_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('adverse_parties', sa.JSON(), nullable=True),
    sa.Column('external_ref', sa.String(length=80), nullable=True),
    sa.Column('firm_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['firmcrm_accounts.id'], ),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['firmcrm_opportunities.id'], ),
    sa.ForeignKeyConstraint(['originating_partner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['practice_area_id'], ['firmcrm_practice_areas.id'], ),
    sa.ForeignKeyConstraint(['responsible_partner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmcrm_engagements_firm_id'), 'firmcrm_engagements', ['firm_id'], unique=False)
    op.create_index('firmcrm_uq_engagements_opportunity', 'firmcrm_engagements', ['firm_id', 'opportunity_id'], unique=True)
    op.create_foreign_key('firmcrm_fk_leads_converted_opportunity_id_opportunities', 'firmcrm_leads', 'firmcrm_opportunities', ['converted_opportunity_id'], ['id'], use_alter=True)
    op.create_foreign_key('firmcrm_fk_accounts_referral_contact_id_contacts', 'firmcrm_accounts', 'firmcrm_contacts', ['referral_contact_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('firmcrm_fk_accounts_referral_contact_id_contacts', 'firmcrm_accounts', type_='foreignkey')
    op.drop_constraint('firmcrm_fk_leads_converted_opportunity_id_opportunities', 'firmcrm_leads', type_='foreignkey')
    op.drop_index('firmcrm_uq_engagements_opportunity', table_name='firmcrm_engagements')
    op.drop_index(op.f('ix_firmcrm_engagements_firm_id'), table_name='firmcrm_engagements')
    op.drop_table('firmcrm_engagements')
    op.drop_index(op.f('ix_firmcrm_conflict_checks_opportunity_id'), table_name='firmcrm_conflict_checks')
    op.drop_index(op.f('ix_firmcrm_conflict_checks_firm_id'), table_name='firmcrm_conflict_checks')
    op.drop_index(op.f('ix_firmcrm_conflict_checks_account_id'), table_name='firmcrm_conflict_checks')
    op.drop_table('firmcrm_conflict_checks')
    op.drop_index(op.f('ix_firmcrm_activities_account_id'), table_name='firmcrm_activities')
    op.drop_index(op.f('ix_firmcrm_activities_opportunity_id'), table_name='firmcrm_activities')
    op.drop_index('firmcrm_ix_activities_occurred', table_name='firmcrm_activities')
    op.drop_index(op.f('ix_firmcrm_activities_firm_id'), table_name='firmcrm_activities')
    op.drop_index(op.f('ix_firmcrm_activities_contact_id'), table_name='firmcrm_activities')
    op.drop_index('firmcrm_ix_activities_owner_kind_completed', table_name='firmcrm_activities')
    op.drop_index(op.f('ix_firmcrm_activities_lead_id'), table_name='firmcrm_activities')
    op.drop_table('firmcrm_activities')
    op.drop_index(op.f('ix_firmcrm_stage_history_firm_id'), table_name='firmcrm_stage_history')
    op.drop_table('firmcrm_stage_history')
    op.drop_index(op.f('ix_firmcrm_campaign_members_firm_id'), table_name='firmcrm_campaign_members')
    op.drop_table('firmcrm_campaign_members')
    op.drop_index(op.f('ix_firmcrm_opportunities_is_archived'), table_name='firmcrm_opportunities')
    op.drop_index(op.f('ix_firmcrm_opportunities_firm_id'), table_name='firmcrm_opportunities')
    op.drop_index('firmcrm_ix_opportunities_owner_status', table_name='firmcrm_opportunities')
    op.drop_index(op.f('ix_firmcrm_opportunities_name'), table_name='firmcrm_opportunities')
    op.drop_index('firmcrm_ix_opportunities_status_stage', table_name='firmcrm_opportunities')
    op.drop_table('firmcrm_opportunities')
    op.drop_index(op.f('ix_firmcrm_leads_is_archived'), table_name='firmcrm_leads')
    op.drop_index(op.f('ix_firmcrm_leads_firm_id'), table_name='firmcrm_leads')
    op.drop_table('firmcrm_leads')
    op.drop_index(op.f('ix_firmcrm_ethical_wall_members_wall_id'), table_name='firmcrm_ethical_wall_members')
    op.drop_index(op.f('ix_firmcrm_ethical_wall_members_firm_id'), table_name='firmcrm_ethical_wall_members')
    op.drop_index(op.f('ix_firmcrm_ethical_wall_members_user_id'), table_name='firmcrm_ethical_wall_members')
    op.drop_table('firmcrm_ethical_wall_members')
    op.drop_index(op.f('ix_firmcrm_campaigns_firm_id'), table_name='firmcrm_campaigns')
    op.drop_index(op.f('ix_firmcrm_campaigns_is_archived'), table_name='firmcrm_campaigns')
    op.drop_table('firmcrm_campaigns')
    op.drop_index(op.f('ix_firmcrm_contacts_email'), table_name='firmcrm_contacts')
    op.drop_index(op.f('ix_firmcrm_contacts_is_archived'), table_name='firmcrm_contacts')
    op.drop_index(op.f('ix_firmcrm_contacts_last_name'), table_name='firmcrm_contacts')
    op.drop_index(op.f('ix_firmcrm_contacts_firm_id'), table_name='firmcrm_contacts')
    op.drop_index('firmcrm_uq_contacts_email_active', table_name='firmcrm_contacts', postgresql_where=sa.text('email IS NOT NULL AND is_archived = false'), sqlite_where=sa.text('email IS NOT NULL AND is_archived = 0'))
    op.drop_table('firmcrm_contacts')
    op.drop_index(op.f('ix_firmcrm_stages_firm_id'), table_name='firmcrm_stages')
    op.drop_table('firmcrm_stages')
    op.drop_table('firmcrm_members')
    op.drop_table('firmcrm_settings')
    op.drop_index(op.f('ix_firmcrm_audit_log_entity_id'), table_name='firmcrm_audit_log')
    op.drop_index(op.f('ix_firmcrm_audit_log_contact_id'), table_name='firmcrm_audit_log')
    op.drop_index(op.f('ix_firmcrm_audit_log_entity_type'), table_name='firmcrm_audit_log')
    op.drop_index(op.f('ix_firmcrm_audit_log_opportunity_id'), table_name='firmcrm_audit_log')
    op.drop_index(op.f('ix_firmcrm_audit_log_firm_id'), table_name='firmcrm_audit_log')
    op.drop_index(op.f('ix_firmcrm_audit_log_at'), table_name='firmcrm_audit_log')
    op.drop_index(op.f('ix_firmcrm_audit_log_account_id'), table_name='firmcrm_audit_log')
    op.drop_table('firmcrm_audit_log')
    op.drop_index(op.f('ix_firmcrm_import_jobs_firm_id'), table_name='firmcrm_import_jobs')
    op.drop_table('firmcrm_import_jobs')
    op.drop_index('firmcrm_uq_active_wall', table_name='firmcrm_ethical_walls', postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    op.drop_index(op.f('ix_firmcrm_ethical_walls_firm_id'), table_name='firmcrm_ethical_walls')
    op.drop_index('firmcrm_ix_ethical_walls_entity', table_name='firmcrm_ethical_walls')
    op.drop_table('firmcrm_ethical_walls')
    op.drop_index(op.f('ix_firmcrm_accounts_firm_id'), table_name='firmcrm_accounts')
    op.drop_index(op.f('ix_firmcrm_accounts_name'), table_name='firmcrm_accounts')
    op.drop_index(op.f('ix_firmcrm_accounts_is_archived'), table_name='firmcrm_accounts')
    op.drop_table('firmcrm_accounts')
    op.drop_index(op.f('ix_firmcrm_pipelines_firm_id'), table_name='firmcrm_pipelines')
    op.drop_table('firmcrm_pipelines')
    op.drop_index(op.f('ix_firmcrm_practice_areas_firm_id'), table_name='firmcrm_practice_areas')
    op.drop_table('firmcrm_practice_areas')
    # ### end Alembic commands ###
