"""Add is_public and description to templates

Revision ID: b1626becc820
Revises: 
Create Date: 2025-07-22 14:50:21.214648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1626becc820'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('templates', sa.Column('is_public', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('templates', 'user_id', nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'user_id', nullable=False)
    op.drop_column('templates', 'is_public')
    op.drop_column('templates', 'description')
    # ### end Alembic commands ###
