"""remove_job_runs_update_relationships

Revision ID: d1988184ff7e
Revises: 21606085958e
Create Date: 2025-07-31 14:18:17.799474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1988184ff7e'
down_revision: Union[str, Sequence[str], None] = '21606085958e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Since we're deleting all existing jobs, we can safely drop and recreate these tables
    
    # Drop automation_runs and job_exports tables (they'll be recreated with correct structure)
    op.drop_table('automation_runs')
    op.drop_table('job_exports')
    op.drop_table('job_runs')
    
    # Recreate job_exports with correct foreign key to extraction_jobs
    op.create_table('job_exports',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('job_id', sa.UUID(), nullable=False),
        sa.Column('dest_type', sa.String(length=15), nullable=False),
        sa.Column('file_type', sa.String(length=10), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('external_id', sa.Text(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("dest_type IN ('download', 'gdrive', 'gmail')", name='check_dest_type'),
        sa.CheckConstraint("file_type IN ('csv', 'xlsx')", name='check_file_type'),
        sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Recreate automation_runs with correct foreign key to extraction_jobs
    op.create_table('automation_runs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('automation_id', sa.UUID(), nullable=False),
        sa.Column('job_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Drop old indexes that are no longer needed
    op.drop_index(op.f('idx_extraction_jobs_cleanup'), table_name='extraction_jobs', postgresql_where="((status)::text <> 'cancelled'::text)")
    op.drop_index(op.f('idx_extraction_jobs_config_step'), table_name='extraction_jobs')
    op.drop_index(op.f('idx_extraction_jobs_resumable'), table_name='extraction_jobs', postgresql_where="(((config_step)::text <> 'submitted'::text) OR ((status)::text = ANY ((ARRAY['in_progress'::character varying, 'partially_completed'::character varying, 'failed'::character varying])::text[])))")
    op.drop_index(op.f('idx_extraction_jobs_user_status_activity'), table_name='extraction_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_exports', sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_exports', type_='foreignkey')
    op.create_foreign_key(op.f('job_exports_run_id_fkey'), 'job_exports', 'job_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_column('job_exports', 'job_id')
    op.create_index(op.f('idx_extraction_jobs_user_status_activity'), 'extraction_jobs', ['user_id', 'status', sa.literal_column('last_active_at DESC')], unique=False)
    op.create_index(op.f('idx_extraction_jobs_resumable'), 'extraction_jobs', ['user_id', 'config_step', 'status'], unique=False, postgresql_where="(((config_step)::text <> 'submitted'::text) OR ((status)::text = ANY ((ARRAY['in_progress'::character varying, 'partially_completed'::character varying, 'failed'::character varying])::text[])))")
    op.create_index(op.f('idx_extraction_jobs_config_step'), 'extraction_jobs', ['config_step'], unique=False)
    op.create_index(op.f('idx_extraction_jobs_cleanup'), 'extraction_jobs', ['last_active_at', 'status', 'persist_data'], unique=False, postgresql_where="((status)::text <> 'cancelled'::text)")
    op.add_column('automation_runs', sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'automation_runs', type_='foreignkey')
    op.create_foreign_key(op.f('automation_runs_run_id_fkey'), 'automation_runs', 'job_runs', ['run_id'], ['id'], ondelete='CASCADE')
    op.drop_column('automation_runs', 'job_id')
    op.create_table('job_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tasks_total', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tasks_completed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tasks_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], name=op.f('job_runs_job_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('job_runs_pkey'))
    )
    # ### end Alembic commands ###
