import Image from 'next/image'
import Link from 'next/link'

import { generateMetadata, pageMetadata } from '@/lib/metadata'

export const metadata = generateMetadata(pageMetadata.about)

export default function AboutPage() {
  return <main id="main-content">
    <section className="ps-page-hero"><div className="ps-container ps-page-hero__split"><div><span className="ps-label">About us</span><h1>Document AI, engineered from real CPA workflows</h1></div><p className="ps-kicker">Truly customizable document AI built by professionals who live inside these documents every day.</p></div></section>
    <section className="ps-section"><div className="ps-container ps-portrait-grid"><Image className="ps-portrait" src="/ian.jpg" width={720} height={900} alt="Ian Stewart, Founder of CPAAutomation" priority /><div><span className="ps-label">Founder & engineer</span><h2>Ian Stewart</h2><p className="ps-kicker">Incoming First-Year at University of California, Berkeley</p><p>CPAAutomation.ai started with a simple question: why are CPAs still buried in repetitive, manual tasks when technology can assist?</p><p>For me, this mission is personal. I grew up watching my mom work long hours as a CPA, juggling endless paperwork that kept her from focusing on the parts of the job that truly mattered: serving clients and solving problems.</p><p>I combined my passion for coding with this firsthand perspective. The result was CPAAutomation.ai: a platform built to streamline workflows, reduce busywork, and give CPAs back their time.</p><p>What began as a personal project has grown into a bigger vision: empowering accountants everywhere to work smarter, not harder.</p></div></div></section>
    <section className="ps-section ps-section--muted"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">Validation</span><h2>Vetted by industry experts</h2></div><p>Senior practitioners across accounting and finance pressure-tested our extraction against the documents they work with every day.</p></div><div className="ps-profiles"><article className="ps-profile"><Image src="/rae.jpg" width={180} height={210} alt="Rae Stewart" /><div><h3>Rae Stewart</h3><p>Senior Director, Accounting · Kaiser Permanente</p><blockquote>“Provided extensive validation of our extraction algorithms for healthcare industry financial documents and compliance requirements.”</blockquote></div></article><article className="ps-profile"><Image src="/ray.jpg" width={180} height={210} alt="Ray Sang" /><div><h3>Ray Sang</h3><p>Finance Systems · Plaid, Inc.</p><blockquote>“Validated our platform&apos;s ability to handle complex technology sector financial processes and automation workflows.”</blockquote></div></article></div></div></section>
    <section className="ps-section ps-dark ps-grid-bg"><div className="ps-container ps-showcase"><div><span className="ps-label">Our mission</span><h2>Bridging documents and modern AI</h2><p className="ps-kicker">Extraction accuracy that meets the rigorous standards of accounting and legal workflows.</p></div><div><p>CPAAutomation was created to bridge the gap between traditional document processing and modern AI capabilities. We understand that financial and legal professionals need extraction tools that truly comprehend the nuances of their documents.</p><p>Our platform combines deep domain expertise from certified professionals with cutting-edge AI technology to deliver extraction accuracy that meets the rigorous standards of accounting and legal workflows.</p></div></div></section>
    <section className="ps-section"><div className="ps-container"><div className="ps-section-head"><div><h2>Built by professionals, for professionals</h2></div></div><div className="ps-card-grid"><article className="ps-info-card"><span className="ps-label">CPA expertise</span><h3>Built for the work</h3><p>Our extraction algorithms are developed and validated by certified public accountants who understand the complexities of financial document processing and compliance requirements.</p></article><article className="ps-info-card"><span className="ps-label">Legal validation</span><h3>Validated for precision</h3><p>Licensed attorneys contribute to our extraction rule development, ensuring that our AI understands legal document structures and meets professional standards for data accuracy.</p></article></div></div></section>
    <section className="ps-section ps-section--muted"><div className="ps-container"><div className="ps-section-head"><div><span className="ps-label">What we stand for</span><h2>Our values</h2></div></div><div className="ps-card-grid">{[['Professional accuracy','Every extraction rule is designed and tested by professionals who use these documents daily in their practice.'],['Data security','We prioritize your data security with immediate file deletion post-processing and US-only server hosting.'],['Customizable flexibility','While our base rules are professionally designed, users can create custom prompts for maximum flexibility.'],['Enterprise ready','Built to scale with dedicated US-based support and custom integrations for enterprise workflows.']].map(([a,b],i)=><article className="ps-info-card" key={a}><span className="ps-label">0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>
    <section className="ps-cta"><div className="ps-container ps-cta__inner"><div><span className="ps-label">Get in touch</span><h2>Questions about our platform?</h2><p>Connect with our team to learn more about how CPAAutomation can transform your document processing workflow.</p></div><div className="ps-button-row"><Link className="ps-button ps-button--light" href="/contact">Contact us</Link><Link className="ps-button ps-button--outline" href="/demo">View demo</Link></div></div></section>
  </main>
}
