'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import {
  BrainCircuit,
  GripVertical,
  Loader2,
  Plus,
  Play,
  Sparkles,
  Trash2,
  Wand2,
  X,
  Zap,
} from 'lucide-react'
import {
  DndContext,
  PointerSensor,
  closestCenter,
  useDraggable,
  useDroppable,
  useSensor,
  useSensors,
  type DragEndEvent,
} from '@dnd-kit/core'
import {
  SortableContext,
  arrayMove,
  useSortable,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Textarea } from '@/components/ui/textarea'
import {
  useGenerateAdditionalReconciliationPass,
  useGenerateReconciliationRules,
  usePerformReconciliationMatch,
  useReconcileBasic,
  useUpdateAnalyticsReconciliation,
} from '@/hooks/useAnalyticsReconciliation'
import { useToast } from '@/hooks/use-toast'
import { cn } from '@/lib/utils'
import {
  buildAvailableRules,
  type AvailableRuleCategory,
  type MatchGroupType,
  type ReconciliationMatchGroup,
  type ReconciliationPass,
  type ReconciliationRule,
  type ReconciliationTransaction,
  type UnmatchedException,
} from '@/lib/analytics/reconciliationTypes'
import {
  INITIAL_GROUPS,
  INITIAL_SOURCE_A,
  INITIAL_SOURCE_B,
} from '@/lib/analytics/mockReconData'

const MATCH_TYPES: MatchGroupType[] = ['1:1', '1:Many', 'Many:1', 'Many:Many']

const LIBRARY_PREFIX = 'library::'
const RULE_PREFIX = 'rule::'
const PASS_DROP_PREFIX = 'pass-drop::'

interface ReconciliationRulesStepProps {
  reconciliationId: string
  sourceA: ReconciliationTransaction[]
  sourceB: ReconciliationTransaction[]
  rules: ReconciliationPass[]
  onComplete: () => void
  locked?: boolean
}

function newId(prefix: string) {
  const rand =
    typeof crypto !== 'undefined' && 'randomUUID' in crypto
      ? crypto.randomUUID()
      : Math.random().toString(36).slice(2)
  return `${prefix}-${rand}`
}

export function ReconciliationRulesStep({
  reconciliationId,
  sourceA,
  sourceB,
  rules,
  onComplete,
  locked = false,
}: ReconciliationRulesStepProps) {
  const { toast } = useToast()
  const [passes, setPasses] = useState<ReconciliationPass[]>(rules)
  const [refineText, setRefineText] = useState('')

  useEffect(() => {
    setPasses(rules)
  }, [rules])

  const availableRules = useMemo(
    () => buildAvailableRules(sourceA, sourceB),
    [sourceA, sourceB],
  )
  const headers = useMemo(
    () => Array.from(new Set(availableRules.map((c) => c.category))),
    [availableRules],
  )
  const allRuleTypes = useMemo(
    () => Array.from(new Set(availableRules.flatMap((c) => c.rules))),
    [availableRules],
  )

  const generateMutation = useGenerateReconciliationRules()
  const additionalMutation = useGenerateAdditionalReconciliationPass()
  const matchMutation = usePerformReconciliationMatch()
  const basicMutation = useReconcileBasic()
  const updateMutation = useUpdateAnalyticsReconciliation()

  const autoGenerated = passes.length > 0
  const isBusy =
    generateMutation.isPending ||
    additionalMutation.isPending ||
    matchMutation.isPending ||
    basicMutation.isPending ||
    updateMutation.isPending

  // Synthetic AI Match progress — backend doesn't stream pass progress, so we
  // animate currentPass from 1 → N-1 while the request is in flight and snap
  // to N when it resolves.
  const totalPasses = Math.max(passes.length, 1)
  const [matchProgress, setMatchProgress] = useState(0)
  useEffect(() => {
    if (!matchMutation.isPending) {
      setMatchProgress(0)
      return
    }
    setMatchProgress(1)
    const intervalMs = 800
    const id = setInterval(() => {
      setMatchProgress((p) => (p < totalPasses - 1 ? p + 1 : p))
    }, intervalMs)
    return () => clearInterval(id)
  }, [matchMutation.isPending, totalPasses])

  useEffect(() => {
    // Auto-generate the initial pass set when the user lands here with no rules.
    if (
      passes.length === 0 &&
      headers.length > 0 &&
      !generateMutation.isPending &&
      !autoGenerated &&
      !locked
    ) {
      void handleGenerate()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const persistPasses = async (next: ReconciliationPass[]) => {
    await updateMutation.mutateAsync({
      reconciliationId,
      data: { rules: next as unknown as Record<string, unknown>[] },
    })
  }

  const updatePass = (passId: string, updates: Partial<ReconciliationPass>) => {
    const next = passes.map((p) => (p.id === passId ? { ...p, ...updates } : p))
    setPasses(next)
    void persistPasses(next)
  }

  const togglePassMatchType = (passId: string, type: MatchGroupType) => {
    const pass = passes.find((p) => p.id === passId)
    if (!pass) return
    const has = (pass.matchTypes ?? []).includes(type)
    const matchTypes = has
      ? (pass.matchTypes ?? []).filter((t) => t !== type)
      : [...(pass.matchTypes ?? []), type]
    updatePass(passId, { matchTypes })
  }

  const updateRule = (
    passId: string,
    ruleId: string,
    updates: Partial<ReconciliationRule>,
  ) => {
    const next = passes.map((p) =>
      p.id === passId
        ? { ...p, rules: p.rules.map((r) => (r.id === ruleId ? { ...r, ...updates } : r)) }
        : p,
    )
    setPasses(next)
    void persistPasses(next)
  }

  const removeRule = (passId: string, ruleId: string) => {
    const next = passes.map((p) =>
      p.id === passId ? { ...p, rules: p.rules.filter((r) => r.id !== ruleId) } : p,
    )
    setPasses(next)
    void persistPasses(next)
  }

  const appendRuleFromLibrary = (passId: string, ruleType: string) => {
    const next = passes.map((p) =>
      p.id === passId
        ? {
            ...p,
            rules: [...p.rules, { id: newId('rule'), type: ruleType, config: {} }],
          }
        : p,
    )
    setPasses(next)
    void persistPasses(next)
  }

  const reorderRulesInPass = (passId: string, fromId: string, toId: string) => {
    const pass = passes.find((p) => p.id === passId)
    if (!pass) return
    const fromIdx = pass.rules.findIndex((r) => r.id === fromId)
    const toIdx = pass.rules.findIndex((r) => r.id === toId)
    if (fromIdx === -1 || toIdx === -1 || fromIdx === toIdx) return
    const reordered = arrayMove(pass.rules, fromIdx, toIdx)
    const next = passes.map((p) => (p.id === passId ? { ...p, rules: reordered } : p))
    setPasses(next)
    void persistPasses(next)
  }

  const addEmptyPass = () => {
    const next: ReconciliationPass[] = [
      ...passes,
      {
        id: newId('pass'),
        name: `Pass ${passes.length + 1}`,
        matchTypes: ['1:1'],
        rules: [],
        logic: 'AND',
      },
    ]
    setPasses(next)
    void persistPasses(next)
  }

  const handleGenerate = async () => {
    try {
      const result = await generateMutation.mutateAsync({
        headers,
        availableRules: availableRules as unknown as Record<string, unknown>,
      })
      const incoming = ((result.passes ?? []) as unknown as ReconciliationPass[]) ?? []
      // Make sure every pass and rule has an id — the LLM often omits them.
      const stamped = incoming.map((p) => ({
        ...p,
        id: p.id ?? newId('pass'),
        rules: (p.rules ?? []).map((r) => ({ ...r, id: r.id ?? newId('rule') })),
      }))
      setPasses(stamped)
      await persistPasses(stamped)
      toast({
        title: 'Rules generated',
        description: `${stamped.length} matching pass${stamped.length === 1 ? '' : 'es'} created.`,
      })
    } catch (error) {
      toast({
        title: 'Rule generation failed',
        description: error instanceof Error ? error.message : 'Try again.',
        variant: 'destructive',
      })
    }
  }

  const handleRefine = async () => {
    if (!refineText.trim()) {
      toast({ title: 'Add instructions first', description: 'Describe the pass to add.' })
      return
    }
    try {
      const result = await additionalMutation.mutateAsync({
        instructions: refineText.trim(),
        availableRules: availableRules as unknown as Record<string, unknown>,
      })
      const incoming = (result.pass ?? null) as unknown as ReconciliationPass | null
      if (!incoming) {
        toast({ title: 'No pass returned', variant: 'destructive' })
        return
      }
      const pass: ReconciliationPass = {
        ...incoming,
        id: incoming.id ?? newId('pass'),
        rules: (incoming.rules ?? []).map((r) => ({ ...r, id: r.id ?? newId('rule') })),
      }
      const next = [...passes, pass]
      setPasses(next)
      await persistPasses(next)
      setRefineText('')
      toast({ title: 'Pass added', description: pass.name })
    } catch (error) {
      toast({
        title: 'Refine failed',
        description: error instanceof Error ? error.message : 'Try again.',
        variant: 'destructive',
      })
    }
  }

  const handleRemovePass = async (passId: string) => {
    const next = passes.filter((p) => p.id !== passId)
    setPasses(next)
    await persistPasses(next)
  }

  // The AI Assistant emits `ai-add-recon-pass` when the model decides a new
  // matching pass is warranted (via `[ACTION:ADD_RECON_PASS:<instruction>]`).
  const passesRef = useRef(passes)
  const availableRulesRef = useRef(availableRules)
  useEffect(() => {
    passesRef.current = passes
  }, [passes])
  useEffect(() => {
    availableRulesRef.current = availableRules
  }, [availableRules])

  useEffect(() => {
    const handler = (event: Event) => {
      const detail = (event as CustomEvent).detail as { instruction?: string } | undefined
      const instruction = detail?.instruction?.trim()
      if (!instruction) return
      void (async () => {
        try {
          const result = await additionalMutation.mutateAsync({
            instructions: instruction,
            availableRules: availableRulesRef.current as unknown as Record<string, unknown>,
          })
          const incoming = (result.pass ?? null) as unknown as ReconciliationPass | null
          if (!incoming) {
            toast({ title: 'AI returned no pass', variant: 'destructive' })
            return
          }
          const pass: ReconciliationPass = {
            ...incoming,
            id: incoming.id ?? newId('pass'),
            rules: (incoming.rules ?? []).map((r) => ({ ...r, id: r.id ?? newId('rule') })),
          }
          const next = [...passesRef.current, pass]
          setPasses(next)
          await persistPasses(next)
          toast({ title: 'AI added a matching pass', description: pass.name })
        } catch (error) {
          toast({
            title: 'AI pass suggestion failed',
            description: error instanceof Error ? error.message : 'Try again.',
            variant: 'destructive',
          })
        }
      })()
    }
    window.addEventListener('ai-add-recon-pass', handler)
    return () => window.removeEventListener('ai-add-recon-pass', handler)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const applyMatchResult = async (
    matchGroups: ReconciliationMatchGroup[],
    unmatchedExceptions: UnmatchedException[] = [],
  ) => {
    const matchedAIds = new Set<string>()
    const matchedBIds = new Set<string>()
    for (const g of matchGroups) {
      for (const id of g.sourceAIds ?? []) matchedAIds.add(id)
      for (const id of g.sourceBIds ?? []) matchedBIds.add(id)
    }

    const exceptionsById = new Map<string, UnmatchedException>()
    for (const ex of unmatchedExceptions) exceptionsById.set(ex.id, ex)

    const stamp = (t: ReconciliationTransaction): ReconciliationTransaction => {
      const isMatched = (t.source === 'A' ? matchedAIds : matchedBIds).has(t.id)
      const ex = exceptionsById.get(t.id)
      return {
        ...t,
        status: isMatched ? 'matched' : 'unmatched',
        matchGroupId: isMatched
          ? matchGroups.find((g) =>
              (t.source === 'A' ? g.sourceAIds : g.sourceBIds)?.includes(t.id),
            )?.id
          : undefined,
        exceptionCategory: !isMatched ? ex?.exceptionCategory : undefined,
        exceptionReasoning: !isMatched ? ex?.exceptionReasoning : undefined,
      }
    }

    const nextA = sourceA.map(stamp)
    const nextB = sourceB.map(stamp)

    await updateMutation.mutateAsync({
      reconciliationId,
      data: {
        source_a: nextA as unknown as Record<string, unknown>[],
        source_b: nextB as unknown as Record<string, unknown>[],
        match_groups: matchGroups as unknown as Record<string, unknown>[],
      },
    })
  }

  const handleRunMatch = async () => {
    if (passes.length === 0) {
      toast({ title: 'Generate rules first', description: 'No passes to apply.' })
      return
    }
    try {
      const result = await matchMutation.mutateAsync({
        sourceA: sourceA as unknown as Record<string, unknown>[],
        sourceB: sourceB as unknown as Record<string, unknown>[],
        rules: passes as unknown as Record<string, unknown>[],
      })
      const groups = (result.matchGroups ?? []) as unknown as ReconciliationMatchGroup[]
      const exceptions = (result.unmatchedExceptions ?? []) as unknown as UnmatchedException[]
      await applyMatchResult(groups, exceptions)
      toast({
        title: 'Match complete',
        description: `${groups.length} match group${groups.length === 1 ? '' : 's'} created.`,
      })
      onComplete()
    } catch (error) {
      // Demo fallback: when the live Gemini match call fails (no API key, blocked
      // content, network, etc.), replace the reconciliation's sources and groups
      // with the bundled sample data so the user still lands on a usable Results
      // step. Mirrors CPAAnalytics' Reconciliation.tsx behavior.
      try {
        await updateMutation.mutateAsync({
          reconciliationId,
          data: {
            source_a: INITIAL_SOURCE_A as unknown as Record<string, unknown>[],
            source_b: INITIAL_SOURCE_B as unknown as Record<string, unknown>[],
            match_groups: INITIAL_GROUPS as unknown as Record<string, unknown>[],
          },
        })
        toast({
          title: 'Live match unavailable — loaded sample reconciliation',
          description: error instanceof Error ? error.message : 'Showing demo data.',
        })
        onComplete()
      } catch (fallbackError) {
        toast({
          title: 'Match failed',
          description:
            fallbackError instanceof Error
              ? fallbackError.message
              : error instanceof Error
                ? error.message
                : 'Try again.',
          variant: 'destructive',
        })
      }
    }
  }

  const handleRunBasic = async () => {
    try {
      const result = await basicMutation.mutateAsync({
        sourceA: sourceA as unknown as Record<string, unknown>[],
        sourceB: sourceB as unknown as Record<string, unknown>[],
      })
      const groups = (result.matchGroups ?? []) as unknown as ReconciliationMatchGroup[]
      const exceptions = (result.unmatchedExceptions ?? []) as unknown as UnmatchedException[]
      await applyMatchResult(groups, exceptions)
      toast({
        title: 'Basic reconciliation complete',
        description: `${groups.length} match group${groups.length === 1 ? '' : 's'} created.`,
      })
      onComplete()
    } catch (error) {
      toast({
        title: 'Basic match failed',
        description: error instanceof Error ? error.message : 'Try again.',
        variant: 'destructive',
      })
    }
  }

  // dnd-kit ---------------------------------------------------------------
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 6 } }),
  )

  const findPassForOverId = (overId: string): string | null => {
    if (overId.startsWith(PASS_DROP_PREFIX)) return overId.slice(PASS_DROP_PREFIX.length)
    if (overId.startsWith(RULE_PREFIX)) {
      // rule::<passId>::<ruleId>
      const rest = overId.slice(RULE_PREFIX.length)
      const sep = rest.indexOf('::')
      if (sep === -1) return null
      return rest.slice(0, sep)
    }
    return null
  }

  const onDragEnd = (event: DragEndEvent) => {
    const { active, over } = event
    if (!over) return
    const activeId = String(active.id)
    const overId = String(over.id)

    // Library → pass: append a new rule.
    if (activeId.startsWith(LIBRARY_PREFIX)) {
      const ruleType = activeId.slice(LIBRARY_PREFIX.length)
      const passId = findPassForOverId(overId)
      if (passId) appendRuleFromLibrary(passId, ruleType)
      return
    }

    // Rule reorder within pass.
    if (activeId.startsWith(RULE_PREFIX) && overId.startsWith(RULE_PREFIX)) {
      const a = activeId.slice(RULE_PREFIX.length).split('::')
      const o = overId.slice(RULE_PREFIX.length).split('::')
      if (a.length === 2 && o.length === 2 && a[0] === o[0]) {
        reorderRulesInPass(a[0], a[1], o[1])
      }
    }
  }

  // -----------------------------------------------------------------------

  return (
    <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={onDragEnd}>
      <div className="space-y-6">
        <Alert>
          <AlertTitle>Matching rules</AlertTitle>
          <AlertDescription>
            Each pass is a group of conditions evaluated together. Drag rules from the library on
            the left into a pass to fine-tune matching. Run AI Match to apply them, or use Basic
            Reconciliation to skip rules entirely (date + amount only).
          </AlertDescription>
        </Alert>

        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="text-sm text-foreground-muted">
            {passes.length} pass{passes.length === 1 ? '' : 'es'} ·{' '}
            {sourceA.length} A rows · {sourceB.length} B rows
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <Button variant="outline" onClick={handleGenerate} disabled={isBusy || locked}>
              {generateMutation.isPending ? (
                <Loader2 className="mr-1.5 size-4 animate-spin" aria-hidden />
              ) : (
                <Wand2 className="mr-1.5 size-4" aria-hidden />
              )}
              Regenerate rules
            </Button>
            <Button variant="outline" onClick={handleRunBasic} disabled={isBusy || locked}>
              {basicMutation.isPending ? (
                <Loader2 className="mr-1.5 size-4 animate-spin" aria-hidden />
              ) : (
                <Zap className="mr-1.5 size-4" aria-hidden />
              )}
              Basic match
            </Button>
            <Button onClick={handleRunMatch} disabled={isBusy || passes.length === 0 || locked}>
              {matchMutation.isPending ? (
                <Loader2 className="mr-1.5 size-4 animate-spin" aria-hidden />
              ) : (
                <Play className="mr-1.5 size-4" aria-hidden />
              )}
              Run AI Match
            </Button>
          </div>
        </div>

        <div className="relative flex flex-col gap-4 lg:flex-row">
          {/* AI Matching Engine overlay */}
          {matchMutation.isPending && (
            <div className="absolute inset-0 z-30 flex items-center justify-center rounded-2xl bg-background/80 backdrop-blur-sm">
              <div className="w-full max-w-md space-y-5 rounded-2xl border border-border bg-card p-8 text-center shadow-xl">
                <div className="relative mx-auto size-20">
                  <div className="absolute inset-0 rounded-full border-4 border-primary/20" aria-hidden />
                  <div
                    className="absolute inset-0 animate-spin rounded-full border-4 border-primary border-t-transparent"
                    style={{ animationDuration: '1.5s' }}
                    aria-hidden
                  />
                  <div className="absolute inset-0 flex items-center justify-center text-primary">
                    <BrainCircuit className="size-8" aria-hidden />
                  </div>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-foreground">AI Matching Engine</h3>
                  <p className="mt-1 text-sm text-foreground-muted">
                    Applying {totalPasses} pass{totalPasses === 1 ? '' : 'es'} across your sources…
                  </p>
                </div>
                <div className="h-2 w-full overflow-hidden rounded-full bg-surface-muted">
                  <div
                    className="h-full bg-primary transition-all duration-500 ease-out"
                    style={{ width: `${(matchProgress / totalPasses) * 100}%` }}
                  />
                </div>
                <p className="text-xs font-semibold uppercase tracking-widest text-foreground-muted">
                  Pass {Math.max(1, matchProgress)} of {totalPasses}
                </p>
              </div>
            </div>
          )}

          <RuleLibrary categories={availableRules} disabled={locked} />

          <div className="flex-1 space-y-3">
            {passes.length === 0 && !generateMutation.isPending && (
              <div className="rounded-xl border border-dashed border-border bg-card p-8 text-center text-sm text-foreground-muted">
                No passes yet. Click <strong>Regenerate rules</strong> to draft a set based on your
                data, or run a Basic match without rules.
              </div>
            )}
            {generateMutation.isPending && passes.length === 0 && (
              <div className="flex items-center justify-center gap-2 rounded-xl border border-border bg-card p-8 text-sm text-foreground-muted">
                <Loader2 className="size-4 animate-spin" aria-hidden /> Generating matching rules…
              </div>
            )}
            {passes.map((pass, idx) => (
              <PassCard
                key={pass.id ?? `pass-${idx}`}
                index={idx}
                pass={pass}
                allRuleTypes={allRuleTypes}
                locked={locked || isBusy}
                onRename={(name) => updatePass(pass.id!, { name })}
                onToggleType={(t) => togglePassMatchType(pass.id!, t)}
                onLogicChange={(logic) => updatePass(pass.id!, { logic })}
                onRuleChange={(rId, updates) => updateRule(pass.id!, rId, updates)}
                onRemoveRule={(rId) => removeRule(pass.id!, rId)}
                onAppendRule={(ruleType) => appendRuleFromLibrary(pass.id!, ruleType)}
                onRemovePass={() => handleRemovePass(pass.id!)}
              />
            ))}
            <Button
              variant="outline"
              className="w-full justify-center border-dashed py-6"
              onClick={addEmptyPass}
              disabled={locked || isBusy}
            >
              <Plus className="mr-1.5 size-4" aria-hidden /> Add pass
            </Button>
          </div>
        </div>

        <div className="rounded-xl border border-border bg-card p-4">
          <Label htmlFor="refine-instructions" className="text-sm font-semibold">
            <Plus className="mr-1 inline size-4 align-text-bottom" aria-hidden /> Add a pass with
            instructions
          </Label>
          <Textarea
            id="refine-instructions"
            className="mt-2"
            rows={2}
            placeholder='e.g. "Match Many:Many on description containing invoice numbers"'
            value={refineText}
            onChange={(e) => setRefineText(e.target.value)}
            disabled={isBusy || locked}
          />
          <div className="mt-2 flex justify-end">
            <Button
              variant="outline"
              onClick={handleRefine}
              disabled={isBusy || locked || !refineText.trim()}
            >
              {additionalMutation.isPending ? (
                <Loader2 className="mr-1.5 size-4 animate-spin" aria-hidden />
              ) : (
                <Plus className="mr-1.5 size-4" aria-hidden />
              )}
              Add pass
            </Button>
          </div>
        </div>
      </div>
    </DndContext>
  )
}

function RuleLibrary({
  categories,
  disabled,
}: {
  categories: AvailableRuleCategory[]
  disabled?: boolean
}) {
  return (
    <div
      className={cn(
        'lg:w-64 shrink-0 rounded-xl border border-border bg-card p-4',
        disabled && 'opacity-60 pointer-events-none',
      )}
    >
      <h3 className="mb-3 text-sm font-semibold text-foreground">Rule library</h3>
      <p className="mb-4 text-xs text-foreground-muted">Drag a rule into a pass to add it.</p>
      <div className="max-h-[28rem] space-y-4 overflow-y-auto pr-1">
        {categories.length === 0 && (
          <p className="text-xs text-foreground-subtle">
            Upload data to populate the library.
          </p>
        )}
        {categories.map((category) => (
          <div key={category.category}>
            <h4 className="mb-1.5 text-[10px] font-bold uppercase tracking-widest text-foreground-muted">
              {category.category}
            </h4>
            <div className="space-y-1.5">
              {category.rules.map((rule) => (
                <LibraryItem key={rule} ruleType={rule} />
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

function LibraryItem({ ruleType }: { ruleType: string }) {
  const { attributes, listeners, setNodeRef, isDragging } = useDraggable({
    id: `${LIBRARY_PREFIX}${ruleType}`,
  })
  return (
    <div
      ref={setNodeRef}
      {...attributes}
      {...listeners}
      className={cn(
        'flex cursor-grab items-center gap-1.5 rounded-md border border-border bg-surface-muted px-2 py-1.5 text-xs font-medium text-foreground transition-colors hover:border-primary/50 hover:bg-primary/5',
        isDragging && 'opacity-40',
      )}
    >
      <GripVertical className="size-3.5 text-foreground-muted" aria-hidden />
      {ruleType}
    </div>
  )
}

function PassCard({
  index,
  pass,
  allRuleTypes,
  locked,
  onRename,
  onToggleType,
  onLogicChange,
  onRuleChange,
  onRemoveRule,
  onAppendRule,
  onRemovePass,
}: {
  index: number
  pass: ReconciliationPass
  allRuleTypes: string[]
  locked: boolean
  onRename: (name: string) => void
  onToggleType: (t: MatchGroupType) => void
  onLogicChange: (logic: 'AND' | 'OR') => void
  onRuleChange: (ruleId: string, updates: Partial<ReconciliationRule>) => void
  onRemoveRule: (ruleId: string) => void
  onAppendRule: (ruleType: string) => void
  onRemovePass: () => void
}) {
  const passId = pass.id!
  const { setNodeRef, isOver } = useDroppable({ id: `${PASS_DROP_PREFIX}${passId}` })
  const [nameDraft, setNameDraft] = useState(pass.name)
  useEffect(() => setNameDraft(pass.name), [pass.name])

  const ruleIds = (pass.rules ?? []).map((r) => `${RULE_PREFIX}${passId}::${r.id}`)

  return (
    <div className="rounded-xl border border-border bg-card shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border bg-surface-muted/40 p-3">
        <div className="flex flex-1 items-center gap-2">
          <div className="flex size-6 shrink-0 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">
            {index + 1}
          </div>
          <Sparkles className="size-4 text-primary" aria-hidden />
          <Input
            value={nameDraft}
            onChange={(e) => setNameDraft(e.target.value)}
            onBlur={() => {
              if (nameDraft.trim() && nameDraft !== pass.name) onRename(nameDraft.trim())
            }}
            disabled={locked}
            className="h-8 max-w-xs border-none bg-transparent px-1 text-sm font-semibold shadow-none focus-visible:ring-1"
          />
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-[10px] font-bold uppercase tracking-widest text-foreground-muted">
            Match
          </span>
          {MATCH_TYPES.map((t) => {
            const active = (pass.matchTypes ?? []).includes(t)
            return (
              <button
                key={t}
                type="button"
                onClick={() => onToggleType(t)}
                disabled={locked}
                className={cn(
                  'rounded px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider transition-colors',
                  active
                    ? 'bg-primary/10 text-primary'
                    : 'bg-surface-muted text-foreground-muted hover:bg-surface-muted/70',
                  locked && 'cursor-not-allowed opacity-60',
                )}
              >
                {t}
              </button>
            )
          })}
          <Select
            value={pass.logic}
            onValueChange={(v) => onLogicChange(v as 'AND' | 'OR')}
            disabled={locked}
          >
            <SelectTrigger className="h-7 w-20 text-xs">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="AND">AND</SelectItem>
              <SelectItem value="OR">OR</SelectItem>
            </SelectContent>
          </Select>
          <Button
            variant="ghost"
            size="icon"
            aria-label={`Remove pass ${pass.name}`}
            onClick={onRemovePass}
            disabled={locked}
          >
            <Trash2 className="size-4" aria-hidden />
          </Button>
        </div>
      </div>

      <div
        ref={setNodeRef}
        className={cn(
          'min-h-[5rem] p-4 transition-colors',
          isOver && 'bg-primary/5',
        )}
      >
        {pass.rules.length === 0 ? (
          <div className="rounded-xl border-2 border-dashed border-border p-6 text-center text-sm text-foreground-muted">
            Drag rules here
          </div>
        ) : (
          <SortableContext items={ruleIds} strategy={verticalListSortingStrategy}>
            <div className="space-y-2">
              {pass.rules.map((rule) => (
                <SortableRuleRow
                  key={rule.id}
                  passId={passId}
                  rule={rule}
                  allRuleTypes={allRuleTypes}
                  locked={locked}
                  onChange={(updates) => onRuleChange(rule.id!, updates)}
                  onRemove={() => onRemoveRule(rule.id!)}
                />
              ))}
            </div>
          </SortableContext>
        )}

        {allRuleTypes.length > 0 && (
          <div className="mt-3">
            <Select
              value=""
              onValueChange={(v) => {
                if (v) onAppendRule(v)
              }}
              disabled={locked}
            >
              <SelectTrigger className="h-8 w-fit min-w-[10rem] text-xs">
                <Plus className="mr-1 size-3.5" aria-hidden />
                <SelectValue placeholder="Add rule" />
              </SelectTrigger>
              <SelectContent>
                {allRuleTypes.map((r) => (
                  <SelectItem key={r} value={r} className="text-xs">
                    {r}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        )}
      </div>
    </div>
  )
}

function SortableRuleRow({
  passId,
  rule,
  allRuleTypes,
  locked,
  onChange,
  onRemove,
}: {
  passId: string
  rule: ReconciliationRule
  allRuleTypes: string[]
  locked: boolean
  onChange: (updates: Partial<ReconciliationRule>) => void
  onRemove: () => void
}) {
  const ruleId = rule.id!
  const sortable = useSortable({ id: `${RULE_PREFIX}${passId}::${ruleId}` })
  const style = {
    transform: CSS.Transform.toString(sortable.transform),
    transition: sortable.transition,
  }

  const tolerance = (rule.config?.tolerance as number | string | undefined) ?? ''
  const range = (rule.config?.range as number | string | undefined) ?? ''

  return (
    <div
      ref={sortable.setNodeRef}
      style={style}
      className={cn(
        'flex flex-wrap items-center gap-2 rounded-lg border border-border bg-background p-2',
        sortable.isDragging && 'opacity-40',
      )}
    >
      <button
        type="button"
        aria-label="Reorder rule"
        className="cursor-grab touch-none p-1 text-foreground-muted hover:text-foreground"
        {...sortable.attributes}
        {...sortable.listeners}
      >
        <GripVertical className="size-4" aria-hidden />
      </button>
      <Select
        value={rule.type}
        onValueChange={(v) => onChange({ type: v, config: {} })}
        disabled={locked}
      >
        <SelectTrigger className="h-8 max-w-[18rem] flex-1 text-xs">
          <SelectValue />
        </SelectTrigger>
        <SelectContent>
          {/* Make sure the current rule type is selectable even if it's no
              longer in the dynamically-derived list (e.g. data changed). */}
          {Array.from(new Set([rule.type, ...allRuleTypes])).map((r) => (
            <SelectItem key={r} value={r} className="text-xs">
              {r}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>

      {rule.type.includes('Tolerance') && (
        <div className="flex items-center gap-1.5 border-l border-border pl-2">
          <Badge variant="outline" className="text-[10px]">
            ±
          </Badge>
          <Input
            type="number"
            value={tolerance}
            disabled={locked}
            placeholder={rule.type.includes('Percentage') ? '%' : 'abs'}
            onChange={(e) =>
              onChange({
                config: { ...(rule.config ?? {}), tolerance: parseFloat(e.target.value) || 0 },
              })
            }
            className="h-7 w-20 text-xs"
          />
        </div>
      )}

      {rule.type.includes('Range') && (
        <div className="flex items-center gap-1.5 border-l border-border pl-2">
          <Badge variant="outline" className="text-[10px]">
            ±
          </Badge>
          <Input
            type="number"
            value={range}
            disabled={locked}
            placeholder="days"
            onChange={(e) =>
              onChange({
                config: { ...(rule.config ?? {}), range: parseInt(e.target.value, 10) || 0 },
              })
            }
            className="h-7 w-16 text-xs"
          />
          <span className="text-[10px] font-medium text-foreground-muted">days</span>
        </div>
      )}

      <Button
        variant="ghost"
        size="icon"
        aria-label="Remove rule"
        onClick={onRemove}
        disabled={locked}
        className="ml-auto size-7"
      >
        <X className="size-3.5" aria-hidden />
      </Button>
    </div>
  )
}

export default ReconciliationRulesStep
