'use client'

import { useEffect, useMemo, useState } from 'react'
import { Loader2, Plus, Play, Sparkles, Trash2, Wand2, Zap } from 'lucide-react'

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import {
  useGenerateAdditionalReconciliationPass,
  useGenerateReconciliationRules,
  usePerformReconciliationMatch,
  useReconcileBasic,
  useUpdateAnalyticsReconciliation,
} from '@/hooks/useAnalyticsReconciliation'
import { useToast } from '@/hooks/use-toast'
import {
  buildAvailableRules,
  type ReconciliationMatchGroup,
  type ReconciliationPass,
  type ReconciliationTransaction,
  type UnmatchedException,
} from '@/lib/analytics/reconciliationTypes'

interface ReconciliationRulesStepProps {
  reconciliationId: string
  sourceA: ReconciliationTransaction[]
  sourceB: ReconciliationTransaction[]
  rules: ReconciliationPass[]
  onComplete: () => void
}

export function ReconciliationRulesStep({
  reconciliationId,
  sourceA,
  sourceB,
  rules,
  onComplete,
}: ReconciliationRulesStepProps) {
  const { toast } = useToast()
  const [passes, setPasses] = useState<ReconciliationPass[]>(rules)
  const [refineText, setRefineText] = useState('')

  useEffect(() => {
    setPasses(rules)
  }, [rules])

  const availableRules = useMemo(
    () => buildAvailableRules(sourceA, sourceB),
    [sourceA, sourceB],
  )
  const headers = useMemo(
    () => Array.from(new Set(availableRules.map((c) => c.category))),
    [availableRules],
  )

  const generateMutation = useGenerateReconciliationRules()
  const additionalMutation = useGenerateAdditionalReconciliationPass()
  const matchMutation = usePerformReconciliationMatch()
  const basicMutation = useReconcileBasic()
  const updateMutation = useUpdateAnalyticsReconciliation()

  const autoGenerated = passes.length > 0
  const isBusy =
    generateMutation.isPending ||
    additionalMutation.isPending ||
    matchMutation.isPending ||
    basicMutation.isPending ||
    updateMutation.isPending

  useEffect(() => {
    // Auto-generate the initial pass set when the user lands here with no rules.
    if (passes.length === 0 && headers.length > 0 && !generateMutation.isPending && !autoGenerated) {
      void handleGenerate()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const persistPasses = async (next: ReconciliationPass[]) => {
    await updateMutation.mutateAsync({
      reconciliationId,
      data: { rules: next as unknown as Record<string, unknown>[] },
    })
  }

  const handleGenerate = async () => {
    try {
      const result = await generateMutation.mutateAsync({
        headers,
        availableRules: availableRules as unknown as Record<string, unknown>,
      })
      const next = ((result.passes ?? []) as unknown as ReconciliationPass[]) ?? []
      setPasses(next)
      await persistPasses(next)
      toast({
        title: 'Rules generated',
        description: `${next.length} matching pass${next.length === 1 ? '' : 'es'} created.`,
      })
    } catch (error) {
      toast({
        title: 'Rule generation failed',
        description: error instanceof Error ? error.message : 'Try again.',
        variant: 'destructive',
      })
    }
  }

  const handleRefine = async () => {
    if (!refineText.trim()) {
      toast({ title: 'Add instructions first', description: 'Describe the pass to add.' })
      return
    }
    try {
      const result = await additionalMutation.mutateAsync({
        instructions: refineText.trim(),
        availableRules: availableRules as unknown as Record<string, unknown>,
      })
      const pass = (result.pass ?? null) as unknown as ReconciliationPass | null
      if (!pass) {
        toast({ title: 'No pass returned', variant: 'destructive' })
        return
      }
      const next = [...passes, pass]
      setPasses(next)
      await persistPasses(next)
      setRefineText('')
      toast({ title: 'Pass added', description: pass.name })
    } catch (error) {
      toast({
        title: 'Refine failed',
        description: error instanceof Error ? error.message : 'Try again.',
        variant: 'destructive',
      })
    }
  }

  const handleRemovePass = async (idx: number) => {
    const next = passes.filter((_, i) => i !== idx)
    setPasses(next)
    await persistPasses(next)
  }

  const applyMatchResult = async (
    matchGroups: ReconciliationMatchGroup[],
    unmatchedExceptions: UnmatchedException[] = [],
  ) => {
    // Tag every transaction with its post-match status so the Results step can
    // render matched/unmatched columns without a refetch.
    const matchedAIds = new Set<string>()
    const matchedBIds = new Set<string>()
    for (const g of matchGroups) {
      for (const id of g.sourceAIds ?? []) matchedAIds.add(id)
      for (const id of g.sourceBIds ?? []) matchedBIds.add(id)
    }

    const exceptionsById = new Map<string, UnmatchedException>()
    for (const ex of unmatchedExceptions) exceptionsById.set(ex.id, ex)

    const stamp = (t: ReconciliationTransaction): ReconciliationTransaction => {
      const isMatched = (t.source === 'A' ? matchedAIds : matchedBIds).has(t.id)
      const ex = exceptionsById.get(t.id)
      return {
        ...t,
        status: isMatched ? 'matched' : 'unmatched',
        matchGroupId: isMatched
          ? matchGroups.find((g) =>
              (t.source === 'A' ? g.sourceAIds : g.sourceBIds)?.includes(t.id),
            )?.id
          : undefined,
        exceptionCategory: !isMatched ? ex?.exceptionCategory : undefined,
        exceptionReasoning: !isMatched ? ex?.exceptionReasoning : undefined,
      }
    }

    const nextA = sourceA.map(stamp)
    const nextB = sourceB.map(stamp)

    await updateMutation.mutateAsync({
      reconciliationId,
      data: {
        source_a: nextA as unknown as Record<string, unknown>[],
        source_b: nextB as unknown as Record<string, unknown>[],
        match_groups: matchGroups as unknown as Record<string, unknown>[],
      },
    })
  }

  const handleRunMatch = async () => {
    if (passes.length === 0) {
      toast({ title: 'Generate rules first', description: 'No passes to apply.' })
      return
    }
    try {
      const result = await matchMutation.mutateAsync({
        sourceA: sourceA as unknown as Record<string, unknown>[],
        sourceB: sourceB as unknown as Record<string, unknown>[],
        rules: passes as unknown as Record<string, unknown>[],
      })
      const groups = (result.matchGroups ?? []) as unknown as ReconciliationMatchGroup[]
      const exceptions = (result.unmatchedExceptions ?? []) as unknown as UnmatchedException[]
      await applyMatchResult(groups, exceptions)
      toast({
        title: 'Match complete',
        description: `${groups.length} match group${groups.length === 1 ? '' : 's'} created.`,
      })
      onComplete()
    } catch (error) {
      toast({
        title: 'Match failed',
        description: error instanceof Error ? error.message : 'Try again.',
        variant: 'destructive',
      })
    }
  }

  const handleRunBasic = async () => {
    try {
      const result = await basicMutation.mutateAsync({
        sourceA: sourceA as unknown as Record<string, unknown>[],
        sourceB: sourceB as unknown as Record<string, unknown>[],
      })
      const groups = (result.matchGroups ?? []) as unknown as ReconciliationMatchGroup[]
      const exceptions = (result.unmatchedExceptions ?? []) as unknown as UnmatchedException[]
      await applyMatchResult(groups, exceptions)
      toast({
        title: 'Basic reconciliation complete',
        description: `${groups.length} match group${groups.length === 1 ? '' : 's'} created.`,
      })
      onComplete()
    } catch (error) {
      toast({
        title: 'Basic match failed',
        description: error instanceof Error ? error.message : 'Try again.',
        variant: 'destructive',
      })
    }
  }

  return (
    <div className="space-y-6">
      <Alert>
        <AlertTitle>Matching rules</AlertTitle>
        <AlertDescription>
          Each pass is a group of conditions evaluated together. Run AI Match to apply them, or use
          Basic Reconciliation to skip rules entirely (date + amount only).
        </AlertDescription>
      </Alert>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="text-sm text-foreground-muted">
          {passes.length} pass{passes.length === 1 ? '' : 'es'} ·{' '}
          {sourceA.length} A rows · {sourceB.length} B rows
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <Button variant="outline" onClick={handleGenerate} disabled={isBusy}>
            {generateMutation.isPending ? (
              <Loader2 className="mr-1.5 size-4 animate-spin" aria-hidden />
            ) : (
              <Wand2 className="mr-1.5 size-4" aria-hidden />
            )}
            Regenerate rules
          </Button>
          <Button variant="outline" onClick={handleRunBasic} disabled={isBusy}>
            {basicMutation.isPending ? (
              <Loader2 className="mr-1.5 size-4 animate-spin" aria-hidden />
            ) : (
              <Zap className="mr-1.5 size-4" aria-hidden />
            )}
            Basic match
          </Button>
          <Button onClick={handleRunMatch} disabled={isBusy || passes.length === 0}>
            {matchMutation.isPending ? (
              <Loader2 className="mr-1.5 size-4 animate-spin" aria-hidden />
            ) : (
              <Play className="mr-1.5 size-4" aria-hidden />
            )}
            Run AI Match
          </Button>
        </div>
      </div>

      <div className="space-y-3">
        {passes.length === 0 && !generateMutation.isPending && (
          <div className="rounded-xl border border-dashed border-border bg-card p-8 text-center text-sm text-foreground-muted">
            No passes yet. Click <strong>Regenerate rules</strong> to draft a set based on your
            data, or run a Basic match without rules.
          </div>
        )}
        {generateMutation.isPending && passes.length === 0 && (
          <div className="flex items-center justify-center gap-2 rounded-xl border border-border bg-card p-8 text-sm text-foreground-muted">
            <Loader2 className="size-4 animate-spin" aria-hidden /> Generating matching rules…
          </div>
        )}
        {passes.map((pass, idx) => (
          <div key={pass.id ?? idx} className="rounded-xl border border-border bg-card p-4">
            <div className="flex flex-wrap items-start justify-between gap-2">
              <div className="flex flex-wrap items-center gap-2">
                <Sparkles className="size-4 text-primary" aria-hidden />
                <span className="font-semibold text-foreground">{pass.name}</span>
                {(pass.matchTypes ?? []).map((t) => (
                  <Badge key={t} variant="secondary">
                    {t}
                  </Badge>
                ))}
                <Badge variant="outline">{pass.logic}</Badge>
              </div>
              <Button
                variant="ghost"
                size="icon"
                aria-label={`Remove pass ${pass.name}`}
                onClick={() => handleRemovePass(idx)}
                disabled={isBusy}
              >
                <Trash2 className="size-4" aria-hidden />
              </Button>
            </div>
            <ul className="mt-2 flex flex-wrap gap-1.5">
              {(pass.rules ?? []).map((r, i) => (
                <li
                  key={i}
                  className="rounded-md border border-border bg-surface-muted px-2 py-1 text-xs"
                >
                  {r.type}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      <div className="rounded-xl border border-border bg-card p-4">
        <Label htmlFor="refine-instructions" className="text-sm font-semibold">
          <Plus className="mr-1 inline size-4 align-text-bottom" aria-hidden /> Add a pass with
          instructions
        </Label>
        <Textarea
          id="refine-instructions"
          className="mt-2"
          rows={2}
          placeholder='e.g. "Match Many:Many on description containing invoice numbers"'
          value={refineText}
          onChange={(e) => setRefineText(e.target.value)}
          disabled={isBusy}
        />
        <div className="mt-2 flex justify-end">
          <Button variant="outline" onClick={handleRefine} disabled={isBusy || !refineText.trim()}>
            {additionalMutation.isPending ? (
              <Loader2 className="mr-1.5 size-4 animate-spin" aria-hidden />
            ) : (
              <Plus className="mr-1.5 size-4" aria-hidden />
            )}
            Add pass
          </Button>
        </div>
      </div>
    </div>
  )
}

export default ReconciliationRulesStep
