import { ProtectedAction } from '@/components/marketing/ProtectedAction'
import { generateMetadata, pageMetadata } from '@/lib/metadata'

export const metadata = generateMetadata(pageMetadata.features)

export default function FeaturesPage() { return <main id="main-content">
  <section className="ps-page-hero"><div className="ps-container ps-page-hero__split"><div><span className="ps-label">Features</span><h1>Everything you need to extract data from any file</h1></div><div><p className="ps-kicker">No complex training required — just type in plain English.</p><ProtectedAction destination="/dashboard">Try it now →</ProtectedAction></div></div></section>
  <section className="ps-section"><div className="ps-container ps-showcase"><div><span className="ps-label">Extraction</span><h2>Data extraction</h2><p className="ps-kicker">Intelligently extract and structure key information from any document type with precision. Advanced algorithms understand context and maintain data relationships while converting unstructured content into organized, actionable insights.</p><ul className="ps-feature-list">{['Financial statements','Contract documents','Medical records','Legal forms','Research papers','Technical reports','Compliance documents'].map(x=><li key={x}>{x}</li>)}</ul></div><div className="ps-ui" role="img" aria-label="Data extraction example showing invoice processing"><div className="ps-ui__bar"><span>Invoice_10482.pdf</span><span>Processing complete</span></div><div className="ps-ui__body"><table className="ps-table"><tbody>{[['Vendor','Northstar Systems'],['Invoice number','10482'],['Invoice date','2026-07-18'],['Subtotal','$18,450.00'],['Tax','$1,522.13'],['Total','$19,972.13'],['G/L code','6210 · Software']].map(([a,b])=><tr key={a}><th>{a}</th><td>{b}</td></tr>)}</tbody></table></div></div></div></section>
  <section className="ps-section ps-section--muted"><div className="ps-container ps-showcase ps-showcase--reverse"><div><span className="ps-label">Tables</span><h2>Table extraction</h2><p className="ps-kicker">Advanced table recognition that captures complex layouts and preserves data relationships. Handles multi-column formats, nested headers, and irregular table structures with high accuracy.</p><ul className="ps-feature-list">{['Multi-page reports','Complex spreadsheets','Financial tables','Data matrices'].map(x=><li key={x}>{x}</li>)}</ul></div><div className="ps-ui" role="img" aria-label="Table extraction example showing spreadsheet with highlighted table"><div className="ps-ui__bar"><span>Financial table · page 18–22</span><span>42 rows captured</span></div><div className="ps-ui__body"><table className="ps-table"><thead><tr><th>Account</th><th>Current</th><th>Prior</th><th>Variance</th></tr></thead><tbody>{[['Revenue','$2,480,000','$2,110,000','+17.5%'],['Cost of sales','$1,190,000','$1,080,000','+10.2%'],['Operating income','$622,000','$491,000','+26.7%'],['Net income','$451,000','$360,000','+25.3%']].map(row=><tr key={row[0]}>{row.map(x=><td key={x}>{x}</td>)}</tr>)}</tbody></table></div></div></div></section>
  <section className="ps-section ps-dark ps-grid-bg"><div className="ps-container ps-showcase"><div><span className="ps-label">Customization</span><h2>Custom extraction at will</h2><p className="ps-kicker">Create custom columns with self-defined formats and prompts. Users have the ability to classify data, add further details like accounting G/L codes, and create intelligent categorization rules tailored to their specific business needs.</p><ul className="ps-feature-list">{['Custom data formats','Classification rules','Accounting codes','Smart categorization','Business rule automation'].map(x=><li key={x}>{x}</li>)}</ul><ProtectedAction destination="/dashboard" className="ps-button ps-button--light">Go to dashboard →</ProtectedAction></div><div className="ps-terminal" role="img" aria-label="AI data cleaning interface showing before and after data transformation"><div className="ps-window-bar"><span>custom_extraction.rule</span><span>active</span></div><pre>FIELD      raw_value        normalized{`\n`}date       Jul 18, 2026     2026-07-18{`\n`}vendor     NORTHSTAR SYS    Northstar Systems{`\n`}amount     $19,972.13       19972.13{`\n`}category   SaaS platform    Software{`\n`}gl_code    —                6210{`\n\n`}<span className="accent">prompt:</span> Classify software costs using the firm&apos;s G/L mapping and flag contracts over $10,000.</pre></div></div></section>
</main> }
