'use client'

import * as React from 'react'
import Link from 'next/link'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Copy, ExternalLink, Link2, RotateCw, ShieldX } from 'lucide-react'
import { apiClient } from '@/lib/api'
import { useEsignBrands, useEsignTemplate, useEsignTemplates } from '@/hooks/useEnvelopes'
import { useCreatePowerForm, usePowerFormAction, usePowerForms, usePowerFormSubmissions, useTemplateVersions } from '@/hooks/useEsignScale'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Badge } from '@/components/ui/badge'
import { useToast } from '@/hooks/use-toast'

type RoleConfig = { recipient_index: number; identity_source: 'visitor' | 'preset'; initiating_signer: boolean; name?: string; email?: string }

export default function PowerFormsPage() {
  const { toast } = useToast(); const queryClient = useQueryClient(); const templates = useEsignTemplates(); const brands = useEsignBrands()
  const forms = usePowerForms(); const create = useCreatePowerForm(); const action = usePowerFormAction()
  const [templateId, setTemplateId] = React.useState(''); const template = useEsignTemplate(templateId); const versions = useTemplateVersions(templateId)
  const [versionId, setVersionId] = React.useState(''); const [name, setName] = React.useState(''); const [cap, setCap] = React.useState('')
  const [startsAt, setStartsAt] = React.useState(''); const [endsAt, setEndsAt] = React.useState(''); const [instructions, setInstructions] = React.useState(''); const [brandId, setBrandId] = React.useState('none')
  const [roles, setRoles] = React.useState<RoleConfig[]>([]); const [publicFields, setPublicFields] = React.useState<string[]>([])
  const [latestUrl, setLatestUrl] = React.useState<string | null>(null); const [selectedId, setSelectedId] = React.useState<string>()
  const selected = forms.data?.powerforms.find(form => form.id === selectedId); const submissions = usePowerFormSubmissions(selectedId)
  const [upgradeVersion, setUpgradeVersion] = React.useState('')

  React.useEffect(() => setVersionId(versions.data?.versions[0]?.id ?? ''), [versions.data])
  React.useEffect(() => { setRoles((template.data?.recipient_roles ?? []).map((_, index) => ({ recipient_index: index, identity_source: 'visitor', initiating_signer: index === 0 }))); setPublicFields([]) }, [template.data])
  const fieldOptions = React.useMemo(() => Array.from(new Set((template.data?.fields ?? []).filter(field => 'sender_prefill' in (field.properties ?? {})).map(field => String((field.properties as { data_label?: string }).data_label ?? '')).filter(Boolean))), [template.data])
  const updateRole = (index: number, patch: Partial<RoleConfig>) => setRoles(current => current.map((role, i) => i === index ? { ...role, ...patch } : role))

  const upgradeOptions = useQuery({ queryKey: ['esign', 'powerform', selectedId, 'upgrade-options'], enabled: !!selected,
    queryFn: async () => { const candidates = await Promise.all((templates.data?.templates ?? []).map(async tpl => ({ template: tpl, versions: (await apiClient.listEsignTemplateVersions(tpl.id)).versions }))); return candidates.find(item => item.versions.some(version => version.id === selected!.template_version_id)) ?? null } })
  const preview = useQuery({ queryKey: ['esign', 'powerform', selectedId, 'upgrade-preview', upgradeVersion], enabled: !!selectedId && !!upgradeVersion,
    queryFn: () => apiClient.previewEsignPowerFormUpgrade(selectedId!, upgradeVersion) })

  const submit = async () => {
    try {
      const result = await create.mutateAsync({ name, template_version_id: versionId, starts_at: startsAt ? new Date(startsAt).toISOString() : null, ends_at: endsAt ? new Date(endsAt).toISOString() : null, submission_cap: cap ? Number(cap) : null, role_config: roles, public_fields: publicFields, instructions: instructions || null, brand_id: brandId === 'none' ? null : brandId })
      setLatestUrl(result.public_url ?? null); setSelectedId(result.id); toast({ title: 'PowerForm created', description: 'The public URL is shown once. Store it now.' })
    } catch (error) { toast({ title: 'Could not create PowerForm', description: error instanceof Error ? error.message : undefined, variant: 'destructive' }) }
  }
  const runAction = async (id: string, requested: 'active' | 'paused' | 'revoked' | 'rotate') => { try { const result = await action.mutateAsync({ id, action: requested }); if (result.public_url) setLatestUrl(result.public_url); toast({ title: requested === 'rotate' ? 'URL rotated' : `PowerForm ${requested}` }) } catch (error) { toast({ title: 'Action failed', description: error instanceof Error ? error.message : undefined, variant: 'destructive' }) } }

  return <div className="space-y-6">
    <div><p className="text-sm font-medium text-primary">Self-service signing</p><h1 className="text-2xl font-semibold">PowerForms</h1><p className="mt-1 text-sm text-foreground-muted">Reusable, email-verified links pinned to an immutable published template version.</p></div>
    {latestUrl && <section className="rounded-xl border border-warning/30 bg-warning-soft p-4"><p className="text-sm font-medium">Copy this public URL now</p><p className="mb-3 text-xs text-foreground-muted">For security, public URLs are revealed only at creation or rotation. CPAAutomation stores only a hash.</p><div className="flex gap-2"><Input readOnly value={latestUrl} /><Button variant="outline" onClick={() => { void navigator.clipboard.writeText(latestUrl); toast({ title: 'Link copied' }) }}><Copy className="mr-2 size-4" /> Copy</Button></div></section>}
    <section className="space-y-5 rounded-xl border border-border bg-surface p-5 shadow-sm"><h2 className="font-semibold">Create a link</h2>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div><Label>Name</Label><Input value={name} onChange={e => setName(e.target.value)} placeholder="New client engagement" /></div><div><Label>Submission cap (optional)</Label><Input type="number" min={1} value={cap} onChange={e => setCap(e.target.value)} /></div><div><Label>Brand</Label><Select value={brandId} onValueChange={setBrandId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Firm default</SelectItem>{brands.data?.brands.filter(brand => brand.active).map(brand => <SelectItem key={String(brand.id)} value={String(brand.id)}>{String(brand.name)}</SelectItem>)}</SelectContent></Select></div>
        <div><Label>Template</Label><Select value={templateId} onValueChange={setTemplateId}><SelectTrigger><SelectValue placeholder="Choose template" /></SelectTrigger><SelectContent>{templates.data?.templates.map(t => <SelectItem value={t.id} key={t.id}>{t.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Published version</Label><Select value={versionId} onValueChange={setVersionId}><SelectTrigger><SelectValue placeholder="Publish template first" /></SelectTrigger><SelectContent>{versions.data?.versions.map(v => <SelectItem value={v.id} key={v.id}>Version {v.version}</SelectItem>)}</SelectContent></Select></div>
        <div><Label>Opens at (optional)</Label><Input type="datetime-local" value={startsAt} onChange={e => setStartsAt(e.target.value)} /></div><div><Label>Closes at (optional)</Label><Input type="datetime-local" value={endsAt} onChange={e => setEndsAt(e.target.value)} /></div><div className="sm:col-span-2"><Label>Visitor instructions</Label><Textarea value={instructions} onChange={e => setInstructions(e.target.value)} placeholder="Explain what the visitor needs before they begin." /></div></div>
      {!!roles.length && <div className="space-y-2"><Label>Recipient identities</Label>{roles.map((role, index) => <div key={index} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[1fr_150px_170px_1fr_1fr] sm:items-end"><p className="pb-2 text-sm font-medium">{String(template.data?.recipient_roles[index]?.label ?? `Role ${index + 1}`)}</p><Select value={role.identity_source} onValueChange={value => updateRole(index, { identity_source: value as 'visitor' | 'preset', initiating_signer: value === 'preset' ? false : role.initiating_signer })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="visitor">Visitor provided</SelectItem><SelectItem value="preset">Preset by firm</SelectItem></SelectContent></Select><label className="flex items-center gap-2 pb-2 text-sm"><input type="radio" name="initiator" checked={role.initiating_signer} disabled={role.identity_source !== 'visitor'} onChange={() => setRoles(current => current.map((item, i) => ({ ...item, initiating_signer: i === index })))} /> Initiating signer</label>{role.identity_source === 'preset' && <><Input placeholder="Preset name" value={role.name ?? ''} onChange={e => updateRole(index, { name: e.target.value })} /><Input type="email" placeholder="Preset email" value={role.email ?? ''} onChange={e => updateRole(index, { email: e.target.value })} /></>}</div>)}</div>}
      {!!fieldOptions.length && <div><Label>Public sender-prefill fields</Label><div className="mt-2 flex flex-wrap gap-3">{fieldOptions.map(field => <label key={field} className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><input type="checkbox" checked={publicFields.includes(field)} onChange={e => setPublicFields(current => e.target.checked ? [...current, field] : current.filter(item => item !== field))} />{field}</label>)}</div></div>}
      <Button disabled={!name || !versionId || !roles.length || !roles.some(role => role.initiating_signer) || create.isPending || (!!startsAt && !!endsAt && endsAt <= startsAt)} onClick={() => void submit()}><Link2 className="mr-2 size-4" /> Create PowerForm</Button>
    </section>

    <div className="grid gap-5 xl:grid-cols-[330px_minmax(0,1fr)]"><section className="rounded-xl border border-border bg-surface shadow-sm"><div className="border-b p-4"><h2 className="font-semibold">Published links</h2></div>{forms.data?.powerforms.length ? <ul className="divide-y">{forms.data.powerforms.map(form => <li key={form.id}><button onClick={() => { setSelectedId(form.id); setUpgradeVersion('') }} className="flex w-full items-center gap-3 p-4 text-left hover:bg-surface-muted/50"><Link2 className="size-5 text-foreground-muted" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{form.name}</span><span className="block text-xs text-foreground-muted">{form.submission_count}{form.submission_cap ? ` / ${form.submission_cap}` : ''} submissions</span></span><Badge variant="outline">{form.state}</Badge></button></li>)}</ul> : <p className="p-8 text-center text-sm text-foreground-muted">No PowerForms yet.</p>}</section>
      <section className="rounded-xl border border-border bg-surface p-5 shadow-sm">{!selected ? <p className="py-16 text-center text-sm text-foreground-muted">Choose a PowerForm to manage access, versions, and submissions.</p> : <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{selected.name}</h2><p className="text-xs text-foreground-muted">Version pinned · {selected.starts_at ? `opens ${new Date(selected.starts_at).toLocaleString()}` : 'open immediately'} · {selected.ends_at ? `closes ${new Date(selected.ends_at).toLocaleString()}` : 'no closing date'}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => void runAction(selected.id, 'rotate')}><RotateCw className="mr-1 size-3" /> Rotate URL</Button>{selected.state !== 'revoked' && <><Button size="sm" variant="outline" onClick={() => void runAction(selected.id, selected.state === 'active' ? 'paused' : 'active')}>{selected.state === 'active' ? 'Pause' : 'Resume'}</Button><Button size="sm" variant="outline" className="text-destructive" onClick={() => void runAction(selected.id, 'revoked')}><ShieldX className="mr-1 size-3" /> Revoke</Button></>}</div></div>
        <div className="rounded-md border p-3"><Label>Upgrade pinned version</Label><div className="mt-2 flex gap-2"><Select value={upgradeVersion} onValueChange={setUpgradeVersion}><SelectTrigger><SelectValue placeholder="Choose a newer version" /></SelectTrigger><SelectContent>{upgradeOptions.data?.versions.filter(version => version.id !== selected.template_version_id).map(version => <SelectItem key={version.id} value={version.id}>Version {version.version}</SelectItem>)}</SelectContent></Select><Button disabled={!upgradeVersion || !preview.data?.compatible} onClick={async () => { try { await apiClient.upgradeEsignPowerForm(selected.id, upgradeVersion); await queryClient.invalidateQueries({ queryKey: ['esign', 'powerforms'] }); setUpgradeVersion(''); toast({ title: 'Pinned version upgraded' }) } catch (error) { toast({ title: 'Upgrade failed', description: error instanceof Error ? error.message : undefined, variant: 'destructive' }) } }}>Upgrade</Button></div>{preview.data && <div className={`mt-3 rounded p-3 text-xs ${preview.data.compatible ? 'bg-success-soft' : 'bg-warning-soft'}`}><p className="font-medium">{preview.data.compatible ? 'Compatible upgrade' : 'Mapping changes required'}</p><p>{preview.data.current_field_count} → {preview.data.target_field_count} fields{preview.data.changed_roles.length ? ` · changed roles: ${preview.data.changed_roles.join(', ')}` : ''}</p>{preview.data.warnings.map(warning => <p key={warning}>{warning}</p>)}</div>}</div>
        <div><h3 className="mb-2 text-sm font-medium">Submissions</h3>{submissions.data?.submissions.length ? <div className="divide-y rounded-md border">{submissions.data.submissions.map(submission => <div key={submission.id} className="flex flex-wrap items-center gap-3 p-3 text-sm"><span className="min-w-0 flex-1"><span className="block truncate font-medium">{submission.initiating_email}</span><span className="block text-xs text-foreground-muted">{new Date(submission.created_at).toLocaleString()} · {submission.attempt_count} attempt{submission.attempt_count === 1 ? '' : 's'}{submission.last_error ? ` · ${submission.last_error}` : ''}</span></span><Badge variant="outline">{submission.status}</Badge>{submission.envelope_id && <Button size="sm" variant="ghost" asChild><Link href={`/dashboard/esign/${submission.envelope_id}`}>Envelope <ExternalLink className="ml-1 size-3" /></Link></Button>}{submission.status === 'failed' && <Button size="sm" variant="outline" onClick={async () => { try { await apiClient.retryEsignPowerFormSubmission(selected.id, submission.id); await submissions.refetch(); toast({ title: 'Submission retried' }) } catch (error) { toast({ title: 'Retry failed', description: error instanceof Error ? error.message : undefined, variant: 'destructive' }) } }}>Retry</Button>}</div>)}</div> : <p className="rounded-md border border-dashed p-5 text-sm text-foreground-muted">No submissions yet.</p>}</div>
      </div>}</section></div>
  </div>
}
