"""unique engagement per opportunity

Revision ID: 11225d8c2da1
Revises: f6b686616fc1
Create Date: 2026-08-23 10:56:27.690167
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '11225d8c2da1'
down_revision = 'f6b686616fc1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Data repair: earlier builds could create one engagement per Closed-Won event. Keep the earliest per opportunity,
    # detach later duplicates (terminated, tagged) so the unique index can be created without losing rows.
    op.execute(sa.text("""
        UPDATE engagements SET opportunity_id = NULL, status = 'terminated',
               external_ref = COALESCE(external_ref, '') || ' DUPLICATE-OF-OPP-' || CAST(id AS VARCHAR)
        WHERE opportunity_id IS NOT NULL AND id NOT IN (
            SELECT MIN(id) FROM engagements WHERE opportunity_id IS NOT NULL GROUP BY opportunity_id)
    """))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.create_index('uq_engagements_opportunity', ['opportunity_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engagements', schema=None) as batch_op:
        batch_op.drop_index('uq_engagements_opportunity')

    # ### end Alembic commands ###
