"""ethical walls

Revision ID: f6b686616fc1
Revises: 509e42cd1dc6
Create Date: 2026-08-22 14:58:41.969605
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'f6b686616fc1'
down_revision = '509e42cd1dc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ethical_walls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deactivated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ethical_walls', schema=None) as batch_op:
        batch_op.create_index('ix_ethical_walls_entity', ['entity_type', 'entity_id', 'is_active'], unique=False)

    op.create_table('ethical_wall_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wall_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wall_id'], ['ethical_walls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wall_id', 'user_id')
    )
    with op.batch_alter_table('ethical_wall_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ethical_wall_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ethical_wall_members_wall_id'), ['wall_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ethical_wall_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ethical_wall_members_wall_id'))
        batch_op.drop_index(batch_op.f('ix_ethical_wall_members_user_id'))

    op.drop_table('ethical_wall_members')
    with op.batch_alter_table('ethical_walls', schema=None) as batch_op:
        batch_op.drop_index('ix_ethical_walls_entity')

    op.drop_table('ethical_walls')
    # ### end Alembic commands ###
