"""initial schema

Revision ID: 509e42cd1dc6
Revises: 
Create Date: 2026-08-22 10:12:57.639153
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '509e42cd1dc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('practice_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('discipline', sa.String(length=30), nullable=False),
    sa.Column('clearance_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('is_lost', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('aliases', sa.String(length=500), nullable=True),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('entity_kind', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('revenue_band', sa.String(length=40), nullable=True),
    sa.Column('employee_band', sa.String(length=40), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('originating_partner_id', sa.Integer(), nullable=True),
    sa.Column('referral_account_id', sa.Integer(), nullable=True),
    sa.Column('referral_contact_id', sa.Integer(), nullable=True),
    sa.Column('client_since', sa.Date(), nullable=True),
    sa.Column('risk_rating', sa.String(length=10), nullable=True),
    sa.Column('is_public_company', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['originating_partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referral_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['referral_contact_id'], ['contacts.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_is_archived'), ['is_archived'], unique=False)

    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('created_rows', sa.Integer(), nullable=False),
    sa.Column('updated_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('exceptions', sa.JSON(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('lifecycle', sa.String(length=20), nullable=False),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_last_name'), ['last_name'], unique=False)
        batch_op.create_index('uq_contacts_email_active', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL AND is_archived = false'), sqlite_where=sa.text('email IS NOT NULL AND is_archived = 0'))

    op.create_table('campaign_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('referral_contact_id', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('need_summary', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('unqualified_reason', sa.String(length=200), nullable=True),
    sa.Column('converted_account_id', sa.Integer(), nullable=True),
    sa.Column('converted_contact_id', sa.Integer(), nullable=True),
    sa.Column('converted_opportunity_id', sa.Integer(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['converted_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['converted_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['converted_opportunity_id'], ['opportunities.id'], use_alter=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ),
    sa.ForeignKeyConstraint(['referral_contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_is_archived'), ['is_archived'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('primary_contact_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('originating_partner_id', sa.Integer(), nullable=True),
    sa.Column('responsible_partner_id', sa.Integer(), nullable=True),
    sa.Column('referral_contact_id', sa.Integer(), nullable=True),
    sa.Column('referral_account_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('expected_close', sa.Date(), nullable=True),
    sa.Column('proposal_due', sa.Date(), nullable=True),
    sa.Column('engagement_letter_status', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('lost_reason', sa.String(length=60), nullable=True),
    sa.Column('competitor', sa.String(length=120), nullable=True),
    sa.Column('adverse_parties', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('next_step', sa.String(length=255), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['originating_partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ),
    sa.ForeignKeyConstraint(['primary_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['referral_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['referral_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['responsible_partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_name'), ['name'], unique=False)
        batch_op.create_index('ix_opportunities_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index('ix_opportunities_status_stage', ['status', 'stage_id'], unique=False)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index('ix_activities_occurred', ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index('ix_activities_owner_kind_completed', ['owner_id', 'kind', 'completed_at'], unique=False)

    op.create_table('conflict_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.String(length=20), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('parties', sa.JSON(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('independence_attestation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflict_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflict_checks_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflict_checks_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('practice_area_id', sa.Integer(), nullable=True),
    sa.Column('responsible_partner_id', sa.Integer(), nullable=True),
    sa.Column('originating_partner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fee_type', sa.String(length=20), nullable=False),
    sa.Column('annual_value', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('adverse_parties', sa.JSON(), nullable=True),
    sa.Column('external_ref', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['originating_partner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['practice_area_id'], ['practice_areas.id'], ),
    sa.ForeignKeyConstraint(['responsible_partner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('from_stage_id', sa.Integer(), nullable=True),
    sa.Column('to_stage_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('days_in_previous', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['from_stage_id'], ['stages.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


    # Cyclic FKs (use_alter=True) are added after both tables exist.
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_accounts_referral_contact_id_contacts', 'contacts', ['referral_contact_id'], ['id'])
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_leads_converted_opportunity_id_opportunities', 'opportunities', ['converted_opportunity_id'], ['id'])


def downgrade() -> None:
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leads_converted_opportunity_id_opportunities', type_='foreignkey')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_accounts_referral_contact_id_contacts', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_history')
    op.drop_table('engagements')
    with op.batch_alter_table('conflict_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflict_checks_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_conflict_checks_account_id'))

    op.drop_table('conflict_checks')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_owner_kind_completed')
        batch_op.drop_index(batch_op.f('ix_activities_opportunity_id'))
        batch_op.drop_index('ix_activities_occurred')
        batch_op.drop_index(batch_op.f('ix_activities_lead_id'))
        batch_op.drop_index(batch_op.f('ix_activities_contact_id'))
        batch_op.drop_index(batch_op.f('ix_activities_account_id'))

    op.drop_table('activities')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index('ix_opportunities_status_stage')
        batch_op.drop_index('ix_opportunities_owner_status')
        batch_op.drop_index(batch_op.f('ix_opportunities_name'))
        batch_op.drop_index(batch_op.f('ix_opportunities_is_archived'))

    op.drop_table('opportunities')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_is_archived'))

    op.drop_table('leads')
    op.drop_table('campaign_members')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index('uq_contacts_email_active', postgresql_where=sa.text('email IS NOT NULL AND is_archived = false'), sqlite_where=sa.text('email IS NOT NULL AND is_archived = 0'))
        batch_op.drop_index(batch_op.f('ix_contacts_last_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_is_archived'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))

    op.drop_table('contacts')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))

    op.drop_table('refresh_tokens')
    op.drop_table('import_jobs')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_is_archived'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_archived'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('stages')
    op.drop_table('practice_areas')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
